<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.26">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Suyog Chandramouli">
<meta name="dcterms.date" content="2025-02-04">

<title>Multiple Regression – PSY 504, Spring 2026</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-4ddf543e2355fdfec88fa953ceab072a.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-169522303b7bc79663207a91790de262.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="../../site_libs/kePrint-0.0.1/kePrint.js"></script>
<link href="../../site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">
<meta name="robots" content="noindex, nofollow">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top quarto-banner">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">PSY 504, Spring 2026</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">Lectures</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://docs.google.com/document/d/1mXjcFA67TXVNmGNlOfn11-vb5wBbP5yJ8LPKqMjoweM/edit" target="_blank"> 
<span class="menu-text">Syllabus</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://docs.google.com/document/d/1fZhqADwjg8B8YvxYaPCOVUBOh3ounTP8L2g5p31fp18/edit" target="_blank"> 
<span class="menu-text">Schedule</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../about.html"> 
<span class="menu-text">About</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">Multiple Regression</h1>
            <p class="subtitle lead"><small>(modified from Jason Geller)</small></p>
                                <div class="quarto-categories">
                <div class="quarto-category">Linear Models</div>
              </div>
                  </div>
  </div>
    
  <div class="quarto-title-meta-author">
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-heading">Affiliation</div>
    
      <div class="quarto-title-meta-contents">
      <p class="author">Suyog Chandramouli </p>
    </div>
    <div class="quarto-title-meta-contents">
          <p class="affiliation">
              PSY504, Advanced Statistics in Psychology<br>Princeton University
            </p>
        </div>
    </div>

  <div class="quarto-title-meta">

        
      <div>
      <div class="quarto-title-meta-heading">Published</div>
      <div class="quarto-title-meta-contents">
        <p class="date">February 4, 2025</p>
      </div>
    </div>
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
    <div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="Mul_Reg.html"><i class="bi bi-file-slides"></i>RevealJS</a></li></ul></div></div>
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">





<section id="packages" class="level2">
<h2 class="anchored" data-anchor-id="packages">Packages</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(grateful)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>pkgs <span class="ot">&lt;-</span> <span class="fu">cite_packages</span>(<span class="at">output =</span> <span class="st">"table"</span>, <span class="at">out.dir =</span> <span class="st">"."</span>)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>pkgs</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>       Package Version                                       Citation
1         afex   1.5.1                                          @afex
2         base   4.4.2                                          @base
3    easystats   0.7.3                                     @easystats
4      emmeans  1.10.6                                       @emmeans
5    ggeffects   2.3.2                                     @ggeffects
6           gt  0.11.1                                            @gt
7   ICSOutlier   0.4.1                                    @ICSOutlier
8      insight   1.4.6                                       @insight
9   kableExtra   1.4.0                                    @kableExtra
10       knitr    1.51             @knitr2014; @knitr2015; @knitr2025
11       olsrr   0.6.1                                         @olsrr
12      pacman   0.5.1                                        @pacman
13      papaja   0.1.3                                        @papaja
14 performance  0.16.0                                   @performance
15   rmarkdown    2.29 @rmarkdown2018; @rmarkdown2020; @rmarkdown2024
16         see   0.9.0                                           @see
17   supernova   3.0.0                                     @supernova
18   tidyverse   2.0.0                                     @tidyverse
19     ungeviz   0.1.0                                       @ungeviz</code></pre>
</div>
</div>
<div class="notes">
<ul>
<li><p>these are the packages we’re using today</p></li>
<li><p>There’s this package named <code>grateful</code> which lets you list all the packages that you’ve used in your code!</p></li>
<li><p>Good for reproducibility. But it also allows you to cite them / just add them to your references.</p></li>
<li><p>You can even take it one further and get all the dependencies if you wish.</p></li>
</ul>
</div>
</section>
<section id="today" class="level2">
<h2 class="anchored" data-anchor-id="today">Today</h2>
<div class="nonincremental">
<ul>
<li><p>Introduction to multiple regression</p>
<ul>
<li>Motivation</li>
<li>Interpretation of coefs</li>
</ul></li>
<li><p>Assumptions of multiple regression</p></li>
<li><p>Effect size and power</p></li>
<li><p>Plotting</p></li>
<li><p>Write-up</p></li>
</ul>
</div>
<div class="notes">
<ul>
<li><p>Roadmap. Motivation. See MR in action.</p></li>
<li><p>Q: I said that MR is an extension of LR, which allows us to consider more than 1 vars. But have you already considered more than 1 variable before? A: YES! with ANOVA. But why is that different? Hybrid is also called ancova</p></li>
<li><p>We’ll build on simple regression — add more predictors</p></li>
<li><p>Then tackle the messiness: assumptions, outliers, multicollinearity</p></li>
<li><p>End with how to report results properly</p></li>
</ul>
</div>
</section>
<section id="previously..-simpsons-paradox" class="level2">
<h2 class="anchored" data-anchor-id="previously..-simpsons-paradox">Previously.. Simpson’s paradox</h2>
<p><img src="images/clipboard-3775470264.png" class="img-fluid"></p>
<div class="notes">
<ul>
<li><p>In the context that looking at the data and thinking carefully about it matters</p></li>
<li><p>Y: admission rates for department</p></li>
<li><p>X: percent of women who applied.</p></li>
<li><p>Department and levels… also interaction effects (more messy and realistic, but not as much a paradox)</p></li>
</ul>
</div>
</section>
<section id="simpsons-paradox" class="level2">
<h2 class="anchored" data-anchor-id="simpsons-paradox">Simpson’s paradox</h2>
<p><img src="images/clipboard-3804447656.png" class="img-fluid"></p>
</section>
<section id="simpsons-paradox-1" class="level2">
<h2 class="anchored" data-anchor-id="simpsons-paradox-1">Simpson’s paradox</h2>
<p><img src="images/clipboard-1350581558.png" class="img-fluid"></p>
<div class="notes">
<ul>
<li><p>Q: How do we solve for this?</p></li>
<li><p>A: first, by even considering that the department matters: by adding it to your model</p></li>
<li><p>A2: Mixed effects models are even more helpful. It prevents a single small, outlier department from skewing your entire conclusion. Let’s you do more such as account for different levels in it, etc.</p></li>
</ul>
</div>
</section>
<section id="correlation-confounds" class="level2">
<h2 class="anchored" data-anchor-id="correlation-confounds">Correlation &amp; Confounds</h2>
<p><img src="images/clipboard-3005683190.png" class="img-fluid"></p>
</section>
<section id="simple-linear-model" class="level2">
<h2 class="anchored" data-anchor-id="simple-linear-model">Simple Linear Model</h2>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/Pxy.png" class="img-fluid quarto-figure quarto-figure-center figure-img"></p>
</figure>
</div>
<div class="notes">
<ul>
<li><p>SLR: One predictor, one outcome</p></li>
<li><p>X predicts Y — that’s our foundation</p></li>
<li><p>Single arrow, single relationship</p></li>
</ul>
</div>
</section>
<section id="multiple-predictors-in-linear-regression" class="level2">
<h2 class="anchored" data-anchor-id="multiple-predictors-in-linear-regression">Multiple predictors in linear regression</h2>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/xymult.png" class="img-fluid quarto-figure quarto-figure-center figure-img"></p>
</figure>
</div>
<div class="notes">
<ul>
<li><p>Now we add more Xs</p></li>
<li><p>Multiple arrows pointing to Y</p></li>
<li><p>Same logic, just more of it</p></li>
</ul>
</div>
</section>
<section id="multiple-regression" class="level2">
<h2 class="anchored" data-anchor-id="multiple-regression">Multiple regression</h2>
<p><span class="math display">\[\begin{align}
\hat{Y} &amp;= b_0 + \beta_1 X
\end{align}\]</span></p>
<p><span class="math display">\[\large \hat{Y} = b_0 + b_1X_1 + b_2X_2 + \dots+b_kX_k\]</span></p>
<ul>
<li>Simple as adding predictors to our linear equation</li>
</ul>
<div class="notes">
<ul>
<li><p>Simple regression on top, multiple regression below</p></li>
<li><p>We just keep adding terms</p></li>
<li><p>Q: what do you anctipate to change in the outputs?</p></li>
</ul>
<p>– A: Each X gets its own slope</p>
</div>
</section>
<section id="multiple-regression-equation" class="level2">
<h2 class="anchored" data-anchor-id="multiple-regression-equation">Multiple regression equation</h2>
<div class="incremental">
<p><span class="math display">\[\large \hat{Y} = b_0 + b_1X_1 + b_2X_2 + \dots+b_kX_k\]</span></p>
<ul class="incremental">
<li><span class="math inline">\(\hat{Y}\)</span> = predicted value on the outcome variable Y</li>
<li><span class="math inline">\(b_0\)</span> = predicted value on Y when all Xs = 0</li>
<li><span class="math inline">\(X_k\)</span> = predictor variables</li>
<li><span class="math inline">\(b_k\)</span> = unstandardized regression coefficients</li>
<li><span class="math inline">\(k\)</span> = the number of predictor variables</li>
</ul>
</div>
<div class="notes">
<ul>
<li><p>Let’s break this apart</p></li>
<li><p>Y-hat is our prediction</p></li>
<li><p>b₀ is the intercept — Y <em>when all predictors are zero</em> (just like SLR)</p></li>
<li><p>Each b is a slope, each X is a predictor</p></li>
<li><p>k is how many predictors we have</p></li>
</ul>
</div>
</section>
<section id="straight-line-to-hyperplane" class="level2">
<h2 class="anchored" data-anchor-id="straight-line-to-hyperplane">Straight Line to Hyperplane</h2>
<div class="columns">
<div class="column incremental" style="width:50%;">
<ul class="incremental">
<li><p>More than two predictors (plane)</p>
<ul class="incremental">
<li>Multi-dimensional space</li>
</ul></li>
<li><p>Regression coefficients are “partial” regression coefficients</p>
<ul class="incremental">
<li><p>Slope for variable X1 (<span class="math inline">\(b_1\)</span>) predicts the change in Y per unit X1 holding X2 constant</p></li>
<li><p>Slope for variable X2 (<span class="math inline">\(b_2\)</span>) predicts the change in Y per unit X2 holding X1 constant</p></li>
</ul></li>
</ul>
</div><div class="column" style="width:50%;">
<p><br></p>
<p><br></p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/multip.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="722"></p>
</figure>
</div>
</div>
</div>
<div class="notes">
<ul>
<li><p>With one predictor we had a line that was fit to the data</p></li>
<li><p>With Two predictors we are fitting a plane</p></li>
<li><p>More than two: terminology is a hyperplane (hard to visualize)</p></li>
<li><p>Key insight: each coefficient is now “partial” – It tells you the effect of X₁ <em>after controlling for</em> X₂ – what does that mean? It means, you stay at a fixed point in X1, then X2 has a slope – 2 different slopes =&gt; 2 coefficients</p></li>
</ul>
</div>
</section>
<section id="multiple-regression-example" class="level2">
<h2 class="anchored" data-anchor-id="multiple-regression-example">Multiple Regression: Example</h2>
<p><span class="math display">\[
\begin{align*}
\operatorname{CESD\_total} &amp;= b_o + b_{1}(\operatorname{PIL\_total}) \\
&amp;+ b_{2}(\operatorname{AUDIT\_TOTAL\_NEW}) \\
&amp;+ b_{3}(\operatorname{DAST\_TOTAL\_NEW}) \\
&amp;+ e
\end{align*}
\]</span></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-overflow-wrap code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>master <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"https://raw.githubusercontent.com/jgeller112/psy503-psych_stats/master/static/slides/10-linear_modeling/data/regress.csv"</span>)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(master)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  X PIL_total CESD_total AUDIT_TOTAL_NEW DAST_TOTAL_NEW
1 1       121         28               1              0
2 2        76         37               5              0
3 3        98         20               3              0
4 4       122         15               3              1
5 5        99          7               2              0
6 6       134          7               3              0</code></pre>
</div>
</div>
<ul>
<li><p>Mental Health and Drug Use:</p>
<ul>
<li>CESD = depression measure</li>
<li>PIL total = measure of meaning in life</li>
<li>AUDIT total = measure of alcohol use</li>
<li>DAST total = measure of drug usage</li>
</ul></li>
</ul>
<div class="notes">
<ul>
<li><p>Here is some real data from a mental health study</p></li>
<li><p>Outcome we’re predicting : depression (CESD) from three things</p></li>
<li><p>Meaning in life, alcohol use, drug use</p></li>
<li><p>What predicts depression when we account for everything simultaneously?</p></li>
</ul>
</div>
</section>
<section id="multiple-regression-example-1" class="level2">
<h2 class="anchored" data-anchor-id="multiple-regression-example-1">Multiple Regression: Example</h2>
<ul>
<li><em>Validated Measures</em>
<ul>
<li><em>CESD : Center for Epidemiological Studies Depression Scale</em></li>
<li><em>PIL : Purpose in Life Test</em></li>
<li><em>AUDIT : Alcohol Use Disorders Identification Test</em></li>
<li><em>DAST : Drug Abuse Screening Test</em></li>
</ul></li>
</ul>
<div class="notes">
<ul>
<li><p>Here is some real data from a mental health study</p></li>
<li><p>Outcome we’re predicting : depression (CESD) from three predictors</p></li>
<li><p>That is…. Meaning in life, alcohol use, drug use</p></li>
<li><p>What predicts depression when we account for everything simultaneously?</p></li>
</ul>
</div>
</section>
<section id="scatterplot" class="level2">
<h2 class="anchored" data-anchor-id="scatterplot">Scatterplot</h2>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Change the point sizes manually</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>anim<span class="fl">.1</span><span class="ot">&lt;-</span> <span class="fu">ggplot</span>(master, <span class="fu">aes</span>(<span class="at">x=</span>PIL_total, <span class="at">y=</span>CESD_total))<span class="sc">+</span></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>   <span class="fu">geom_point</span>() <span class="sc">+</span> </span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>(<span class="at">base_size=</span><span class="dv">20</span>)</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>anim<span class="fl">.1</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Mul_Reg_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="1152"></p>
</figure>
</div>
</div>
</div>
<div class="notes">
<ul>
<li><p>As usual, we start by visualizing data</p></li>
<li><p>Here is a scatterplot: Meaning in life vs.&nbsp;depression</p></li>
<li><p>Clear negative relationship</p></li>
<li><p>And it makes sense (Purpose in life/meaning increases -&gt; less depression)</p></li>
</ul>
</div>
</section>
<section id="scatterplot-1" class="level2">
<h2 class="anchored" data-anchor-id="scatterplot-1">Scatterplot</h2>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Change the point sizes manually</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>anim<span class="fl">.1</span><span class="ot">&lt;-</span> <span class="fu">ggplot</span>(master, <span class="fu">aes</span>(<span class="at">x=</span>AUDIT_TOTAL_NEW, <span class="at">y=</span>CESD_total))<span class="sc">+</span></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>   <span class="fu">geom_point</span>() <span class="sc">+</span> </span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>(<span class="at">base_size=</span><span class="dv">20</span>)</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>anim<span class="fl">.1</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Mul_Reg_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="1152"></p>
</figure>
</div>
</div>
</div>
<div class="notes">
<ul>
<li><p>Next: Alcohol use vs.&nbsp;depression</p></li>
<li><p>Relationship less clear</p></li>
<li><p>Some positive trend maybe — noisier</p></li>
</ul>
</div>
</section>
<section id="scatterplot-2" class="level2">
<h2 class="anchored" data-anchor-id="scatterplot-2">Scatterplot</h2>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Change the point sizes manually</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>anim<span class="fl">.1</span><span class="ot">&lt;-</span> <span class="fu">ggplot</span>(master, <span class="fu">aes</span>(<span class="at">x=</span>DAST_TOTAL_NEW, <span class="at">y=</span>CESD_total))<span class="sc">+</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>   <span class="fu">geom_point</span>() <span class="sc">+</span> </span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>(<span class="at">base_size=</span><span class="dv">20</span>)</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>anim<span class="fl">.1</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Mul_Reg_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="1152"></p>
</figure>
</div>
</div>
</div>
<div class="notes">
<ul>
<li><p>Finally: Drug use vs.&nbsp;depression</p></li>
<li><p>Also messy</p></li>
<li><p>Most people cluster at zero… At 0 where most points are drug use isn’t helpful for capturing</p></li>
<li><p>Hard to see pattern</p></li>
</ul>
</div>
</section>
<section id="individual-predictors" class="level2">
<h2 class="anchored" data-anchor-id="individual-predictors">Individual Predictors</h2>
<div class="incremental">
<ul class="incremental">
<li><p>We test the individual predictors with a t-test:</p>
<ul class="incremental">
<li><p><span class="math inline">\(t = \frac{b}{SE}\)</span></p></li>
<li><p>Therefore, the model for each individual predictor is our coefficient b</p></li>
<li><p>Single sample t-test to determine if the b value is different from zero</p></li>
</ul></li>
</ul>
</div>
<div class="notes">
<ul>
<li><p>How do we test if each predictor matters?</p></li>
<li><p>Same t-test logic</p></li>
<li><p>Take the coefficient, divide by its standard error</p></li>
<li><p>(Many of these tests are SNR / proportion of variance explained)</p></li>
<li><p>Is b different from zero? That’s our question for each predictor</p></li>
</ul>
</div>
</section>
<section id="fitting-the-model" class="level2">
<h2 class="anchored" data-anchor-id="fitting-the-model">Fitting the model</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>model_fit <span class="ot">&lt;-</span> <span class="fu">lm</span>(CESD_total <span class="sc">~</span> PIL_total <span class="sc">+</span> AUDIT_TOTAL_NEW <span class="sc">+</span> DAST_TOTAL_NEW,</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>             <span class="at">data =</span> master) </span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_fit)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = CESD_total ~ PIL_total + AUDIT_TOTAL_NEW + DAST_TOTAL_NEW, 
    data = master)

Residuals:
    Min      1Q  Median      3Q     Max 
-19.619  -5.172  -1.256   3.420  28.847 

Coefficients:
                Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)     55.16374    3.88905  14.184   &lt;2e-16 ***
PIL_total       -0.38158    0.03384 -11.276   &lt;2e-16 ***
AUDIT_TOTAL_NEW -0.09211    0.09391  -0.981    0.328    
DAST_TOTAL_NEW   1.03415    0.39871   2.594    0.010 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 7.585 on 262 degrees of freedom
  (1 observation deleted due to missingness)
Multiple R-squared:  0.3587,    Adjusted R-squared:  0.3513 
F-statistic: 48.84 on 3 and 262 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<table class="table caption-top table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">term</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">estimate</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">std.error</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">statistic</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">p.value</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">conf.low</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">conf.high</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left; color: white !important; background-color: red !important;">(Intercept)</td>
<td style="text-align: right; color: white !important; background-color: red !important;">55.1637359</td>
<td style="text-align: right; color: white !important; background-color: red !important;">3.8890461</td>
<td style="text-align: right; color: white !important; background-color: red !important;">14.1843873</td>
<td style="text-align: right; color: white !important; background-color: red !important;">0.0000000</td>
<td style="text-align: right; color: white !important; background-color: red !important;">47.5059719</td>
<td style="text-align: right; color: white !important; background-color: red !important;">62.8214999</td>
</tr>
<tr class="even">
<td style="text-align: left;">PIL_total</td>
<td style="text-align: right;">-0.3815778</td>
<td style="text-align: right;">0.0338406</td>
<td style="text-align: right;">-11.2757330</td>
<td style="text-align: right;">0.0000000</td>
<td style="text-align: right;">-0.4482119</td>
<td style="text-align: right;">-0.3149436</td>
</tr>
<tr class="odd">
<td style="text-align: left;">AUDIT_TOTAL_NEW</td>
<td style="text-align: right;">-0.0921089</td>
<td style="text-align: right;">0.0939109</td>
<td style="text-align: right;">-0.9808116</td>
<td style="text-align: right;">0.3275905</td>
<td style="text-align: right;">-0.2770251</td>
<td style="text-align: right;">0.0928073</td>
</tr>
<tr class="even">
<td style="text-align: left;">DAST_TOTAL_NEW</td>
<td style="text-align: right;">1.0341539</td>
<td style="text-align: right;">0.3987126</td>
<td style="text-align: right;">2.5937324</td>
<td style="text-align: right;">0.0100281</td>
<td style="text-align: right;">0.2490649</td>
<td style="text-align: right;">1.8192429</td>
</tr>
</tbody>
</table>
</div>
</div>
<blockquote class="blockquote">
<p><span class="math inline">\(b_0\)</span>: The value of Y when all the Xs=0</p>
</blockquote>
<div class="notes">
<ul>
<li><p>Here’s the R code — simple formula</p></li>
<li><p>outcome ~ predictor1 + predictor2 + predictor3</p></li>
<li><p>You plug all the coefficients in, you get the model with which you can make predictions!</p></li>
<li><p>The intercept (b₀ = 55.16): predicted depression when someone has zero meaning, zero alcohol use, zero drug use INTERCEPT: Not very interpretable in practice but mathematically necessary</p></li>
<li><pre><code>For every 1-unit increase in meaning in life, depression scores are predicted to decrease by 0.38 units, (assuming alcohol and drug use remain the same.)</code></pre></li>
<li><p>can think of t-statistics as SNR: meaning, …</p></li>
<li><p>ignore t-value of intercept</p></li>
<li><p>acohold and depression not so much</p></li>
<li><p>Residuals: distribution (min, max).. median is helpful… not a huge shift</p></li>
<li><p>SE of the estimates… guess of how much the estimate my change as you look at different samples</p></li>
<li><p>DAST….. high of drug abuse</p></li>
</ul>
</div>
</section>
<section id="fitting-the-model-1" class="level2">
<h2 class="anchored" data-anchor-id="fitting-the-model-1">Fitting the model</h2>
<div class="cell">
<div class="cell-output-display">
<table class="table caption-top table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">term</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">estimate</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">std.error</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">statistic</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">p.value</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">conf.low</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">conf.high</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">55.1637359</td>
<td style="text-align: right;">3.8890461</td>
<td style="text-align: right;">14.1843873</td>
<td style="text-align: right;">0.0000000</td>
<td style="text-align: right;">47.5059719</td>
<td style="text-align: right;">62.8214999</td>
</tr>
<tr class="even">
<td style="text-align: left; color: white !important; background-color: red !important;">PIL_total</td>
<td style="text-align: right; color: white !important; background-color: red !important;">-0.3815778</td>
<td style="text-align: right; color: white !important; background-color: red !important;">0.0338406</td>
<td style="text-align: right; color: white !important; background-color: red !important;">-11.2757330</td>
<td style="text-align: right; color: white !important; background-color: red !important;">0.0000000</td>
<td style="text-align: right; color: white !important; background-color: red !important;">-0.4482119</td>
<td style="text-align: right; color: white !important; background-color: red !important;">-0.3149436</td>
</tr>
<tr class="odd">
<td style="text-align: left;">AUDIT_TOTAL_NEW</td>
<td style="text-align: right;">-0.0921089</td>
<td style="text-align: right;">0.0939109</td>
<td style="text-align: right;">-0.9808116</td>
<td style="text-align: right;">0.3275905</td>
<td style="text-align: right;">-0.2770251</td>
<td style="text-align: right;">0.0928073</td>
</tr>
<tr class="even">
<td style="text-align: left;">DAST_TOTAL_NEW</td>
<td style="text-align: right;">1.0341539</td>
<td style="text-align: right;">0.3987126</td>
<td style="text-align: right;">2.5937324</td>
<td style="text-align: right;">0.0100281</td>
<td style="text-align: right;">0.2490649</td>
<td style="text-align: right;">1.8192429</td>
</tr>
</tbody>
</table>
</div>
</div>
<blockquote class="blockquote">
<p><span class="math inline">\(b_1\)</span>: If Alch and drug use are held constant, for every 1 unit increase in X (meaning) leads to a -0.38 decrease in depression scores.</p>
</blockquote>
<div class="notes">
<ul>
<li>The meaning coefficient: -0.38</li>
<li>Negative — more meaning, less depression</li>
<li>“Holding alcohol and drug use constant” — that’s the partial regression magic</li>
<li>Each unit increase in meaning drops depression by 0.38 points</li>
</ul>
</div>
</section>
<section id="fitting-the-model-2" class="level2">
<h2 class="anchored" data-anchor-id="fitting-the-model-2">Fitting the model</h2>
<div class="cell">
<div class="cell-output-display">
<table class="table caption-top table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">term</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">estimate</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">std.error</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">statistic</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">p.value</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">conf.low</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">conf.high</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">55.1637359</td>
<td style="text-align: right;">3.8890461</td>
<td style="text-align: right;">14.1843873</td>
<td style="text-align: right;">0.0000000</td>
<td style="text-align: right;">47.5059719</td>
<td style="text-align: right;">62.8214999</td>
</tr>
<tr class="even">
<td style="text-align: left;">PIL_total</td>
<td style="text-align: right;">-0.3815778</td>
<td style="text-align: right;">0.0338406</td>
<td style="text-align: right;">-11.2757330</td>
<td style="text-align: right;">0.0000000</td>
<td style="text-align: right;">-0.4482119</td>
<td style="text-align: right;">-0.3149436</td>
</tr>
<tr class="odd">
<td style="text-align: left; color: white !important; background-color: red !important;">AUDIT_TOTAL_NEW</td>
<td style="text-align: right; color: white !important; background-color: red !important;">-0.0921089</td>
<td style="text-align: right; color: white !important; background-color: red !important;">0.0939109</td>
<td style="text-align: right; color: white !important; background-color: red !important;">-0.9808116</td>
<td style="text-align: right; color: white !important; background-color: red !important;">0.3275905</td>
<td style="text-align: right; color: white !important; background-color: red !important;">-0.2770251</td>
<td style="text-align: right; color: white !important; background-color: red !important;">0.0928073</td>
</tr>
<tr class="even">
<td style="text-align: left;">DAST_TOTAL_NEW</td>
<td style="text-align: right;">1.0341539</td>
<td style="text-align: right;">0.3987126</td>
<td style="text-align: right;">2.5937324</td>
<td style="text-align: right;">0.0100281</td>
<td style="text-align: right;">0.2490649</td>
<td style="text-align: right;">1.8192429</td>
</tr>
</tbody>
</table>
</div>
</div>
<blockquote class="blockquote">
<p><span class="math inline">\(b_2\)</span>: Holding meaning and drug use constant, for every unit increase in alch use there is a -0.09 decrease in depression scores.</p>
</blockquote>
<div class="notes">
<ul>
<li>Alcohol coefficient: -0.09</li>
<li>Tiny and not significant (p = .33)</li>
<li>After accounting for meaning and drugs, alcohol doesn’t add much</li>
<li>Surprising? Maybe meaning captures the variance</li>
</ul>
</div>
</section>
<section id="fitting-the-model-3" class="level2">
<h2 class="anchored" data-anchor-id="fitting-the-model-3">Fitting the model</h2>
<div class="cell">
<div class="cell-output-display">
<table class="table caption-top table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">term</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">estimate</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">std.error</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">statistic</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">p.value</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">conf.low</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">conf.high</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">55.1637359</td>
<td style="text-align: right;">3.8890461</td>
<td style="text-align: right;">14.1843873</td>
<td style="text-align: right;">0.0000000</td>
<td style="text-align: right;">47.5059719</td>
<td style="text-align: right;">62.8214999</td>
</tr>
<tr class="even">
<td style="text-align: left;">PIL_total</td>
<td style="text-align: right;">-0.3815778</td>
<td style="text-align: right;">0.0338406</td>
<td style="text-align: right;">-11.2757330</td>
<td style="text-align: right;">0.0000000</td>
<td style="text-align: right;">-0.4482119</td>
<td style="text-align: right;">-0.3149436</td>
</tr>
<tr class="odd">
<td style="text-align: left;">AUDIT_TOTAL_NEW</td>
<td style="text-align: right;">-0.0921089</td>
<td style="text-align: right;">0.0939109</td>
<td style="text-align: right;">-0.9808116</td>
<td style="text-align: right;">0.3275905</td>
<td style="text-align: right;">-0.2770251</td>
<td style="text-align: right;">0.0928073</td>
</tr>
<tr class="even">
<td style="text-align: left; color: white !important; background-color: red !important;">DAST_TOTAL_NEW</td>
<td style="text-align: right; color: white !important; background-color: red !important;">1.0341539</td>
<td style="text-align: right; color: white !important; background-color: red !important;">0.3987126</td>
<td style="text-align: right; color: white !important; background-color: red !important;">2.5937324</td>
<td style="text-align: right; color: white !important; background-color: red !important;">0.0100281</td>
<td style="text-align: right; color: white !important; background-color: red !important;">0.2490649</td>
<td style="text-align: right; color: white !important; background-color: red !important;">1.8192429</td>
</tr>
</tbody>
</table>
</div>
</div>
<blockquote class="blockquote">
<p><span class="math inline">\(b_3\)</span>: Holding meaning and alch usage constant, for every unit increase in drug usage there is a 1.03 increase in depression.</p>
</blockquote>
<div class="notes">
<ul>
<li>Drug use coefficient: 1.03</li>
<li>Positive — more drug use, more depression</li>
<li>Significant at p = .01</li>
<li>Each unit increase in drug use adds about 1 point to depression</li>
</ul>
</div>
</section>
<section id="more-predictors-more-problems" class="level2">
<h2 class="anchored" data-anchor-id="more-predictors-more-problems">More predictors =&gt; more problems</h2>
<ul>
<li><p>Assumptions</p>
<ul>
<li><p>Linearity</p></li>
<li><p>Independence</p></li>
<li><p>Normality of residuals</p></li>
<li><p>Equal error (“homoskedasticity”)</p></li>
</ul></li>
</ul>
<div class="incremental">
<ul class="incremental">
<li><p>Issues:</p>
<ul class="incremental">
<li><p>Missingness</p></li>
<li><p>Factors are correlated with one another (multicollinearity)</p></li>
<li><p>Unusual values/outliers</p></li>
</ul></li>
</ul>
</div>
<div class="notes">
<ul>
<li><p>More predictors = more things can go wrong</p></li>
<li><p>Standard assumptions still apply: linearity, independence, normality, homoskedasticity</p></li>
<li><p>New issues: missing data, multicollinearity, outliers</p></li>
<li><p>Let’s tackle each</p></li>
</ul>
</div>
</section>
<section id="problems" class="level2">
<h2 class="anchored" data-anchor-id="problems">Problems</h2>
<ul>
<li>Missingness
<ul>
<li>list-wise deletion (removes entire row where missingness occurs)</li>
</ul></li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>nomiss <span class="ot">&lt;-</span> master <span class="sc">%&gt;%</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">drop_na</span>() <span class="co"># drop missing data</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a><span class="co">#base r</span></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>nomiss <span class="ot">&lt;-</span> master <span class="sc">%&gt;%</span></span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">na.omit</span>() </span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(master)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 267</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(nomiss)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 266</code></pre>
</div>
</div>
<div class="notes">
<ul>
<li><p>Missing data? R uses listwise deletion by default</p></li>
<li><p>One missing value in a row? Whole row gone</p></li>
<li><p>We went from 267 to 266 — not bad here</p></li>
<li><p>Can be catastrophic with more missingness</p></li>
<li><p>Later in the semester, we’ll look at other solutions</p></li>
</ul>
</div>
</section>
<section id="problems-1" class="level2">
<h2 class="anchored" data-anchor-id="problems-1">Problems</h2>
<div class="incremental">
<ul class="incremental">
<li><p>Multicolinearity</p>
<ul class="incremental">
<li><p>You want X and Y to be correlated</p></li>
<li><p>You do not want the Xs to be highly correlated</p></li>
</ul></li>
</ul>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/mult-prob.PNG" class="img-fluid quarto-figure quarto-figure-center figure-img"></p>
</figure>
</div>
</div>
<div class="notes">
<ul>
<li><p>We <em>want</em> X and Y correlated</p></li>
<li><p>We <em>don’t</em> want the Xs correlated with each other</p></li>
<li><p>Figure: We want as much of the red circle to be calculated!</p></li>
<li><p>Next: we also want blues to be seperated! If predictors overlap too much, we can’t untangle their unique effects!! which variable to give credit to! It’s also redundancy.</p></li>
</ul>
</div>
</section>
<section id="multicolinearity" class="level2">
<h2 class="anchored" data-anchor-id="multicolinearity">Multicolinearity</h2>
<div class="incremental">
<ul class="incremental">
<li><p>Problems</p>
<ul class="incremental">
<li><p>Extreme cases (complete collinearity) = Nonidentifiable model</p></li>
<li><p>“Unstable” regression coefficients (“bouncing betas”)</p>
<ul class="incremental">
<li>Imprecise estimation</li>
</ul></li>
<li><p>Large standard errors</p>
<ul class="incremental">
<li>Increased Type II errors
<ul class="incremental">
<li>Not detecting a difference when there is one</li>
</ul></li>
</ul></li>
</ul></li>
</ul>
</div>
<div class="notes">
<ul>
<li>Extreme case: predictors perfectly correlated — model can’t be estimated at all</li>
<li>Less extreme: “bouncing betas” — coefficients become unstable</li>
<li>Standard errors inflate</li>
<li>You miss real effects (Type II errors)</li>
</ul>
</div>
</section>
<section id="multicolinearity-1" class="level2">
<h2 class="anchored" data-anchor-id="multicolinearity-1">Multicolinearity</h2>
<ul>
<li><p>Tolerance</p>
<ul>
<li>Measures influence of one predictor on another</li>
<li>If predictors are highly correlated, tolerance gets smaller</li>
</ul></li>
</ul>
<p><span class="math display">\[Tolerance=1- R^2_j\]</span></p>
<blockquote class="blockquote">
<p>where <span class="math inline">\(R^2_j\)</span> is the proportion of variation in X that is explained by the linear combination of the other predictors in the model</p>
</blockquote>
<div class="notes">
<ul>
<li><p>Tolerance: how much variance in X₁ is NOT explained by other Xs</p></li>
<li><p>Formula: 1 - R²</p></li>
<li><p>Lower tolerance = more problematic</p></li>
<li><p>The predictor is redundant with others</p></li>
<li><p>“How much unique information do I have about X1?”</p></li>
</ul>
</div>
</section>
<section id="multicolinearity-2" class="level2">
<h2 class="anchored" data-anchor-id="multicolinearity-2">Multicolinearity</h2>
<ul>
<li><p>VIF (variance inflation factor)</p>
<ul>
<li>How much does our estimates (SEs) change due to the correlation</li>
</ul></li>
</ul>
<p><span class="math display">\[VIF=\frac{1}{1- R^2_j}\]</span></p>
<ul>
<li><p>Rule of thumb:</p>
<ul>
<li>VIF &gt; 10 indicates issues</li>
</ul></li>
</ul>
<div class="notes">
<ul>
<li><p>VIF is the inverse of tolerance</p></li>
<li><p>“How much damage is being done?”</p></li>
<li><p>How much are standard errors inflated due to collinearity?</p></li>
<li><p>Rule of thumb: VIF &gt; 10 is trouble, some say &gt; 5</p></li>
</ul>
</div>
</section>
<section id="multicolinearity-3" class="level2">
<h2 class="anchored" data-anchor-id="multicolinearity-3">Multicolinearity</h2>
<ul>
<li>Check multicolinearity in your data</li>
</ul>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co">#easystats performance package</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="co">#plot(check_collinearity(model_fit))</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="notes">
<ul>
<li>Easy to check with <code>check_collinearity()</code></li>
<li>Our predictors look fine — low VIF values</li>
<li>No multicollinearity concerns here</li>
</ul>
</div>
</section>
<section id="multicolinearity-4" class="level2">
<h2 class="anchored" data-anchor-id="multicolinearity-4">Multicolinearity</h2>
<div class="incremental">
<ul class="incremental">
<li><p>Strategies</p>
<ul class="incremental">
<li><p>Anticipate collinearity issues at the design stage</p></li>
<li><p>Depends: Drop variable if there’s no theoretical pay-off anyway</p></li>
<li><p>Depends: Fit separate models and compare fit</p></li>
<li><p>Depends: Increase sample size</p></li>
<li><p>Depends: Orthogonalize predictors experimentally</p></li>
<li><p>Depends: Use alternative approaches, such as ridge regression or LASSO</p></li>
<li><p>Do not do anything about it (if prediction is your goal)</p></li>
</ul></li>
</ul>
</div>
<div class="notes">
<ul>
<li><p>What if you have multicollinearity?</p></li>
<li><p>Options depend on your goal</p></li>
<li><p>Drop redundant predictors, combine them into composites</p></li>
<li><p>Use regularization (ridge, LASSO)</p></li>
<li><p>Increase sample size</p></li>
<li><p>Or — if predicting is all you care about — ignore it</p></li>
<li><p>Predictions stay fine; it’s the individual coefficients that suffer</p></li>
</ul>
</div>
</section>
<section id="identifying-unusual-cases" class="level2">
<h2 class="anchored" data-anchor-id="identifying-unusual-cases">Identifying unusual cases</h2>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/out.png" class="img-fluid quarto-figure quarto-figure-center figure-img"></p>
</figure>
</div>
<div class="notes">
<ul>
<li><p>Outliers matter more in regression</p></li>
<li><p>One weird point can drag the whole line</p></li>
<li><p>We need systematic ways to find them</p></li>
</ul>
</div>
</section>
<section id="influential-points" class="level2">
<h2 class="anchored" data-anchor-id="influential-points">Influential points</h2>
<ul>
<li>An observation or case is influential if removing it substantially changes the coefficients of the regression model</li>
</ul>
<blockquote class="blockquote">
<p>Influence = Leverage x Distance (outliers)</p>
</blockquote>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/influ1.png" class="img-fluid quarto-figure quarto-figure-center figure-img"></p>
</figure>
</div>
<div class="notes">
<ul>
<li>Key formula: Influence = Leverage × Distance</li>
<li>Leverage: how extreme is the X value?</li>
<li>Distance: how far is Y from the prediction?</li>
<li>Both matter — high leverage + large residual = influential point</li>
</ul>
</div>
</section>
<section id="influential-points-1" class="level2">
<h2 class="anchored" data-anchor-id="influential-points-1">Influential points</h2>
<div class="incremental">
<ul class="incremental">
<li><p>Influential points have a large impact on the coefficients and standard errors used for inference</p>
<ul class="incremental">
<li>Can be on x or y variables</li>
</ul></li>
<li><p>These points can sometimes be identified in a scatterplot if there is only one predictor variable</p>
<ul class="incremental">
<li>This is often not the case when there are multiple predictors</li>
</ul></li>
<li><p>We will use measures to quantify an individual observation’s influence on the regression model</p>
<ul class="incremental">
<li><strong>Leverage</strong>, <strong>Standardized residuals</strong> , and <strong>Cook’s distance</strong></li>
</ul></li>
</ul>
</div>
<div class="notes">
<ul>
<li>These points mess with your coefficients and standard errors</li>
<li>With one predictor, you might spot them in a scatterplot</li>
<li>Multiple predictors? Need diagnostic measures</li>
<li>Three key measures: leverage, standardized residuals, Cook’s distance</li>
</ul>
</div>
</section>
<section id="leverage" class="level2">
<h2 class="anchored" data-anchor-id="leverage">Leverage</h2>
<ul>
<li>Deals with Xs</li>
</ul>
<blockquote class="blockquote">
<p>Measure of geometric distance of the observation’s predictor point (<span class="math inline">\(X_{i1}\)</span>, <span class="math inline">\(X_{i2}\)</span>) from center point of the predictor space</p>
</blockquote>
<p><span class="math display">\[
h_i = \dfrac{1}{n} + \dfrac{\left(x_i -\overline{x}\right)^2}{\sum_{j=1}^{n}{\left(x_j -\overline{x}\right)^2}} \qquad \text{and}\qquad \overline{h} = \dfrac{k}{n}  \qquad \text{and}\qquad \dfrac{1}{n} \leq h_i \leq 1.0
\]</span></p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>In multiple regression <span class="math inline">\(h_i\)</span> measures distance from the centroid (point of means) of Xs</p>
</div>
</div>
<div class="notes">
<ul>
<li><p>Leverage (h): how unusual is this observation’s X values?</p></li>
<li><p>Far from the center of predictor space = high leverage</p></li>
<li><p>Points on the edge of the X distribution have more “pull” on the regression line</p></li>
</ul>
</div>
</section>
<section id="leverage-1" class="level2">
<h2 class="anchored" data-anchor-id="leverage-1">Leverage</h2>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/lev.png" class="img-fluid quarto-figure quarto-figure-center figure-img"></p>
</figure>
</div>
<div class="notes">
<ul>
<li><p>Visual representation</p></li>
<li><p>Points far from the center have high leverage</p></li>
<li><p>They have more influence on where the line goes</p></li>
<li><p>Not necessarily bad — but watch them</p></li>
</ul>
</div>
</section>
<section id="leverage-2" class="level2">
<h2 class="anchored" data-anchor-id="leverage-2">Leverage</h2>
<ul>
<li>We say a point is high leverage if:</li>
</ul>
<p><span class="math display">\[
h_i &gt; \frac{2K+2}{N}
\]</span></p>
<ul>
<li><p>K is the number of predictors</p></li>
<li><p>N is the sample size</p></li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1"></a>k <span class="ot">&lt;-</span> <span class="dv">3</span> <span class="do">##number of IVs/predictors</span></span>
<span id="cb16-2"><a href="#cb16-2"></a><span class="co"># label 1 if out 0 if not</span></span>
<span id="cb16-3"><a href="#cb16-3"></a>model_out<span class="ot">&lt;-</span> model_fit  <span class="sc">%&gt;%</span></span>
<span id="cb16-4"><a href="#cb16-4"></a>  <span class="fu">augment</span>() <span class="sc">%&gt;%</span></span>
<span id="cb16-5"><a href="#cb16-5"></a>  <span class="fu">mutate</span>(<span class="at">lev_out =</span> <span class="fu">ifelse</span>(.hat<span class="sc">&gt;</span>(<span class="dv">2</span><span class="sc">*+</span><span class="dv">2</span>)<span class="sc">/</span><span class="fu">nrow</span>(.),<span class="dv">1</span>, <span class="dv">0</span>))</span>
<span id="cb16-6"><a href="#cb16-6"></a></span>
<span id="cb16-7"><a href="#cb16-7"></a>model_out</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 266 × 12
   .rownames CESD_total PIL_total AUDIT_TOTAL_NEW DAST_TOTAL_NEW .fitted .resid
   &lt;chr&gt;          &lt;dbl&gt;     &lt;dbl&gt;           &lt;dbl&gt;          &lt;int&gt;   &lt;dbl&gt;  &lt;dbl&gt;
 1 1                 28       121               1              0    8.90  19.1 
 2 2                 37        76               5              0   25.7   11.3 
 3 3                 20        98               3              0   17.5    2.51
 4 4                 15       122               3              1    9.37   5.63
 5 5                  7        99               2              0   17.2  -10.2 
 6 6                  7       134               3              0    3.76   3.24
 7 7                 27       102               2              1   17.1    9.91
 8 8                 10       124               1              0    7.76   2.24
 9 9                  9       126               1              0    6.99   2.01
10 10                 8       112               7              1   12.8   -4.82
# ℹ 256 more rows
# ℹ 5 more variables: .hat &lt;dbl&gt;, .sigma &lt;dbl&gt;, .cooksd &lt;dbl&gt;,
#   .std.resid &lt;dbl&gt;, lev_out &lt;dbl&gt;</code></pre>
</div>
</div>
<div class="notes">
<ul>
<li><p>Threshold formula: h &gt; (2k+2)/n</p></li>
<li><p>k predictors, n observations</p></li>
<li><p>The <code>.hat</code> column from <code>augment()</code> gives you leverage values</p></li>
<li><p>Compare to the threshold, flag the high ones</p></li>
<li><p>for each data point</p></li>
</ul>
</div>
</section>
<section id="standardized-residuals" class="level2">
<h2 class="anchored" data-anchor-id="standardized-residuals">Standardized Residuals</h2>
<ul>
<li>Distance
<ul>
<li>how far away y point is from line</li>
</ul></li>
</ul>
<p><span class="math display">\[
std.res_i = \frac{y_i - \hat{y}_i}{\hat{\sigma}_\epsilon\sqrt{1-h_i}}
\]</span></p>
<blockquote class="blockquote">
<p>Where <span class="math inline">\(\hat{\sigma}_\epsilon\)</span> is regression standard error</p>
</blockquote>
<ul>
<li>Use cut-off &gt; 3</li>
</ul>
<div class="notes">
<ul>
<li>Now the Y side</li>
<li>How far is each point from the line?</li>
<li>Standardized residuals account for leverage too</li>
<li>Rule: |standardized residual| &gt; 3 is suspicious</li>
</ul>
</div>
</section>
<section id="standardized-residuals-1" class="level2">
<h2 class="anchored" data-anchor-id="standardized-residuals-1">Standardized Residuals</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1"></a><span class="co"># label 1 if out 0 if not</span></span>
<span id="cb18-2"><a href="#cb18-2"></a>model_out<span class="ot">&lt;-</span> model_fit  <span class="sc">%&gt;%</span></span>
<span id="cb18-3"><a href="#cb18-3"></a>  <span class="fu">augment</span>() <span class="sc">%&gt;%</span></span>
<span id="cb18-4"><a href="#cb18-4"></a>  <span class="fu">mutate</span>(<span class="at">lev_out =</span> <span class="fu">ifelse</span>(.hat<span class="sc">&gt;</span>(<span class="dv">2</span><span class="sc">*</span>k<span class="sc">+</span><span class="dv">2</span>)<span class="sc">/</span><span class="fu">nrow</span>(.),<span class="dv">1</span>, <span class="dv">0</span>), </span>
<span id="cb18-5"><a href="#cb18-5"></a>         <span class="at">std_out=</span><span class="fu">ifelse</span>(<span class="fu">abs</span>(.std.resid) <span class="sc">&gt;</span> <span class="dv">3</span>, <span class="dv">1</span>, <span class="dv">0</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(olsrr)</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ols_plot_resid_stand</span>(model_fit)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Mul_Reg_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="1152"></p>
</figure>
</div>
</div>
</div>
<div class="notes">
<ul>
<li>Visual inspection</li>
<li>Most residuals cluster near zero</li>
<li>Outliers stick out</li>
<li>The <code>olsrr</code> package makes nice plots</li>
</ul>
</div>
</section>
<section id="leverage-and-distance" class="level2">
<h2 class="anchored" data-anchor-id="leverage-and-distance">Leverage and Distance</h2>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/lev1.png" class="img-fluid figure-img"></p>
<figcaption>Montoya</figcaption>
</figure>
</div>
<div class="notes">
<ul>
<li>Four quadrants to think about</li>
<li>Low leverage + small residual: typical points (good)</li>
<li>This is what we want most of our data to look like</li>
</ul>
</div>
</section>
<section id="leverage-and-distance-1" class="level2">
<h2 class="anchored" data-anchor-id="leverage-and-distance-1">Leverage and distance</h2>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/lev2.png" class="img-fluid figure-img"></p>
<figcaption>Montoya</figcaption>
</figure>
</div>
<div class="notes">
<ul>
<li>High leverage + small residual: unusual X but fits the pattern</li>
<li>Low leverage + large residual: unusual Y but not very influential</li>
<li>These are less concerning</li>
</ul>
</div>
</section>
<section id="leverage-and-distance-2" class="level2">
<h2 class="anchored" data-anchor-id="leverage-and-distance-2">Leverage and distance</h2>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/lev3.png" class="img-fluid figure-img"></p>
<figcaption>Montoya</figcaption>
</figure>
</div>
<div class="notes">
<ul>
<li>High leverage + large residual: TROUBLE</li>
<li>These are your influential points</li>
<li>They can dramatically change your regression line</li>
</ul>
</div>
</section>
<section id="cooks-distance" class="level2">
<h2 class="anchored" data-anchor-id="cooks-distance">Cook’s distance</h2>
<ul>
<li><p>Influence <strong>(Cook’s Distance)</strong></p>
<ul>
<li><p>A measure of how much of an effect that single case has on the whole model</p>
<ul>
<li><p>How close it lies to general line (residuals)</p></li>
<li><p>It’s leverage <span class="math display">\[
D_i = \frac{(std.res_i)^2}{k + 1}\bigg(\frac{h_i}{1-h_i}\bigg)
\]</span></p></li>
<li><p>Threshold:</p></li>
</ul></li>
</ul></li>
</ul>
<p><span class="math display">\[
\frac{4}{N-K-1}
\]</span></p>
<div class="notes">
<ul>
<li>Cook’s D combines everything</li>
<li>How much would coefficients change if we removed this point?</li>
<li>Formula incorporates both leverage and residuals</li>
<li>Threshold: 4/(n-k-1)</li>
</ul>
</div>
</section>
<section id="cooks-distance-1" class="level2">
<h2 class="anchored" data-anchor-id="cooks-distance-1">Cook’s distance</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1"></a><span class="co"># label 1 if out 0 if not</span></span>
<span id="cb20-2"><a href="#cb20-2"></a>model_out<span class="ot">&lt;-</span> model_fit  <span class="sc">%&gt;%</span></span>
<span id="cb20-3"><a href="#cb20-3"></a>  <span class="fu">augment</span>() <span class="sc">%&gt;%</span></span>
<span id="cb20-4"><a href="#cb20-4"></a>  <span class="fu">mutate</span>(<span class="at">lev_out =</span> <span class="fu">ifelse</span>(.hat<span class="sc">&gt;</span>(<span class="dv">2</span><span class="sc">*</span>k<span class="sc">+</span><span class="dv">2</span>)<span class="sc">/</span><span class="fu">nrow</span>(.),<span class="dv">1</span>, <span class="dv">0</span>),</span>
<span id="cb20-5"><a href="#cb20-5"></a>         <span class="at">std_out=</span><span class="fu">ifelse</span>(<span class="fu">abs</span>(.std.resid) <span class="sc">&gt;</span> <span class="dv">3</span>, <span class="dv">1</span>, <span class="dv">0</span>), </span>
<span id="cb20-6"><a href="#cb20-6"></a>         <span class="at">cook_out =</span> <span class="fu">ifelse</span>(.cooksd <span class="sc">&gt;</span> (<span class="dv">4</span> <span class="sc">/</span> (<span class="fu">nrow</span>(.) <span class="sc">-</span> <span class="dv">3</span> <span class="sc">-</span> <span class="dv">1</span>)), <span class="dv">1</span>, <span class="dv">0</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(olsrr)</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ols_plot_cooksd_bar</span>(model_fit)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Mul_Reg_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="1152"></p>
</figure>
</div>
</div>
</div>
<div class="notes">
<ul>
<li>Bar plot of Cook’s D</li>
<li>Tall bars = influential points</li>
<li>Easy to spot</li>
<li>Red line is threshold</li>
</ul>
</div>
</section>
<section id="combine-metrics" class="level2">
<h2 class="anchored" data-anchor-id="combine-metrics">Combine Metrics</h2>
<ul>
<li><p>What do I do with all these numbers?</p>
<ul>
<li><p>Create a total score for the number of indicators a data point has</p></li>
<li><p>You can decide what rule to use, but a suggestion is 2 or more indicators is an outliers</p></li>
</ul></li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1"></a><span class="co"># label 1 if out 0 if not</span></span>
<span id="cb22-2"><a href="#cb22-2"></a>model_out<span class="ot">&lt;-</span> model_fit  <span class="sc">%&gt;%</span></span>
<span id="cb22-3"><a href="#cb22-3"></a>  <span class="fu">augment</span>() <span class="sc">%&gt;%</span></span>
<span id="cb22-4"><a href="#cb22-4"></a>  <span class="fu">mutate</span>(<span class="at">lev_out =</span> <span class="fu">ifelse</span>(.hat<span class="sc">&gt;</span>(<span class="dv">2</span><span class="sc">*</span>k<span class="sc">+</span><span class="dv">2</span>)<span class="sc">/</span><span class="fu">nrow</span>(.),<span class="dv">1</span>, <span class="dv">0</span>), <span class="at">cook_out =</span> <span class="fu">ifelse</span>(.cooksd <span class="sc">&gt;</span> (<span class="dv">4</span> <span class="sc">/</span> (<span class="fu">nrow</span>(.) <span class="sc">-</span> <span class="dv">3</span> <span class="sc">-</span> <span class="dv">1</span>)), <span class="dv">1</span>, <span class="dv">0</span>), <span class="at">std_out=</span><span class="fu">ifelse</span>(.std.resid <span class="sc">&gt;=</span> <span class="dv">3</span>, <span class="dv">1</span>, <span class="dv">0</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb22-5"><a href="#cb22-5"></a>  <span class="fu">rowwise</span>() <span class="sc">%&gt;%</span></span>
<span id="cb22-6"><a href="#cb22-6"></a>  <span class="fu">mutate</span>(<span class="at">sum_out=</span>lev_out<span class="sc">+</span>cook_out<span class="sc">+</span>std_out) <span class="sc">%&gt;%</span></span>
<span id="cb22-7"><a href="#cb22-7"></a>  <span class="fu">filter</span>(sum_out <span class="sc">&lt;</span> <span class="dv">2</span>)</span>
<span id="cb22-8"><a href="#cb22-8"></a></span>
<span id="cb22-9"><a href="#cb22-9"></a></span>
<span id="cb22-10"><a href="#cb22-10"></a><span class="fu">nrow</span>(nomiss)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 266</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1"></a><span class="fu">nrow</span>(model_out)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 255</code></pre>
</div>
</div>
<div class="notes">
<ul>
<li>Multiple indicators, multiple decisions</li>
<li>My suggestion: flag points that exceed 2+ thresholds</li>
<li>More robust than any single measure</li>
<li>Create a sum score, filter out the problems</li>
</ul>
</div>
</section>
<section id="easystats-check_outliers" class="level2">
<h2 class="anchored" data-anchor-id="easystats-check_outliers"><code>Easystats: Check_outliers</code></h2>
<ul>
<li><p>Use consensus method</p>
<ul>
<li>If half of methods say point is outlier, get rid of it</li>
</ul></li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co"># will estimate all outliers methods</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>outliers_list <span class="ot">&lt;-</span> <span class="fu">check_outliers</span>(model_fit, <span class="at">method =</span> <span class="st">"all"</span>)</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a><span class="co"># provides a col called outliers with prob of outliers by method (50% more than half said ob was outlier)</span></span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a>out_data <span class="ot">&lt;-</span>insight<span class="sc">::</span><span class="fu">get_data</span>(model_fit)[outliers_list, ] <span class="co"># Show outliers data</span></span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-8"><a href="#cb26-8" aria-hidden="true" tabindex="-1"></a><span class="co"># get rid of values in outliers list in the main dataset </span></span>
<span id="cb26-9"><a href="#cb26-9" aria-hidden="true" tabindex="-1"></a>clean_data <span class="ot">&lt;-</span> <span class="fu">anti_join</span>(nomiss,out_data, <span class="at">by=</span><span class="fu">c</span>(<span class="st">"CESD_total"</span>, <span class="st">"PIL_total"</span>, <span class="st">"AUDIT_TOTAL_NEW"</span>, <span class="st">"DAST_TOTAL_NEW"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="notes">
<ul>
<li>Even easier: <code>check_outliers()</code> with method = “all”</li>
<li>Uses multiple methods</li>
<li>Consensus approach: if half the methods flag it, remove it</li>
<li>Clean and principled</li>
</ul>
</div>
</section>
<section id="refit-model" class="level2">
<h2 class="anchored" data-anchor-id="refit-model">Refit model</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>model_fit <span class="ot">&lt;-</span> <span class="fu">lm</span>(CESD_total <span class="sc">~</span> PIL_total <span class="sc">+</span> AUDIT_TOTAL_NEW <span class="sc">+</span> DAST_TOTAL_NEW,</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>             <span class="at">data =</span> clean_data) </span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="notes">
<ul>
<li>After removing outliers, refit</li>
<li>Now we have clean data</li>
<li>Our inferences will be more trustworthy</li>
</ul>
</div>
</section>
<section id="assumptions" class="level2">
<h2 class="anchored" data-anchor-id="assumptions">Assumptions</h2>
<ul>
<li><p>Linearity</p></li>
<li><p>Independence</p></li>
<li><p>Normality of residuals</p></li>
<li><p>Equal error (“homoskedasticity”)</p></li>
</ul>
<p>. . .</p>
<ul>
<li><strong>Additivity (more than one variable)</strong></li>
</ul>
<div class="notes">
<ul>
<li>Back to basics</li>
<li>Linearity, independence, normality, homoskedasticity</li>
<li>Plus one new one for multiple regression: additivity</li>
<li>Effects of predictors shouldn’t depend on each other — unless you model interactions</li>
</ul>
</div>
</section>
<section id="assumptions-1" class="level2">
<h2 class="anchored" data-anchor-id="assumptions-1">Assumptions</h2>
<ul>
<li><p>Additivity</p>
<ul>
<li><p>Implies that for an existing model, the effect of a predictor on a response variable (whether it be linear or non-linear) is not affected by changes in other existing predictors</p>
<ul>
<li>Add interaction if not the case</li>
</ul></li>
</ul></li>
</ul>
<div class="notes">
<ul>
<li>Additivity means: effect of X₁ doesn’t change across levels of X₂</li>
<li>If it does, you need an interaction term</li>
<li>We’ll cover interactions later</li>
</ul>
</div>
</section>
<section id="assumptions-2" class="level2">
<h2 class="anchored" data-anchor-id="assumptions-2">Assumptions</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>performance<span class="sc">::</span><span class="fu">check_model</span>(model_fit, <span class="at">check=</span><span class="fu">c</span>(<span class="st">"normality"</span>, <span class="st">"linearity"</span>, <span class="st">"homogeneity"</span>, <span class="st">"qq"</span>, <span class="st">"vif"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Mul_Reg_files/figure-html/unnamed-chunk-22-1.png" class="img-fluid figure-img" width="1152"></p>
</figure>
</div>
</div>
</div>
<div class="notes">
<ul>
<li><code>check_model()</code> gives you everything</li>
<li>Visual diagnostics for all assumptions at once</li>
<li>Look for patterns in residuals</li>
</ul>
</div>
</section>
<section id="violation-assumptions" class="level2">
<h2 class="anchored" data-anchor-id="violation-assumptions">Violation Assumptions</h2>
<ul>
<li><p>Normality (more on this next week)</p></li>
<li><p>Homoskedasticity</p></li>
</ul>
<div class="notes">
<ul>
<li>Two common violations: non-normality and heteroskedasticity</li>
<li>We’ll focus on heteroskedasticity today</li>
<li>Normality next week</li>
</ul>
</div>
</section>
<section id="heteroskedasticity" class="level2">
<h2 class="anchored" data-anchor-id="heteroskedasticity">Heteroskedasticity</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">check_heteroscedasticity</span>(model_fit)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Warning: Heteroscedasticity (non-constant error variance) detected (p = 0.001).</code></pre>
</div>
</div>
<ul>
<li><p>We can use robust SEs</p></li>
<li><p>They work by changing the covariance matrix (the diagonal is the variance)</p>
<p><span class="math display">\[
\text{Var}(\epsilon) = \sigma^2 I_n = \sigma^2
\begin{bmatrix}
1 &amp; 0 &amp; \cdots &amp; 0 \\
0 &amp; 1 &amp; \cdots &amp; 0 \\
\vdots &amp; \vdots &amp; \ddots &amp; \vdots \\
0 &amp; 0 &amp; \cdots &amp; 1
\end{bmatrix}
\]</span></p></li>
</ul>
<div class="notes">
<ul>
<li><code>check_heteroscedasticity()</code> detected a problem (p = .001)</li>
<li>Variance isn’t constant — our standard errors are wrong</li>
<li>Solution: robust standard errors</li>
<li>They adjust the covariance matrix</li>
</ul>
</div>
</section>
<section id="heteroskedasticity-1" class="level2">
<h2 class="anchored" data-anchor-id="heteroskedasticity-1">Heteroskedasticity</h2>
<p><span class="math display">\[
D_{\text{HC3}} =
\begin{bmatrix}
\frac{\epsilon_1^2}{(1-h_{11})^2} &amp; 0 &amp; \cdots &amp; 0 \\
0 &amp; \frac{\epsilon_2^2}{(1-h_{22})^2} &amp; \cdots &amp; 0 \\
\vdots &amp; \vdots &amp; \ddots &amp; \vdots \\
0 &amp; 0 &amp; \cdots &amp; \frac{\epsilon_n^2}{(1-h_{nn})^2}
\end{bmatrix}
\]</span></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(easystats) <span class="co"># model_paramters function</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a><span class="co">#fit model first then read into function</span></span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>mp <span class="ot">&lt;-</span> <span class="fu">model_parameters</span>(model_fit, <span class="at">vcov =</span> <span class="st">"HC3"</span>)</span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a>mp</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Parameter       | Coefficient |   SE |         95% CI | t(256) |      p
-----------------------------------------------------------------------
(Intercept)     |       57.65 | 4.16 | [49.45, 65.84] |  13.85 | &lt; .001
PIL total       |       -0.40 | 0.04 | [-0.47, -0.33] | -11.32 | &lt; .001
AUDIT TOTAL NEW |       -0.10 | 0.09 | [-0.28,  0.07] |  -1.18 | 0.240 
DAST TOTAL NEW  |        0.89 | 0.48 | [-0.06,  1.84] |   1.85 | 0.066 </code></pre>
</div>
</div>
<div class="notes">
<ul>
<li>HC3 is the gold standard for robust SEs</li>
<li>Corrects the covariance matrix</li>
<li>Same coefficients, different (usually larger) standard errors</li>
<li>More honest inference</li>
</ul>
</div>
</section>
<section id="refit-model-1" class="level2">
<h2 class="anchored" data-anchor-id="refit-model-1">Refit Model</h2>
<ul>
<li>Fit model on clean dataset with outliers removed</li>
</ul>
<div class="cell">
<div class="cell-output-display">
<table class="table caption-top table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Parameter</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Coefficient</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">SE</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">CI</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">CI_low</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">CI_high</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">t</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">df_error</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">p</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">57.6453027</td>
<td style="text-align: right;">4.1612337</td>
<td style="text-align: right;">0.95</td>
<td style="text-align: right;">49.4506937</td>
<td style="text-align: right;">65.8399117</td>
<td style="text-align: right;">13.852935</td>
<td style="text-align: right;">256</td>
<td style="text-align: right;">0.0000000</td>
</tr>
<tr class="even">
<td style="text-align: left; color: white !important; background-color: red !important;">PIL_total</td>
<td style="text-align: right; color: white !important; background-color: red !important;">-0.4017946</td>
<td style="text-align: right; color: white !important; background-color: red !important;">0.0354963</td>
<td style="text-align: right; color: white !important; background-color: red !important;">0.95</td>
<td style="text-align: right; color: white !important; background-color: red !important;">-0.4716965</td>
<td style="text-align: right; color: white !important; background-color: red !important;">-0.3318927</td>
<td style="text-align: right; color: white !important; background-color: red !important;">-11.319347</td>
<td style="text-align: right; color: white !important; background-color: red !important;">256</td>
<td style="text-align: right; color: white !important; background-color: red !important;">0.0000000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">AUDIT_TOTAL_NEW</td>
<td style="text-align: right;">-0.1030182</td>
<td style="text-align: right;">0.0874974</td>
<td style="text-align: right;">0.95</td>
<td style="text-align: right;">-0.2753246</td>
<td style="text-align: right;">0.0692882</td>
<td style="text-align: right;">-1.177385</td>
<td style="text-align: right;">256</td>
<td style="text-align: right;">0.2401352</td>
</tr>
<tr class="even">
<td style="text-align: left;">DAST_TOTAL_NEW</td>
<td style="text-align: right;">0.8902347</td>
<td style="text-align: right;">0.4822412</td>
<td style="text-align: right;">0.95</td>
<td style="text-align: right;">-0.0594303</td>
<td style="text-align: right;">1.8398998</td>
<td style="text-align: right;">1.846036</td>
<td style="text-align: right;">256</td>
<td style="text-align: right;">0.0660414</td>
</tr>
</tbody>
</table>
</div>
</div>
<p><span class="math inline">\(b_1\)</span>:</p>
<div class="notes">
<ul>
<li>Results with robust SEs</li>
<li>Notice the standard errors changed, p-values changed too</li>
<li>Meaning: b = -0.40, still significant, still the strongest predictor</li>
</ul>
</div>
</section>
<section id="interpretation" class="level2">
<h2 class="anchored" data-anchor-id="interpretation">Interpretation</h2>
<div class="cell">
<div class="cell-output-display">
<table class="table caption-top table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Parameter</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Coefficient</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">SE</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">CI</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">CI_low</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">CI_high</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">t</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">df_error</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">p</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">57.6453027</td>
<td style="text-align: right;">4.1612337</td>
<td style="text-align: right;">0.95</td>
<td style="text-align: right;">49.4506937</td>
<td style="text-align: right;">65.8399117</td>
<td style="text-align: right;">13.852935</td>
<td style="text-align: right;">256</td>
<td style="text-align: right;">0.0000000</td>
</tr>
<tr class="even">
<td style="text-align: left;">PIL_total</td>
<td style="text-align: right;">-0.4017946</td>
<td style="text-align: right;">0.0354963</td>
<td style="text-align: right;">0.95</td>
<td style="text-align: right;">-0.4716965</td>
<td style="text-align: right;">-0.3318927</td>
<td style="text-align: right;">-11.319347</td>
<td style="text-align: right;">256</td>
<td style="text-align: right;">0.0000000</td>
</tr>
<tr class="odd">
<td style="text-align: left; color: white !important; background-color: red !important;">AUDIT_TOTAL_NEW</td>
<td style="text-align: right; color: white !important; background-color: red !important;">-0.1030182</td>
<td style="text-align: right; color: white !important; background-color: red !important;">0.0874974</td>
<td style="text-align: right; color: white !important; background-color: red !important;">0.95</td>
<td style="text-align: right; color: white !important; background-color: red !important;">-0.2753246</td>
<td style="text-align: right; color: white !important; background-color: red !important;">0.0692882</td>
<td style="text-align: right; color: white !important; background-color: red !important;">-1.177385</td>
<td style="text-align: right; color: white !important; background-color: red !important;">256</td>
<td style="text-align: right; color: white !important; background-color: red !important;">0.2401352</td>
</tr>
<tr class="even">
<td style="text-align: left;">DAST_TOTAL_NEW</td>
<td style="text-align: right;">0.8902347</td>
<td style="text-align: right;">0.4822412</td>
<td style="text-align: right;">0.95</td>
<td style="text-align: right;">-0.0594303</td>
<td style="text-align: right;">1.8398998</td>
<td style="text-align: right;">1.846036</td>
<td style="text-align: right;">256</td>
<td style="text-align: right;">0.0660414</td>
</tr>
</tbody>
</table>
</div>
</div>
<p><span class="math inline">\(b_2\)</span>:</p>
<div class="notes">
<ul>
<li>Alcohol: b = -0.10</li>
<li>Still not significant</li>
<li>Alcohol doesn’t predict depression after controlling for meaning and drugs</li>
</ul>
</div>
</section>
<section id="interpretation-1" class="level2">
<h2 class="anchored" data-anchor-id="interpretation-1">Interpretation</h2>
<div class="cell">
<div class="cell-output-display">
<table class="table caption-top table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Parameter</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Coefficient</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">SE</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">CI</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">CI_low</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">CI_high</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">t</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">df_error</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">p</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">57.6453027</td>
<td style="text-align: right;">4.1612337</td>
<td style="text-align: right;">0.95</td>
<td style="text-align: right;">49.4506937</td>
<td style="text-align: right;">65.8399117</td>
<td style="text-align: right;">13.852935</td>
<td style="text-align: right;">256</td>
<td style="text-align: right;">0.0000000</td>
</tr>
<tr class="even">
<td style="text-align: left;">PIL_total</td>
<td style="text-align: right;">-0.4017946</td>
<td style="text-align: right;">0.0354963</td>
<td style="text-align: right;">0.95</td>
<td style="text-align: right;">-0.4716965</td>
<td style="text-align: right;">-0.3318927</td>
<td style="text-align: right;">-11.319347</td>
<td style="text-align: right;">256</td>
<td style="text-align: right;">0.0000000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">AUDIT_TOTAL_NEW</td>
<td style="text-align: right;">-0.1030182</td>
<td style="text-align: right;">0.0874974</td>
<td style="text-align: right;">0.95</td>
<td style="text-align: right;">-0.2753246</td>
<td style="text-align: right;">0.0692882</td>
<td style="text-align: right;">-1.177385</td>
<td style="text-align: right;">256</td>
<td style="text-align: right;">0.2401352</td>
</tr>
<tr class="even">
<td style="text-align: left; color: white !important; background-color: red !important;">DAST_TOTAL_NEW</td>
<td style="text-align: right; color: white !important; background-color: red !important;">0.8902347</td>
<td style="text-align: right; color: white !important; background-color: red !important;">0.4822412</td>
<td style="text-align: right; color: white !important; background-color: red !important;">0.95</td>
<td style="text-align: right; color: white !important; background-color: red !important;">-0.0594303</td>
<td style="text-align: right; color: white !important; background-color: red !important;">1.8398998</td>
<td style="text-align: right; color: white !important; background-color: red !important;">1.846036</td>
<td style="text-align: right; color: white !important; background-color: red !important;">256</td>
<td style="text-align: right; color: white !important; background-color: red !important;">0.0660414</td>
</tr>
</tbody>
</table>
</div>
</div>
<ul>
<li><span class="math inline">\(b_3\)</span>:</li>
</ul>
<div class="notes">
<ul>
<li>Drugs: b = 0.89</li>
<li>Now marginal with robust SEs (p = .066)</li>
<li>The relationship is there but less certain</li>
</ul>
</div>
</section>
<section id="predictors" class="level2">
<h2 class="anchored" data-anchor-id="predictors">Predictors</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(papaja)</span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>apa_style <span class="ot">&lt;-</span> <span class="fu">apa_print</span>(model_fit)</span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a>apa_style</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>$estimate
$estimate$Intercept
[1] "$b = 57.65$, 95\\% CI $[49.82, 65.47]$"

$estimate$PIL_total
[1] "$b = -0.40$, 95\\% CI $[-0.47, -0.33]$"

$estimate$AUDIT_TOTAL_NEW
[1] "$b = -0.10$, 95\\% CI $[-0.29, 0.09]$"

$estimate$DAST_TOTAL_NEW
[1] "$b = 0.89$, 95\\% CI $[-0.10, 1.88]$"

$estimate$modelfit
$estimate$modelfit$r2
[1] "$R^2 = .37$, 90\\% CI $[0.28, 0.44]$"

$estimate$modelfit$r2_adj
[1] "$R^2_{adj} = .36$"

$estimate$modelfit$aic
[1] "$\\mathrm{AIC} = 1,787.29$"

$estimate$modelfit$bic
[1] "$\\mathrm{BIC} = 1,805.10$"



$statistic
$statistic$Intercept
[1] "$t(256) = 14.50$, $p &lt; .001$"

$statistic$PIL_total
[1] "$t(256) = -11.63$, $p &lt; .001$"

$statistic$AUDIT_TOTAL_NEW
[1] "$t(256) = -1.08$, $p = .283$"

$statistic$DAST_TOTAL_NEW
[1] "$t(256) = 1.77$, $p = .077$"

$statistic$modelfit
$statistic$modelfit$r2
[1] "$F(3, 256) = 49.58$, $p &lt; .001$"



$full_result
$full_result$Intercept
[1] "$b = 57.65$, 95\\% CI $[49.82, 65.47]$, $t(256) = 14.50$, $p &lt; .001$"

$full_result$PIL_total
[1] "$b = -0.40$, 95\\% CI $[-0.47, -0.33]$, $t(256) = -11.63$, $p &lt; .001$"

$full_result$AUDIT_TOTAL_NEW
[1] "$b = -0.10$, 95\\% CI $[-0.29, 0.09]$, $t(256) = -1.08$, $p = .283$"

$full_result$DAST_TOTAL_NEW
[1] "$b = 0.89$, 95\\% CI $[-0.10, 1.88]$, $t(256) = 1.77$, $p = .077$"

$full_result$modelfit
$full_result$modelfit$r2
[1] "$R^2 = .37$, 90\\% CI $[0.28, 0.44]$, $F(3, 256) = 49.58$, $p &lt; .001$"



$table
A data.frame with 6 labelled columns:

             term estimate       conf.int statistic  df p.value
1       Intercept    57.65 [49.82, 65.47]     14.50 256  &lt; .001
2       PIL total    -0.40 [-0.47, -0.33]    -11.63 256  &lt; .001
3 AUDIT TOTAL NEW    -0.10  [-0.29, 0.09]     -1.08 256    .283
4  DAST TOTAL NEW     0.89  [-0.10, 1.88]      1.77 256    .077

term     : Predictor 
estimate : $b$ 
conf.int : 95\\% CI 
statistic: $t$ 
df       : $\\mathit{df}$ 
p.value  : $p$ 
attr(,"class")
[1] "apa_results" "list"       </code></pre>
</div>
</div>
<ul>
<li>Meaning: <span class="math inline">\(b = -0.40\)</span>, 95% CI <span class="math inline">\([-0.47, -0.33]\)</span>, <span class="math inline">\(t(256) = -11.63\)</span>, <span class="math inline">\(p &lt; .001\)</span></li>
<li>Alcohol: <span class="math inline">\(b = -0.10\)</span>, 95% CI <span class="math inline">\([-0.29, 0.09]\)</span>, <span class="math inline">\(t(256) = -1.08\)</span>, <span class="math inline">\(p = .283\)</span></li>
<li>Drugs: <span class="math inline">\(b = 0.89\)</span>, 95% CI <span class="math inline">\([-0.10, 1.88]\)</span>, <span class="math inline">\(t(256) = 1.77\)</span>, <span class="math inline">\(p = .077\)</span></li>
</ul>
<div class="notes">
<ul>
<li><code>papaja</code> formats everything for you</li>
<li>Copy-paste into your paper</li>
<li>No manual formatting errors</li>
</ul>
</div>
</section>
<section id="overall-model-fit" class="level2">
<h2 class="anchored" data-anchor-id="overall-model-fit">Overall Model Fit</h2>
<ul>
<li>Is the overall model significant?</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>apa_style <span class="ot">&lt;-</span> <span class="fu">apa_print</span>(model_fit)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<ul>
<li><span class="math inline">\(R^2 = .37\)</span>, 90% CI <span class="math inline">\([0.28, 0.44]\)</span>, <span class="math inline">\(F(3, 256) = 49.58\)</span>, <span class="math inline">\(p &lt; .001\)</span></li>
</ul>
<div class="notes">
<ul>
<li>The whole model: R² = .37</li>
<li>F-test significant</li>
<li>Our three predictors together explain 37% of depression variance</li>
<li>Is that good? For psychological data, that’s solid</li>
</ul>
</div>
</section>
<section id="adjusted-r2" class="level2">
<h2 class="anchored" data-anchor-id="adjusted-r2">Adjusted <span class="math inline">\(R^2\)</span></h2>
<p><span class="math display">\[
\large R_{A}^2 = 1 - (1 -R^2)\frac{n-1}{n-p-1}
\]</span></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glance</span>(model_fit) <span class="sc">%&gt;%</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>    knitr<span class="sc">::</span><span class="fu">kable</span>() <span class="sc">%&gt;%</span></span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">kable_styling</span>(<span class="at">font_size =</span> <span class="dv">24</span>) <span class="sc">%&gt;%</span></span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a> <span class="fu">column_spec</span>(<span class="dv">2</span>, <span class="at">color =</span> <span class="st">"white"</span>,</span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a>              <span class="at">background =</span> <span class="st">"red"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<table class="table caption-top table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: right;" data-quarto-table-cell-role="th">r.squared</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">adj.r.squared</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">sigma</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">statistic</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">p.value</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">df</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">logLik</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">AIC</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">BIC</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">deviance</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">df.residual</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">nobs</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">0.3675175</td>
<td style="text-align: right; color: white !important; background-color: red !important;">0.3601056</td>
<td style="text-align: right;">7.438596</td>
<td style="text-align: right;">49.58476</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">-888.6458</td>
<td style="text-align: right;">1787.292</td>
<td style="text-align: right;">1805.095</td>
<td style="text-align: right;">14165.17</td>
<td style="text-align: right;">256</td>
<td style="text-align: right;">260</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="notes">
<ul>
<li>Adjusted R² penalizes for adding predictors</li>
<li>Regular R² always increases with more variables — even useless ones</li>
<li>Adjusted R² can decrease</li>
<li>Keeps us honest</li>
</ul>
</div>
</section>
<section id="effect-size" class="level2">
<h2 class="anchored" data-anchor-id="effect-size">Effect size</h2>
<div class="columns">
<div class="column" style="width:50%;">
<ul>
<li>R is the multiple correlation</li>
<li><span class="math inline">\(R^2\)</span> is the multiple correlation squared
<ul>
<li>All overlap in Y used for overall model</li>
<li><span class="math inline">\(A+B+C/(A+B+C+D)\)</span></li>
</ul></li>
</ul>
</div><div class="column" style="width:50%;">
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="https://brendanhcullen.github.io/psy612/lectures/images/venn/Slide3.jpeg" class="img-fluid quarto-figure quarto-figure-center figure-img"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
<div class="notes">
<ul>
<li>Venn diagram view</li>
<li>R² is the total overlap between predictors and outcome</li>
<li>A + B + C in the diagram</li>
<li>Shared and unique variance lumped together</li>
</ul>
</div>
</section>
<section id="effect-size-1" class="level2">
<h2 class="anchored" data-anchor-id="effect-size-1">Effect Size</h2>
<div class="columns">
<div class="column" style="width:50%;">
<ul>
<li>sr is the semipartial correlation
<ul>
<li>It represents (when squared) the proportion of (unique) variance accounted for by the predictor, relative to the total variance of Y
<ul>
<li>Increase in proportion of explained Y variance when X is added
<ul>
<li>How much does X add over and beyond other variables</li>
</ul></li>
</ul></li>
</ul></li>
</ul>
</div><div class="column" style="width:50%;">
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="https://brendanhcullen.github.io/psy612/lectures/images/venn/Slide4.jpeg" class="img-fluid quarto-figure quarto-figure-center figure-img"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
<div class="notes">
<ul>
<li>Semipartial correlation (sr): unique contribution</li>
<li>How much does this predictor add beyond the others?</li>
<li>The sliver that’s only X₁, not shared with X₂</li>
<li>Squared gives you proportion of total Y variance uniquely explained</li>
</ul>
</div>
<hr>
<!-- ## Effect Size -->
<!-- ::::: columns -->
<!-- ::: {.column width="50%"} -->
<!-- -   $pr$ is the partial correlation -->
<!--     -   When squared, proportion of variance not explained by other -->
<!--         predictors but just X -->
<!--         -   Removes influence of other variables -->
<!-- -   Pr \> sr -->
<!-- ::: -->
<!-- ::: {.column width="50%"} -->
<!-- ```{r} -->
<!-- #| echo: false -->
<!-- #| fig-align: center -->
<!-- #| fig-height: 2 -->
<!-- #| fig-width: 4 -->
<!-- #|  -->
<!-- knitr::include_graphics("https://brendanhcullen.github.io/psy612/lectures/images/venn/Slide5.jpeg") -->
<!-- knitr::include_graphics("https://brendanhcullen.github.io/psy612/lectures/images/venn/Slide6.jpeg") -->
<!-- ``` -->
<!-- ::: -->
<!-- ::::: -->
<!-- ::: notes -->
<!-- -   Partial correlation (pr): different denominator -->
<!-- -   Proportion of *unexplained* variance that this predictor captures -->
<!-- -   pr \> sr always -->
<!-- -   Different questions, different uses -->
<!-- ::: -->
<!-- ## When to use? -->
<!-- -   $sr^2$ -->
<!--     -   Most often used when we want to show that some variable adds -->
<!--         incremental variance in Y above and beyond another X variable -->
<!-- -   $pr^2$ -->
<!--     -   Remove influence of another variable -->
<!-- ::: notes -->
<!-- -   sr² for "incremental validity" — does this variable add anything? -->
<!-- -   pr² for "what's the relationship after removing confounds?" -->
<!-- -   Choose based on your research question -->
<!-- ::: -->
<!-- ## Partial correlations -->
<!-- ```{r} -->
<!-- cor <- cor(clean_data[2:5]) -->
<!-- #partial corr from easystats -->
<!-- correlation::cor_to_pcor(cor)^2 -->
<!-- #semipartial you need the covariance  -->
<!-- #cor_to_spcor(cor, cov = sapply(clean_data[2:5], sd)) -->
<!-- ``` -->
<!-- ::: notes -->
<!-- -   `correlation::cor_to_pcor()` gives partial correlations -->
<!-- -   Square them for pr² -->
<!-- -   For semipartial, use `r2_semipartial()` from easystats -->
<!-- ::: -->
<!-- ## Partial correlations -->
<!-- -   Can use your model to get $sr^2$ -->
<!-- ```{r} -->
<!-- #input model to semi-partial -->
<!-- r2_semipartial(model_fit) -->
<!-- ``` -->
<!-- ::: notes -->
<!-- -   sr² for meaning = .33 -->
<!-- -   That's huge — one-third of depression variance is uniquely explained -->
<!--     by meaning in life -->
<!-- -   Alcohol and drugs contribute almost nothing uniquely -->
<!-- ::: -->
<!-- ## Partial correlations -->
<!-- -   We would add these to our other reports: -->
<!--     -   Meaning: $b = -0.40$, 95\% CI $[-0.47, -0.33]$, $t(256) = -11.63$, $p < .001$, $pr^2 = .33$\` -->
<!--     -   Alcohol: $b = -0.10$, 95\% CI $[-0.29, 0.09]$, $t(256) = -1.08$, $p = .283$, -->
<!--         $pr^2 = .02$\` -->
<!--     -   Drugs: $b = 0.89$, 95\% CI $[-0.10, 1.88]$, $t(256) = 1.77$, $p = .077$, $pr^2 = .03$\` -->
<!-- ::: callout-note -->
<!-- $pr^2$: 33% of variance in Depression is explained by meaning that is -->
<!-- not explained by the other variables -->
<!-- $sr^2$: 3% of variance in depression can be uniquely explained by -->
<!-- meaning above and beyond the other vars. -->
<!-- ::: -->
<!-- ::: notes -->
<!-- -   Report both the coefficient and the effect size -->
<!-- -   b tells you the unit change -->
<!-- -   sr² tells you the importance -->
<!-- -   Both matter -->
<!-- ::: -->
<!-- ## Multiple Regression: Power -->
<!-- ```{r echo=TRUE, message=FALSE, warning=FALSE} -->
<!-- R2<-glance(model_fit) -->
<!-- R2 <- R2$adj.r.squared -->
<!-- f2 <- R2 / (1-R2) -->
<!-- WebPower::wp.regression(n=72, p1=3, p2=0, f2=f2, alpha=.05, power=NULL) -->
<!-- ``` -->
<!-- ::: notes -->
<!-- -   Power analysis for multiple regression -->
<!-- -   Convert R² to f² -->
<!-- -   Use `WebPower` package -->
<!-- -   With n = 72 and our effect size, power is nearly 1.0 -->
<!-- -   We're well-powered -->
<!-- ::: -->
</section>
<section id="plotting" class="level1">
<h1>Plotting</h1>
<div class="notes">
<ul>
<li>Section break</li>
<li>Let’s visualize our results</li>
</ul>
</div>
<section id="partial-regression-plots" class="level2">
<h2 class="anchored" data-anchor-id="partial-regression-plots">Partial regression plots</h2>
<ul>
<li>Must partial out other factors by setting them to some value (usually mean)</li>
</ul>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggeffects)</span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a><span class="co">#will hold all other vars at mean level </span></span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>dat <span class="ot">&lt;-</span><span class="fu">ggpredict</span>(model_fit, <span class="at">terms=</span><span class="fu">c</span>(<span class="st">"PIL_total"</span>)) </span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a><span class="co">#add raw data points to plot</span></span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(dat, <span class="at">show_data=</span><span class="cn">TRUE</span>) <span class="sc">+</span> <span class="fu">theme_minimal</span>(<span class="at">base_size=</span><span class="dv">20</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Mul_Reg_files/figure-html/unnamed-chunk-33-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="1152"></p>
</figure>
</div>
</div>
</div>
<div class="notes">
<ul>
<li>Can’t just plot X vs Y anymore — other predictors confound things</li>
<li>Partial regression plots hold other variables at their means</li>
<li>Shows the unique relationship</li>
<li><code>ggeffects</code> makes this easy</li>
</ul>
</div>
</section>
<section id="write-up" class="level2">
<h2 class="anchored" data-anchor-id="write-up">Write-up</h2>
<p>We fitted a linear model(estimated using OLS) to predictCESD_total with PIL_total,AUDIT_TOTAL_NEW andDAST_TOTAL_NEW (formula:CESD_total ~ PIL_total +AUDIT_TOTAL_NEW +DAST_TOTAL_NEW). The model explains a statistically significant and substantial proportion of variance (R2 =0.36, F(3, 262) = 48.84, p &lt;.001, adj. R2 = 0.35).</p>
<ul>
<li>Meaning: <span class="math inline">\(b = -0.40\)</span>, 95% CI <span class="math inline">\([-0.47, -0.33]\)</span>, <span class="math inline">\(t(256) = -11.63\)</span>, <span class="math inline">\(p &lt; .001\)</span>, <span class="math inline">\(pr^2 = .35\)</span>`</li>
<li>Alcohol: <span class="math inline">\(b = -0.10\)</span>, 95% CI <span class="math inline">\([-0.29, 0.09]\)</span>, <span class="math inline">\(t(256) = -1.08\)</span>, <span class="math inline">\(p = .283\)</span>, <span class="math inline">\(pr^2 = .02\)</span>`</li>
<li>Drugs: <span class="math inline">\(b = 0.89\)</span>, 95% CI <span class="math inline">\([-0.10, 1.88]\)</span>, <span class="math inline">\(t(256) = 1.77\)</span>, <span class="math inline">\(p = .077\)</span>, <span class="math inline">\(pr^2 = .03\)</span>`</li>
</ul>
<div class="notes">
<ul>
<li>Putting it all together</li>
<li>State the model, report R² and F-test</li>
<li>Then each predictor with b, CI, t, p, and effect size</li>
<li>This is publication-ready</li>
</ul>
</div>
</section>
<section id="oh-btw-ancova-vs-mr" class="level2">
<h2 class="anchored" data-anchor-id="oh-btw-ancova-vs-mr">Oh btw, ANCOVA vs MR</h2>
<p><img src="images/clipboard-1027189369.png" class="img-fluid"></p>
<div class="notes">
<ul>
<li><p>I’d shown this before</p></li>
<li><p>MR and ANCOVA are the same. but the emphasis is different</p></li>
<li><p>ANCOVA: Group difference after controlling for noise (another predictor u actually don’t care about)</p></li>
<li><p>MR: How do the predictors together explain the outcome</p></li>
</ul>
</div>
</section>
<section id="ancova-vs-mr" class="level2">
<h2 class="anchored" data-anchor-id="ancova-vs-mr">ANCOVA vs MR</h2>
<p><img src="images/clipboard-3775470264.png" class="img-fluid"></p>
</section>
<section id="ancova-vs-mr-1" class="level2">
<h2 class="anchored" data-anchor-id="ancova-vs-mr-1">ANCOVA vs MR</h2>
<ul>
<li><p>Multiple Regression are the same.</p></li>
<li><p>But the emphasis is different with respect to the research question</p></li>
</ul>
<p>– ANCOVA: Group difference after controlling for noise (another predictor u actually don’t care about)</p>
<p>– MR: How do the predictors together explain the outcome</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>