{
  "hash": "3abf6afc2896bbeebdde5edb0d444682",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Lab: Bayes and Penguins (Part 2)\"\nsubtitle: \"PSY 504: Advanced Statistics\"\nauthor: \"Your Name\"\ndate: '2026-04-08'\nformat:\n  html:\n    code-fold: true\n    code-overflow: wrap\n    toc: true\n    toc-depth: 2\n    toc-location: left\nexecute:\n  message: false\n  warning: false\nengine: knitr\n---\n\n⬇️ [Download the .qmd](https://github.com/suyoghc/PSY504_Spring_2026/raw/main/posts/Bayes%202/Bayes_Lab_3_questions.qmd)\n\n::: callout-note\n## Continuing from last week\nThis lab picks up where Part 1 left off ([HTML](Bayes_Lab_2_Penguins.html), [QMD](https://github.com/suyoghc/PSY504_Spring_2026/raw/main/posts/Bayes%202/Bayes_Lab_2_Penguins.qmd)). You'll need the same packages and Chinstrap data from last week.\n:::\n\n::: callout-important\n## How to work through this lab\n\nYou will explore distributions, model checking, and priors using `brms`.\n\n1.  Read and run through each code chunk, making sure you understand what it does before moving on.\n2.  Some questions have a **hidden answer you can reveal** after writing your own response. These cover concepts that later questions build on, so check your understanding before moving on.\n3.  Other questions are **open**: no answer is provided. By that point, the walkthrough has given you enough context to reason through them on your own.\n4.  Write your responses in the code chunks marked `# Enter your answer here` (use R comments for text answers). For coding exercises, write your code in chunks marked `# Enter your code here`.\n:::\n\n# Part 3: Distributions all the way down\n\nIn Part 1, you explored the data and fit models with `lm()` and `brm()` (using default priors). You also drew posterior samples. Now we continue with distributions and priors.\n\n## Setup\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\nlibrary(tidyverse)\nlibrary(brms)\nlibrary(tidybayes)\nlibrary(ggdist)\n```\n:::\n\n\n## Packages and data\n\nWe want the same data set up as in the last lab.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# load the penguins data\ndata(penguins, package = \"palmerpenguins\")\n\n# subset the data\nchinstrap <- penguins %>%\n  filter(species == \"Chinstrap\")\n\nglimpse(chinstrap)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 68\nColumns: 8\n$ species           <fct> Chinstrap, Chinstrap, Chinstrap, Chinstrap, Chinstra…\n$ island            <fct> Dream, Dream, Dream, Dream, Dream, Dream, Dream, Dre…\n$ bill_length_mm    <dbl> 46.5, 50.0, 51.3, 45.4, 52.7, 45.2, 46.1, 51.3, 46.0…\n$ bill_depth_mm     <dbl> 17.9, 19.5, 19.2, 18.7, 19.8, 17.8, 18.2, 18.2, 18.9…\n$ flipper_length_mm <int> 192, 196, 193, 188, 197, 198, 178, 197, 195, 198, 19…\n$ body_mass_g       <int> 3500, 3900, 3650, 3525, 3725, 3950, 3250, 3750, 4150…\n$ sex               <fct> female, male, male, female, male, female, female, ma…\n$ year              <int> 2007, 2007, 2007, 2007, 2007, 2007, 2007, 2007, 2007…\n```\n\n\n:::\n:::\n\n\n## Models\n\nOnce again, we'll fit the model\n\n$$\n\\begin{align}\n\\text{bill\\_length\\_mm}_i & = \\beta_0 + \\beta_1 \\text{body\\_mass\\_g}_i + \\epsilon_i \\\\\n\\epsilon_i & \\sim \\operatorname{Normal}(0, \\sigma_\\epsilon) ,\n\\end{align}\n$$\n\nwith both `lm()` and `brm()`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# OLS\nfit1.ols <- lm(\n  data = chinstrap,\n  bill_length_mm ~ 1 + body_mass_g\n)\n\n# Bayes\nfit1.b <- brm(\n  data = chinstrap,\n  bill_length_mm ~ 1 + body_mass_g\n)\n```\n:::\n\n\n## Bayesians have many kinds of distributions\n\nIn Bayesian statistics, we have at least 6 distributions to keep track of. Those are:\n\n-   the likelihood distributions\n-   the prior parameter distribution (aka priors)\n-   the prior predictive distributions\n-   the posterior parameter distributions (aka posteriors)\n-   the posterior-predictive distribution\n\nIn many respect, it's distributions 'all the way down,' with Bayesians. This can indeed be difficult to keep track of at first. But since this is true for any class of Bayesian models (not just regression), you'll hopefully get used to it.\n\n### Question 3.1 {.unnumbered}\n\nFill in the blanks using $\\theta$, $D$, and $\\mid$ (the conditioning bar):\n\n::: callout-tip\nThe conditioning bar $\\mid$ means \"given.\" Think about which quantity you know and which you're trying to learn about.\n:::\n\n| Distribution | Notation (fill in the blank) |\n|---|---|\n| Likelihood | $P()$ |\n| Prior | $P()$ |\n| Prior predictive | $P()$ |\n| Posterior | $P()$ |\n| Posterior predictive | $P()$ |\n\n::: {.callout-tip collapse=\"true\" title=\"Answer\"}\n| Distribution | Notation |\n|---|---|\n| Likelihood | $P(D \\mid \\theta)$ |\n| Prior | $P(\\theta)$ |\n| Prior predictive | $P(D)$ |\n| Posterior | $P(\\theta \\mid D)$ |\n| Posterior predictive | $P(D_{\\text{new}} \\mid D)$ |\n:::\n\nWe also have some other distributions that follow from these. For example, - the distributions of the model expectations (i.e., the predicted means)\n\n### Likelihood distributions.\n\nWe are approaching Bayesian statistics from a likelihood-based perspective. That is, we situate regression models within the greater context of a likelihood function. (There are ways to do non-parametric Bayesian statistics, which don't focus on likelihoods. We won't get into that right now.)\n\nSo far, we have been using the conventional Gaussian likelihood. If we have some variable $y$, we can express it as normally distributed by\n\n$$\n\\operatorname{Normal}(y \\mid \\mu, \\sigma) = \\frac{1}{\\sqrt{2 \\pi \\sigma}} \\exp \\left( \\frac{1}{2} \\left( \\frac{y - \\mu}{\\sigma}\\right)^2\\right),\n$$\n\nwhere $\\mu$ is the mean and $\\sigma$ is the standard deviation. With this likelihood,\n\n-   $\\mu \\in \\mathbb R$\n    -   the mean can be any real number, ranging from $-\\infty$ to $\\infty$\n-   $\\sigma \\in \\mathbb R_{> 0}$\n    -   the standard deviation can take on any real number greater than zero.\n\nIt's also the assumption\n\n-   $y \\in \\mathbb R$\n    -   the focal variable $y$ can be any real number, ranging from $-\\infty$ to $\\infty$.\n\nOne of the ways we wrote our model formula back in the first file was\n\n$$\n\\begin{align}\n\\text{bill\\_length\\_mm}_i & \\sim \\operatorname{Normal}(\\mu_i, \\sigma) \\\\\n\\mu_i & = \\beta_0 + \\beta_1 \\text{body\\_mass\\_g}_i,\n\\end{align}\n$$\n\nand further in the discussion, we updated that equation with the posterior means for our three parameters to\n\n$$\n\\begin{align}\n\\text{bill\\_length\\_mm}_i & \\sim \\operatorname{Normal}(\\mu_i, 2.92) \\\\\n\\mu_i & = 32.2 + 0.004 \\text{body\\_mass\\_g}_i.\n\\end{align}\n$$\n\nBefore we get into this, though, let's back up and consider an intercept-only model of the form\n\n$$\n\\begin{align}\n\\text{bill\\_length\\_mm}_i & \\sim \\operatorname{Normal}(\\mu_i, \\sigma) \\\\\n\\mu_i & = \\beta_0 ,\n\\end{align}\n$$\n\nwhere there is no predictor variable. Here's how to fit the model with `brm()`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Bayes\nfit0.b <- brm(\n  data = chinstrap,\n  bill_length_mm ~ 1\n)\n```\n:::\n\n\nLet's look at the model summary.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(fit0.b)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n Family: gaussian \n  Links: mu = identity \nFormula: bill_length_mm ~ 1 \n   Data: chinstrap (Number of observations: 68) \n  Draws: 4 chains, each with iter = 2000; warmup = 1000; thin = 1;\n         total post-warmup draws = 4000\n\nRegression Coefficients:\n          Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS\nIntercept    48.84      0.41    48.05    49.65 1.00     3127     2435\n\nFurther Distributional Parameters:\n      Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS\nsigma     3.38      0.28     2.88     3.99 1.00     3135     2644\n\nDraws were sampled using sampling(NUTS). For each parameter, Bulk_ESS\nand Tail_ESS are effective sample size measures, and Rhat is the potential\nscale reduction factor on split chains (at convergence, Rhat = 1).\n```\n\n\n:::\n:::\n\n\nThe intercept parameter $\\beta_0$ is a stand-in for $\\mu$. The $\\sigma$ parameter is just $\\sigma$. Here they are in a plot.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndraws <- as_draws_df(fit0.b) \n\ndraws %>% \n  rename(`beta[0]==mu` = b_Intercept) %>% \n  pivot_longer(`beta[0]==mu`:sigma, names_to = \"parameter\") %>% \n  \n  ggplot(aes(x = value)) +\n  stat_halfeye(.width = .95, normalize = \"panels\") +\n  scale_y_continuous(NULL, breaks = NULL) +\n  xlab(\"parameter space\") +\n  facet_wrap(~ parameter, scales = \"free\", labeller = label_parsed)\n```\n\n::: {.cell-output-display}\n![](Bayes_Lab_3_questions_files/figure-html/unnamed-chunk-4-1.png){width=672}\n:::\n:::\n\n\nHere are the posterior means for those two parameters.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmu <- mean(draws$b_Intercept)\nsigma <- mean(draws$sigma)\n\nmu; sigma\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 48.83877\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 3.376664\n```\n\n\n:::\n:::\n\n\nWe can use `dnorm()` to compute the shape of $\\operatorname{Normal}(48.8, 3.4)$.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntibble(y = seq(from = 30, to = 70, by = 0.1)) %>% \n  mutate(density = dnorm(x = y, mean = mu, sd = sigma)) %>% \n  \n  ggplot(aes(x = y, y = density)) +\n  geom_line() +\n  xlab(\"bill_length_mm\")\n```\n\n::: {.cell-output-display}\n![](Bayes_Lab_3_questions_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n:::\n\n\nWe can compare this to the sample distribution of the `bill_length_mm` data:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nchinstrap %>% \n  ggplot(aes(x = bill_length_mm)) +\n  geom_histogram(aes(y = after_stat(density)),\n                 binwidth = 2.5) +\n  geom_line(data = tibble(bill_length_mm = seq(from = 30, to = 70, by = 0.1)),\n            aes(y = dnorm(x = bill_length_mm, mean = mu, sd = sigma)),\n            color = \"red\")\n```\n\n::: {.cell-output-display}\n![](Bayes_Lab_3_questions_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n:::\n\n\nIt's not a great fit, but not horrible either.\n\n### Question 3.2 {.unnumbered}\n\nThe red curve is the model's best guess at the distribution of `bill_length_mm`. What does this model get right? What does it miss?\n\n::: callout-tip\nThink about what a single Normal curve can and can't capture. Also: this model has no predictor.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Enter your answer here\n```\n:::\n\n\nNow let's see what this means for our univariable model `fit1.b`. First, let's learn about the `posterior_summary()` function, which we'll use to save a few posterior means.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nposterior_summary(fit1.b)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                   Estimate    Est.Error          Q2.5         Q97.5\nb_Intercept    3.219020e+01 3.4991437422  2.520195e+01  3.902057e+01\nb_body_mass_g  4.460538e-03 0.0009337018  2.630735e-03  6.314249e-03\nsigma          2.924427e+00 0.2562101322  2.467389e+00  3.486101e+00\nIntercept      4.884178e+01 0.3557498901  4.817866e+01  4.953159e+01\nlprior        -4.298329e+00 0.0687981373 -4.449870e+00 -4.181116e+00\nlp__          -1.723218e+02 1.2099861347 -1.754015e+02 -1.709036e+02\n```\n\n\n:::\n\n```{.r .cell-code}\nb0    <- posterior_summary(fit1.b)[1, 1]\nb1    <- posterior_summary(fit1.b)[2, 1]\nsigma <- posterior_summary(fit1.b)[3, 1]\n```\n:::\n\n\nNow we plot.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncrossing(body_mass_g    = seq(from = 2500, to = 5000, length.out = 200),\n         bill_length_mm = seq(from = 35, to = 60, length.out = 200))  %>% \n  mutate(density = dnorm(x = bill_length_mm, \n                         mean = b0 + b1 * body_mass_g,\n                         sd = sigma)) %>% \n  \n  ggplot(aes(x = body_mass_g, y = bill_length_mm)) +\n  geom_raster(aes(fill = density),\n              interpolate = TRUE) +\n  geom_point(data = chinstrap,\n             shape = 21, color = \"white\", fill = \"black\", stroke = 1/4) +\n  scale_fill_viridis_c(option = \"A\", begin = .15, limits = c(0, NA)) +\n  coord_cartesian(xlim = range(chinstrap$body_mass_g),\n                  ylim = range(chinstrap$bill_length_mm))\n```\n\n::: {.cell-output-display}\n![](Bayes_Lab_3_questions_files/figure-html/unnamed-chunk-10-1.png){width=672}\n:::\n:::\n\n\nOur univariable model `fit1.b` can be viewed as something like a 3-dimensional Gaussian hill.\n\n### Prior distributions & Prior predictive distributions.\n\nLet's hold off on this for a bit.\n\n### Parameter distributions.\n\nUp above, we plotted the posterior distributions for our intercept-only `fit0.b` model. Here they are again.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndraws %>% \n  rename(`beta[0]==mu` = b_Intercept) %>% \n  pivot_longer(`beta[0]==mu`:sigma, names_to = \"parameter\") %>% \n  \n  ggplot(aes(x = value)) +\n  stat_halfeye(.width = .99, normalize = \"panels\",\n               # customize some of the aesthetics\n               fill = \"lightskyblue1\", color = \"royalblue\", \n               point_color = \"darkorchid4\", point_size = 4, shape = 15) +\n  scale_y_continuous(NULL, breaks = NULL) +\n  labs(title = \"fit0.b\",\n       subtitle = \"This time we used 99% intervals, and got silly with the colors.\",\n       x = \"parameter space\") +\n  facet_wrap(~ parameter, scales = \"free\", labeller = label_parsed)\n```\n\n::: {.cell-output-display}\n![](Bayes_Lab_3_questions_files/figure-html/unnamed-chunk-11-1.png){width=672}\n:::\n:::\n\n\nWe might practice making a similar plot for our univariable model `fit1.b`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nas_draws_df(fit1.b) %>% \n  rename(`beta[0]` = b_Intercept,\n         `beta[1]` = b_body_mass_g) %>% \n  pivot_longer(cols = c(`beta[0]`, `beta[1]`, sigma), \n               names_to = \"parameter\") %>% \n  \n  ggplot(aes(x = value)) +\n  stat_histinterval(.width = .95, normalize = \"panels\") +\n  scale_y_continuous(NULL, breaks = NULL) +\n  labs(title = \"fit1.b\",\n       subtitle = \"Using good old 95% intervals, but switching to histograms\",\n       x = \"parameter space\") +\n  facet_wrap(~ parameter, scales = \"free\", labeller = label_parsed)\n```\n\n::: {.cell-output-display}\n![](Bayes_Lab_3_questions_files/figure-html/unnamed-chunk-12-1.png){width=672}\n:::\n:::\n\n\nSome authors, like John Kruschke, have a strong preference for plotting their posteriors with histograms, rather than density plots.\n\n## Distributions of the model expectations.\n\nTake another look at the `conditional_effects()` plot from earlier.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nconditional_effects(fit1.b) %>% \n  plot(points = TRUE)\n```\n\n::: {.cell-output-display}\n![](Bayes_Lab_3_questions_files/figure-html/unnamed-chunk-13-1.png){width=672}\n:::\n:::\n\n\nThe blue line is the posterior mean, for the $\\mu_i$, the model-based mean for `bill_length_mm`, given the value for the predictor `body_mass_g`. The semitransparent gray ribbon marks the percentile-based interval for the conditional mean.\n\nWe can make a similar plot with the `fitted()` function. First we'll need a predictor grid, we'll call `nd`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnd <- tibble(body_mass_g = seq(\n  from = min(chinstrap$body_mass_g),\n  to = max(chinstrap$body_mass_g),\n  length.out = 100))\n\nglimpse(nd)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 100\nColumns: 1\n$ body_mass_g <dbl> 2700.000, 2721.212, 2742.424, 2763.636, 2784.848, 2806.061…\n```\n\n\n:::\n:::\n\n\nNow pump `nd` into the `fitted()` function.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfitted(fit1.b, newdata = nd) %>% \n  # subset the first 6 rows\n  head()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     Estimate Est.Error     Q2.5    Q97.5\n[1,] 44.23365 1.0238050 42.14411 46.23851\n[2,] 44.32826 1.0052567 42.28035 46.29769\n[3,] 44.42288 0.9867573 42.41195 46.35881\n[4,] 44.51750 0.9683095 42.54554 46.41911\n[5,] 44.61212 0.9499165 42.68544 46.47880\n[6,] 44.70673 0.9315813 42.81839 46.53342\n```\n\n\n:::\n:::\n\n\nNow plot.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfitted(fit1.b, newdata = nd) %>% \n  data.frame() %>% \n  bind_cols(nd) %>% \n  ggplot(aes(x = body_mass_g)) +\n  geom_ribbon(aes(ymin = Q2.5, ymax = Q97.5),\n              alpha = 1/3) +\n  geom_line(aes(y = Estimate)) +\n  # add the data\n  geom_point(data = chinstrap,\n             aes(y = bill_length_mm))\n```\n\n::: {.cell-output-display}\n![](Bayes_Lab_3_questions_files/figure-html/unnamed-chunk-16-1.png){width=672}\n:::\n:::\n\n\nLook what happens if we augment the `probs` argument in `fitted()`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfitted(fit1.b, \n       newdata = nd,\n       probs = c(.025, .975, .25, .75)) %>% \n  data.frame() %>% \n  bind_cols(nd) %>% \n  ggplot(aes(x = body_mass_g)) +\n  # 95% range\n  geom_ribbon(aes(ymin = Q2.5, ymax = Q97.5),\n              alpha = 1/4) +\n  # 50% range\n  geom_ribbon(aes(ymin = Q25, ymax = Q75),\n              alpha = 1/4) +\n  geom_line(aes(y = Estimate)) +\n  geom_point(data = chinstrap,\n             aes(y = bill_length_mm))\n```\n\n::: {.cell-output-display}\n![](Bayes_Lab_3_questions_files/figure-html/unnamed-chunk-17-1.png){width=672}\n:::\n:::\n\n\nNow look what happens if we set `summary = FALSE`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfitted(fit1.b, \n       newdata = nd,\n       summary = FALSE) %>% \n  str()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n num [1:4000, 1:100] 42.5 45.5 44.4 43.6 44.1 ...\n```\n\n\n:::\n:::\n\n\nWe get full 4,000 draw posterior distributions for each of the 100 levels of the predictor `body_mass_g`. Now look at what happens if we wrangle that output a little, and plot with aid from `stat_lineribbon()` from the **ggdist** package.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfitted(fit1.b, \n       newdata = nd,\n       summary = F) %>% \n  data.frame() %>% \n  set_names(pull(nd, body_mass_g)) %>% \n  mutate(draw = 1:n()) %>% \n  pivot_longer(-draw) %>% \n  mutate(body_mass_g = as.double(name)) %>%\n  \n  ggplot(aes(x = body_mass_g, y = value)) +\n  stat_lineribbon() +\n  scale_fill_brewer() +\n  coord_cartesian(ylim = range(chinstrap$bill_length_mm)) +\n  theme_classic()\n```\n\n::: {.cell-output-display}\n![](Bayes_Lab_3_questions_files/figure-html/unnamed-chunk-19-1.png){width=672}\n:::\n:::\n\n\nLook what happens when we request more intervals in the `.width` argument.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfitted(fit1.b, \n       newdata = nd,\n       summary = F) %>% \n  data.frame() %>% \n  set_names(pull(nd, body_mass_g)) %>% \n  mutate(draw = 1:n()) %>% \n  pivot_longer(-draw) %>% \n  mutate(body_mass_g = as.double(name)) %>%\n  \n  ggplot(aes(x = body_mass_g, y = value)) +\n  # make more ribbons\n  stat_lineribbon(.width = c(.1, .2, .3, .4, .5, .6, .7, .8, .9),\n                  # remove the line\n                  linewidth = 0) +\n  scale_fill_brewer() +\n  coord_cartesian(ylim = range(chinstrap$bill_length_mm)) +\n  theme_classic()\n```\n\n::: {.cell-output-display}\n![](Bayes_Lab_3_questions_files/figure-html/unnamed-chunk-20-1.png){width=672}\n:::\n:::\n\n\nThe conditional mean, $\\mu_i$, has its own distribution. We can take this visualization approach even further to make a color gradient.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfitted(fit1.b, \n       newdata = nd,\n       summary = F) %>% \n  data.frame() %>% \n  set_names(pull(nd, body_mass_g)) %>% \n  mutate(draw = 1:n()) %>% \n  pivot_longer(-draw) %>% \n  mutate(body_mass_g = as.double(name)) %>%\n  \n  ggplot(aes(x = body_mass_g, y = value, fill = after_stat(.width))) +\n  # make more ribbons\n  stat_lineribbon(.width = ppoints(50)) +\n  scale_fill_distiller(limits = 0:1) +\n  coord_cartesian(ylim = range(chinstrap$bill_length_mm)) +\n  theme_classic()\n```\n\n::: {.cell-output-display}\n![](Bayes_Lab_3_questions_files/figure-html/unnamed-chunk-21-1.png){width=672}\n:::\n:::\n\n\nFor technical details on this visualization approach, go here: <https://mjskay.github.io/ggdist/articles/lineribbon.html#lineribbon-gradients>.\n\nThe **ggdist** package even has an experimental visualization approach that's based on density gradients, rather than interval-width gradients. Since this is experimental, I'm not going to go into the details. But if you're curious and adventurous, you can learn more here: <https://mjskay.github.io/ggdist/articles/lineribbon.html#lineribbon-density-gradients>.\n\n### Posterior-predictive distributions.\n\nThe last section showed the posterior distributions for the model expectations (i.e., the conditional means). In the context of the Gaussian distribution, that's $\\mu$, or $\\mu_i$ in the case of the univariable model `fit1.b`. But the whole Gaussian distribution includes $\\mu$ and $\\sigma$.\n\nThis is where the `predict()` function comes in. First, we compare the `fitted()` output to `predict()`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfitted(fit1.b, newdata = nd) %>% \n  # subset the first 6 rows\n  head()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     Estimate Est.Error     Q2.5    Q97.5\n[1,] 44.23365 1.0238050 42.14411 46.23851\n[2,] 44.32826 1.0052567 42.28035 46.29769\n[3,] 44.42288 0.9867573 42.41195 46.35881\n[4,] 44.51750 0.9683095 42.54554 46.41911\n[5,] 44.61212 0.9499165 42.68544 46.47880\n[6,] 44.70673 0.9315813 42.81839 46.53342\n```\n\n\n:::\n\n```{.r .cell-code}\npredict(fit1.b, newdata = nd) %>% \n  # subset the first 6 rows\n  head()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     Estimate Est.Error     Q2.5    Q97.5\n[1,] 44.23211  3.102651 38.32178 50.32730\n[2,] 44.29920  3.146962 38.24330 50.59841\n[3,] 44.42653  3.164127 38.03926 50.64089\n[4,] 44.47491  3.117934 38.44270 50.67178\n[5,] 44.63282  3.142262 38.56949 50.94807\n[6,] 44.75521  3.052955 38.85073 50.99229\n```\n\n\n:::\n:::\n\n\nThe posterior means (`Estimate`) are about the same, but the SD's (`Est.Error`) are much larger in the `predict()` output, and the widths of the 95% intervals are too. Let's make a plot.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npredict(fit1.b, newdata = nd) %>% \n  data.frame() %>% \n  bind_cols(nd) %>% \n  ggplot(aes(x = body_mass_g)) +\n  geom_ribbon(aes(ymin = Q2.5, ymax = Q97.5),\n              alpha = 1/3) +\n  geom_line(aes(y = Estimate)) +\n  # add the data\n  geom_point(data = chinstrap,\n             aes(y = bill_length_mm)) +\n  coord_cartesian(ylim = range(chinstrap$bill_length_mm))\n```\n\n::: {.cell-output-display}\n![](Bayes_Lab_3_questions_files/figure-html/unnamed-chunk-23-1.png){width=672}\n:::\n:::\n\n\nThe gray band is the 95% interval for the entire posterior predictive distribution, not just the mean. In a good model, about 95% of the data points should be within those bands.\n\nThe jagged edges of the band reflect uncertainty in $\\sigma$, not just the mean.\n\nIf we wanted to, we could integrate the `fitted()`-based conditional posterior mean, with the `predict()`-based posterior-predictive distribution.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# save the fitted() results\nf <- fitted(fit1.b, newdata = nd) %>% \n  data.frame() %>% \n  bind_cols(nd) \n\npredict(fit1.b, newdata = nd) %>% \n  data.frame() %>% \n  bind_cols(nd) %>% \n  \n  ggplot(aes(x = body_mass_g)) +\n  # 95% posterior-predictive range\n  geom_ribbon(aes(ymin = Q2.5, ymax = Q97.5),\n              alpha = 1/4) +\n  # 95% conditional mean range\n  geom_ribbon(data = f,\n              aes(ymin = Q2.5, ymax = Q97.5),\n              alpha = 1/4) +\n  # posterior mean of the conditional mean\n  geom_line(data = f,\n            aes(y = Estimate)) +\n  # original data\n  geom_point(data = chinstrap,\n             aes(y = bill_length_mm)) +\n  coord_cartesian(ylim = range(chinstrap$bill_length_mm))\n```\n\n::: {.cell-output-display}\n![](Bayes_Lab_3_questions_files/figure-html/unnamed-chunk-24-1.png){width=672}\n:::\n:::\n\n\n### Question 3.3 {.unnumbered}\n\n`fitted()` gives uncertainty in the mean; `predict()` gives uncertainty in new observations. In your own words, why is the `predict()` band always wider? When would you report each one?\n\n::: callout-tip\nLook at the model equation. `fitted()` uses only $\\beta_0 + \\beta_1 x$. What extra step does `predict()` add?\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Enter your answer here\n```\n:::\n\n\n::: {.callout-tip collapse=\"true\" title=\"Answer\"}\n`predict()` adds a random draw from $\\text{Normal}(0, \\sigma)$ on top. Use `fitted()` for \"what's the average bill length at this body mass?\" Use `predict()` for \"where might the next penguin's bill length fall?\"\n:::\n\nIt's the posterior predictive distribution that we use to predict new data points. For example, here's what happens if we use `predict()` without the `newdata` argument.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npredict(fit1.b) %>% \n  head()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     Estimate Est.Error     Q2.5    Q97.5\n[1,] 47.84228  2.927958 42.12494 53.40081\n[2,] 49.54560  2.940014 43.80953 55.38665\n[3,] 48.48634  2.989070 42.62021 54.10952\n[4,] 47.91161  2.966407 42.09254 53.83108\n[5,] 48.77327  2.988233 42.93486 54.70046\n[6,] 49.82069  2.952518 43.99991 55.74329\n```\n\n\n:::\n:::\n\n\nWe get posterior predictive summaries for each of the original data points. Here's what happens if we set `summary = FALSE`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npredict(fit1.b, summary = FALSE) %>% \n  str()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n num [1:4000, 1:68] 39.9 47.7 47.5 48.9 44.6 ...\n - attr(*, \"dimnames\")=List of 2\n  ..$ : NULL\n  ..$ : NULL\n```\n\n\n:::\n:::\n\n\nThis time, we got 4,000 posterior draws for each. We can reduce that output with the `ndraws` argument.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npredict(fit1.b, summary = FALSE, ndraws = 6) %>% \n  str()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n num [1:6, 1:68] 44.7 51.9 51.6 45.7 45.3 ...\n - attr(*, \"dimnames\")=List of 2\n  ..$ : NULL\n  ..$ : NULL\n```\n\n\n:::\n:::\n\n\nNow wrangle and plot.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1)\n\npredict(fit1.b, summary = FALSE, ndraws = 6) %>% \n  data.frame() %>% \n  mutate(draw = 1:n()) %>% \n  pivot_longer(-draw) %>% \n  mutate(row = str_remove(name, \"X\") %>% as.double()) %>% \n  left_join(chinstrap %>% \n              mutate(row = 1:n()),\n            by = join_by(row)) %>% \n  \n  ggplot(aes(x = body_mass_g, y = value)) + \n  geom_point() +\n  ylab(\"bill_length_mm\") +\n  facet_wrap(~ draw, labeller = label_both)\n```\n\n::: {.cell-output-display}\n![](Bayes_Lab_3_questions_files/figure-html/unnamed-chunk-29-1.png){width=672}\n:::\n:::\n\n\nWith `predict()`, we can use the entire posterior-predictive distribution to simulate new data based on the values of our predictor variable(s). To give you a better sense of what's happening under the hood, here's an `as_draws_df()` based alternative.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1)\n\n# walk this code through\nas_draws_df(fit1.b) %>% \n  rename(beta0 = b_Intercept,\n         beta1 = b_body_mass_g) %>% \n  select(.draw, beta0, beta1, sigma) %>% \n  slice_sample(n = 6) %>% \n  expand_grid(chinstrap %>% select(body_mass_g)) %>% \n  mutate(bill_length_mm = rnorm(n = n(),\n                                mean = beta0 + beta1 * body_mass_g,\n                                sd = sigma)) %>% \n  \n  ggplot(aes(x = body_mass_g, y = bill_length_mm)) + \n  geom_point() +\n  facet_wrap(~ .draw, labeller = label_both)\n```\n\n::: {.cell-output-display}\n![](Bayes_Lab_3_questions_files/figure-html/unnamed-chunk-30-1.png){width=672}\n:::\n:::\n\n\nNow take a look at what happens when we plot the densities of several simulated draws.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1)\n\nas_draws_df(fit1.b) %>% \n  rename(beta0 = b_Intercept,\n         beta1 = b_body_mass_g) %>% \n  select(.draw, beta0, beta1, sigma) %>% \n  slice_sample(n = 50) %>%  # increase the number of random draws\n  expand_grid(chinstrap %>% select(body_mass_g)) %>% \n  mutate(bill_length_mm = rnorm(n = n(),\n                                mean = beta0 + beta1 * body_mass_g,\n                                sd = sigma)) %>% \n  \n  ggplot(aes(x = bill_length_mm, group = .draw)) + \n  geom_density(size = 1/4, color = alpha(\"black\", 1/2)) +\n  coord_cartesian(xlim = range(chinstrap$bill_length_mm) + c(-2, 2))\n```\n\n::: {.cell-output-display}\n![](Bayes_Lab_3_questions_files/figure-html/unnamed-chunk-31-1.png){width=672}\n:::\n:::\n\n\nThe similarities and differences among the individual density lines give you a sense of the (un)certainty of the posterior-predictive distribution.\n\n## Posterior predictive checks with `pp_check()`\n\nYou just did a posterior predictive check by hand — simulating datasets from the posterior and comparing their densities to the observed data. The `pp_check()` function automates this in one line:\n\n\n::: {.cell}\n\n```{.r .cell-code}\npp_check(fit1.b, ndraws = 100)\n```\n\n::: {.cell-output-display}\n![](Bayes_Lab_3_questions_files/figure-html/unnamed-chunk-32-1.png){width=672}\n:::\n:::\n\n\nThe dark line is the observed data density. The light lines are 100 simulated datasets from the posterior predictive distribution. If the model is good, the light lines should envelope the dark line.\n\nWe can also target specific summary statistics:\n\n\n::: {.cell}\n\n```{.r .cell-code}\npp_check(fit1.b, type = \"stat\", stat = \"mean\")\n```\n\n::: {.cell-output-display}\n![](Bayes_Lab_3_questions_files/figure-html/unnamed-chunk-33-1.png){width=672}\n:::\n\n```{.r .cell-code}\npp_check(fit1.b, type = \"stat\", stat = \"sd\")\n```\n\n::: {.cell-output-display}\n![](Bayes_Lab_3_questions_files/figure-html/unnamed-chunk-33-2.png){width=672}\n:::\n:::\n\n\nThe `stat = \"mean\"` check shows a histogram of posterior predictive means, with the observed mean as a vertical line. The `stat = \"sd\"` check does the same for spread. These targeted checks isolate whether the model captures specific features of the data.\n\n### Question 3.4 {.unnumbered}\n\nCompare the `pp_check()` output to the manual density overlay you made above. What is `pp_check()` doing under the hood?\n\n::: callout-tip\nLook at the dark line and the light lines. You made something very similar a few chunks ago.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Enter your answer here\n```\n:::\n\n\n**This may be a good time for you to work on Exercise 3 (see end of the document).**\n\n# Part 4: Beginning to look at priors\n\n## Bayes' rule\n\nBayes' theorem will allow us to determine the plausibility of various values of our parameter(s) of interest, $\\theta$, given the data $d$, which we can express formally as $\\Pr(\\theta \\mid d)$. Bayes' rule takes on the form\n\n$$\n\\Pr(\\theta \\mid d) = \\frac{\\Pr(d \\mid \\theta) \\Pr(\\theta)}{\\Pr(d)}.\n$$\n\nwhere\n\n-   $\\Pr(d \\mid \\theta)$ is the *likelihood*,\n-   $\\Pr(\\theta)$ is the *prior*,\n-   $\\Pr(d)$ is the *average probability of the data*, and\n-   $\\Pr(\\theta \\mid d)$ is the *posterior*.\n\nWe can express this in words as\n\n$$\n\\text{Posterior} = \\frac{\\text{Probability of the data} \\times \\text{Prior}}{\\text{Average probability of the data}}.\n$$\n\nThe denominator $\\Pr(d)$ is a normalizing constant, and dividing by this constant is what converts the posterior $\\Pr(\\theta \\mid d)$ into a probability metric.\n\n## Prior predictive checks\n\nEvery model makes predictions. Most of the time we think about predictions after fitting — but a model with priors is already making predictions before it sees a single data point. If those predictions are absurd, no amount of data will fully rescue the analysis. A quick check now saves you from trusting results that were compromised from the start.\n\nWe can do this by fitting the model with `sample_prior = \"only\"`, which tells brms to ignore the data entirely and just simulate from the priors and likelihood:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit_prior_only <- brm(\n  data = chinstrap,\n  bill_length_mm ~ 1 + body_mass_g,\n  prior = prior(normal(0, 0.01), class = b),\n  sample_prior = \"only\"\n)\n```\n:::\n\n\nNote: we had to set an explicit prior on the slope (`class = b`) because the default flat prior can't be sampled — it spans $-\\infty$ to $\\infty$. We used `normal(0, 0.01)`, which is a reasonable weakly informative prior for this scale.\n\nNow run `pp_check()` on the prior-only model:\n\n\n::: {.cell}\n\n```{.r .cell-code}\npp_check(fit_prior_only, ndraws = 50)\n```\n\n::: {.cell-output-display}\n![](Bayes_Lab_3_questions_files/figure-html/unnamed-chunk-35-1.png){width=672}\n:::\n:::\n\n\n`pp_check()` overlays your observed data (dark line) as a reference, but the evaluation here is different from a posterior predictive check. The light lines are datasets the model would generate using only the priors — no learning from data at all. You're not asking \"do these match my data?\" (priors that already reproduce the data would be suspiciously informative). You're asking \"are these physically plausible for penguin bill lengths?\" Predictions in the 30–60 mm range are reasonable. Predictions spanning hundreds of millimeters mean the priors are encoding implausible assumptions.\n\n### Question 4.1 {.unnumbered}\n\nThe prior predictive check shows data the model would generate *before seeing any real data*. Do the predictions look reasonable? What would you change if they predicted bill lengths of 500 mm (that's 50 cm — about the length of your forearm)?\n\n::: callout-tip\nThe dark line is just a scale reference. Ask: could these simulated datasets plausibly be penguin bill measurements? You don't want the light lines to match the dark line (that would mean your priors are doing the data's job), but they should be in a biologically sensible range.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Enter your answer here\n```\n:::\n\n\n## Default priors\n\nTo set your priors with **brms**, the `brm()` function has a `prior` argument. If you don't explicitly use the `prior` argument, `brm()` will use default priors. This is what happened with our `fit1.b` model from above. We used default priors. If you'd like to see what those priors are, execute `fit1.b$prior`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# maybe show str(fit1.b)\nfit1.b$prior\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                   prior     class        coef group resp dpar nlpar lb ub tag\n                  (flat)         b                                            \n                  (flat)         b body_mass_g                                \n student_t(3, 49.5, 3.6) Intercept                                            \n    student_t(3, 0, 3.6)     sigma                                    0       \n       source\n      default\n (vectorized)\n      default\n      default\n```\n\n\n:::\n:::\n\n\nThus, a fuller expression of our model is\n\n$$\n\\begin{align}\n\\text{bill\\_length\\_mm}_i & \\sim \\operatorname{Normal}(\\mu_i, \\sigma) \\\\\n\\mu_i & = \\beta_0 + \\beta_1 \\text{body\\_mass\\_g}_i \\\\\n\\beta_0 & \\sim \\operatorname{Student-t}(3, 49.5, 3.6) \\\\\n\\beta_1 & \\sim \\operatorname{Uniform}(-\\infty, \\infty) \\\\\n\\sigma & \\sim \\operatorname{Student-t}^+(3, 0, 3.6).\n\\end{align}\n$$\n\nIf we had wanted to see the `brm()` defaults before fitting the model, we could have used the `get_prior()` function.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nget_prior(\n  data = chinstrap,\n  bill_length_mm ~ 1 + body_mass_g\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                   prior     class        coef group resp dpar nlpar lb ub tag\n                  (flat)         b                                            \n                  (flat)         b body_mass_g                                \n student_t(3, 49.5, 3.6) Intercept                                            \n    student_t(3, 0, 3.6)     sigma                                    0       \n       source\n      default\n (vectorized)\n      default\n      default\n```\n\n\n:::\n:::\n\n\nIf you recall, the normal distribution is a member of the Student-t family, where the $\\nu$ (aka degrees of freedom or normality parameter) is set to $\\infty$. To give you a sense, here are the densities of three members of the Student-t family, with varying $\\nu$ values.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncrossing(theta = seq(from = -4.5, to = 4.5, length.out = 200),\n         nu = c(3, 10, Inf)) %>% \n  mutate(density = dt(x = theta, df = nu)) %>% \n  \n  ggplot(aes(x = theta, y = density, color = factor(nu))) +\n  geom_line(linewidth = 1) +\n  scale_color_viridis_d(expression(nu), option = \"A\", end = .7) +\n  labs(title = \"3 members of the Student-t family\",\n       x = expression(theta)) +\n  coord_cartesian(xlim = c(-4, 4))\n```\n\n::: {.cell-output-display}\n![](Bayes_Lab_3_questions_files/figure-html/unnamed-chunk-39-1.png){width=672}\n:::\n:::\n\n\nThus, Student-t distributions have thicker tails when they have smaller $\\nu$ parameters. In the case where $\\nu = 3$, the tails are pretty thick, which means they are more tolerant of more extreme values. And thus priors with small-$\\nu$ parameters will be weaker (i.e., more permissive) than their Gaussian counterparts.\n\nWe can visualize functions from **ggdist** to visualize the default `brm()` priors. We'll start with the `student_t(3, 49.5, 3.6)` $\\beta_0$ prior, and also take the opportunity to compare that with a slightly stronger `normal(49.5, 3.6)` alternative.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nc(prior(student_t(3, 49.5, 3.6)),\n  prior(normal(49.5, 3.6))) %>% \n  parse_dist() %>% \n  \n  ggplot(aes(xdist = .dist_obj, y = prior)) + \n  stat_halfeye() +\n  labs(x = expression(italic(p)(beta[0])),\n       y = NULL) +\n  coord_cartesian(xlim = c(25, 75))\n```\n\n::: {.cell-output-display}\n![](Bayes_Lab_3_questions_files/figure-html/unnamed-chunk-40-1.png){width=672}\n:::\n:::\n\n\nSee how the $\\nu = 3$ parameter in the default prior produces much thicker tails than its Gaussian counterpart. We can make the same kind of plot for our default $\\sigma$ prior and its half-Gaussian counterpart.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nc(prior(student_t(3, 0, 3.6), lb = 0),  # note our use of the lb = 0 argument\n  prior(normal(0, 3.6), lb = 0)) %>% \n  parse_dist() %>% \n  \n  ggplot(aes(xdist = .dist_obj, y = prior)) + \n  stat_halfeye(point_interval = mean_qi, .width = c(.90, .99)) +\n  labs(x = expression(italic(p)(sigma)),\n       y = NULL) +\n  coord_cartesian(xlim = c(0, 30))\n```\n\n::: {.cell-output-display}\n![](Bayes_Lab_3_questions_files/figure-html/unnamed-chunk-41-1.png){width=672}\n:::\n:::\n\n\nHere's how we could have explicitly set our priors by hand.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit2.b <- brm(\n  data = chinstrap,\n  bill_length_mm ~ 1 + body_mass_g,\n  prior = prior(student_t(3, 49.5, 3.6), class = Intercept) +\n    prior(student_t(3, 0, 3.6), class = sigma, lb = 0)\n)\n```\n:::\n\n\nCompare the results.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(fit1.b)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n Family: gaussian \n  Links: mu = identity \nFormula: bill_length_mm ~ 1 + body_mass_g \n   Data: chinstrap (Number of observations: 68) \n  Draws: 4 chains, each with iter = 2000; warmup = 1000; thin = 1;\n         total post-warmup draws = 4000\n\nRegression Coefficients:\n            Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS\nIntercept      32.19      3.50    25.20    39.02 1.00     5352     2971\nbody_mass_g     0.00      0.00     0.00     0.01 1.00     5391     3056\n\nFurther Distributional Parameters:\n      Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS\nsigma     2.92      0.26     2.47     3.49 1.00     1916     1553\n\nDraws were sampled using sampling(NUTS). For each parameter, Bulk_ESS\nand Tail_ESS are effective sample size measures, and Rhat is the potential\nscale reduction factor on split chains (at convergence, Rhat = 1).\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(fit2.b)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n Family: gaussian \n  Links: mu = identity \nFormula: bill_length_mm ~ 1 + body_mass_g \n   Data: chinstrap (Number of observations: 68) \n  Draws: 4 chains, each with iter = 2000; warmup = 1000; thin = 1;\n         total post-warmup draws = 4000\n\nRegression Coefficients:\n            Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS\nIntercept      32.18      3.50    25.31    39.08 1.00     4772     2744\nbody_mass_g     0.00      0.00     0.00     0.01 1.00     4733     2783\n\nFurther Distributional Parameters:\n      Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS\nsigma     2.92      0.25     2.47     3.45 1.00     2114     2180\n\nDraws were sampled using sampling(NUTS). For each parameter, Bulk_ESS\nand Tail_ESS are effective sample size measures, and Rhat is the potential\nscale reduction factor on split chains (at convergence, Rhat = 1).\n```\n\n\n:::\n:::\n\n\n### Question 4.2 {.unnumbered}\n\nCompare the priors in `fit1.b` (default) and `fit2.b` (hand-set). Are they the same? If the results are nearly identical, what does that tell you?\n\n::: callout-tip\nCompare `fit1.b$prior` to the priors you set explicitly in `fit2.b`. Count the parameters — did you set a prior on all of them?\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Enter your answer here\n```\n:::\n\n\n::: {.callout-tip collapse=\"true\" title=\"Answer\"}\nThe results are nearly identical because the explicit priors on the intercept and $\\sigma$ match what brms chose by default. The slope ($\\beta_1$) still uses the default flat prior in both models — `fit2.b` didn't set one explicitly, so brms filled it in. The lesson: brms always has priors, whether you set them or not.\n:::\n\nIf you want to learn more about the default prior settings for **brms**, read through the `set_prior` section of the **brms** reference manual (https://CRAN.R-project.org/package=brms/brms.pdf).\n\n## Model comparison with LOO-CV\n\nIn your MLM unit, you compared models with AIC and BIC. The Bayesian analog is **Leave-One-Out Cross-Validation** (LOO-CV).\n\nThe idea: hide one data point, fit the model on the remaining 67, and predict the held-out point. Repeat for every point. Models that predict held-out data well are capturing real structure; models that predict poorly are either too simple or fitting noise.\n\nRather than actually refitting the model 67 times, `loo()` approximates the cross-validation using your existing posterior draws. It estimates how much each data point influenced the fit. Points the model already predicts well had little influence; points that surprised the model — the ones that would have been flagged as unusual in a residual plot — had a lot. Averaging across all points gives you an overall score for how well the model predicts new data. So a model that is consistently unsurprised by held-out points gets a high score, and one that is frequently caught off guard gets a low one.\n\nThe key number in the output is **ELPD** (expected log pointwise predictive density). Higher ELPD = better out-of-sample prediction. When comparing two models, `loo_compare()` puts the better model on top and reports the difference with a standard error. A difference many times larger than its SE is reliable.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nloo0 <- loo(fit0.b)\nloo1 <- loo(fit1.b)\nloo_compare(loo0, loo1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       elpd_diff se_diff\nfit1.b  0.0       0.0   \nfit0.b -9.2       3.7   \n```\n\n\n:::\n:::\n\n\nThe first row is the better model. The `elpd_diff` column tells you how much better, and `se_diff` tells you how certain that difference is.\n\n### Question 4.3 {.unnumbered}\n\nThe `loo_compare()` output shows that `fit1.b` has better predictive accuracy than `fit0.b`. In practical terms, what does this tell you about whether `body_mass_g` is a useful predictor of `bill_length_mm`?\n\n::: callout-tip\nThe first row in `loo_compare()` is the better model. What does it mean for your research question if the predictor model wins?\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Enter your answer here\n```\n:::\n\n\n### Exercise 3 {.unnumbered}\n\nIn the previous lab, you made a subset of the `penguins` data called `gentoo`, which was only the cases for which `species == \"Gentoo\"`. Do that again and refit the Bayesian model to those data.\n\n-   Subset the data to Gentoo penguins.\n-   Refit the Bayesian `brm()` model on the Gentoo data.\n-   Remake some of the figures from Part 3 with the new model.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Enter your code here\n```\n:::\n\n\n## References\n\nGelman, A., Hill, J., & Vehtari, A. (2020). *Regression and other stories*. Cambridge University Press. https://doi.org/10.1017/9781139161879\n\nKruschke, J. K. (2015). *Doing Bayesian data analysis: A tutorial with R, JAGS, and Stan*. Academic Press. https://sites.google.com/site/doingbayesiandataanalysis/\n\nMcElreath, R. (2020). *Statistical rethinking: A Bayesian course with examples in R and Stan* (Second Edition). CRC Press. https://xcelab.net/rm/statistical-rethinking/\n\nMcElreath, R. (2015). *Statistical rethinking: A Bayesian course with examples in R and Stan*. CRC Press. https://xcelab.net/rm/statistical-rethinking/\n\n## Session information\n",
    "supporting": [
      "Bayes_Lab_3_questions_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}