project:
  type: website
  output-dir: docs
  render:
    - "index.qmd"
    - "about.qmd"
    - "**/*.qmd"
    - "!Stats Vault/**"
    - "!**/ord_lab_q.qmd"
    - "!**/*ordinal-regression.qmd"
    - "!**/*-narrated-J.qmd"
    - "!**/*Bayes_Lab_1_Coins.qmd"
    - "!**/*_narrative.qmd"
    - "!**/*Key.qmd"
    - "!**/*J2.qmd"
    - "!**/phase*.qmd"
    - "!**/temp.qmd"
    - "!**/deck*.qmd"
    - "!**/*MLM_2026*.qmd"
    - "!**/*MLM_exercise*.qmd"
    - "!**/*MLM_simulation*.qmd"
    - "!**/*Lecture_short.qmd"
    - "!**/*Bayes_Lab_3.qmd"
    - "!**/*_solutions*"
    - "!**/*Poisson_Regression_S*"
    - "!**/*Bayes_Hierarchical*Lecture*"
    - "!**/*_navarro*"
    - "!**/*Diagnostics*Lecture*"
    - "!**/Bayes_Lab_4_Hierarchical.qmd"
    - "!**/*Lecture_Narrated*"
    - "!**/*Missing_Data_Lab*"
    - "!**/*Missing_Data_2026_Quiz*"
    - "!**/*Missing_Data_2025*"
    - "!**/*Missing_Data_2026.qmd"


website:
  title: "PSY 504, Spring 2026"
  navbar:
    background: light
    logo-alt: "PSY 504"
    left:
      - text: "Lectures"
        href: index.qmd
      - text: "Syllabus"
        href: https://docs.google.com/document/d/1mXjcFA67TXVNmGNlOfn11-vb5wBbP5yJ8LPKqMjoweM/edit
        target: _blank
      - text: "Schedule"
        href: https://docs.google.com/document/d/1fZhqADwjg8B8YvxYaPCOVUBOh3ounTP8L2g5p31fp18/edit
        target: _blank
      - text: "About"
        href: about.qmd

format:
  html:
    include-in-header:
      text: |
        <meta name="robots" content="noindex, nofollow">
    theme:
      - cosmo
      - custom.scss
    css: styles.css
    toc: false

resources:
  - robots.txt

editor: visual