project:
  type: website
  output-dir: docs
  render:
    - "index.qmd"
    - "about.qmd"
    - "**/*.qmd"
    - "!**/ord_lab_q.qmd"
    - "!**/*ordinal-regression.qmd"
    - "!**/*-narrated-J.qmd"
    - "!**/*Bayes_Lab_1_Coins.qmd"
    - "!**/*_narrative.qmd"
    - "!**/*Key.qmd"

website:
  title: "PSY 504, Spring 2026"
  navbar:
    background: light
    logo-alt: "PSY 504"
    left:
      - text: "Lectures"
        href: index.qmd
      - text: "Syllabus"
        href: https://docs.google.com/document/d/1mXjcFA67TXVNmGNlOfn11-vb5wBbP5yJ8LPKqMjoweM/edit
        target: _blank
      - text: "Schedule"
        href: https://docs.google.com/document/d/1fZhqADwjg8B8YvxYaPCOVUBOh3ounTP8L2g5p31fp18/edit
        target: _blank
      - text: "About"
        href: about.qmd

format:
  html:
    include-in-header:
      text: |
        <meta name="robots" content="noindex, nofollow">
    theme:
      - cosmo
      - custom.scss
    css: styles.css
    toc: false

resources:
  - robots.txt

editor: visual