{
  "hash": "01879914fcb4a014518f524cfe69ec8b",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Lab: Hierarchical Bayesian Models\"\nsubtitle: \"PSY 504: Advanced Statistics\"\nauthor: \"Your Name\"\ndate: '2026-04-15'\nformat:\n  html:\n    code-fold: true\n    code-overflow: wrap\n    toc: true\n    toc-depth: 2\n    toc-location: left\nexecute:\n  message: false\n  warning: false\nengine: knitr\n---\n\n⬇️ [Download the .qmd](https://github.com/suyoghc/PSY504_Spring_2026/raw/main/posts/Bayes%202/Bayes_Lab_4_Hierarchical.qmd)\n\n::: callout-note\n## Building on what you know\nThis lab brings together two threads from the course: Bayesian inference with `brms` (Labs 2--3) and multilevel models with `lme4` (MLM lectures). You'll fit hierarchical Bayesian models and see partial pooling, shrinkage, and group-level credible intervals in action.\n:::\n\n::: callout-important\n## How to work through this lab\n\n1.  Read and run each code chunk, making sure you understand what it does before moving on.\n2.  Some questions have a **hidden answer you can reveal** after writing your own response. These cover concepts that later questions build on, so check your understanding before continuing.\n3.  Other questions are **open**: no answer is provided.\n4.  Write your responses in the code chunks marked `# Enter your answer here` (use R comments for text answers). For coding exercises, write your code in chunks marked `# Enter your code here`.\n5.  The final section is a **transfer exercise** where you apply what you've learned to a new dataset with less scaffolding.\n:::\n\n# Part 1: The reedfrogs data\n\n## Setup\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\nlibrary(tidyverse)\nlibrary(brms)\nlibrary(tidybayes)\nlibrary(bayesplot)\nlibrary(ggdist)\nlibrary(lme4)\n```\n:::\n\n\n## The data\n\nWe'll use data from a predation experiment on African reed frog tadpoles (*Hyperolius spinigularis*), originally from Vonesh & Bolker (2005). This dataset is one of the canonical examples in McElreath's *Statistical Rethinking* for introducing hierarchical models. But unlike the book's implementation, we will be using `brms()` and tidyverse.\n\nHere is the setup of the experiment: Tadpoles were placed in 48 experimental tanks. The researchers varied three things across the tanks --- the initial number of tadpoles per tank (the **density**: 10, 25, or 35), whether a predator was present, and the tadpole body size. After the experiment, they counted how many survived.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\n# Load the data\nd <- read.csv(\"https://raw.githubusercontent.com/rmcelreath/rethinking/master/data/reedfrogs.csv\", sep = \";\") %>%\n  mutate(\n    tank = factor(1:n()),\n    density = as.integer(density),\n    surv = as.integer(surv)\n  )\n\nglimpse(d)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 48\nColumns: 6\n$ density  <int> 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 1…\n$ pred     <chr> \"no\", \"no\", \"no\", \"no\", \"no\", \"no\", \"no\", \"no\", \"pred\", \"pred…\n$ size     <chr> \"big\", \"big\", \"big\", \"big\", \"small\", \"small\", \"small\", \"small…\n$ surv     <int> 9, 10, 7, 10, 9, 9, 10, 9, 4, 9, 7, 6, 7, 5, 9, 9, 24, 23, 22…\n$ propsurv <dbl> 0.90, 1.00, 0.70, 1.00, 0.90, 0.90, 1.00, 0.90, 0.40, 0.90, 0…\n$ tank     <fct> 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18…\n```\n\n\n:::\n:::\n\n\nKey variables:\n\n-   `surv` — number of tadpoles that survived (our outcome)\n-   `density` — initial number of tadpoles in the tank (10, 25, or 35)\n-   `propsurv` — proportion surviving (`surv / density`)\n-   `pred` — predator presence (`no` or `pred`)\n-   `size` — tadpole body size (`big` or `small`)\n-   `tank` — tank ID (1 through 48), our grouping variable\n\nLet’s see what survival looks like across tanks:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(d, aes(x = reorder(tank, propsurv), y = propsurv, fill = factor(density))) +\n  geom_col() +\n  scale_fill_manual(values = c(\"10\" = \"steelblue\", \"25\" = \"coral\", \"35\" = \"seagreen\"),\n                    name = \"Initial density\") +\n  labs(x = \"Tank (ordered by survival proportion)\",\n       y = \"Proportion surviving\") +\n  theme_bw(base_size = 14) +\n  theme(axis.text.x = element_blank(), axis.ticks.x = element_blank())\n```\n\n::: {.cell-output-display}\n![](Bayes_Lab_4_Hierarchical_updated_files/figure-html/unnamed-chunk-3-1.png){width=960}\n:::\n:::\n\n\nThere is substantial variation across tanks. Some tanks had 100% survival, others lost most of their tadpoles.\n\n### Question 1.1 {.unnumbered}\n\nRecreate the bar chart above, but facet it by `density` (using `facet_wrap(~ density, scales = \"free_x\")`). What do you notice about the spread of survival proportions across the three density levels?\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Enter your code here\n```\n:::\n\n\n::: {.callout-tip collapse=\"true\" title=\"Answer\"}\nThe density = 25 and density = 35 facets show wider spread than density = 10. All three levels include tanks near 1.0, but the larger tanks include more tanks with very low survival (likely driven by predator presence). The density = 10 tanks cluster mostly at the high end, with a few dropping to around 0.4.\n:::\n\n### Question 1.2 {.unnumbered}\n\nWith only 10 tadpoles, a single death moves the survival proportion by 0.10. With 35 tadpoles, a single death moves it by only ~0.03. What does this mean for how much we should trust the raw proportions from small vs. large tanks?\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Enter your answer here\n```\n:::\n\n\n::: {.callout-tip collapse=\"true\" title=\"Answer\"}\nThe raw proportions from small tanks are less reliable. Each individual outcome has a larger effect on the estimate, so the proportion carries more sampling noise. A tank with 10/10 surviving could easily have a true rate of 0.85 where we got lucky, but a tank with 35/35 is stronger evidence of genuinely high survival. When we fit the partial pooling model later, the model will reflect this: tanks with fewer observations will have wider credible intervals and be pulled more toward the grand mean.\n:::\n\n\n# Part 2: From `glm()` to `brm()` — Bayesian logistic regression\n\n## A quick bridge\n\nYou already know how to fit logistic regression with `glm()`:\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\nglm_fit <- glm(cbind(surv, density - surv) ~ 1,\n               family = binomial, data = d)\ncoef(glm_fit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n(Intercept) \n  0.8430498 \n```\n\n\n:::\n:::\n\n\nThe intercept is on the **log-odds** scale.\n\n::: callout-note\n## `glm()` vs `brms` syntax for binomial models\nIn `glm()`, you specify a binomial outcome with `cbind(successes, failures)`. In `brms`, the syntax is `successes | trials(total)` — you give the outcome and the number of trials instead. The `|` here is not a conditioning bar; it's how `brms` attaches extra information to the response (the same slot handles censoring, weights, and other annotations in more advanced models). \n\nFor now, just read `surv | trials(density)` as: \"the outcome is `surv`, out of `density` trials.\"\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\nfit_complete <- brm(\n  surv | trials(density) ~ 1,\n  family = binomial,\n  data = d,\n  file = \"fits/lab4_fit_complete\"\n)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfixef(fit_complete)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n           Estimate Est.Error      Q2.5     Q97.5\nIntercept 0.8441955 0.0662965 0.7128571 0.9787072\n```\n\n\n:::\n:::\n\n\nThe intercept is in log-odds. To convert to a probability, use `brms::inv_logit_scaled()`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninv_logit_scaled(fixef(fit_complete)[, \"Estimate\"])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.6993481\n```\n\n\n:::\n:::\n\n\n### Question 2.1 {.unnumbered}\n\nCompare the `glm()` coefficient to the `brm()` posterior mean. Are they similar? Why would you expect them to be?\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Enter your answer here\n```\n:::\n\n\n::: {.callout-tip collapse=\"true\" title=\"Answer\"}\nThey should be very similar. With 48 tanks and hundreds of total observations, the data dominate the (default, weakly informative) prior. The Bayesian posterior mean converges toward the MLE when the data are plentiful and the prior is weak. The key difference is that `brm()` gives you a full posterior distribution, not just a point estimate.\n:::\n\n\n# Prior predictive check\n\nBefore fitting the hierarchical model and looking at results, it's good practice to ask: **do our priors make sense?** We can answer this by fitting the model with `sample_prior = \"only\"`, which ignores the data entirely and generates predictions based solely on the priors.\n\nWe'll use the priors we plan to use for the partial pooling model: `normal(0, 1.5)` on the intercept and `exponential(1)` on the group-level SD.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit_prior_only <- brm(\n  surv | trials(density) ~ 1 + (1 | tank),\n  family = binomial,\n  prior = c(\n    prior(normal(0, 1.5), class = Intercept),\n    prior(exponential(1), class = sd)\n  ),\n  data = d,\n  sample_prior = \"only\",\n  file = \"fits/lab4_fit_prior_only\"\n)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npp_check(fit_prior_only, ndraws = 100) +\n  theme_bw(base_size = 14) +\n  labs(title = \"Prior predictive check: what does the model expect before seeing data?\")\n```\n\n::: {.cell-output-display}\n![](Bayes_Lab_4_Hierarchical_updated_files/figure-html/unnamed-chunk-12-1.png){width=768}\n:::\n:::\n\n\n### Question 2.2 {.unnumbered}\n\nLook at the prior predictive distributions. Do the simulated survival counts span a reasonable range?\n\nNow try it yourself with a much wider prior on the group-level SD. Refit the prior-only model using `prior(normal(0, 10), class = sd)` instead of `exponential(1)`, run `pp_check()` on it, and compare the two. What changes?\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Enter your code here — refit with the wider prior and run pp_check()\n```\n:::\n\n\n::: {.callout-tip collapse=\"true\" title=\"Answer\"}\nWith `exponential(1)` on the group-level SD, the prior predictive distribution covers a wide but sensible range of survival counts — the priors allow tanks to differ without implying anything absurd. With `normal(0, 10)` on the SD, the group-level standard deviation can be enormous, implying that some tanks have survival rates near 0% and others near 100% as entirely separate modes. The prior predictive distribution looks bimodal and extreme. The `exponential(1)` prior gently regularizes $\\sigma_{\\text{tank}}$, keeping it in a reasonable range.\n:::\n\n\n# Part 3: Three models\n\n## Complete pooling\n\nWe already fit the complete pooling model above: one grand intercept, ignoring tanks entirely. Every tank is assumed to have the same underlying survival probability.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(fit_complete)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n Family: binomial \n  Links: mu = logit \nFormula: surv | trials(density) ~ 1 \n   Data: d (Number of observations: 48) \n  Draws: 4 chains, each with iter = 2000; warmup = 1000; thin = 1;\n         total post-warmup draws = 4000\n\nRegression Coefficients:\n          Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS\nIntercept     0.84      0.07     0.71     0.98 1.00     1573     2237\n\nDraws were sampled using sampling(NUTS). For each parameter, Bulk_ESS\nand Tail_ESS are effective sample size measures, and Rhat is the potential\nscale reduction factor on split chains (at convergence, Rhat = 1).\n```\n\n\n:::\n:::\n\n\n### Question 3.1 {.unnumbered}\n\nWhat assumption does this model make about differences between tanks?\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Enter your answer here\n```\n:::\n\n\n::: {.callout-tip collapse=\"true\" title=\"Answer\"}\nComplete pooling assumes all tanks share exactly the same survival probability. Any observed differences between tanks are treated as pure sampling noise. The model has no mechanism for representing real variation between tanks.\n:::\n\n\n## No pooling\n\nEach tank gets its own intercept, estimated entirely from its own data:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit_no_pool <- brm(\n  surv | trials(density) ~ 0 + tank,\n  family = binomial,\n  data = d,\n  file = \"fits/lab4_fit_no_pool\"\n)\n```\n:::\n\n\nExtract the per-tank estimates and convert to probabilities:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nno_pool_estimates <- fixef(fit_no_pool) %>%\n  data.frame() %>%\n  rownames_to_column(\"tank\") %>%\n  mutate(\n    tank = str_remove(tank, \"tank\"),\n    prob = inv_logit_scaled(Estimate),\n    prob_lower = inv_logit_scaled(Q2.5),\n    prob_upper = inv_logit_scaled(Q97.5)\n  )\n\nhead(no_pool_estimates)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  tank    Estimate   Est.Error       Q2.5      Q97.5      prob prob_lower\n1    1   2.7125190   1.3133001  0.7975257   6.004470 0.9377613  0.6894450\n2    2 367.4580210 212.2430414 17.9806458 723.950688 1.0000000  1.0000000\n3    3   0.8953763   0.7250049 -0.5047399   2.348278 0.7099984  0.3764274\n4    4 327.0714383 208.7500152 17.5573331 712.704633 1.0000000  1.0000000\n5    5   2.5486446   1.2118460  0.6721279   5.528472 0.9274824  0.6619795\n6    6   2.6342316   1.1998490  0.6787587   5.232694 0.9330324  0.6634616\n  prob_upper\n1  0.9975384\n2  1.0000000\n3  0.9127973\n4  1.0000000\n5  0.9960437\n6  0.9946892\n```\n\n\n:::\n:::\n\n\n### Question 3.2 {.unnumbered}\n\nLook at the credible intervals for a few tanks. Compare a tank that started with 10 tadpoles to one that started with 35. Which has a wider interval? Why?\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Enter your code here — pick one tank with density 10 and one with density 35\n# and compare their intervals\n```\n:::\n\n\n::: {.callout-tip collapse=\"true\" title=\"Answer\"}\nTanks with density = 10 have wider credible intervals because they have fewer observations. With only 10 data points, there is more uncertainty about the true survival probability. Tanks with density = 35 have tighter intervals because more data constrain the estimate.\n:::\n\n\n## Partial pooling\n\nThe hierarchical model lets each tank have its own intercept, but those intercepts come from a shared population distribution. The model learns how spread out the tank-level intercepts are (via the group-level SD, $\\sigma_{\\text{tank}}$).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit_partial <- brm(\n  surv | trials(density) ~ 1 + (1 | tank),\n  family = binomial,\n  prior = c(\n    prior(normal(0, 1.5), class = Intercept),\n    prior(exponential(1), class = sd)\n  ),\n  data = d,\n  file = \"fits/lab4_fit_partial\"\n)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(fit_partial)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n Family: binomial \n  Links: mu = logit \nFormula: surv | trials(density) ~ 1 + (1 | tank) \n   Data: d (Number of observations: 48) \n  Draws: 4 chains, each with iter = 2000; warmup = 1000; thin = 1;\n         total post-warmup draws = 4000\n\nMultilevel Hyperparameters:\n~tank (Number of levels: 48) \n              Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS\nsd(Intercept)     1.61      0.21     1.25     2.08 1.00     1242     2124\n\nRegression Coefficients:\n          Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS\nIntercept     1.37      0.26     0.88     1.91 1.01      637     1533\n\nDraws were sampled using sampling(NUTS). For each parameter, Bulk_ESS\nand Tail_ESS are effective sample size measures, and Rhat is the potential\nscale reduction factor on split chains (at convergence, Rhat = 1).\n```\n\n\n:::\n:::\n\n\nThe `sd(Intercept)` row under \"Group-Level Effects\" is the estimated population standard deviation of tank-level intercepts (on the log-odds scale). It controls how much pooling happens.\n\n### Question 3.3 {.unnumbered}\n\nWhat does the `sd(Intercept)` parameter represent in this model? What would happen to the tank-level estimates if it were very close to 0? What if it were very large?\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Enter your answer here\n```\n:::\n\n\n::: {.callout-tip collapse=\"true\" title=\"Answer\"}\n`sd(Intercept)` is the standard deviation of the population distribution from which tank-level intercepts are drawn. If it were close to 0, all tanks would be forced to have nearly the same intercept, recovering complete pooling. If it were very large, each tank's estimate would be barely influenced by the others, recovering no pooling. The model estimates this parameter from the data, guided by the `exponential(1)` prior, so the amount of pooling is learned, not hand-picked.\n:::\n\n\n## Quick diagnostics check\n\nNow that the partial pooling model is fit, check that the sampler ran well:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmcmc_trace(fit_partial, pars = c(\"b_Intercept\", \"sd_tank__Intercept\")) +\n  theme_bw(base_size = 14)\n```\n\n::: {.cell-output-display}\n![](Bayes_Lab_4_Hierarchical_updated_files/figure-html/unnamed-chunk-22-1.png){width=960}\n:::\n:::\n\n\nGood trace plots look like \"fat, hairy caterpillars\" — the chains overlap and wander freely through the same region. But trace plots are a visual check. The `summary()` output also reports three numerical diagnostics:\n\n::: callout-note\n## Rhat ($\\hat{R}$)\n$\\hat{R}$ compares the variance *between* chains to the variance *within* each chain. If all chains have converged to the same posterior, $\\hat{R} \\approx 1.0$. **Values above 1.01 indicate the chains haven't converged** and the estimates should not be trusted.\n:::\n\n::: callout-note\n## Bulk ESS and Tail ESS\nMCMC draws are autocorrelated, so 4,000 draws carry less information than 4,000 independent samples. **Effective sample size (ESS)** estimates how many independent draws your correlated samples are worth. **Bulk ESS** measures this for the center of the posterior (reliable means and medians). **Tail ESS** measures it for the tails (reliable credible interval endpoints). Both should be **above 400**.\n:::\n\n### Question 3.4 {.unnumbered}\n\nLook at the trace plots and the `summary()` output from `fit_partial`. Are the Rhat values all below 1.01? Are Bulk_ESS and Tail_ESS above 400 for every parameter? Do the trace plots show good mixing?\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Enter your answer here\n```\n:::\n\n\n::: {.callout-tip collapse=\"true\" title=\"Answer\"}\nFor a well-behaved model like this one, Rhat should be very close to 1.00 for all parameters, and both Bulk_ESS and Tail_ESS should be well above 400. The trace plots should show all four chains wandering through the same region with no visible separation. If any of these checks fail, it would indicate a sampling problem, and you'd want to investigate before trusting the estimates.\n:::\n\n\n# Part 4: Shrinkage\n\nPartial pooling produces **shrinkage**: estimates pulled toward the grand mean. Tanks with few observations or extreme raw values get pulled more. Let's see this.\n\n## Building a shrinkage plot\n\nFirst, get the raw (empirical) survival proportions and the partial-pooling estimates side by side:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Raw proportions (empirical, no-pooling)\ntank_raw <- d %>%\n  select(tank, density, propsurv) %>%\n  rename(raw_prop = propsurv)\n\n# Partial pooling estimates from the hierarchical model\ntank_partial <- coef(fit_partial)$tank[, , \"Intercept\"] %>%\n  data.frame() %>%\n  rownames_to_column(\"tank\") %>%\n  mutate(partial_prop = inv_logit_scaled(Estimate))\n\n# Combine\nshrinkage_df <- left_join(tank_raw, tank_partial, by = \"tank\")\n\nhead(shrinkage_df)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  tank density raw_prop Estimate Est.Error       Q2.5    Q97.5 partial_prop\n1    1      10      0.9 2.147612 0.8881881  0.5875600 4.071804    0.8954454\n2    2      10      1.0 3.087858 1.1261755  1.1713703 5.627815    0.9563891\n3    3      10      0.7 1.009350 0.6833436 -0.2765423 2.450563    0.7328928\n4    4      10      1.0 3.077038 1.1183410  1.1670062 5.502601    0.9559356\n5    5      10      0.9 2.153982 0.8886413  0.6022492 4.063667    0.8960403\n6    6      10      0.9 2.151516 0.8966860  0.6181832 4.097106    0.8958103\n```\n\n\n:::\n:::\n\n\nNow plot:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Grand mean (on probability scale)\ngrand_mean <- inv_logit_scaled(fixef(fit_partial)[, \"Estimate\"])\n\nggplot(shrinkage_df, aes(x = raw_prop, y = partial_prop)) +\n  geom_abline(slope = 1, intercept = 0, linetype = \"dashed\", color = \"gray50\") +\n  geom_hline(yintercept = grand_mean, linetype = \"dotted\", color = \"red\", linewidth = 0.5) +\n  geom_point(aes(size = density, color = factor(density)), alpha = 0.8) +\n  scale_color_manual(values = c(\"10\" = \"steelblue\", \"25\" = \"coral\", \"35\" = \"seagreen\"),\n                     name = \"Initial density\") +\n  scale_size_continuous(range = c(2, 5), guide = \"none\") +\n  labs(x = \"Raw proportion surviving (no pooling)\",\n       y = \"Partial pooling estimate\",\n       title = \"Shrinkage toward the grand mean\") +\n  coord_equal(xlim = c(0, 1), ylim = c(0, 1)) +\n  theme_bw(base_size = 14)\n```\n\n::: {.cell-output-display}\n![](Bayes_Lab_4_Hierarchical_updated_files/figure-html/unnamed-chunk-25-1.png){width=768}\n:::\n:::\n\n\nPoints on the dashed diagonal would mean no shrinkage at all. Points pulled toward the red dotted line (the grand mean) show shrinkage in action.\n\n### Question 4.1 {.unnumbered}\n\nDescribe the pattern you see in the shrinkage plot. Which tanks moved the most? How does tank size (density) relate to the amount of shrinkage?\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Enter your answer here\n```\n:::\n\n\n### Question 4.2 {.unnumbered}\n\nConsider a tank that started with 10 tadpoles and all 10 survived (raw proportion = 1.0). What does the partial pooling model do to this estimate? Why?\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Enter your answer here\n```\n:::\n\n\n::: {.callout-tip collapse=\"true\" title=\"Answer\"}\nThe partial pooling model pulls that tank's estimate down from 1.0 toward the grand mean. A 100% survival rate from only 10 tadpoles is likely an overestimate of the true survival probability — with more tadpoles, we'd probably see some deaths. The model recognizes that this extreme value is partly real signal and partly sampling noise, and the shrinkage separates the two. Tanks with density = 10 and extreme proportions (near 0 or 1) show the most shrinkage because they have the least data and the most extreme raw estimates.\n:::\n\n\n# Part 5: Group-level credible intervals\n\n## Caterpillar plot\n\nOne of the advantages of Bayesian hierarchical models is that you get full posterior distributions for each group-level parameter. Let's visualize these as a caterpillar plot.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Extract tank-level intercepts with credible intervals\ntank_intervals <- coef(fit_partial)$tank[, , \"Intercept\"] %>%\n  data.frame() %>%\n  rownames_to_column(\"tank\") %>%\n  mutate(\n    prob = inv_logit_scaled(Estimate),\n    prob_lower = inv_logit_scaled(Q2.5),\n    prob_upper = inv_logit_scaled(Q97.5)\n  ) %>%\n  left_join(d %>% select(tank, density), by = \"tank\") %>%\n  arrange(prob) %>%\n  mutate(rank = row_number())\n\n# Grand mean\ngm <- inv_logit_scaled(fixef(fit_partial)[, \"Estimate\"])\n\nggplot(tank_intervals, aes(x = prob, xmin = prob_lower, xmax = prob_upper,\n                            y = rank, color = factor(density))) +\n  geom_vline(xintercept = gm, linetype = \"dashed\", color = \"gray40\") +\n  geom_pointrange(size = 0.3) +\n  scale_color_manual(values = c(\"10\" = \"steelblue\", \"25\" = \"coral\", \"35\" = \"seagreen\"),\n                     name = \"Initial density\") +\n  labs(x = \"Estimated survival probability\",\n       y = \"Tank (rank ordered)\",\n       title = \"Tank-level credible intervals (partial pooling)\") +\n  theme_bw(base_size = 14)\n```\n\n::: {.cell-output-display}\n![](Bayes_Lab_4_Hierarchical_updated_files/figure-html/unnamed-chunk-28-1.png){width=768}\n:::\n:::\n\n\n### A tidybayes alternative\n\nThe `tidybayes` package offers a more fluent pipeline for extracting and plotting posterior draws:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit_partial %>%\n  spread_draws(r_tank[tank, ]) %>%\n  mutate(tank_intercept = r_tank + fixef(fit_partial)[, \"Estimate\"],\n         prob = inv_logit_scaled(tank_intercept)) %>%\n  group_by(tank) %>%\n  median_qi(prob) %>%\n  mutate(tank = as.character(tank)) %>%\n  left_join(d %>% mutate(tank = as.character(tank)) %>%\n              select(tank, density), by = \"tank\") %>%\n  arrange(prob) %>%\n  mutate(rank = row_number()) %>%\n\n  ggplot(aes(x = prob, xmin = .lower, xmax = .upper,\n             y = rank, color = factor(density))) +\n  geom_vline(xintercept = gm, linetype = \"dashed\", color = \"gray40\") +\n  geom_pointinterval(size = 0.3) +\n  scale_color_manual(values = c(\"10\" = \"steelblue\", \"25\" = \"coral\", \"35\" = \"seagreen\"),\n                     name = \"Initial density\") +\n  labs(x = \"Estimated survival probability\",\n       y = \"Tank (rank ordered)\",\n       title = \"Tank-level credible intervals (tidybayes version)\") +\n  theme_bw(base_size = 14)\n```\n\n::: {.cell-output-display}\n![](Bayes_Lab_4_Hierarchical_updated_files/figure-html/unnamed-chunk-29-1.png){width=768}\n:::\n:::\n\n\n### Question 5.1 {.unnumbered}\n\nHow do these credible intervals compare to what you would get from `glmer()` in `lme4`? What is fundamentally different about the Bayesian version?\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Enter your answer here\n```\n:::\n\n\n::: {.callout-tip collapse=\"true\" title=\"Answer\"}\n`glmer()` estimates the group-level standard deviation ($\\sigma_{\\text{tank}}$) as a single point value and then conditions on it to produce group-level intervals. The Bayesian model integrates over the full posterior uncertainty in $\\sigma_{\\text{tank}}$, so the credible intervals for each tank reflect uncertainty in both the tank-level intercept *and* the variance component. When the number of groups is small or group sizes are unbalanced, this difference matters: the Bayesian intervals are typically wider and more honest about the overall uncertainty.\n:::\n\n\n## Comparing Bayesian and frequentist intervals\n\nLet's make that comparison concrete. Here is the same model fit with `glmer()`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit_freq <- glmer(\n  cbind(surv, density - surv) ~ 1 + (1 | tank),\n  family = binomial,\n  data = d\n)\n```\n:::\n\n\nWe can extract the frequentist tank-level intercepts and their conditional standard errors, then build intervals to compare against the Bayesian credible intervals:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Frequentist estimates\nfreq_intercept <- fixef(fit_freq)[[\"(Intercept)\"]]\nfreq_ranef <- ranef(fit_freq, condVar = TRUE)$tank\nfreq_se <- sqrt(attr(freq_ranef, \"postVar\")[1, 1, ])\n\nfreq_df <- tibble(\n  tank = rownames(freq_ranef),\n  freq_est = freq_intercept + freq_ranef[, 1],\n  freq_lower = freq_est - 1.96 * freq_se,\n  freq_upper = freq_est + 1.96 * freq_se\n) %>%\n  mutate(across(c(freq_est, freq_lower, freq_upper), inv_logit_scaled))\n\n# Bayesian estimates (already computed)\nbayes_df <- tank_intervals %>%\n  mutate(tank = as.character(tank))\n\n# Combine\ncompare_df <- left_join(bayes_df, freq_df, by = \"tank\") %>%\n  arrange(prob) %>%\n  mutate(rank = row_number())\n\nggplot(compare_df, aes(y = rank)) +\n  # Frequentist intervals (red)\n  geom_pointrange(aes(x = freq_est, xmin = freq_lower, xmax = freq_upper),\n                  color = \"tomato\", size = 0.25, alpha = 0.7,\n                  position = position_nudge(y = -0.15)) +\n  # Bayesian intervals (blue)\n  geom_pointrange(aes(x = prob, xmin = prob_lower, xmax = prob_upper),\n                  color = \"steelblue\", size = 0.25, alpha = 0.7,\n                  position = position_nudge(y = 0.15)) +\n  geom_vline(xintercept = gm, linetype = \"dashed\", color = \"gray40\") +\n  labs(x = \"Estimated survival probability\",\n       y = \"Tank (rank ordered)\",\n       title = \"Bayesian (blue) vs frequentist (red) tank-level intervals\") +\n  theme_bw(base_size = 14)\n```\n\n::: {.cell-output-display}\n![](Bayes_Lab_4_Hierarchical_updated_files/figure-html/unnamed-chunk-32-1.png){width=960}\n:::\n:::\n\n\n### Question 5.2 {.unnumbered}\n\nCompare the blue (Bayesian) and red (frequentist) intervals. What differences do you notice? Which tend to be wider?\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Enter your answer here\n```\n:::\n\n\n::: {.callout-tip collapse=\"true\" title=\"Answer\"}\nThe Bayesian intervals are generally slightly wider than the frequentist intervals. `glmer()` estimates $\\sigma_{\\text{tank}}$ as a single number and treats it as known when computing the tank-level intervals. The Bayesian model carries forward uncertainty in $\\sigma_{\\text{tank}}$, so its intervals reflect two sources of uncertainty at once: where each tank's intercept falls, and how spread out tanks are in general. The difference is most visible for tanks with extreme estimates or small sample sizes.\n:::\n\n\n# Part 6: Model checking and comparison\n\n## Posterior predictive check\n\n\n::: {.cell}\n\n```{.r .cell-code}\npp_check(fit_partial, ndraws = 100) +\n  theme_bw(base_size = 14)\n```\n\n::: {.cell-output-display}\n![](Bayes_Lab_4_Hierarchical_updated_files/figure-html/unnamed-chunk-34-1.png){width=768}\n:::\n:::\n\n\n### Question 6.1 {.unnumbered}\n\nDoes the posterior predictive distribution capture the general shape of the observed data? Are there any systematic discrepancies?\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Enter your answer here\n```\n:::\n\n\n## LOO-CV model comparison\n\n\n::: {.cell}\n\n```{.r .cell-code}\nloo_complete <- loo(fit_complete)\nloo_partial <- loo(fit_partial)\n\nloo_compare(loo_complete, loo_partial)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n             elpd_diff se_diff\nfit_partial     0.0       0.0 \nfit_complete -181.9      33.5 \n```\n\n\n:::\n:::\n\n\n::: callout-note\n## LOO-CV and ELPD\nLeave-One-Out Cross-Validation (LOO-CV) estimates how well a model predicts held-out data. For each observation, the model is (approximately) refit without it and asked to predict it. The result is summarized as **ELPD** (expected log predictive density) — higher is better. `loo_compare()` puts the best model on top; the `elpd_diff` column tells you how much better it is, and `se_diff` tells you how certain that difference is. A difference much larger than its SE is strong evidence.\n:::\n\n### Question 6.2 {.unnumbered}\n\nWhich model wins on LOO-CV? By how much (in ELPD units)? Is this surprising?\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Enter your answer here\n```\n:::\n\n\n::: {.callout-tip collapse=\"true\" title=\"Answer\"}\nThe partial pooling model should win decisively. The complete pooling model ignores all tank-level variation, so it makes poor predictions for tanks that deviate from the overall mean. The ELPD difference should be large relative to its standard error, indicating strong evidence in favor of the hierarchical model. Since we could *see* substantial between-tank variation in the raw data, it would be surprising if complete pooling won.\n:::\n\n::: callout-note\n## Pareto-k diagnostics\nThe `loo()` function uses an approximation rather than actually refitting the model N times. **Pareto-k** values measure how reliable that approximation is for each observation. Values below 0.5 are fine; 0.5--0.7 are acceptable; **above 0.7 means the approximation is unreliable** for that observation. High Pareto-k values often come from influential observations — in hierarchical models, these tend to be observations in small groups or with extreme outcomes. If you see problematic values, `reloo()` can refit the model leaving out those specific observations for exact LOO estimates.\n:::\n\n### Question 6.3 {.unnumbered}\n\nCheck the Pareto-k diagnostics from `loo()`. Are there any problematic observations? What would you do about them?\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Enter your code here — look at loo_partial and check for warnings\n```\n:::\n\n\n::: {.callout-tip collapse=\"true\" title=\"Answer\"}\nYou should see that nearly all 48 observations have Pareto-k values above 0.7. This happens because the data is aggregated to one row per tank. Leaving out a single row removes an entire tank's data, which is highly influential in a model with tank-level random effects. Despite the unreliable LOO approximation, the comparison with complete pooling is so decisive (ELPD difference ~182 with SE ~34) that the conclusion is robust. For more precise LOO estimates with aggregated data, you can use `loo(fit_partial, moment_match = TRUE)`.\n:::\n\n\n# Optional: Going further\n\nIf you finish early, try adding `pred` (predator presence) as a fixed effect to the reedfrogs partial pooling model. Fit the model, compare it to the intercept-only partial pooling model using `loo_compare()`, and interpret the result.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Enter your code and answers here\n```\n:::\n\n\n## Resources\n\n-   Kurz (2023). [*Statistical Rethinking with brms and the tidyverse*](https://bookdown.org/content/4857/), Chapter 13\n-   McElreath (2020). *Statistical Rethinking*, Chapters 12--13\n-   Gelman & Hill (2007). *Data Analysis Using Regression and Multilevel/Hierarchical Models*, Chapter 12\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}