{
  "hash": "be4dcb60e57b84b12aa82bc214f05799",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Multilevel Modeling (with R) Part 2\"\nsubtitle: \"<small>(adapted from materials by Jason Geller)</small>\"\nauthor: \"Suyog Chandramouli\"\ndate: '2026-03-30'\nfooter: \"PSY 504: Advanced Statistics\"\nformat:\n  revealjs:\n    theme: solarized\n    css: slide-style.css\n    multiplex: false\n    transition: fade\n    slide-number: true\n    incremental: false\n    chalkboard: true\n    fontsize: \"25pt\"\nwebr:\n  packages: [\"tidyverse\", \"easystats\", \"broom\", \"kableExtra\", \"interactions\", \"emmeans\", \"lme4\",\"lmertest\",  \"ggeffects\"]\nfilters:\n  - webr\nexecute:\n  freeze: auto\n  echo: true\n  message: false\n  warning: false\n  fig-align: center\n  fig-width: 12\n  fig-height: 8\n  editor_options:\n  chunk_output_type: inline\n  code-overflow: wrap\n  html:\n    code-fold: true\n    code-tools: true\n---\n\n## Multilevel models\n\n-   When to use them:\n\n    -   Nested designs\n\n    -   Repeated measures\n\n    -   Longitudinal data\n\n    -   Complex designs\n\n-   Why use them:\n\n    -   Captures variance occurring between groups and within groups\n\n-   What they are:\n\n    -   Linear model with extra residuals\n\n## Today\n\n-   Everything you need to know to run and report a MLM\n\n    -   ICC and the null model\n    -   Organizing data and centering\n    -   Estimation\n    -   Model building and crossed random effects\n    -   Fit and interpret multilevel models\n    -   Visualization and partial pooling\n    -   Effect size\n    -   Reporting\n    -   Power and sample size\n    -   Bridge to Bayesian\n\n## Packages\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse) # data wrangling\nlibrary(knitr) # nice tables\nlibrary(lme4) # fit mixed models\nlibrary(lmerTest) # mixed models\nlibrary(broom.mixed) # tidy output of mixed models\nlibrary(afex) # fit mixed models for lrt test\nlibrary(emmeans) # marginal means\nlibrary(ggeffects) # marginal means\nlibrary(ggrain) # rain plots\nlibrary(easystats) # nice ecosystem of packages\n\noptions(scipen=999) # get rid of sci notation\n```\n:::\n\n\n-   Find the .qmd document here to follow along: <https://github.com/suyoghc/PSY504-Spring-2026/blob/main/posts/Multilevel%20Models/mlm_part2_students.qmd>\n\n## Today's data\n\n-   What did you say?\n\n    -   Ps (*N* = 31) listened to *both* clear (NS) and 6 channel vocoded speech (V6)\n        -   (<https://www.mrc-cbu.cam.ac.uk/personal/matt.davis/vocode/a1_6.wav>)\n            -   Fixed factor: ?\n            -   Random factor: ?\n            -   What would change if we replicated this study?\n            -   What would stay the same?\n\n## Today's data\n\n\n::: {.cell}\n\n```{.r .cell-code}\neye  <- read_csv(\"data/vocoded_pupil.csv\") # data for class\n```\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](mlm_part2_students_files/figure-revealjs/unnamed-chunk-3-1.png){fig-align='center' width=1152}\n:::\n:::\n\n\n## Data organization\n\n-   Data Structure\n\n    -   MLM analysis (in R) requires data in long format\n\n![](images/pivot_longer.png){fig-align=\"center\"}\n\n## Data organization\n\n-   Level 1: trial\n\n-   Level 2: subject\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|subject | trial|vocoded | mean_pupil|\n|:-------|-----:|:-------|----------:|\n|EYE15   |     3|V6      |  0.0839555|\n|EYE15   |     4|V6      |  0.0141083|\n|EYE15   |     5|V6      |  0.0224967|\n|EYE15   |     6|V6      |  0.0007424|\n|EYE15   |     7|V6      |  0.0242540|\n|EYE15   |     8|V6      |  0.0267617|\n\n\n:::\n:::\n\n\n# The Null Model & ICC\n\n## Null model (unconditional means)\n\nRemember the ICC from the simulation app? Here's how to compute it from real data.\n\n-   ICC is a standardized way of expressing how much variance is due to clustering/group\n    -   Ranges from 0-1\n-   Can also be interpreted as correlation among observations within cluster/group!\n-   If ICC is sufficiently low (i.e., $\\rho$ \\< .1), then you don't have to use MLM! *BUT YOU PROBABLY SHOULD*\n\n## Null model (unconditional means)\n\n-   What does this formula say?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(lme4) # pop linear modeling package\n\nnull_model <- lmer(mean_pupil ~ (1|subject), data = eye, REML=TRUE)\n\nsummary(null_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLinear mixed model fit by REML. t-tests use Satterthwaite's method [\nlmerModLmerTest]\nFormula: mean_pupil ~ (1 | subject)\n   Data: eye\n\nREML criterion at convergence: -19811.6\n\nScaled residuals: \n    Min      1Q  Median      3Q     Max \n-5.1411 -0.5530 -0.0463  0.4822 10.8130 \n\nRandom effects:\n Groups   Name        Variance  Std.Dev.\n subject  (Intercept) 0.0001303 0.01142 \n Residual             0.0016840 0.04104 \nNumber of obs: 5609, groups:  subject, 31\n\nFixed effects:\n             Estimate Std. Error        df t value Pr(>|t|)  \n(Intercept)  0.005227   0.002124 29.457806   2.461   0.0199 *\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n## Calculating ICC\n\n-   Run baseline (null) model\n\n-   Get intercept variance and residual variance\n\n$$\\mathrm{ICC}=\\frac{\\text { between-group variability }}{\\text { between-group variability+within-group variability}}$$\n\n$$\nICC=\\frac{\\operatorname{Var}\\left(u_{0 j}\\right)}{\\operatorname{Var}\\left(u_{0 j}\\right)+\\operatorname{Var}\\left(e_{i j}\\right)}=\\frac{\\tau_{00}}{\\tau_{00}+\\sigma^{2}}\n$$\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# easystats\n#adjusted icc just random effects\n#unadjusted fixed effects taken into account\nperformance::icc(null_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# Intraclass Correlation Coefficient\n\n    Adjusted ICC: 0.072\n  Unadjusted ICC: 0.072\n```\n\n\n:::\n:::\n\n\n## Quick reminder\n\n-   Fixed effects = model for the **means**\n\n    -   \"What is the average effect of vocoding on pupil size?\"\n    -   Centering changes what this coefficient estimates\n\n-   Random effects = model for the **variance**\n\n    -   \"How much do subjects differ in their baseline? In their response?\"\n    -   Centering doesn't affect this\n\n## Centering\n\n::: columns\n::: {.column width=\"50%\"}\n-   In a single-level regression, centering ensures that the zero value for each predictor is meaningful before running the model\n\n-   In MLM, if you have specific questions about within, between, and contextual effects, you need to center!\n\n-   But which mean?\n:::\n\n::: {.column width=\"50%\"}\n![](images/centering_mlm.png)\n\n![](){fig-align=\"center\"}\n:::\n:::\n\n## Group- vs. Grand-Mean Centering\n\n-   Grand-mean centering: $x_{ij} - x$\n\n    -   Variable represents each observation's deviation from everyone's norm, regardless of group\n\n-   Group-mean centering: $x_{ij} - x_j$\n\n    -   Variable represents each observation's deviation from their group's norm (removes group effect)\n\n## Group- vs. Grand-Mean Centering\n\n::: columns\n::: {.column width=\"50%\"}\n-   Level 1 predictors\n\n    -   Grand-mean centering\n\n        -   **Include means of level 2**\n            -   Allows us to directly test within-group effect\n            -   Coefficient associated with the Level 2 group mean represents **contextual effect**\n:::\n\n::: {.column width=\"50%\"}\n-   Group-mean centering\n\n    -   Level 1 coefficient will always be with within-group effect, regardless of whether the group means are included at Level 2 or not\n    -   If level 2 means included, coefficient represents the between-groups effect\n:::\n:::\n\n::: callout-note\nCan apply to categorical predictors as well (see Yaremych, Preacher, & Hedeker, 2023)\n:::\n\n## Centering in R\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# how to group mean center \nd <- d %>% \n  # Grand mean centering (CMC)\n  mutate(iv.gmc = iv-mean(iv)) %>%\n  # group  mean centering (more generally, centering within cluster)\n  group_by(id) %>% \n  mutate(iv.cm = mean(iv),\n         iv.cwc = iv-iv.cm)\n\nlibrary(datawizard) #easystats \n\n#data wizard way\nx <- demean(x, select=c(\"x\"), group=\"ID\") #gets within-group and included cluster means\n```\n:::\n\n\n# Model Estimation\n\n## Why not OLS?\n\n![](images/simp2.png){fig-align=\"center\"}\n\n-   Remember: ignoring group structure can reverse your conclusions\n-   OLS has no way to account for groups — one error term for everything\n-   MLE with random effects is the fix\n\n## Maximum Likelihood\n\n-   In MLM we try to maximize the likelihood of the data — no OLS!\n\n-   We'll revisit likelihood in depth when we cover Bayesian inference — it's half of Bayes' theorem\n\n## Likelihood\n\n-   You've seen this in logistic regression and the Bayesian lecture: \"Given our data, which parameter values are most plausible?\"\n\n-   MLM uses the same principle — but now searching over fixed effects AND variance components\n\nInteractive: <https://rpsychologist.com/likelihood/>\n\n## Log-Likelihood and Deviance\n\n-   You know log-likelihood from logistic regression:\n\n    -   Sum of log(scores) across observations — higher = better fit\n\n-   **New: Deviance** = $-2 \\times \\log L$\n\n    -   Converts log-likelihood into a scale where we can compare models\n    -   Difference in deviance between two models $\\approx \\chi^2$ — gives us a p-value\n    -   Known as the **likelihood ratio test (LRT)**\n\n## Comparing nested models\n\n-   Suppose there are two models:\n\n    -   Reduced model includes predictors $x_1, \\ldots, x_q$\n    -   Full model includes predictors $x_1, \\ldots, x_q, x_{q+1}, \\ldots, x_p$\n\n-   We want to test the hypotheses:\n\n    -   $H_0$: smaller model is better\n\n    -   $H_1$: Larger model is better\n\n-   To do so, we will use the drop-in-deviance test (also known as the nested likelihood ratio test)\n\n## Drop-In-Deviance Test\n\n-   Hypotheses:\n\n    -   $H_0$: smaller model is better\n\n    -   $H_1$: Larger model is better\n\n-   Test Statistic: $$G = (-2 \\log L_{reduced}) - (-2 \\log L_{full})$$\n\n-   P-value: $P(\\chi^2 > G)$:\n\n    -   Calculated using a $\\chi^2$ distribution\n    -   df = $df_1$ - $df_2$\n\n## Testing deviance\n\n-   We can use the `anova` function to conduct this test\n\n    -   Add test = \"Chisq\" to conduct the drop-in-deviance test\n\n-   I like `test_likelihoodratio` from `easystats`\n\n\n::: {.cell}\n\n```{.r .cell-code}\nanova(model1, model2, test=\"chisq\")\n\n# test using easystats function\n\ntest_likelihoodratio(model1, model2)\n```\n:::\n\n\n## Model fitting: ML or REML?\n\n-   Two flavors of maximum likelihood\n\n    -   Maximum Likelihood (ML or FIML)\n\n        -   Jointly estimate the fixed effects and variance components using all the sample data\n\n        -   Can be used to draw conclusions about fixed and random effects\n\n        -   Issue:\n\n            -   Results are biased because fixed effects are estimated without error\n\n## Model fitting: ML or REML\n\n-   Restricted Maximum Likelihood (REML)\n\n    -   Estimates the variance components using the sample residuals not the sample data\n\n    -   It is conditional on the fixed effects, so it accounts for uncertainty in fixed effects estimates\n\n        -   This results in unbiased estimates of variance components\n        -   Associated with error/penalty\n\n## Model fitting: ML or REML?\n\n-   Research has not determined one method absolutely superior to the other\n\n-   **REML** (`REML = TRUE`; default in `lmer`) is preferable when:\n\n    -   The number of parameters is large\n\n    -   Primary objective is to obtain relaible estimates of the variance parameters\n\n    -   For REML, likelihood ratio tests can only be used to draw conclusions about variance components\n\n-   **ML** (`REML = FALSE`) <u>must</u> be used if you want to compare nested fixed effects models using a likelihood ratio test (e.g., a drop-in-deviance test)\n\n## ML or REML?\n\n-   What would we use if we wanted to compare the below models?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nx= lmer(DV ~ IV1 + IV2 + (1|ID))\n\ny= lmer(DV ~ IV1*IV2 + (1|ID))\n```\n:::\n\n\n## ML or REML?\n\n-   What would we use if we wanted to compare the below models?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nx = lmer(DV ~ IV1 + IV2 + (1+IV2|ID))\n\ny = lmer(DV ~ IV1+ IV2 + (1|ID))\n```\n:::\n\n\n# Fitting and Interpreting Models\n\n## Modeling approach\n\n-   Forward/backward approach\n\n```{webr-r}\n\n```\n\n-   `Keep it maximal`[^1]\n\n    -   Whatever can vary, should vary\n\n        -   **Decreases Type 1 error**\n\n[^1]: Barr, D. J., Levy, R., Scheepers, C., & Tily, H. J. (2013). Random effects structure for confirmatory hypothesis testing: Keep it maximal. Journal of memory and language, 68(3), 10.1016/j.jml.2012.11.001. <https://doi.org/10.1016/j.jml.2012.11.001>\n\n## The other side of the debate\n\n-   Matuschek et al. (2017)[^2]: Maximal models can **substantially reduce power**\n\n    -   In simulations, parsimonious models (retaining only variance components supported by data) achieved better power with acceptable Type I error\n\n-   Field (Ch 19) advocates a **bottom-up** approach: start simple, add complexity\n\n-   Both approaches are defensible — the key is being principled and transparent\n\n[^2]: Matuschek, H., Kliegl, R., Vasishth, S., Baayen, H., & Bates, D. (2017). Balancing Type I error and power in linear mixed models. Journal of Memory and Language, 94, 305–315.\n\n## Practical guidance\n\n-   **\"Keep it maximal\"** = safest default for Type I error control\n\n-   If convergence fails: principled simplification is good practice, not a failure\n\n-   Singmann & Kellen (2019): Start maximal. If it doesn't converge, reduce transparently. Report what you did and why.\n\n-   The key: **report your decisions** (which terms removed, why, in what order)\n\n## Modeling approach: convergence\n\n-   Full (maximal) model\n\n    -   Only when there is convergence issues should you remove terms\n        -   if non-convergence (pay attention to warning messages in summary output!):\n            -   Try different optimizer (`afex::all_fit()`)\n                -   Sort out random effects\n                    -   Remove correlations between slopes and intercepts\n                    -   Random slopes\n                    -   Random Intercepts\n                -   Sort out fixed effects (e.g., interaction)\n                -   Once you arrive at the final model present it using REML estimation\n\n## Modeling approach\n\n-   If your model is singular (check output!!!!)\n\n    -   Variance might be close to 0\n    -   Perfect correlations (1 or -1)\n\n-   Drop the parameter!\n\n## Modeling approach\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata <- read.csv(\"data/heck2011.csv\")\n\nsummary(lmer(math~ses + (1+ses|schcode), data=data))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLinear mixed model fit by REML. t-tests use Satterthwaite's method [\nlmerModLmerTest]\nFormula: math ~ ses + (1 + ses | schcode)\n   Data: data\n\nREML criterion at convergence: 48190.1\n\nScaled residuals: \n    Min      1Q  Median      3Q     Max \n-3.8578 -0.5553  0.1290  0.6437  5.7098 \n\nRandom effects:\n Groups   Name        Variance Std.Dev. Corr \n schcode  (Intercept)  3.2042  1.7900        \n          ses          0.7794  0.8828   -1.00\n Residual             62.5855  7.9111        \nNumber of obs: 6871, groups:  schcode, 419\n\nFixed effects:\n             Estimate Std. Error        df t value            Pr(>|t|)    \n(Intercept)   57.6959     0.1315  378.6378  438.78 <0.0000000000000002 ***\nses            3.9602     0.1408 1450.7730   28.12 <0.0000000000000002 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nCorrelation of Fixed Effects:\n    (Intr)\nses -0.284\noptimizer (nloptwrap) convergence code: 0 (OK)\nboundary (singular) fit: see help('isSingular')\n```\n\n\n:::\n:::\n\n\n. . .\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlmer(math~ses + (1+ses||schcode), data=data) # removes correlation() with double pipes. Does not work with categorical variables\n```\n:::\n\n\n# Crossed Random Effects\n\n## Crossed random effects\n\n-   In Part 1 we saw **crossed designs** — here's how to fit them\n\n-   Nested: $y_{ij} = \\beta_0 + \\beta_1 x_{ij} + U_{0j} + e_{ij}$\n\n-   Crossed: $y_{ijk} = \\beta_0 + \\beta_1 x_{ijk} + U_{0j} + W_{0k} + e_{ijk}$\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlmer(y ~ condition + (1|subject) + (1|item), data = d)\n```\n:::\n\n\n-   Just one extra random intercept term — $W_{0k}$ for items alongside $U_{0j}$ for subjects\n-   $U_{0j}$ and $W_{0k}$ are assumed **independent** (any subject × item interaction → residual)\n-   Replaces the old \"F1 and F2\" separate-analyses approach (Clark, 1973)\n\n## When to use crossed random effects\n\n-   Whenever you sample both **participants** AND **stimuli** (words, images, scenarios, etc.)\n\n    -   Psycholinguistics, cognitive psych, social psych with vignettes\n    -   Most experimental paradigms with stimulus sets\n\n-   Note: crossed random effects increase model complexity\n\n    -   Convergence issues are more likely here\n    -   This is often where the maximal-vs-parsimonious debate becomes practical\n\n## Maximal model: Fixed effect random intercepts (subject) and slopes (vocoded) model\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmax_model <- lmer(mean_pupil ~vocoded +(1+vocoded|subject), data = eye)\n\nsummary(max_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLinear mixed model fit by REML. t-tests use Satterthwaite's method [\nlmerModLmerTest]\nFormula: mean_pupil ~ vocoded + (1 + vocoded | subject)\n   Data: eye\n\nREML criterion at convergence: -19813.7\n\nScaled residuals: \n    Min      1Q  Median      3Q     Max \n-5.0296 -0.5509 -0.0467  0.4810 10.7164 \n\nRandom effects:\n Groups   Name        Variance   Std.Dev. Corr \n subject  (Intercept) 0.00013592 0.011658      \n          vocodedV6   0.00002816 0.005307 -0.19\n Residual             0.00167497 0.040926      \nNumber of obs: 5609, groups:  subject, 31\n\nFixed effects:\n             Estimate Std. Error        df t value Pr(>|t|)  \n(Intercept)  0.003643   0.002235 28.852287    1.63   0.1140  \nvocodedV6    0.003124   0.001453 30.471987    2.15   0.0396 *\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nCorrelation of Fixed Effects:\n          (Intr)\nvocodedV6 -0.306\n```\n\n\n:::\n:::\n\n\n## Fixed effects\n\n-   Interpretation same as lm\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#grab the fixed effects\nsummary(max_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLinear mixed model fit by REML. t-tests use Satterthwaite's method [\nlmerModLmerTest]\nFormula: mean_pupil ~ vocoded + (1 + vocoded | subject)\n   Data: eye\n\nREML criterion at convergence: -19813.7\n\nScaled residuals: \n    Min      1Q  Median      3Q     Max \n-5.0296 -0.5509 -0.0467  0.4810 10.7164 \n\nRandom effects:\n Groups   Name        Variance   Std.Dev. Corr \n subject  (Intercept) 0.00013592 0.011658      \n          vocodedV6   0.00002816 0.005307 -0.19\n Residual             0.00167497 0.040926      \nNumber of obs: 5609, groups:  subject, 31\n\nFixed effects:\n             Estimate Std. Error        df t value Pr(>|t|)  \n(Intercept)  0.003643   0.002235 28.852287    1.63   0.1140  \nvocodedV6    0.003124   0.001453 30.471987    2.15   0.0396 *\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nCorrelation of Fixed Effects:\n          (Intr)\nvocodedV6 -0.306\n```\n\n\n:::\n:::\n\n\n## Degrees of freedom and p-values\n\n-   Degrees of freedom (denominator) and *p*-values can be assessed with several methods:\n\n    -   ***Satterthwaite*** (default when install `lmerTest` and then run `lmer`)\n\n    -   Asymptotic (Inf) (**default** behavior lme4)\n\n    -   Kenward-Roger — **recommended for small samples** (more conservative; Singmann & Kellen, 2019)\n\n## Random effects/variance components\n\n-   Tells us how much variability there is around the fixed intercept/slope\n\n    -   How much does the average pupil size change between participants\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(max_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLinear mixed model fit by REML. t-tests use Satterthwaite's method [\nlmerModLmerTest]\nFormula: mean_pupil ~ vocoded + (1 + vocoded | subject)\n   Data: eye\n\nREML criterion at convergence: -19813.7\n\nScaled residuals: \n    Min      1Q  Median      3Q     Max \n-5.0296 -0.5509 -0.0467  0.4810 10.7164 \n\nRandom effects:\n Groups   Name        Variance   Std.Dev. Corr \n subject  (Intercept) 0.00013592 0.011658      \n          vocodedV6   0.00002816 0.005307 -0.19\n Residual             0.00167497 0.040926      \nNumber of obs: 5609, groups:  subject, 31\n\nFixed effects:\n             Estimate Std. Error        df t value Pr(>|t|)  \n(Intercept)  0.003643   0.002235 28.852287    1.63   0.1140  \nvocodedV6    0.003124   0.001453 30.471987    2.15   0.0396 *\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nCorrelation of Fixed Effects:\n          (Intr)\nvocodedV6 -0.306\n```\n\n\n:::\n:::\n\n\n## Random effects/variance components\n\n-   Correlation between random intercepts and slopes\n\n    -   Negative correlation\n\n        -   Higher intercept (for normal speech) less of effect (lower slope)\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output .cell-output-stdout}\n\n```\nParameter1 |  Parameter2 |     r |        95% CI | t(29) |     p\n----------------------------------------------------------------\nvocodedV6  | (Intercept) | -0.10 | [-0.44, 0.26] | -0.57 | 0.576\n\nObservations: 31\n```\n\n\n:::\n:::\n\n\n## Visualize Random Effects\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# use easystats to grab group variance\nrandom <- estimate_grouplevel(max_model)\n\nplot(random) + theme_lucid()\n```\n\n::: {.cell-output-display}\n![](mlm_part2_students_files/figure-revealjs/unnamed-chunk-18-1.png){fig-align='center' width=1152}\n:::\n:::\n\n\n## What are you actually seeing?\n\n-   These aren't raw subject means — they've been **pulled toward the grand mean**\n\n-   Subjects with more extreme values → pulled more\n\n-   Subjects with fewer observations → pulled more\n\n-   This is called **shrinkage** or **partial pooling**\n\n-   McElreath (2020): Models without this suffer \"statistical amnesia\" — they can't learn that what happened in one group is informative about other groups\n\n## Why does this happen?\n\n-   The assumption $U_{0j} \\sim N(0, \\sigma_{U_0})$ says: \"subject effects are drawn from a common distribution\"\n\n-   This **IS** the mechanism — it regularizes extreme estimates toward the population mean\n\n    -   More data for a subject → estimate stays closer to raw mean\n    -   Less data → estimate pulled more toward grand mean\n\n-   We'll see this much more clearly in the Bayesian framework — where it becomes a visible **prior**\n\n## Model comparisons\n\n-   Can compare models using `anova` function or `test_likelihoodratio` from `easystats`\n\n    -   *Will be refit using ML if interested in fixed effects*\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# you try\n```\n:::\n\n\n# AIC/BIC\n\n-   LRT requires nested models\n\n## AIC\n\n-   AIC:\n\n$$\nD + 2p\n$$\n\n-   where d = deviance and p = \\# of parameters in model\n\n-   Can compare AICs[^3]:\n\n    $$\n     \\Delta_i = AIC_{i} - AIC_{min}\n    $$\n\n-   Less than 2: More parsimonious model is preferred\n\n-   Between 4 and 7: some evidence for lower AIC model\n\n-   Greater than 10,: strong evidence for lower AIC\n\n[^3]: BURNHAM, ANDERSON, & HUYVAERT (2011)\n\n## BIC\n\n-   BIC:\n\n$$\nD + ln(n)*p\n$$\n\n-   where d = deviance, p = \\# of parameters in model, n = sample size\n\n-   Change in BIC:\n\n    -   $\\Delta{BIC}$ \\<= 2 (No difference)\n\n    -   $\\Delta{BIC}$ \\> 3 (evidence for smaller BIC model)\n\n## AIC/BIC\n\n\n::: {.cell}\n\n```{.r .cell-code}\nperformance::model_performance(max_model) %>% # easystats\n  kable()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRandom effect variances not available. Returned R2 does not account for random effects.\n```\n\n\n:::\n\n::: {.cell-output-display}\n\n\n|       AIC|      AICc|       BIC|R2_conditional | R2_marginal|      RMSE|     Sigma|\n|---------:|---------:|---------:|:--------------|-----------:|---------:|---------:|\n| -19801.66| -19801.65| -19761.87|NA             |   0.0014548| 0.0407697| 0.0409264|\n\n\n:::\n:::\n\n\n## Hypothesis testing\n\n-   Multiple options\n\n    1.  t/F tests with approximate degrees of freedom (Kenward-Rogers or Satterwaithe)\n    2.  Parametric bootstrap\n    3.  **Likelihood ratio test (LRT)**\n\n    -   Can be interpreted as main effects and interactions\n    -   Use `afex` package to do that\n\n## Hypothesis testing - `afex`\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(afex) # load afex in \n\nm <- mixed(mean_pupil ~ 1 + vocoded +  (1+vocoded|subject), data =eye, method = \"LRT\") # fit lmer using afex\n\nnice(m) %>%\n  kable()\n```\n\n::: {.cell-output-display}\n\n\n|Effect  | df|Chisq  |p.value |\n|:-------|--:|:------|:-------|\n|vocoded |  1|4.47 * |.034    |\n\n\n:::\n:::\n\n\n## Using `emmeans`\n\n-   Get means and contrasts\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(emmeans) # get marginal means \n\nemmeans(max_model, specs = \"vocoded\") %>% \n  kable() # grabs means/SEs for each level of vocode \n```\n\n::: {.cell-output-display}\n\n\n|vocoded |    emmean|        SE|  df|  asymp.LCL| asymp.UCL|\n|:-------|---------:|---------:|---:|----------:|---------:|\n|NS      | 0.0036427| 0.0022348| Inf| -0.0007374| 0.0080229|\n|V6      | 0.0067668| 0.0022618| Inf|  0.0023337| 0.0111999|\n\n\n:::\n\n```{.r .cell-code}\npairs(emmeans(max_model, specs = \"vocoded\")) %>%\n  confint() %>%\n  kable()\n```\n\n::: {.cell-output-display}\n\n\n|contrast |   estimate|        SE|  df|  asymp.LCL|  asymp.UCL|\n|:--------|----------:|---------:|---:|----------:|----------:|\n|NS - V6  | -0.0031241| 0.0014532| Inf| -0.0059723| -0.0002759|\n\n\n:::\n\n```{.r .cell-code}\n# use this to get pariwise compairsons between levels of factors\n```\n:::\n\n\n# Assumptions\n\n## Check assumptions\n\n::: columns\n::: {.column width=\"50%\"}\n-   Linearity\n\n-   Normality\n\n    -   Level 1 residuals are normally distributed around zero\n\n    -   Level 2 residuals are multivariate-normal with a mean of zero\n\n-   Homoskedacticity\n\n    -   Level 1/Level 2 predictors and residuals are homoskedastic\n:::\n\n::: {.column width=\"50%\"}\n-   Collinearity\n\n-   Outliers\n:::\n:::\n\n## Assumptions\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(easystats) # performance package\n\ncheck_model(max_model)\n```\n\n::: {.cell-output-display}\n![](mlm_part2_students_files/figure-revealjs/unnamed-chunk-23-1.png){fig-align='center' width=1152}\n:::\n:::\n\n\n## Visualization\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](mlm_part2_students_files/figure-revealjs/unnamed-chunk-24-1.png){width=1152}\n:::\n:::\n\n\n## `ggeffects`\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nggemmeans(max_model, terms=c(\"vocoded\")) %>% plot()\n```\n\n::: {.cell-output-display}\n![](mlm_part2_students_files/figure-revealjs/unnamed-chunk-25-1.png){fig-align='center' width=1152}\n:::\n:::\n\n\n## Effect size\n\n-   Report pseudo-$R^2$ for marginal (fixed) and conditional model (full model) (Nakagawa et al. 2017)\n\n$$\nR^2_{LMM(c)} = \\frac{\\sigma_f^2\\text{fixed} + \\sigma_a^2\\text{random}}{\\sigma_f^2\\text{fixed} + \\sigma_a^2\\text{random} + \\sigma_e^2\\text{residual}}\n$$\n\n$$\nR^2_{\\text{LMM}(m)} = \\frac{\\sigma_f^2\\text{fixed}}{\\sigma_f^2\\text{fixed} + \\sigma_a^2\\text{random} + \\sigma_e^2\\text{residual}}\n$$\n\n-   Report semi-partial $R^2$ for each predictor variable\n    -   $R^2_\\beta$\n        -   `partR2` package in R does this for you\n\n## Effect size\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#get r2 for model with performance from easystats\n\nperformance::r2(max_model) \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRandom effect variances not available. Returned R2 does not account for random effects.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# R2 for Mixed Models\n\n  Conditional R2: NA\n     Marginal R2: 0.001\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# get semi-part\nlibrary(partR2)\n# does not work with random slopes for some reason :/\nR2_3 <- partR2(max_model,data=eye, \n  partvars = c(\"vocoded\"),\n  R2_type = \"marginal\", nboot = 10, CI = 0.95\n)\n```\n:::\n\n\n## Effect size\n\n-   Cohen's $d$ for treatment effects/categorical predictions[^4]\n\n[^4]: Brysbaert, M., & Debeer, D. (2023, September 12). How to run linear mixed effects analysis for pairwise comparisons? A tutorial and a proposal for the calculation of standardized effect sizes. <https://doi.org/10.31234/osf.io/esnku>\n\n$$\nd = \\frac{\\text{Effect}}{\\sqrt{\\sigma^2_\\text{Intercept} + \\sigma^2_\\text{slope} + \\sigma^2_\\text{residual}}}\n$$\n\n\n::: {.cell}\n\n```{.r .cell-code}\nemmeans(max_model,~ vocoded) %>% \n eff_size(.,sigma=.04, edf=30) # need to calcuate sigma and add dfs\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n contrast effect.size     SE  df asymp.LCL asymp.UCL\n NS - V6      -0.0781 0.0377 Inf    -0.152  -0.00421\n\nsigma used for effect sizes: 0.04 \nDegrees-of-freedom method: inherited from asymptotic when re-gridding \nConfidence level used: 0.95 \n```\n\n\n:::\n:::\n\n\n# Reporting Results\n\n## Describing a MLM analysis - Structure\n\n-   What was the nested data structure (e.g., how many levels; what were the units at each level?)\n\n    • How many units were in each level, on average?\n\n    • What was the range of the number of lower-level units in each group/cluster?\n\n## Describing a MLM analysis - Model\n\n::: columns\n::: {.column width=\"50%\"}\n-   What equation can best represent your model?\n\n-   What estimation method was used (e.g., ML, REML)?\n\n-   If there were convergence issues, how was this addressed?\n\n-   What software (and version) was used (when using R, what packages as well)?\n:::\n\n::: {.column width=\"50%\"}\n-   If degrees of freedom were used, what kind?\n\n-   What type of models were estimated (i.e., unconditional, random intercept, random slope, max)?\n\n-   What variables were centered and what kind of centering was used?\n\n-   What model assumptions were checked and what were the results?\n:::\n:::\n\n## Describing a MLM analysis - Results\n\n::: columns\n::: {.column width=\"50%\"}\n-   What was the ICC of the outcome variable?\n\n-   Are fixed effects and variance components reported?\n\n-   What inferential statistics were used (e.g., t-statistics, LRTs)?\n\n-   How precise were the results (report the standard errors and/or confidence intervals)?\n:::\n\n::: {.column width=\"50%\"}\n-   Were model comparisons performed (e.g., AIC, BIC, if using an LRT,report the χ2, degrees of freedom, and p value)?\n\n-   Were effect sizes reported for overall model and individual predictors (e.g., Cohen’s d, $R^2$ )?\n:::\n:::\n\n## Write-up\n\n\n::: {.cell}\n\n```{.r .cell-code}\nreport::report(max_model) # easystats report function\n```\n:::\n\n\nWe fitted a linear mixed model (estimated using REML and nloptwrap optimizer) to predict mean_pupil with vocoded (formula: mean_pupil ~ vocoded). The model included vocoded as random effects (formula: ~1 + vocoded | subject). The model's explanatory power related to the fixed effects alone (marginal R2) is 1.45e-03. The model's intercept, corresponding to vocoded = NS, is at 3.64e-03 (95% CI [-7.38e-04, 8.02e-03], t(5603) = 1.63, p = 0.103). Within this model:\n\n  - The effect of vocoded [V6] is statistically significant and positive (beta = 3.12e-03, 95% CI [2.75e-04, 5.97e-03], t(5603) = 2.15, p = 0.032; Std. beta = 0.07, 95% CI [6.49e-03, 0.14])\n\nStandardized parameters were obtained by fitting the model on a standardized version of the dataset. 95% Confidence Intervals (CIs) and p-values were computed using a Wald t-distribution approximation.\n\n## Table\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodelsummary::modelsummary(list(\"max model\" = max_model), output=\"html\") # modelsummary package\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<!-- preamble start -->\n\n    <script src=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.js\"></script>\n\n    <script>\n      // Create table-specific functions using external factory\n      const tableFns_8cu4nlwxz4qibw9uz9er = TinyTable.createTableFunctions(\"tinytable_8cu4nlwxz4qibw9uz9er\");\n      // tinytable span after\n      window.addEventListener('load', function () {\n          var cellsToStyle = [\n            // tinytable style arrays after\n          { positions: [ { i: '13', j: 2 } ], css_id: 'tinytable_css_nkkavmamzlrgexw8y3ai',}, \n          { positions: [ { i: '8', j: 2 } ], css_id: 'tinytable_css_mq3xp06guzzjgpgvp64s',}, \n          { positions: [ { i: '1', j: 2 }, { i: '2', j: 2 }, { i: '3', j: 2 }, { i: '4', j: 2 }, { i: '5', j: 2 }, { i: '6', j: 2 }, { i: '7', j: 2 }, { i: '9', j: 2 }, { i: '10', j: 2 }, { i: '11', j: 2 }, { i: '12', j: 2 } ], css_id: 'tinytable_css_qbcrr6s97bvkuin87xps',}, \n          { positions: [ { i: '0', j: 2 } ], css_id: 'tinytable_css_nyzc3fmvm4bwif97jhux',}, \n          { positions: [ { i: '13', j: 1 } ], css_id: 'tinytable_css_gegktz1bq2ixnzqdklxm',}, \n          { positions: [ { i: '8', j: 1 } ], css_id: 'tinytable_css_toi1kh925uwj5lx596ge',}, \n          { positions: [ { i: '1', j: 1 }, { i: '2', j: 1 }, { i: '3', j: 1 }, { i: '4', j: 1 }, { i: '5', j: 1 }, { i: '6', j: 1 }, { i: '7', j: 1 }, { i: '9', j: 1 }, { i: '10', j: 1 }, { i: '11', j: 1 }, { i: '12', j: 1 } ], css_id: 'tinytable_css_5vyqdvjl3txhlyt278vu',}, \n          { positions: [ { i: '0', j: 1 } ], css_id: 'tinytable_css_zp7l753fupj68ja1smkt',}, \n          ];\n\n          // Loop over the arrays to style the cells\n          cellsToStyle.forEach(function (group) {\n              group.positions.forEach(function (cell) {\n                  tableFns_8cu4nlwxz4qibw9uz9er.styleCell(cell.i, cell.j, group.css_id);\n              });\n          });\n      });\n    </script>\n\n    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.css\">\n    <style>\n    /* tinytable css entries after */\n    #tinytable_8cu4nlwxz4qibw9uz9er td.tinytable_css_nkkavmamzlrgexw8y3ai, #tinytable_8cu4nlwxz4qibw9uz9er th.tinytable_css_nkkavmamzlrgexw8y3ai {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.08em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }\n    #tinytable_8cu4nlwxz4qibw9uz9er td.tinytable_css_mq3xp06guzzjgpgvp64s, #tinytable_8cu4nlwxz4qibw9uz9er th.tinytable_css_mq3xp06guzzjgpgvp64s {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }\n    #tinytable_8cu4nlwxz4qibw9uz9er td.tinytable_css_qbcrr6s97bvkuin87xps, #tinytable_8cu4nlwxz4qibw9uz9er th.tinytable_css_qbcrr6s97bvkuin87xps { text-align: center }\n    #tinytable_8cu4nlwxz4qibw9uz9er td.tinytable_css_nyzc3fmvm4bwif97jhux, #tinytable_8cu4nlwxz4qibw9uz9er th.tinytable_css_nyzc3fmvm4bwif97jhux {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }\n    #tinytable_8cu4nlwxz4qibw9uz9er td.tinytable_css_gegktz1bq2ixnzqdklxm, #tinytable_8cu4nlwxz4qibw9uz9er th.tinytable_css_gegktz1bq2ixnzqdklxm {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.08em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }\n    #tinytable_8cu4nlwxz4qibw9uz9er td.tinytable_css_toi1kh925uwj5lx596ge, #tinytable_8cu4nlwxz4qibw9uz9er th.tinytable_css_toi1kh925uwj5lx596ge {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }\n    #tinytable_8cu4nlwxz4qibw9uz9er td.tinytable_css_5vyqdvjl3txhlyt278vu, #tinytable_8cu4nlwxz4qibw9uz9er th.tinytable_css_5vyqdvjl3txhlyt278vu { text-align: left }\n    #tinytable_8cu4nlwxz4qibw9uz9er td.tinytable_css_zp7l753fupj68ja1smkt, #tinytable_8cu4nlwxz4qibw9uz9er th.tinytable_css_zp7l753fupj68ja1smkt {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }\n    </style>\n    <div class=\"container\">\n      <table class=\"tinytable\" id=\"tinytable_8cu4nlwxz4qibw9uz9er\" style=\"width: auto; margin-left: auto; margin-right: auto;\" data-quarto-disable-processing='true'>\n        \n        <thead>\n              <tr>\n                <th scope=\"col\" data-row=\"0\" data-col=\"1\"> </th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"2\">max model</th>\n              </tr>\n        </thead>\n        \n        <tbody>\n                <tr>\n                  <td data-row=\"1\" data-col=\"1\">(Intercept)</td>\n                  <td data-row=\"1\" data-col=\"2\">0.004</td>\n                </tr>\n                <tr>\n                  <td data-row=\"2\" data-col=\"1\"></td>\n                  <td data-row=\"2\" data-col=\"2\">(0.002)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"3\" data-col=\"1\">vocodedV6</td>\n                  <td data-row=\"3\" data-col=\"2\">0.003</td>\n                </tr>\n                <tr>\n                  <td data-row=\"4\" data-col=\"1\"></td>\n                  <td data-row=\"4\" data-col=\"2\">(0.001)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"5\" data-col=\"1\">SD (Intercept subject)</td>\n                  <td data-row=\"5\" data-col=\"2\">0.012</td>\n                </tr>\n                <tr>\n                  <td data-row=\"6\" data-col=\"1\">SD (vocodedV6 subject)</td>\n                  <td data-row=\"6\" data-col=\"2\">0.005</td>\n                </tr>\n                <tr>\n                  <td data-row=\"7\" data-col=\"1\">Cor (Intercept~vocodedV6 subject)</td>\n                  <td data-row=\"7\" data-col=\"2\">−0.195</td>\n                </tr>\n                <tr>\n                  <td data-row=\"8\" data-col=\"1\">SD (Observations)</td>\n                  <td data-row=\"8\" data-col=\"2\">0.041</td>\n                </tr>\n                <tr>\n                  <td data-row=\"9\" data-col=\"1\">Num.Obs.</td>\n                  <td data-row=\"9\" data-col=\"2\">5609</td>\n                </tr>\n                <tr>\n                  <td data-row=\"10\" data-col=\"1\">R2 Marg.</td>\n                  <td data-row=\"10\" data-col=\"2\">0.001</td>\n                </tr>\n                <tr>\n                  <td data-row=\"11\" data-col=\"1\">AIC</td>\n                  <td data-row=\"11\" data-col=\"2\">−19801.7</td>\n                </tr>\n                <tr>\n                  <td data-row=\"12\" data-col=\"1\">BIC</td>\n                  <td data-row=\"12\" data-col=\"2\">−19761.9</td>\n                </tr>\n                <tr>\n                  <td data-row=\"13\" data-col=\"1\">RMSE</td>\n                  <td data-row=\"13\" data-col=\"2\">0.04</td>\n                </tr>\n        </tbody>\n      </table>\n    </div>\n<!-- hack to avoid NA insertion in last line -->\n```\n\n:::\n:::\n\n\n## Power\n\n-   Simulation-based power analyses\n\n    -   Simulate new data\n\n        -   `faux` (<https://scienceverse.github.io/faux/articles/sim_mixed.html>)\n\n    -   Use pilot data (what I would do)\n\n        -   `mixedpower` (<https://link.springer.com/article/10.3758/s13428-021-01546-0>)\n        -   `simr` (<https://besjournals.onlinelibrary.wiley.com/doi/full/10.1111/2041-210X.12504>)\n\n## The number one power insight\n\n-   Number of **Level 2 units** (clusters/groups) matters MORE than observations per cluster\n\n-   \"500 observations in 8 schools\" → poor power for school-level effects\n\n-   \"200 observations across 40 schools\" → much better\n\n-   Rule of thumb: aim for **20-30+ Level 2 units** minimum (Kreft, 1996)\n\n-   Adding more observations within clusters has **diminishing returns** for between-cluster power\n\n## Planning your study\n\n-   Increase the **number of groups/clusters FIRST**, then observations per group\n\n-   Use simulation tools (`faux`, `simr`) to verify power for YOUR specific design\n\n-   Power depends on: number of clusters, cluster size, ICC, effect size, random effects structure\n\n# Wrapping Up\n\n## What we've built\n\n-   The frequentist MLM toolkit: **specify → fit → interpret → test → report**\n\n-   You can handle: nested data, repeated measures, unbalanced designs, crossed random effects\n\n-   Tools: `lme4` + `lmerTest` + `afex` + `emmeans` + `easystats`\n\n## Limitations we encountered\n\n-   **Convergence issues** — some models just won't fit (especially with complex random effects)\n\n-   **Boundary problems** — variance estimates stuck at zero (singular fits)\n\n-   **The p-value debates** — Satterthwaite vs KR vs LRT, and none are exact\n\n-   **Point estimates only** — no full distribution of uncertainty for parameters\n\n-   Can't easily make probability statements: *\"There is a 95% probability that...\"*\n\n## Coming up: Bayesian regression\n\n-   The models and formula syntax carry over — the inference framework changes\n\n-   `brm(y ~ x + (1|group))` instead of `lmer(y ~ x + (1|group))`\n\n-   Some of these limitations become much easier — or disappear entirely\n\n-   And the partial pooling / shrinkage we saw today? It becomes beautifully visible.\n\n# Appendix {visibility=\"uncounted\"}\n\n## Likelihood visualizations\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](images/like1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n## Likelihood visualizations\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](images/like2.png){fig-align='center' width=100%}\n:::\n:::\n\n\n## Likelihood visualizations\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](images/like4.png){fig-align='center' width=100%}\n:::\n:::\n\n\n## Likelihood visualizations\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](images/like5.png){fig-align='center' width=100%}\n:::\n:::\n\n\n## Likelihood visualizations\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](images/like6.png){fig-align='center' width=100%}\n:::\n:::\n\n\n## $\\chi^2$ distribution\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](mlm_part2_students_files/figure-revealjs/unnamed-chunk-36-1.png){fig-align='center' width=1152}\n:::\n:::\n\n",
    "supporting": [
      "mlm_part2_students_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}