{
  "hash": "8f4b751c820826afadfdffe87cb8e163",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Introduction to Bayesian Inference\"\nsubtitle: \"<small>(modified from Jason Geller)</small>\"\nauthor: \"Suyog Chandramouli \"\ncategories: [Bayes]\ndate: '2026-02-16'\ninstitute: 'PSY504, Advanced Statistics in Psychology<br>Princeton University'\nfooter: \"PSY 504: Advanced Statistics\"\nformat: \n  revealjs:\n    theme: solarized\n    css: slide-style.css \n    transition: fade\n    multiplex: false\n    slide-number: true\n    incremental: false \n    chalkboard: true\n    fontsize: \"25pt\"\nwebr:\n  packages: [\"tidyverse\", \"easystats\", \"broom\", \"knitr\", \"emmeans\", \"ggeffects\",\"brms\"]\nfilters:\n  - webr\nexecute:\n  freeze: auto\n  echo: true\n  message: false\n  warning: false\n  fig-align: center\n  fig-width: 12\n  fig-height: 8\n  editor_options: \n  chunk_output_type: inline\n  code-overflow: wrap\n  html:\n    code-fold: true\n    code-tools: true\neditor: \n  markdown: \n    wrap: sentence\n---\n\n## Packages\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(tidybayes)\nlibrary(brms) # run bayesian models\nlibrary(emoji)\nlibrary(emmeans)\nlibrary(easystats)\nlibrary(ggdist)\nlibrary(marginaleffects)\nlibrary(ggeffects)\nlibrary(knitr)\nlibrary(gghalves)\nlibrary(ggokabeito)\nlibrary(ggbeeswarm)\n\noptions(scipen=999)\n```\n:::\n\n\n-   QMD available in: <https://github.com/suyoghc/PSY504_Spring_2026/tree/main/posts>\n\n# Today\n\n-   A gentle introduction to Bayesian inference\n\n-   Fit, interpret, and report a Bayesian regression with `brms`\n\n# Models and Data Generating Processes {.center}\n\n## What is a data generating process (DGP)?\n\nThe process that produced your data.\n\n. . .\n\nLast semester: every simulation you wrote was a DGP.\n\nSteps:\n\n-   Pick a distribution.\n\n-   Pick parameters.\n\n-   Generate data.\n\n. . .\n\nLast week: logistic regression was a DGP\n\n## A model (class) is a *family* of DGPs\n\nA **model** = a structure with free parameters.\n\n. . .\n\nEach choice of parameters → a different member of the family.\n\n. . .\n\n$$Y_i \\sim \\text{Normal}(\\mu_i, \\sigma), \\quad \\mu_i = \\beta_0 + \\beta_1 X_i$$\n\n. . .\n\n-   $\\beta_0 = 50, \\beta_1 = 0.3, \\sigma = 10$ → one member\n-   $\\beta_0 = 40, \\beta_1 = 0.8, \\sigma = 5$ → another member\n\n## Two families you already know\n\n::::: columns\n::: {.column width=\"50%\"}\n**Linear model**\n\n$$\n\\begin{align}\nY_i &\\sim \\text{Normal}(\\mu_i, \\sigma) \\\\\n\\mu_i &= \\beta_0 + \\beta_1 X_i\n\\end{align}\n$$\n:::\n\n::: {.column width=\"50%\"}\n**Logistic model**\n\n$$\n\\begin{align}\nY_i &\\sim \\text{Bernoulli}(p_i) \\\\\n\\text{logit}(p_i) &= \\beta_0 + \\beta_1 X_i\n\\end{align}\n$$\n:::\n:::::\n\n. . .\n\nModel structure:\n\n-   you specify parameters\n\n-   at each X, the parameters produce a different distribution\n\n-   data gets drawn from it (the \\~ ; captures randomness)\n\n## The DGP runs forward (parameters → data)\n\nWe fix the parameters.\nAnd **generate** data.\n\n. . .\n\n\"If $\\beta_0 = 50$, $\\beta_1 = 0.3$, $\\sigma = 10$ — what grades would I see?\"\n\n``` r\nrnorm(n = 33, mean = 50 + 0.3 * avgView, sd = 10)\n```\n\n. . .\n\n-   Parameters are **known**/ fixed by you\n-   Data **varies** (different in each simulation)\n-   `r` functions: `rnorm()`, `rbinom()`\n\n## What \\~ means\n\n$Y_i \\sim \\text{Binomial}(n, \\theta)$ means you are sampling n points from:\n\n$$p(Y = k \\mid \\theta) = \\binom{n}{k}\\theta^k(1-\\theta)^{n-k}$$\n\n. . .\n\nNow you can ask questions like \"If $\\theta = 0.6$ — what data/outcomes are possible, and how likely are they?\"\n\n. . .\n\n``` r\ndbinom(0:5, size = 5, prob = 0.6)\n```\n\nThese sum to 1.\n. . .\n\nThe probability of each outcome is covered.\n\nYou get a proper probability distribution.\n\n. . .\n\nThis is $p(\\text{data} \\mid \\theta)$**.**\n\n## $p(\\text{data} \\mid \\theta)$ for the coin family\n\nConsider 5 tosses.\n\nEach row is DGP/ a member of the model family.\n\n|                | 0 heads | 1 head | 2 heads | 3 heads | 4 heads | 5 heads | **Row sum** |\n|---------|---------|---------|---------|---------|---------|---------|---------|\n| $\\theta = 0.2$ | .328    | .410   | .205    | .051    | .006    | .000    | **1.0**     |\n| $\\theta = 0.4$ | .078    | .259   | .346    | .230    | .077    | .010    | **1.0**     |\n| $\\theta = 0.5$ | .031    | .156   | .312    | .312    | .156    | .031    | **1.0**     |\n| $\\theta = 0.6$ | .010    | .077   | .230    | .346    | .259    | .078    | **1.0**     |\n| $\\theta = 0.8$ | .000    | .006   | .051    | .205    | .410    | .328    | **1.0**     |\n\n. . .\n\nEvery row sums to 1.\n\nEach row is a probability distribution.\n\n## The true DGP is unknown\n\nSay, you observed 3 heads out of 5 tosses.\n\n. . .\n\nCan you answer, \"Which $\\theta$ produced the data?\"\n\n. . .\n\n|                | 0 heads | 1 head | 2 heads | 3 heads | 4 heads | 5 heads | **Row sum** |\n|---------|---------|---------|---------|---------|---------|---------|---------|\n| $\\theta = 0.2$ | .328    | .410   | .205    | .051    | .006    | .000    | **1.0**     |\n| $\\theta = 0.4$ | .078    | .259   | .346    | .230    | .077    | .010    | **1.0**     |\n| $\\theta = 0.5$ | .031    | .156   | .312    | .312    | .156    | .031    | **1.0**     |\n| $\\theta = 0.6$ | .010    | .077   | .230    | .346    | .259    | .078    | **1.0**     |\n| $\\theta = 0.8$ | .000    | .006   | .051    | .205    | .410    | .328    | **1.0**     |\n\n. . .\n\nIn reality, you don't know.\nBut you're making an educated guess.\n\n. . .\n\n**Inference** = using the data to figure out which model parameters (row) likely produced it.\n\n## Inference runs backward (data → parameters)\n\nYou observed 3 heads out of 5 tosses.\n\nWhich model parameterization produced these observations?\n\n. . .\n\nHere, data are fixed.\n\nBut, parameters are unknown.\n\n. . .\n\nTwo strategies for guessing:\n\n. . .\n\n-   MLE — find the best-scoring row in the table\n\n. . .\n\n-   Bayes — get a distribution over all plausible members\n\n## How do we score the members?\n\nFix the data.\n\nIn each row, ask: how often does one expect the outcome?\n\n. . .\n\nWe observe 3 heads out of 5.\n\n. . .\n\n$\\theta = 0.6$ → score: 0.346\n\n$\\theta = 0.5$ → score: 0.312\n\n$\\theta = 0.2$ → score: 0.051\n\n. . .\n\nHigher score =\\> that row explains the data better.\n\n## Inference : Data (column) is fixed\n\n|                | 0 heads | 1 head | 2 heads | **3 heads**     | 4 heads | 5 heads |\n|----------------|---------|--------|---------|-----------------|---------|---------|\n| $\\theta = 0.2$ |         |        |         | **.051**        |         |         |\n| $\\theta = 0.4$ |         |        |         | **.230**        |         |         |\n| $\\theta = 0.5$ |         |        |         | **.312**        |         |         |\n| $\\theta = 0.6$ |         |        |         | **.346**        |         |         |\n| $\\theta = 0.8$ |         |        |         | **.205**        |         |         |\n|                |         |        |         | **Sum = 1.144** |         |         |\n\n. . .\n\nData fixed at 3 heads.\n\nRead **down** the column.\n\n. . .\n\nPeak at $\\theta = 0.6$.\nMaximum Likelihood Estimation (MLE) picks the max.\n\n. . .\n\nSum = 1.144.\nThe column is not a distribution!\n\n## Inference : Data (column) is fixed\n\nYou might also have observed 4 heads in 5 tosses\n\n|                | **4 heads** |\n|----------------|-------------|\n| $\\theta = 0.2$ | .006        |\n| $\\theta = 0.4$ | .077        |\n| $\\theta = 0.5$ | .156        |\n| $\\theta = 0.6$ | .259        |\n| $\\theta = 0.7$ | .360        |\n| $\\theta = 0.8$ | **.410**    |\n\n. . .\n\nMLE picks $\\theta = 0.8$.\nThe true value is 0.5.\n\n. . .\n\nWith just 5 flips MLE is noisy.\n\nThe best-scoring $\\theta$ isn't necessarily the true $\\theta$.\n\n## Inference : Data (column) is fixed\n\nTry to make a statement:\n\n. . .\n\nForward: \"There's a **35% chance** of getting 3 heads.\" ✓\n\n. . .\n\nBackward: \"There's a \\*\\*\\_\\_\\_% chance\\*\\* that $\\theta$ is 0.6.\" ?\n\n. . .\n\nWe can't fill in the blank yet.\n\nThe scores don't add to 1.\n\n. . .\n\nWe are looking for $p(\\theta \\mid \\text{data})$.\n\n## The likelihood is not enough\n\nWe want $p(\\theta \\mid \\text{data})$ — a distribution.\n\n. . .\n\nThe likelihood finds the peak.\nThat's MLE.\n\n. . .\n\nBut it can't fill in the blank: \"\\_\\_\\_% chance $\\theta$ is between 0.4 and 0.8.\"\n\n## You know things before seeing data\n\n. . .\n\nYou're flipping a coin — not rolling a die, not drawing cards.\n\n. . .\n\nMost coins are roughly fair.\n$\\theta$ is probably near 0.5.\n\n. . .\n\n$\\theta = 0.0$ or $\\theta = 1.0$?\nPossible — but highly unlikely.\n\n. . .\n\nThe likelihood doesn't have this knowledge.\n\nIt just scores based on $P(D|\\theta_i)$\n\n## A prior distribution\n\nWhich $\\theta$ values are plausible — **before** you flip?\n\n$$p(\\theta)$$\n\n. . .\n\n\"Most coins are fair-ish\" → prior peaked near 0.5\n\n. . .\n\n\"I have no idea\" → flat prior, all $\\theta$ equally plausible\n\n. . .\n\n\"This coin came from a magic shop\" → prior allows extreme values\n\n. . .\n\nUnlike the likelihood — the prior **is** a distribution.\nSums to 1.\n\n## Bayes' rule\n\n$$p(\\theta \\mid \\text{data}) \\;\\propto\\; \\underbrace{p(\\theta)}_{\\text{Prior}} \\;\\times\\; \\underbrace{L(\\theta)}_{\\text{Likelihood}}$$\n\n. . .\n\nPrior (distribution) × Likelihood (scoring function) = **Posterior** (distribution)\n\n. . .\n\n-   Prior — what you believed before\n-   Likelihood — what the data say\n-   Posterior — your updated belief\n\n. . .\n\nThe posterior **is** $p(\\theta \\mid \\text{data})$.\n\nNow you can fill in the blank.\n\n## The coin posterior\n\n3 heads out of 5.\nFlat prior.\nMultiply prior × likelihood at each $\\theta$:\n\n. . .\n\n| $\\theta$ | Prior | Likelihood | Prior × Likelihood | **Posterior** |\n|----------|-------|------------|--------------------|---------------|\n| 0.2      | .200  | .051       | .010               | **.045**      |\n| 0.4      | .200  | .230       | .046               | **.201**      |\n| 0.5      | .200  | .312       | .062               | **.273**      |\n| 0.6      | .200  | .346       | .069               | **.303**      |\n| 0.8      | .200  | .205       | .041               | **.179**      |\n|          |       |            | Sum = .229         | **1.0**       |\n\n. . .\n\nPrior × Likelihood doesn't sum to 1.\nDivide each by the sum (.229) to normalize.\n\n. . .\n\nPosterior sums to 1.\nNow it's a distribution.\n\n. . .\n\n\"There's a **30% chance** $\\theta$ is 0.6.\" The blank is filled.\n\n## Bayes' rule\n\n$$p(\\theta \\mid \\text{data}) \\;\\propto\\; \\underbrace{p(\\theta)}_{\\text{Prior}} \\;\\times\\; \\underbrace{L(\\theta)}_{\\text{Likelihood}}$$\n\n. . .\n\nPrior (distribution) × Likelihood (scoring function) = **Posterior** (distribution)\n\n. . .\n\n-   Prior — what you believed before\n-   Likelihood — what the data say\n-   Posterior — your updated belief\n\n. . .\n\nThe full version:\n\n$$p(\\theta \\mid \\text{data}) = \\frac{p(\\theta) \\times L(\\theta)}{\\sum_{\\theta} p(\\theta) \\times L(\\theta)}$$\n\nThe denominator just makes it sum to 1.\n\n## The coin posterior — with an informative prior\n\n3 heads out of 5.\nBut now: \"most coins are roughly fair.\"\n\n. . .\n\n| $\\theta$ | Prior | Likelihood | Prior × Likelihood | **Posterior** |\n|----------|-------|------------|--------------------|---------------|\n| 0.0      | .010  | .000       | .000               | **.000**      |\n| 0.1      | .040  | .008       | .000               | **.001**      |\n| 0.3      | .200  | .132       | .026               | **.102**      |\n| 0.5      | .400  | .312       | .125               | **.483**      |\n| 0.6      | .250  | .346       | .086               | **.334**      |\n| 0.8      | .100  | .205       | .020               | **.079**      |\n|          |       |            | Sum = .258         | **1.0**       |\n\n. . .\n\nMLE picked $\\theta = 0.6$.\nThe posterior peaks at $\\theta = 0.5$.\n\n. . .\n\nThe prior pulled the estimate toward \"fair.\" Data alone said 0.6.\nPrior knowledge said \"probably near 0.5.\" The posterior is a compromise.\n\n## Three ingredients\n\n:::::: columns\n::: {.column width=\"33%\"}\n**Prior** $p(\\theta)$\n\nBelief before data\n\nDistribution ✓\n:::\n\n::: {.column width=\"33%\"}\n**Likelihood** $L(\\theta)$\n\nWhat data say\n\nNot a distribution ✗\n:::\n\n::: {.column width=\"33%\"}\n**Posterior** $p(\\theta \\mid \\text{data})$\n\nUpdated belief\n\nDistribution ✓\n:::\n::::::\n\n. . .\n\n-   Both high → posterior high\n-   Either low → posterior pulled down\n-   With lots of data — likelihood dominates\n-   With little data — prior matters more\n\n## Why can't we just compute it?\n\nIn principle — just multiply prior × likelihood at every $\\theta$.\n\n. . .\n\nBut most models in practice have continuous parameters — every $\\theta$ between 0 and 1.\n\n$$p(\\theta \\mid \\text{data}) = \\frac{p(\\theta) \\times L(\\theta)}{\\int p(\\theta) \\times L(\\theta) \\, d\\theta}$$\n\n. . .\n\nThe denominator integrates over **every possible** $\\theta$.\n\n. . .\n\n1 parameter → easy.\n\n3 → hard.\n\n20 → forget it.\n\n. . .\n\nSolution: don't compute it.\n**Sample from it.** . . . Probabilistic programming languages let you do this more easily.\n\n## What does \"sample from it\" mean?\n\nWe can't write down $p(\\theta \\mid \\text{data})$ as a formula.\n\n. . .\n\nBut we can generate thousands of $\\theta$ values that **behave as if** they came from it.\n\n. . .\n\nImagine drawing 10,000 values of $\\theta$ from the posterior:\n\n-   \\~300 of them would be near 0.6\n-   \\~270 near 0.5\n-   \\~45 near 0.2\n-   Almost none near 0.0\n\n. . .\n\nThe histogram of those draws **is** the posterior.\n\nWe can compute probabilities now without the formula/ without knowing the likelihood function!\n\n## What Bayes gives you that MLE doesn't\n\n|   | MLE | Bayes |\n|------------------------|------------------------|------------------------|\n| Point estimate | ✓ (peak) | ✓ (posterior mean/median) |\n| Uncertainty | SE from curvature | Full distribution |\n| Probability statements | ✗ | \"95% chance β₁ ∈ \\[0.1, 0.5\\]\" |\n| Prior knowledge | ✗ | ✓ |\n| Small samples | Unstable (due to sampling error) | Priors stabilize estimates |\n| Evidence FOR null | ✗ | ✓ (Bayes Factors) |\n\n# The rise of Bayesian statistics {.center}\n\n## The rise of Bayesian statistics\n\n![](images/bayes_pop.jpg)\n\n## Why now?\n\n::::: columns\n::: {.column width=\"50%\"}\n**Technology**\n\n-   Faster computers\n-   Better algorithms (MCMC -\\> HMC)\n-   Accessible software (`brms`, Stan)\n:::\n\n::: {.column width=\"50%\"}\n**Frustration**\n\n-   Can't incorporate prior knowledge\n-   p-values don't answer what we want\n-   Can't find evidence FOR the null\n-   Replication crisis\n:::\n:::::\n\n## Bayesian statistics as a tool\n\n::::: columns\n::: {.column width=\"50%\"}\n-   Google \"Bayesian\" → philosophical wars\n\n-   Subjective vs. objective.\n    Frequentist vs. Bayesian.\n\n-   Interesting.\n    Not our focus.\n:::\n\n::: {.column width=\"50%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](images/bayespower.jpg){width=271}\n:::\n:::\n\n:::\n:::::\n\n## Two views of probability\n\n::::: columns\n::: {.column width=\"50%\"}\n**Frequentist**\n\nProbability = long-run frequency.\n\n\"If I repeated this experiment forever, 60% of the time I'd get heads.\"\n\n. . .\n\nParameters are **fixed** but unknown.\n\nData are **random**.\n\nOnly data get probability statements.\n:::\n\n::: {.column width=\"50%\"}\n**Bayesian**\n\nProbability = degree of belief.\n\n\"I'm 60% sure this coin is biased toward heads.\"\n\n. . .\n\nParameters are **uncertain** — they get distributions.\n\nData are **fixed** (you observed them).\n\nParameters get probability statements.\n:::\n:::::\n\n# Bayesian belief updating {.center}\n\n## Belief updating: an example\n\nLet's watch Bayes' rule work — step by step.\n\n. . .\n\nWhat proportion of people are dog people?\n\n. . .\n\n-   Data: 0 = cat person, 1 = dog person\n-   Parameter: $\\theta$ = proportion of dog people\n-   Sample: 5 people\n\n. . .\n\nSame structure as the coin — just a different question.\n\n## Step 1: State your prior\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](images/diffpriors.png){fig-align='center' width=1978}\n:::\n:::\n\n\n. . .\n\nPeople vary in how strongly they state prior beliefs.\n\n. . .\n\n-   **Informative** → \"I'm pretty sure it's near 0.5\"\n-   **Weakly informative** → \"Probably between 0.2 and 0.8\"\n-   **Non-informative** → \"I have no idea\"\n\n. . .\n\nMost researchers use **weakly informative** priors.\n\n## Step 2: Your prior makes predictions\n\nBefore seeing data — what does each model predict?\n\n![](images/prior_predictive.png){fig-align=\"center\"}\n\n. . .\n\nNarrow prior → specific predictions.\n\nWide prior → anything is plausible.\n\n## Step 3: Collect data\n\n![](images/bayes_data.png){fig-align=\"center\"}\n\n. . .\n\n3 out of 5 are dog people.\n\nEverything before this happened **without data**.\n\nNow we update.\n\n## Step 4: Which model predicted better?\n\nThe **marginal likelihood** — how plausible is the observed data under each model?\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](images/marg_like.png){fig-align='center' width=2085}\n:::\n:::\n\n\n. . .\n\nGo back to each model's predictions.\nEvaluate at the observed data.\n\nThe ratio of these = the **Bayes Factor**.\n\n## Bayes Factors\n\nHow much did the data change your mind?\n\n$$BF_{12} = \\frac{P(\\text{data} \\mid M_1)}{P(\\text{data} \\mid M_2)}$$\n\n. . .\n\n-   $BF > 1$ → data favor $M_1$\n-   $BF < 1$ → data favor $M_2$\n-   $BF = 1$ → data equally consistent with both\n\n. . .\n\nUnlike p-values — BFs can provide evidence **for** the null.\n\n. . .\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](images/bf.png){fig-align='center' width=60%}\n:::\n:::\n\n\n## Step 5: Update → Posterior\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](images/step6.png){fig-align='center' width=2005}\n:::\n:::\n\n\n. . .\n\nThe wide prior (blue) gets reshaped — narrower, pulled toward the data.\n\n. . .\n\nThe spike prior (green) doesn't budge.\n\nIf you rule something out completely, no data can bring it back.\n\n## Prior → Posterior\n\n![](images/priorpost.jpg){fig-align=\"center\"}\n\n. . .\n\nThe posterior sits between prior and likelihood.\n\nWith more data — pulled toward the likelihood.\n\nWith less data — stays closer to the prior.\n\n## Credible intervals\n\nThe posterior gives you what you always wanted from confidence intervals:\n\n. . .\n\n\"With 95% probability, $\\theta$ lies within this interval.\"\n\n. . .\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](images/step7.png){fig-align='center' width=70%}\n:::\n:::\n\n\n. . .\n\nThis is a **direct probability statement** about the parameter.\n\nNot \"if we repeated the experiment...\"\n\n# From coins to regression {.center}\n\n## Same recipe, more parameters\n\n|   | Coin | Regression |\n|------------------------|------------------------|------------------------|\n| Model | $Y \\sim \\text{Binomial}(n, \\theta)$ | $Y \\sim \\text{Normal}(\\mu_i, \\sigma)$ |\n| Parameters | $\\theta$ | $\\beta_0, \\beta_1, \\sigma$ |\n| Prior | $p(\\theta)$ | $p(\\beta_0), p(\\beta_1), p(\\sigma)$ |\n| Likelihood | Score each $\\theta$ | Score each $(\\beta_0, \\beta_1, \\sigma)$ |\n| Posterior | $p(\\theta \\mid \\text{data})$ | $p(\\beta_0, \\beta_1, \\sigma \\mid \\text{data})$ |\n\n. . .\n\nMore parameters.\nSame recipe.\n\n. . .\n\n`brms` handles all of it.\n\n## Computing a likelihood\n\n``` r\ncompute_ll <- function(b0, b1, data) {\n  p_hat <- plogis(b0 + b1 * data$lead_weight)\n  sum(data$outcomes * log(p_hat) + \n      (1 - data$outcomes) * log(1 - p_hat))\n}\n```\n\n. . .\n\nSame idea — many parameters, score each combination.\n\n. . .\n\nThe linear model has one too — swap in `dnorm()`.\n\n## The likelihood for a linear model\n\n$$Y_i \\sim \\text{Normal}(\\mu_i, \\sigma), \\quad \\mu_i = \\beta_0 + \\beta_1 X_i$$\n\nSay $\\beta_0 = 50$, $\\beta_1 = 0.3$, $\\sigma = 10$:\n\n. . .\n\n-   Student watches 30 min → predicted mean = $50 + 0.3(30) = 59$\n-   Actual grade = 65\n-   Score: `dnorm(65, mean = 59, sd = 10)` ≈ 0.03\n\n. . .\n\nDo this for every student.\nMultiply.\nThat's the likelihood.\n\nDifferent parameters → different score.\n\n## Priors for regression\n\nSame logic as the coin — just different parameters.\n\n. . .\n\n-   Grades are 0–100. $\\beta_0$ can't be 500. → $\\beta_0 \\sim \\text{Normal}(50, 20)$\n\n. . .\n\n-   Watching lectures shouldn't hurt. $\\beta_1$ probably isn't −20. → $\\beta_1 \\sim \\text{Normal}(0, 5)$\n\n. . .\n\n-   $\\sigma$ must be positive, probably not 1000. → $\\sigma \\sim \\text{Half-Cauchy}(0, 10)$\n\n. . .\n\nMLE ignores all of this.\nBayes encodes it.\n\n## Declaring Priors\n\nYou have to identify:\n\n-   Distribution of every statistic you want to estimate, including the dependent variable and each parameter of its distribution\n    -   (e.g., DV \\~ N( $\\mu$ , $\\sigma$))\n-   Expected values for the location and spread of the distributions\n\n## How to choose\n\n-   People argue about priors\n\n    -   Where do they come from?\n\n    -   Priors differ in how informative they are\n\n    -   Priors differ in how 'proper' they are\n\n-   Creates camps:\n\n    -   \"Subjective Bayesians\" vs. \"Objective Bayesians\" vs. \"Empirical Bayesians\" vs. \"Pragmatic Bayesians\"\n\n## Informativeness of priors\n\n-   Informative Priors (\"Subjective Bayesians\")\n\n    -   Prior distributions that are specific about the values of model parameters (e.g., true correlation ≈ N(μ = -0.5)\n\n-   Non-informative Priors (\"Objective Bayesians\")\n\n    -   Priors that let data speak for themselves; invariant to transformation\n\n-   Weakly-informative priors (\"WIP\"; Most Bayesians)\n\n    -   Specifying the distribution (e.g., Normal), with starting values known to bias estimates the least\n\n## Informativeness of priors\n\n-   People vary in how strongly they state their prior beliefs\n\n-   If you state your belief strongly\n\n    -   E.g., the true correlation is \\~N(0.3, 0.06)\n        -   Pitfall: Your beliefs have greater influence over the shape of the posterior distribution\n\n-   If you state your belief weakly\n\n    -   E.g., true correlation is equally likely at any real value between -1 and 1\n        -   Pitfall: You run the risk of overestimating the relative densities of the posterior distribution to the prior distribution\n\n## Bayesian belief updating\n\n-   Prior odds\n\n    -   Compares the relative plausibility of two models before data collection\n\n$$\\frac{p(M1)}{p(M2)}$$\n\n![](images/step2.png){fig-align=\"center\"}\n\n## Bayesian belief updating\n\n-   Prior prediction distribution\n\n    -   Makes a prediction about plausibility of the data\n\n        -   What is the probability to observe 0, 1, 2, … dog people in a random sample of 5 people given our model?\n\n![](images/prior_predictive.png){fig-align=\"center\"}\n\n## Bayesian belief updating\n\n![](images/bayes_data.png){fig-align=\"center\"}\n\n## Bayesian belief updating\n\n-   Marginal Likelihood\n\n    -   How plausible are the observed data under the model?\n\n        -   Evaluation of the prior predictive distribution at the observed data\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](images/marg_like.png){fig-align='center' width=2085}\n:::\n:::\n\n\n## Bayesian belief updating\n\n![](images/marginallike.png){fig-align=\"center\" width=\"1001\"}\n\n## Bayes factors\n\n::::: columns\n::: {.column width=\"50%\"}\n-   Frequentists have *p* values\n\n-   Bayesians have Bayes factors (BF)\n\n    -   Tells you how much more likely the observed data are under one model than under another model\n\n    -   Can be interpreted as degree of relative evidence for a model\n\n        $$\\text{Bayes factor} (BF) = \\frac{P(\\mathcal{D}|M_1)}{P(\\mathcal{D}|M_2)}$$\n:::\n\n::: {.column width=\"50%\"}\n![](images/bayes-bf2.png){fig-align=\"center\"}\n\n-   $BF_{12}$ \\> 1: More evidence for M1\n\n-   $BF_{12}$ \\< 1: More evidence for M2\n:::\n:::::\n\n## Bayesian belief updating\n\n![](images/bayes-BF.png){fig-align=\"center\"}\n\n## Bayes factors\n\n-   How convincing is the evidence that M1 is better than M2?\n\n    -   Moderate to strong evidence (BF \\> 3) to publish in psych\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](images/bf.png){fig-align='center' width=459}\n:::\n:::\n\n\n## Bayesian belief updating\n\n-   A posterior distribution is a conditional probability distribution that represents belief about a parameter, taking the evidence into account\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](images/step6.png){fig-align='center' width=2005}\n:::\n:::\n\n\n## Bayesian belief updating\n\n![](images/priorpost.jpg){fig-align=\"center\"}\n\n## Bayesian belief updating\n\n-   Posterior\n\n    -   Credible intervals (Highest Density Intervals)\n\n        -   Give us a way to express the uncertainty in estimating parameter values\n\n        -   Provide a range within which we believe the true value of a parameter lies, with a certain probability\n\n            -   With a probability of x%, the parameter lies within this interval\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](images/step7.png){fig-align='center' width=70%}\n:::\n:::\n\n\n## Bayesian belief updating\n\n![](images/post_odds.png){fig-align=\"center\"}\n\n# Note: Two uses of \"Bayesian\" in psychology\n\n::::: columns\n::: {.column width=\"50%\"}\n**Bayesian data analysis**\n\n(what we're doing)\n\nA tool for **analyzing data**.\n\nBayes' rule used estimate parameters from your experiment.\n\nThe model describes your **data**.\n:::\n\n::: {.column width=\"50%\"}\n**Bayesian models of cognition**\n\n(Griffiths, Tenenbaum, etc.)\n\nA theory of **how people think**.\n\nThe claim: human minds use something like Bayes' rule to learn and make decisions.\n\nThe model describes cognition.\n:::\n:::::\n\nYou can use Bayesian data analysis without committing to the Bayesian Brian hypothesis!\n\n## Bayesian models as psychological theory\n\nThe claim: people behave **as if** they do Bayesian inference.\n\n. . .\n\n-   **Language:** Children infer word meanings from few examples (Xu & Tenenbaum, 2007)\n\n. . .\n\n-   **Perception:** The brain combines noisy sensory input with prior expectations (Knill & Pouget, 2004)\n\n. . .\n\n-   **Causal reasoning:** People learn causal structure from sparse evidence (Griffiths & Tenenbaum, 2005)\n\n. . .\n\n-   **Motor control:** You catch a ball by combining visual uncertainty with learned priors (Körding & Wolpert, 2004)\n\n# Implementation in R {.center}\n\n## Bayesian regression example\n\n-   Does synchronous attendance and average viewing matter in hybrid courses?\n\n    -   33 students in Fall 2020 statistics course\n\n        -   Looked at:\n\n            -   Grade `Final course grade`: Min: 30 Max: 97\n\n            -   sync `Mode of attendance`: (0=asynchronous; 1=synchronous)\n\n            -   avgView `Average standardized viewing time for recorded lectures`: in minutes\n\n## Data\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#data<-read.csv(\"https://osf.io/sxk2a/download\")\ndata<-read.csv(\"statGrades.csv\")\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(brms) # run bayes lm\n\nlibrary(marginaleffects) # get posteriors\n\nlibrary(ggeffects) # graph\n\nlibrary(easystats) # easystats packages # bayesttestR\n\nlibrary(bayesplot) # graph trace plots\n\nlibrary(ggdist) # graph distributions and geoms\n```\n:::\n\n\n## `avgView` plot\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](Bayes_Intro_2026_Lecture_files/figure-revealjs/unnamed-chunk-14-1.png){width=70%}\n:::\n:::\n\n\n## `sync` plot\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](Bayes_Intro_2026_Lecture_files/figure-revealjs/unnamed-chunk-15-1.png){fig-align='center' width=70%}\n:::\n:::\n\n\n## Simple regression\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlm_class <- lm(grade~avgView+sync_cont, data=data)\n\nmodel_parameters(lm_class) %>%\n\n  print_md()\n```\n\n::: {.cell-output-display}\n\n\n|Parameter   | Coefficient |   SE |          95% CI | t(30) |      p |\n|:-----------|:-----------:|:----:|:---------------:|:-----:|:------:|\n|(Intercept) |       55.68 | 9.23 |  (36.83, 74.53) |  6.03 | < .001 |\n|avgView     |        0.46 | 0.15 |    (0.15, 0.77) |  3.02 | 0.005  |\n|sync cont   |        0.30 | 7.92 | (-15.88, 16.47) |  0.04 | 0.970  |\n\n\n:::\n:::\n\n\n## `brms`\n\n-   Bayesian regression models in Stan (`brms`)\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#| results: hide\n\n#|\n\nbrm_class1 <- brm(grade~avgView+sync_cont, data=data,\n\nfamily= gaussian(),#distribution\n\nprior=NULL,\n\nchains=4, # how many chains are run\n\ncore=4, #computer cores to use\n\nwarmup = 2000, # warm-up for MCMC\n\niter = 5000) # number of MCMC samples\n```\n:::\n\n\n## Computing the posterior\n\n-   Markov chain Monte Carlo (MCMC) sampler!\n\n-   Given possible priors and your data, a computer uses a Monte Carlo sampling technique to build stochastic Markov Chains, a process referred to as MCMC\n\n-   We run multiple chains (e.g., 4 chains in `brms`) with equal numbers of iterations (e.g., 5000 iterations) in each chain to estimate convergence/stability\n\n-   MCMC chains contain samples from the posterior distribution of the theory given the data\n\n## Markov Chain (MC)\n\n::::: columns\n::: {.column width=\"50%\"}\n![](images/MC.png){fig-align=\"center\" width=\"212\"}\n\n![](images/mc.GIF)\n:::\n\n::: {.column width=\"50%\"}\n-   Chain of discrete events, moving forward in time\n\n    -   Probability of each event is a conditional probability, given the last event\n\n-   Memoryless\n\n    -   Future events can be predicted by knowing only the current event\n\n-   Issue: they can stay the same/loop\n:::\n:::::\n\n## Monte Carlo (MC)\n\n-   Monte Carlo simulations involve simulating a random process and then directly averaging the values of interest\n\n```{webr-r}\n\n# Define the number of simulations\n\nn_simulations <- 100\n\n# Define the sample size for each simulation\n\nsample_size <- 100\n\n# Define the mean and standard deviation for the normal distribution\n\nmean <- 0\n\nsd <- 1\n\n# Initialize a vector to store the mean of each simulation\n\nsimulation_means <- numeric(n_simulations)\n\n# Perform the simulations\n\nfor(i in 1:n_simulations) {\n\n  sample_data <- rnorm(n = sample_size, mean = mean, sd = sd)\n\n  simulation_means[i] <- mean(sample_data)\n\n}\n\n# Print the results\n\nprint(simulation_means)\n\n```\n\n# MCMC in action\n\n-   https://chi-feng.github.io/mcmc-demo/app.html\n\n## MCMC diagnostics\n\n-   Trace plots\n\n    -   Look for the fuzzy ***caterpillars***\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nbayesplot::color_scheme_set(\"mix-blue-red\")\n\nbayesplot::mcmc_trace(brm_class1, pars = c(\"b_avgView\"),\n\n           facet_args = list(ncol = 1, strip.position = \"left\"))\n```\n\n::: {.cell-output-display}\n![](Bayes_Intro_2026_Lecture_files/figure-revealjs/unnamed-chunk-18-1.png){fig-align='center' width=40%}\n:::\n:::\n\n\n## MCMC Diagnostics\n\n-   Bad plots\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](images/bad.jpeg){width=316}\n:::\n:::\n\n\n## MCMC Diagnostics\n\n-   Can use numeric methods\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkable(diagnostic_posterior(brm_class1), digits=3)\n```\n\n::: {.cell-output-display}\n\n\n|Parameter   | Rhat|      ESS|  MCSE|\n|:-----------|----:|--------:|-----:|\n|b_avgView   |    1| 8696.058| 0.002|\n|b_Intercept |    1| 8452.392| 0.105|\n|b_sync_cont |    1| 8396.609| 0.090|\n\n\n:::\n:::\n\n\n-   $\\hat{R}$\n\n    -   Measure of consistency of Markov chains\n\n        -   Should be close to 1 (not larger than 1.01)\n\n    -   Ratio of variance (like *F* test)\n\n## MCMC Diagnostics\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkable(diagnostic_posterior(brm_class1), digits=3)\n```\n\n::: {.cell-output-display}\n\n\n|Parameter   | Rhat|      ESS|  MCSE|\n|:-----------|----:|--------:|-----:|\n|b_avgView   |    1| 8696.058| 0.002|\n|b_Intercept |    1| 8452.392| 0.105|\n|b_sync_cont |    1| 8396.609| 0.090|\n\n\n:::\n:::\n\n\n-   Effective sample size (ESS)\n\n    -   Number of independent pieces there is in autocorrelated chains (Krushke, 2015, p182-3)\n\n        -   MCMC chains are autocorrelated\n\n    -   ESS should be \\> 1000\n\n## Priors\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprior_summary(brm_class1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                  prior     class      coef group resp dpar nlpar lb ub tag\n                 (flat)         b                                          \n                 (flat)         b   avgView                                \n                 (flat)         b sync_cont                                \n student_t(3, 85, 11.9) Intercept                                          \n  student_t(3, 0, 11.9)     sigma                                  0       \n       source\n      default\n (vectorized)\n (vectorized)\n      default\n      default\n```\n\n\n:::\n:::\n\n\n::: callout-note\nNon-informative priors will give you essentially same results as a frequentist analysis\n:::\n\n## Weakly informative priors\n\n-   Normal(0, 10)\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#| echo: false\n\n#|\n\nx=distribution_normal(100, 0, 10)\n\nplot(density(x))\n```\n\n::: {.cell-output-display}\n![](Bayes_Intro_2026_Lecture_files/figure-revealjs/unnamed-chunk-23-1.png){width=1152}\n:::\n:::\n\n\n## Weakly informative priors\n\n-   Cauchy(mean=0, width=.707)\n\n    -   50% of probability lies between .707 and -.707\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#| echo: false\n\n#|\n\nx=distribution_cauchy(100, 0, 10)\n\nplot(density(x))\n```\n\n::: {.cell-output-display}\n![](Bayes_Intro_2026_Lecture_files/figure-revealjs/unnamed-chunk-24-1.png){width=1152}\n:::\n:::\n\n\n## Visualize prior predictive distribution\n\n-   Make sure prior distribution makes sensible predictions (if using informative priors)\n\n::::: columns\n::: {.column width=\"50%\"}\n\n::: {.cell}\n\n```{.r .cell-code}\n# set prior using prior function\n\n# these priors are not good and only for demo\n\nprior1 <- prior(cauchy(0, .707), class=b)\n\nprior2 <- prior(normal(0, 10), class = b)\n\nprior3 <- prior(normal(0, .51), class = b)\n\n#include prior\n\n# only sample from prior so we can plot it and look\n\nbrm_class_prior <- brm(grade~avgView, data=data,\n\nsample_prior=\"only\", #use this to check prior pulls\n\nprior=prior2, # add in prior information\n\nfamily= gaussian(),\n\nwarmup = 2000,\n\niter = 5000)\n\n# check prior\n```\n:::\n\n:::\n\n::: {.column width=\"50%\"}\n\n::: {.cell}\n\n```{.r .cell-code}\n#| eval: false\n\npp_check(brm_class_prior)\n```\n\n::: {.cell-output-display}\n![](Bayes_Intro_2026_Lecture_files/figure-revealjs/unnamed-chunk-26-1.png){width=1152}\n:::\n:::\n\n:::\n:::::\n\n## Describing the posterior\n\n-   A point-estimate which is a one-value summary (similar to the $\\beta$ in frequentist regressions)\n\n    -   Mean/median\n\n-   A credible interval representing the associated uncertainty\n\n-   Some indices of significance, giving information about the relative importance of this effect (e.g., Bayes Factors)\n\n## Posterior distribution plot\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n#| eval: false\n\npp_check(brm_class1, type=\"stat_grouped\", group=\"sync_cont\")\n```\n\n::: {.cell-output-display}\n![](Bayes_Intro_2026_Lecture_files/figure-revealjs/unnamed-chunk-27-1.png){fig-align='center' width=60%}\n:::\n:::\n\n\n## Posterior distribution plot\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#| eval: false\n\npp_check(brm_class1,group=\"avgView\")\n```\n\n::: {.cell-output-display}\n![](Bayes_Intro_2026_Lecture_files/figure-revealjs/unnamed-chunk-28-1.png){width=1152}\n:::\n:::\n\n\n## Point-estimate\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel_parameters(brm_class1) %>%\n\n  kable()\n```\n\n::: {.cell-output-display}\n\n\n|Parameter   |Component   |     Median|   CI|      CI_low|    CI_high|        pd|      Rhat|      ESS|\n|:-----------|:-----------|----------:|----:|-----------:|----------:|---------:|---------:|--------:|\n|b_Intercept |conditional | 56.0728895| 0.95|  37.2608598| 74.9142813| 1.0000000| 1.0000658| 8452.392|\n|b_avgView   |conditional |  0.4608603| 0.95|   0.1530982|  0.7712898| 0.9983333| 1.0000523| 8696.058|\n|b_sync_cont |conditional |  0.3346671| 0.95| -16.0394485| 16.4672209| 0.5175833| 1.0000143| 8396.609|\n|sigma       |sigma       | 15.1942040| 0.95|  11.9320925| 19.8876910| 1.0000000| 0.9999993| 9373.130|\n\n\n:::\n:::\n\n\n## Uncertainty: Credible intervals\n\n-   Credible intervals (high density intervals)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nposteriors <- get_parameters(brm_class1)\n\nresuls=hdi(posteriors$b_avgView, ci=0.95)\n```\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](hdi_avg.jpg){fig-align='center' width=100%}\n:::\n:::\n\n\n## Uncertainty: Credible intervals\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(see)\n\nposteriors <- get_parameters(brm_class1)\n\nresults=hdi(posteriors$b_sync_cont, ci=0.95)\n```\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](hdi_sync.jpg){fig-align='center' width=100%}\n:::\n:::\n\n\n## Visualizing uncertainty: `avgView`\n\n::::: columns\n::: {.column width=\"50%\"}\n\n::: {.cell}\n\n```{.r .cell-code}\n#get predictions from margainaleffects\n\npred <- predictions(brm_class1,\n\n                    newdata = datagrid(\n\n        avgView = seq(6, 75, by = 5))) %>%\n\n        posterior_draws()\n\npred_fig <- ggplot(pred, aes(x = avgView, y = draw)) +\n\n    stat_lineribbon() +\n\n    scale_fill_brewer(palette = \"Reds\") +\n\n    labs(x = \"Average Watch Time (min)\",\n\n         y = \"Grades (predicted)\",\n\n         fill = \"\")\n```\n:::\n\n:::\n\n::: {.column width=\"50%\"}\n\n::: {.cell}\n\n```{.r .cell-code}\n#| echo: false\n\n#|\n\npred_fig\n```\n\n::: {.cell-output-display}\n![](Bayes_Intro_2026_Lecture_files/figure-revealjs/unnamed-chunk-35-1.png){width=1152}\n:::\n:::\n\n:::\n:::::\n\n## Visualizing uncertainty: `sync`\n\n::::: columns\n::: {.column width=\"50%\"}\n\n::: {.cell}\n\n```{.r .cell-code}\n#| eval: false\n\n#|\n\npred <- avg_predictions(brm_class1, variables = \"sync_cont\") %>%  posterior_draws()\n\npred$sync_cont<-as.factor(pred$sync_cont)\n\nggplot(pred, aes(x = draw, y = sync_cont, fill = sync_cont)) +\n\n  stat_halfeye(.width=c(.8, .95))  +\n\n  scale_fill_viridis_d(option = \"plasma\", end = 0.8) +\n\n  guides(fill = \"none\") +\n\n  labs(x =\"Class\", y = \"Grades\",\n\n       caption = \"80% and 95% credible intervals shown in black\") +\n\n  theme_lucid(base_size=25)\n```\n\n::: {.cell-output-display}\n![](Bayes_Intro_2026_Lecture_files/figure-revealjs/unnamed-chunk-36-1.png){width=1152}\n:::\n:::\n\n:::\n\n::: {.column width=\"50%\"}\n\n::: {.cell}\n\n```{.r .cell-code}\n#| echo: false\n\npred <- avg_predictions(brm_class1, variables = \"sync_cont\") %>%  posterior_draws()\n\npred$sync_cont<-as.factor(pred$sync_cont)\n\nggplot(pred, aes(x = draw, y = sync_cont, fill = sync_cont)) +\n\n  stat_halfeye()  +\n\n  scale_fill_viridis_d(option = \"plasma\", end = 0.8) +\n\n  guides(fill = \"none\") +\n\n  labs(x =\"Class\", y = \"Grades\",\n\n       caption = \"80% and 95% credible intervals shown in black\") +\n\n  theme_lucid(base_size=25)\n```\n\n::: {.cell-output-display}\n![](Bayes_Intro_2026_Lecture_files/figure-revealjs/unnamed-chunk-37-1.png){width=1152}\n:::\n:::\n\n:::\n:::::\n\n## Descriptives\n\n-   `bayestestR` from `easystats`\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndescribe_posterior(\n\n  brm_class1,\n\n  effects = \"fixed\",\n\n  component = \"all\",\n\n  test=c(\"p_direction\"),\n\n  centrality = \"all\"\n\n) %>%\n\n  kable()\n```\n\n::: {.cell-output-display}\n\n\n|   |Parameter   |Component   |     Median|       Mean|        MAP|   CI|      CI_low|    CI_high|        pd|      Rhat|      ESS|\n|:--|:-----------|:-----------|----------:|----------:|----------:|----:|-----------:|----------:|---------:|---------:|--------:|\n|2  |b_Intercept |conditional | 56.0728895| 56.1106414| 54.9691150| 0.95|  37.2608598| 74.9142813| 1.0000000| 1.0000658| 8452.392|\n|1  |b_avgView   |conditional |  0.4608603|  0.4607349|  0.4678039| 0.95|   0.1530982|  0.7712898| 0.9983333| 1.0000523| 8696.058|\n|3  |b_sync_cont |conditional |  0.3346671|  0.3192760|  0.3033202| 0.95| -16.0394485| 16.4672209| 0.5175833| 1.0000143| 8396.609|\n|4  |sigma       |sigma       | 15.1942040| 15.3828541| 14.8382196| 0.95|  11.9320925| 19.8876910| 1.0000000| 0.9999993| 9373.130|\n\n\n:::\n:::\n\n\n::: callout-note\nprobability of direction (pd) is pretty cool!\n\nIt tells us how much of the distribution is completely positive or negative.\n\nIt is correlated with p values!\n:::\n\n## Significance\n\n-   Does the credible interval for `avgView` contain 0?\n\n    -   If yes, \"not significant\"\n\n    -   If no, \"significant\"\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhdi(posteriors$b_avgView, ci=0.95)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          [,1]      [,2]\n[1,] 0.1479602 0.7637246\n```\n\n\n:::\n:::\n\n\n. . .\n\n-   It does not in our case so significant!\n\n## Significance\n\n-   Does the credible interval for `sync_cont` contain 0?\n\n    -   If yes, \"not significant\"\n\n    -   If no, \"significant\"\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhdi(posteriors$b_sync_cont, ci=0.95)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          [,1]     [,2]\n[1,] -16.19875 16.22421\n```\n\n\n:::\n:::\n\n\n. . .\n\n-   It does not in our case - not significant!\n\n## Significant differences\n\n-   Use `marginaleffects` or emmeans to get mean differences between variables\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmarginaleffects::avg_comparisons(brm_class1, variables=\"sync_cont\")  %>%\n\n  kable()\n```\n\n::: {.cell-output-display}\n\n\n|term      |contrast |  estimate|  conf.low| conf.high| predicted_lo| predicted_hi| predicted| tmp_idx|\n|:---------|:--------|---------:|---------:|---------:|------------:|------------:|---------:|-------:|\n|sync_cont |+1       | 0.3346671| -16.03945|  16.46722|     79.85804|     80.20687|  79.85804|       1|\n\n\n:::\n:::\n\n\n## Significant differences: BFs\n\n-   Adding prior to our model\n\n    -   Cannot compute BFs without specifying a weak or informative prior!\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbrm_class_cat <- brm(grade~avgView + sync_cont, prior=prior2,\n\ndata=data,\n\nfamily=gaussian(),\n\nsample_prior=\"yes\") # make sure to sample prior\n```\n:::\n\n\n## Significant differences: BFs\n\n-   Can compare model parameters to determine if effect is 0 (or some other value)\n\n-   Use `bayesfactor_parameter` function to test a model with the observed effect to a model with the effect at 0\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(bayestestR) # bayes functions easystats\n\n# contrast\n\n#BF only if you use weakly-strong priors\n\nBF <- bayestestR::bayesfactor_parameters(brm_class_cat, null = 0)\n\nBF\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nBayes Factor (Savage-Dickey density ratio)\n\nParameter   |       BF\n----------------------\n(Intercept) | 6.43e+04\navgView     |     1.29\nsync_cont   |    0.628\n\n* Evidence Against The Null: 0\n```\n\n\n:::\n:::\n\n\n## Model comparisons: BF\n\n-   Use `bayestestR::bayesfactor_models` to get a BF for full models selection\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Model 1: grade ~ sync + avgView\n\n#save_pars for bayes factors\n\nbrm_class1 <- brm(grade~avgView + sync, data=data , family = gaussian(), prior=prior2, sample_prior=\"yes\", save_pars = save_pars(all=TRUE), warmup = 2000, iter = 5000)\n\n#grade ~ avgView\n\nbrm_class2 <- brm(grade~avgView, data=data, prior=prior2, family = gaussian(), sample_prior=\"yes\", save_pars = save_pars(all=TRUE),\n\n    warmup = 2000, iter = 5000)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#| eval: false\n\n#|\n\n# testing models\n\n# compared to intercept-only or null model\n\nbayesfactor_models(brm_class1, brm_class2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nBayes Factors for Model Comparison\n\n    Model     BF\n[2] avgView 1.63\n\n* Against Denominator: [1] avgView + sync\n*   Bayes Factor Type: marginal likelihoods (bridgesampling)\n```\n\n\n:::\n:::\n\n\n-   `avgview` only model is 15 times more likely than a model with\n\n## Significant differences: BFs\n\n-   Is the effect 0?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nBF <- bayestestR::bayesfactor_parameters(brm_class2, null = 0)\n\nBF\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nBayes Factor (Savage-Dickey density ratio)\n\nParameter   |       BF\n----------------------\n(Intercept) | 8.72e+05\navgView     |     7.09\n\n* Evidence Against The Null: 0\n```\n\n\n:::\n:::\n\n\n. . .\n\n-   Not 0!\n\n## Original question\n\n-   Do my students' course grades depend on mode of attendance and average viewing time?\n\n-   Only `avgView`\n\n    -   BF favored a model with only `avgView`\n\n        -   Strong evidence that effect not zero (BF = 15)\n\n    -   Weak evidence for an effect of mode of attendance\n\n. . .\n\n-   What do we get from Bayesian analysis that we don't get from regular linear regression?\n\n## Reporting Bayesian analysis\n\n\n::: {.cell}\n\n```{.r .cell-code}\nreport_bayes=report::report(brm_class1)\n```\n:::\n\n\n1.  Include which prior settings were used\n\n2.  Justify the prior settings (particularly for informed priors in a testing scenario)\n\n3.  Include a plot of the prior and posterior distribution\n\n4.  Report the posterior mean/median and x% credible intervals\n\n5.  If relevant, report the results from both estimation and hypothesis testing\n\n6.  Include BFs for model comparisons or parameters (sensitivity analysis)\n\n7.  Include model convergence diagnostics (trace plot, $\\hat R$, ESS)\n\n#\\~\\~\n\n## Bayesian pros\n\n-   Bayesian inference allows you to make direct probability statements for things that you are interested in\n\n-   Quantify the amount of support for one hypothesis relative to another\n\n-   It allows you to incorporate prior information you have in a formal way (via the prior distribution)\n\n-   Sample size does not affect estimates as much as it does the likelihood\n\n## Bayesian cons:\n\n-   Priors (can be good and bad)\n\n-   Computationally intensive\n\n## Caveat: What can Bayes not do?\n\n-   Ban questionable research practices (e.g., HARKing)\n\n-   Provide a remedy for:\n\n    -   Small sample sizes\n\n    -   Unrepresentative samples\n\n    -   Poor experimental design\n\n## Resources\n\n![](images/book1.png){fig-align=\"center\"}\n\n## Resources\n\n![](images/book2.png){fig-align=\"center\"}\n\n-   Check out the awesome YouTube videos that go through each chapter.\n\n## Resources\n\n![](images/clipboard-1935275650.png){fig-align=\"center\"}\n\nFree online textbook\n\n# Tomorrow\n\n![](images/clipboard-292211255.png)\n\n. . .\n\n<https://betanalpha.github.io/assets/chapters_html/reading_times.html>\n",
    "supporting": [
      "Bayes_Intro_2026_Lecture_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}