{
  "hash": "b83b85cee72a481a309ee8f246841ac9",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Ordinal Regression\"\nsubtitle: \"Princeton University\"\nauthor: \"Suyog Chandramouli\"\ndate: '2026-02-21'\ncategories: [GLM]\nfooter: \"PSY 504: Advanced Statistics\"\nformat: \n  revealjs:\n    theme: solarized\n    css: slide-style.css \n    transition: fade\n    slide-number: true\n    incremental: false \n    chalkboard: true\n    fontsize: \"25pt\"\nwebr:\n  packages: [\"tidyverse\", \"easystats\", \"broom\", \"knitr\", \"emmeans\", \"ordinal\", \"ggeffects\", \"marginaleffects\"]\nfilters:\n  - webr\nexecute:\n  freeze: auto\n  echo: true\n  message: false\n  warning: false \n  fig-align: center\n  fig-width: 12\n  fig-height: 8\n  editor_options: \n  chunk_output_type: inline\n  code-overflow: wrap\n  html:\n    code-fold: true\n    code-tools: true\n---\n\n## Packages\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(easystats)\nlibrary(marginaleffects)\nlibrary(effects)\nlibrary(ordinal)\nlibrary(ggeffects)\nlibrary(emmeans)\nlibrary(car)\nlibrary(knitr)\nlibrary(patchwork)\nlibrary(MASS)\nlibrary(broom)\nlibrary(modelsummary)\n\noptions(scipen = 999)\n```\n:::\n\n\n-   Access the .qmd document here: <https://github.com/suyoghc/PSY504_Spring_2026/tree/main/posts>\n\n::: notes\nJust the setup slide — let these load while people settle in. Mention they can follow along with the .qmd file on GitHub.\n:::\n\n## Announcements\n\n## Today\n\n::::: columns\n::: {.column width=\"50%\"}\n-   From logistic to ordinal\n\n-   Motivating simulation: Loaded dice\n\n    -   Why not just use OLS?\n    -   The latent variable idea\n    -   Cumulative logit link\n    -   Thresholds and slopes\n:::\n\n::: {.column width=\"50%\"}\n-   Application: Graduate school\n\n    -   Model fitting\n    -   Parameter interpretation\n    -   Proportional odds assumption\n    -   Model comparisons\n    -   Visualizing\n    -   Reporting\n:::\n:::::\n\n::: notes\nHere's the roadmap. **The first half is a simulation** — just like the weighted coins we used for logistic regression, we're going to build an ordinal outcome from scratch so you can see every piece of the model before we ever write a formula. **The second half is a real dataset** — graduate school applications — where we'll fit actual models, compare them, and practice reporting.\n\n***Let's start by connecting to what you already know.***\n:::\n\n## Last time: Logistic regression\n\n-   Binary outcomes: 0 or 1\n\n. . .\n\n-   We modeled P(Y = 1) using the logit link\n\n$$\\text{logit}(p) = \\log\\frac{p}{1-p} = \\beta_0 + \\beta_1 X$$\n\n. . .\n\n-   The logit mapped probabilities $(0, 1)$ → log-odds $(-\\infty, +\\infty)$, allowing a linear model\n\n. . .\n\n::: callout-note\nToday we extend this idea. What happens when your outcome has **more than two** ordered categories?\n:::\n\n::: notes\nQuick recap.\\\n\\\n1) Last time we had binary outcomes — heads or tails, pass or fail, yes or no.\\\n\\\n2) We used the **logit link** to map probabilities, which live between 0 and 1, onto the full real line so that a linear model could work. **THIS trick that made binary outcomes compatible with linear regression.**\n\n*But what if your outcome isn't just two categories?\\\nWhat if it's ordered — like Strongly Disagree through Strongly Agree?\\\nThat's what we'll be covering today.\\\n\\\nINTERACT: HAVE YOU USED ORDINAL DATA? DID YOU DO STATS WITH IT? ORDINAL OR VANILLA?*\n:::\n\n## Ordinal Response Variables\n\n-   In psychology many variables have a natural ordering\n\n    -   Grades (e.g., A, B, C)\n    -   Education level (e.g., BA, MS, PhD)\n    -   Competitions (e.g., 1st, 2nd, 3rd)\n    -   Economic status (e.g., wealthy, middle class, poor)\n\n-   Most common are Likert scale (\"Lick-ert\") items\n\n::: notes\nOrdinal data is everywhere in psychology. These are variables where **the categories have a meaningful order, but the distances between them are unknown**. Is the gap between an A and a B the same as between a B and a C? We don't know — and that's the whole problem.\n\nThe single most common source of ordinal data in psychology is the Likert scale — and yes, it's pronounced \"Lick-ert,\" not \"Lie-kert.\"\n\n*Let me show you a fun example of how ordinal responses arise naturally.*\n:::\n\n## This is a cat, not a dog?\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](images/Idli.JPG){fig-align='center' width=50%}\n:::\n:::\n\n\n1.  Very likely to be a cat\n2.  Somewhat likely to be a cat\n3.  As likely to be cat or dog\n4.  Somewhat likely to be a dog\n5.  Very likely to be a dog\n\n::: notes\nThis is Button Idli. If I asked you to rate how likely this is to be a cat, you'd pick one of these five options. **Notice that the responses have a clear order — 1 is \"definitely cat\" and 5 is \"definitely dog\" — but the spacing between them is subjective.** Is the psychological distance between \"very likely\" and \"somewhat likely\" the same as between \"somewhat likely\" and \"as likely\"? Probably not.\n\nJ: As you progress from one to two to three to four to five, there's an underlying latent variable — call it \"catness\" — that increases as you move up the scale. **That latent variable is the hidden continuous thing the model is going to try to recover.** Keep that idea in mind.\n\nThis is what makes ordinal data fundamentally different from continuous data, and **it's why we need a dedicated modeling approach.**\n\n*So what do people actually do with data like this? Let's look at the options.*\n:::\n\n## Methods for analysis\n\n-   **Metric models** (e.g., t-test, OLS)\n    -   Overestimate information in data; common & \"simple\"\n-   **Nonparametric** (e.g., signed ranks)\n    -   Underestimate information; don't scale well\n-   **Ordinal models** ← today\n    -   Treat outcomes appropriately as ordered categories\n\n::: notes\nThere are basically three camps.\n\n**First, metric models** — this is what almost everyone does. You treat your 1-through-5 scale as if it were a continuous number and run an ANOVA or a t-test. J: **Nobody wants to give up their t-tests, ANOVAs, and regular regressions.** There's been a longstanding argument that if you have more than four categories, the variable is \"close enough\" to continuous and you can run models as you normally would. It's common because it's easy, but it makes assumptions we know are wrong.\n\n**Second, nonparametric tests** — like the Wilcoxon — these make fewer assumptions, but they throw away information and don't scale to complex designs.\n\n**Third, ordinal models** — these are the Goldilocks option. They respect the ordering without pretending the distances are equal.\n\n*How bad can metric models really be? Let's look at what the literature says.*\n:::\n\n## \"What could possibly go wrong?\" {.smaller}\n\nLiddell and Kruschke (2018) surveyed 68 Psychology articles and found that **every** article used metric models on ordinal data.\n\n. . .\n\nThree main problems:\n\n-   Response categories may not be (psychologically) **equidistant**\n\n-   Responses can be **non-normally distributed**\n\n-   Differences in **variances** of the underlying variable are treated inappropriately\n\n. . .\n\n::: callout-warning\nUsing metric models on ordinal data can lead to false alarms, failures to detect true effects, distorted effect sizes, and even inversions of effects.\n:::\n\n::: notes\n-   This highlighted several issues which made the field start taking things more seriously\n\n    -   L&K surveyed 68 articles and **every single one** used metric models on ordinal outcomes. Every one!\n        -   hey searched for the word **\"Likert\"** across three top journals' 2016 volumes:\n            -   JEP, Psych Science, PJSP\n\n-   not used as often\n\n-   L&K showed more. Consequences aren't just theoretical.\n\n-   They showed three specific problems.\n\n    -   **First, the categories may not be equidistant**\n        -   the psychological gap between \"disagree\" and \"neutral\" might be much larger than between \"neutral\" and \"agree.\"\n    -   **Second, ordinal responses are often skewed**\n        -   a lot of people pick the extreme ends, which violates normality.\n    -   **Third, group differences in variance get confused with differences in means**, which can flip the direction of your effect entirely.\n\n*So let's actually see what happens when we use the wrong model. We're going to simulate some ordinal data from scratch.*\n:::\n\n# Under the Hood: The Loaded Dice\n\n::: notes\n*Just like we used weighted coins to understand logistic regression, we're going to use loaded dice to understand ordinal regression. Same philosophy — build it, see it, then model it.*\n:::\n\n## The Loaded Dice {.center}\n\nEasier to understand ordinal regression if we **simulate it from scratch** and watch the steps unfold.\n\nJust like our weighted coins helped us understand logistic regression.\n\n::: notes\nRemember the coin toss simulation?\n\n-   We had 8 coins, each with a different amount of lead, and more lead meant a higher probability of heads.\n\n-   **We're going to do the exact same thing, but now instead of two outcomes — heads or tails — we'll have three ordered categories: Low, Medium, and High.**\n\nThe big conceptual addition is the idea of **thresholds**\n\n-   — invisible boundaries that chop a continuous latent variable into ordered categories.\n\n-   That's the core insight of ordinal regression, and the simulation will make it concrete.\n\n*Here's the setup.*\n:::\n\n## Simulation with a Data Generating Process {.smaller}\n\n6 dice. 30 rolls each.\n\nEach die has a lead weight. More lead → the die tends to produce higher scores on a continuous latent \"quality\" scale.\n\nWe then **bin** these latent scores into three ordered categories: **Low**, **Medium**, **High**.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(504)\n\n# --- DATA GENERATING PROCESS ---\n# Lead weight determines each die's latent mean\ndice <- tibble(\n  die         = 1:6,\n  lead_weight = 1:6,\n  latent_mean = c(-1.5, -0.5, 0, 0.5, 1.0, 2.0)\n)\n\n# TRUE thresholds (students will try to recover these)\ntau1 <- -0.5   # boundary between Low and Medium\ntau2 <-  1.0   # boundary between Medium and High\n\n# Roll each die 30 times → continuous latent score → categorize\nrolls <- dice %>%\n  rowwise() %>%\n  mutate(latent = list(rnorm(30, mean = latent_mean, sd = 1))) %>%\n  unnest(latent) %>%\n  ungroup() %>%\n  group_by(die) %>%\n  mutate(roll = row_number()) %>%\n  ungroup() %>%\n  mutate(\n    category = case_when(\n      latent <= tau1 ~ \"Low\",\n      latent <= tau2 ~ \"Medium\",\n      TRUE           ~ \"High\"\n    ),\n    category = ordered(category, levels = c(\"Low\", \"Medium\", \"High\"))\n  )\n```\n:::\n\n\n::: notes\nLet me walk you through this.\n\nWe have **6 dice, each rolled 30 times**.\n\n-   Each die has a different amount of lead, from 1 gram to 6 grams.\n\n-   More lead means the die's latent \"quality\" score tends to be higher — just like more lead on the coin meant a higher probability of heads.\n\nBut here's the key difference.\n\n-   **Each roll produces a continuous latent score** \\[nobody sees\\]\n\n    -   — drawn from a normal distribution centered on that die's latent mean.\n\n    -   Then we chop that continuous score into categories using two thresholds. **If the latent score is below −0.5, we call it \"Low.\" Between −0.5 and 1.0, it's \"Medium.\" Above 1.0, it's \"High.\"**\n\nThis is the data-generating process that ordinal regression assumes is happening in the real world. There's **a hidden continuous variable**, and our **categories are just a coarse binning of it.**\n\nJ: This assumption — that we can map observed responses onto a continuous latent variable and divide it into bins using thresholds — is what's called the **latent variable interpretation** of the model. I think it's a very reasonable assumption for the kinds of variables we work with in psychology.\n\n**Write these numbers down!**\n\n-   **tau 1 equals negative 0.5,**\n\n-   **tau 2 equals 1.0.** We're going to see if our model can recover them.\n\n*Let me show you what this looks like.*\n:::\n\n## The truth you normally never see {.smaller}\n\nEach point is a roll. The **dashed lines** are the true thresholds. Color = the category it falls into.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](05-ordinal-regression-narrated-J_files/figure-revealjs/unnamed-chunk-4-1.png){width=1056}\n:::\n:::\n\n\n. . .\n\n::: callout-important\nIn real life, you **never see this plot**. You only see the colors — the categories. The y-axis is hidden from you. Ordinal regression's job is to recover the thresholds and the effect of lead weight **using only the categories**.\n:::\n\n::: notes\nThis is the God's-eye view —\n\n-   the plot you'd never see in practice.\n\n-   The y-axis is the **latent continuous variable**, the hidden quality score. Each dot is a single roll.\n\n-   The two dashed horizontal lines are the true thresholds: tau 1 at −0.5 and tau 2 at 1.0.\n\n\\[TODO: something about thresholds being new parameters or a new source of complexity?\\]\n\nLook at the colors.\n\n-   **Below the first dashed line, everything is red — Low.**\n\n-   **Between the two lines, yellow — Medium.**\n\n-   **Above the top line, green — High.** The thresholds are doing the slicing.\n\n\\[\\[INTERACT\\]\\]\n\n\\- **as lead weight increases from left to right,**\n\n-   the cloud of points shifts upward.\n\n-   More weight, higher latent scores, more green dots.\n\n-   **That upward shift is the \"effect\" of lead weight — and it's what the slope in our model will capture.**\n\n**But here's the crucial point** — read the callout.\n\nIn real life, you never see the y-axis. You only see the colors. A survey participant picks \"Agree\" or \"Strongly Agree\" — you don't see their underlying feeling on a continuous scale. **Ordinal regression's entire job is to recover this hidden structure from just the category labels.**\n\n*So what does the data actually look like to us, the researchers?*\n:::\n\n## What you actually observe\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](05-ordinal-regression-narrated-J_files/figure-revealjs/unnamed-chunk-5-1.png){width=1056}\n:::\n:::\n\n\n. . .\n\nMore weight → more \"High\" and fewer \"Low.\" The pattern is clear. How do we model it?\n\n::: notes\nThis is what your data actually looks like. No latent variable, no thresholds — **just how many rolls fell into each category for each die.** It's a stacked bar chart.\n\nThe pattern is clear even here.\n\n-   The 1-gram die is mostly red — Low.\n\n-   The 6-gram die is mostly green — High.\n\n-   **As lead weight increases, the distribution shifts from Low to High.** That's the signal we want to capture.\n\nThis is exactly what a Likert-scale dataset looks like.\n\nYou have groups, you have ordered categories, and you can see proportions shifting. The question is: what's the best way to model this?\n\n***The tempting answer is: just code the categories as numbers and run OLS. But before we do that — let's compute the cumulative log-odds by hand so you know what the model is actually estimating.***\n:::\n\n## From counts to cumulative log-odds {.smaller}\n\nBefore we model anything, let's do the arithmetic ourselves. Pick the **3-gram die** (30 rolls):\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndie3 <- rolls %>% filter(lead_weight == 3)\n\n# Step 1: Category counts and proportions\ndie3_counts <- die3 %>%\n  count(category) %>%\n  mutate(\n    prop         = n / sum(n),\n    cum_prop     = cumsum(prop),\n    cum_odds     = cum_prop / (1 - cum_prop),\n    log_cum_odds = log(cum_odds)\n  )\n\nkable(die3_counts, digits = 3)\n```\n\n::: {.cell-output-display}\n\n\n|category |  n| prop| cum_prop| cum_odds| log_cum_odds|\n|:--------|--:|----:|--------:|--------:|------------:|\n|Low      | 12|  0.4|      0.4|    0.667|       -0.405|\n|Medium   | 15|  0.5|      0.9|    9.000|        2.197|\n|High     |  3|  0.1|      1.0|      Inf|          Inf|\n\n\n:::\n:::\n\n\n. . .\n\n::: callout-tip\n## 🔗 Connection to the model\n\nThose log-cumulative-odds you just computed? **They're exactly what the model's thresholds estimate** when there's no predictor.\n:::\n\n```{webr-r}\n# Try it yourself: pick a different die (change the number) and repeat\nmy_die <- rolls %>% filter(lead_weight == 5)\n\nmy_die %>%\n  count(category) %>%\n  mutate(\n    prop = n / sum(n),\n    cum_prop = cumsum(prop),\n    cum_odds = cum_prop / (1 - cum_prop),\n    log_cum_odds = log(cum_odds)\n  )\n```\n\n::: notes\n**tau = 0** → `plogis(0)` = 0.50. Even odds. Half the distribution falls at or below this cut.\\\n**tau = 0.5** → `plogis(0.5)` ≈ 0.62. 62% at or below.\\\n**tau = 1** → `plogis(1)` ≈ 0.73. 73% at or below.\\\n**tau = 2** → `plogis(2)` ≈ 0.88. 88% at or below.\\\n**tau = −2** → `plogis(-2)` ≈ 0.12. Only 12% at or below.\n\nPattern: positive tau → most people fall at or below that cut. Negative tau → most people are above it.\n\nTau = 0 is the pivot point — 50/50 split.\\\n\\\nRM: This step comes from McElreath's approach — before fitting any model, **compute the cumulative probabilities, cumulative odds, and log-cumulative odds by hand.**\n\n-   You know odds — now we go cumulative.\n\n-   This way, when you see the model output later, the numbers will feel like something you calculated yourself rather than something the software produced.\n\n\\[TODO: better explanation of why cumulative\\]\n\nLet's walk through it for the 3-gram die.\n\n-   Count up the rolls: some number are Low, some Medium, some High.\n\n-   **Step 1: compute the proportion in each category.**\n\n-   Step 2: compute the cumulative proportion — the proportion at or below each category.\n\n-   At Low it's just the Low proportion; at Medium it's Low plus Medium; at High it's 1.0.\n\n-   **Step 3: compute the cumulative odds** — the cumulative proportion divided by one minus the cumulative proportion. **Step 4: take the log.** Those are your cumulative log-odds.\n\n**Now look at the callout box.** Those log-cumulative-odds are exactly the threshold parameters in an intercept-only ordinal regression model.\n\nYou just did ordinal regression by hand — no software needed. When we fit the model in a few slides, you'll recognize these numbers.\n\nTry it in the webr block — pick a different die and see how the log-cumulative-odds change. Heavier dice should have higher cumulative log-odds at each threshold, because more of their rolls land in higher categories.\n\n*But what if we take the naive approach and just treat these categories as numbers?*\n:::\n\n## What if we just use OLS? {.smaller}\n\nCode the categories as numbers (Low = 1, Medium = 2, High = 3) and fit a linear regression.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrolls_numeric <- rolls %>%\n  mutate(y_numeric = as.numeric(category))\n\nols_bad <- lm(y_numeric ~ lead_weight, data = rolls_numeric)\n\nggplot(rolls_numeric, aes(x = lead_weight, y = y_numeric)) +\n  geom_jitter(aes(color = category), width = 0.15, height = 0.1, alpha = 0.4, size = 2) +\n  geom_smooth(method = \"lm\", se = TRUE, color = \"red\", linewidth = 1.2, fullrange = TRUE) +\n  scale_color_manual(values = c(\"Low\" = color_low, \"Medium\" = color_med, \"High\" = color_high),\n                     guide = \"none\") +\n  scale_x_continuous(limits = c(-1, 9)) +\n  scale_y_continuous(breaks = 1:3, labels = c(\"Low\", \"Medium\", \"High\")) +\n  geom_hline(yintercept = c(0.5, 3.5), linetype = \"dashed\", color = \"grey50\") +\n  annotate(\"text\", x = 8, y = 3.4, label = \"Impossible!\", color = \"red\", size = 5) +\n  annotate(\"text\", x = -0.5, y = 0.6, label = \"Impossible!\", color = \"red\", size = 5) +\n  labs(x = \"Lead weight (grams)\", y = \"Response\",\n       title = \"OLS on ordinal data: looks fine, isn't\") +\n  theme_lucid(base_size = 16)\n```\n\n::: {.cell-output-display}\n![](05-ordinal-regression-narrated-J_files/figure-revealjs/unnamed-chunk-7-1.png){width=960}\n:::\n:::\n\n\n::: notes\n\\[\\[TODO\\]\\] \\~ Make interactive\n\n**1. The familiar problem — mostly same as last time.**\n\n-   Plot P(High) vs. lead weight.\n\n-   Fit OLS.\n\n-   Line escapes \\[0, 1\\]. \"We've seen this before.\"\n\n\\[\\[TODO\\]\\] \\~ Make interactive\n\n**2. Anything new? Which probability?**\n\n-   This is the thing binary data didn't have.\n\n    -   With coins, there was one probability to model — P(heads).\n\n    -   With three categories, you have choices.\n\n        -   P(High)?\n\n        -   P(Medium or High)? P(Low)?\n\n        -   Each gives a different line.\n\n        -   OLS can only handle one at a time — you're forced to collapse an ordered outcome into a single binary split. That's information loss. You had three categories and you threw two of them into a bucket. And you don't really get predictions that make sense — so people don't use it.\n\n**3. The \"just code it 1-2-3\" escape route makes things worse.**\n\n-   Students will think: \"OK, so don't model a probability — just predict the category number.\"\n\n-   That dodges the boundary issue but walks into a bigger one.\n\n-   Now you're assuming the gap between 1 and 2 equals the gap between 2 and 3. The numbers are labels you chose, not distances you measured.\n\n**Then the cumulative logit model is the answer to all three:**\n\n-   Logit link → probabilities stay in \\[0, 1\\] ✓\n-   Models all cumulative splits simultaneously → no information loss ✓\n-   Thresholds are estimated, not assumed equal → no equal-spacing assumption ✓\n\nThe punchline: Binary data had one problem with OLS. Ordinal data has three. The cumulative logit solves all of them.\n\n*Let me show you exactly why that matters — same data, different thresholds.*\n:::\n\n## Thresholds matter — OLS can't see them {.smaller}\n\nSame latent scores, **two different threshold placements**. OLS treats both identically.\n\n::: panel-tabset\n## Observed distributions\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](05-ordinal-regression-narrated-J_files/figure-revealjs/unnamed-chunk-8-1.png){width=1152}\n:::\n:::\n\n\n## OLS on both\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](05-ordinal-regression-narrated-J_files/figure-revealjs/unnamed-chunk-9-1.png){width=1152}\n:::\n:::\n\n\n## Ordinal model recovers both\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Ordinal model on original thresholds\nfit_orig <- clm(category ~ lead_weight, data = rolls, link = \"logit\")\n\n# Ordinal model on squeezed thresholds\nfit_alt <- clm(category_alt ~ lead_weight, data = rolls_alt, link = \"logit\")\n\nbind_rows(\n  tibble(thresholds = \"Original (−0.5, 1.0)\", term = names(coef(fit_orig)), estimate = coef(fit_orig)),\n  tibble(thresholds = \"Squeezed (0.0, 0.5)\",  term = names(coef(fit_alt)),  estimate = coef(fit_alt))\n) %>%\n  kable(digits = 3)\n```\n\n::: {.cell-output-display}\n\n\n|thresholds           |term             | estimate|\n|:--------------------|:----------------|--------:|\n|Original (−0.5, 1.0) |Low&#124;Medium  |    2.266|\n|Original (−0.5, 1.0) |Medium&#124;High |    4.941|\n|Original (−0.5, 1.0) |lead_weight      |    1.052|\n|Squeezed (0.0, 0.5)  |Low&#124;Medium  |    3.625|\n|Squeezed (0.0, 0.5)  |Medium&#124;High |    4.470|\n|Squeezed (0.0, 0.5)  |lead_weight      |    1.216|\n\n\n:::\n:::\n\n:::\n\n::: callout-important\n## The point\n\nThe distributions look completely different. OLS gives nearly the same answer for both. The ordinal model **recovers the different thresholds** — it knows the measurement scales differ.\n:::\n\n::: notes\nThis is the slide that makes the case concrete. **Same latent scores. Same lead weight effect. Same underlying reality.** The only thing that changed is where we placed the thresholds — the boundaries that carve the latent variable into categories.\n\n**Look at the stacked bars in the first tab.** On the left, the original thresholds give you a wide Medium band — lots of yellow. On the right, the squeezed thresholds almost eliminate Medium — it's mostly red and green. **These look like completely different datasets.** But the hidden continuous variable underneath is identical.\n\nHere's a psychology translation. **Researcher A** uses: Dissatisfied / Neutral / Satisfied. **Researcher B** uses: Dissatisfied / Slightly Dissatisfied / Satisfied. Same people. Same underlying feelings. But Researcher B squeezed two options into the low end — a tiny gap between \"dissatisfied\" and \"slightly dissatisfied,\" then a huge jump to \"satisfied.\" That's a narrow band in the middle, just like the squeezed thresholds in the simulation.\n\n**Now flip to the OLS tab.** Two regression lines — and they look almost the same. Similar slopes. Similar confidence bands. **OLS cannot tell these apart.** It doesn't know where the thresholds are. It doesn't know one version has a wide middle category and the other has a tiny one. It just sees 1, 2, 3 and draws a line.\n\nYou built these thresholds. You know they're at −0.5 and 1.0 in one case and 0.0 and 0.5 in the other. **OLS has no idea.**\n\n**Now flip to the third tab.**\n\n-   The ordinal model recovers the thresholds correctly in both cases.\n\n-   The slopes are similar\n\n    -   — because the underlying effect *is* the same\n\n    -   — but the thresholds are different, because the measurement scales are different.\n\n    -   **That's what the threshold parameters buy you.** They let the model see something OLS is blind to.\n\n-   **thresholds and a slope.**\n\n```         \n**Thresholds = intercepts.** They answer: when the predictor is zero, where do the cuts fall?\\\n\\\nThe point isn't that they're identical — it's that they're **in the same ballpark**, while the thresholds are **dramatically different**: 2.27 vs 3.63 for the first cut, 4.94 vs 4.47 for the second.\n\nThe slope wiggles. The thresholds move a lot. OLS only sees something like the slope — it's completely blind to the threshold shift.\\\n\\\n*Let me summarize the problems with OLS before we move on to the right model.*\n```\n:::\n\n## Problems with the \"treat it as numeric\" approach\n\n::: callout-warning\n## Three things went wrong\n\n1.  **Assumes equal spacing** — is the jump from Low → Medium the same as Medium → High? We don't know, but OLS assumes it is.\n\n2.  **Predicts impossible values** — the line escapes the range of the data.\n\n3.  **Wrong distributional assumptions** — residuals are not normal, variance is not constant.\n:::\n\n. . .\n\nWe need a model that respects the **ordered** nature of the outcome without assuming it's metric.\n\n::: notes\nLet me hammer these three points. **First: equal spacing.** When you code Low as 1, Medium as 2, High as 3, you're asserting that the categories are evenly spaced. But think about a pain scale — the difference between \"no pain\" and \"mild pain\" is not the same as between \"severe pain\" and \"worst pain imaginable.\"\n\n**Second: impossible predictions.** Just like logistic regression fixed the impossible-probability problem by using the logit link, ordinal regression will fix this by working with cumulative probabilities.\n\n**Third: distributional assumptions.** The residuals from OLS on ordinal data violate normality and homoscedasticity. These aren't minor technicalities — they affect your p-values and confidence intervals — your hypothesis tests and effect estimates.\n\n*So we need a new model. And the good news is, if you understood logistic regression, you already understand 80% of it. We just need one new idea: cumulative splits.*\n:::\n\n# Cumulative Logit Model\n\n::: notes\n*Now we move from \"what's wrong with OLS\" to \"what's the right model.\" The key concept is cumulative splits — and they're a natural extension of what you already know.*\n:::\n\n## The key idea: Cumulative splits {.smaller}\n\nWith **binary** logistic regression, we modeled one split:\n\n$$\\text{logit}(P(Y = 1)) = \\beta_0 + \\beta_1 X$$\n\n. . .\n\nWith **ordinal** regression, we model **multiple cumulative splits**:\n\n-   Split 1: P(Low) vs. P(Medium or High)\n-   Split 2: P(Low or Medium) vs. P(High)\n\n. . .\n\nEach split is its own logistic regression — but they all share the **same slope**.\n\n::: callout-note\n## 🔗 The connection\n\nWith 2 categories, ordinal regression **is** logistic regression. There's 1 threshold, 1 slope.\n\nWith K categories, you get **K − 1 thresholds** but still just **1 slope** per predictor. Think of it as running K − 1 logistic regressions simultaneously, forced to have the same slope.\n:::\n\n::: notes\nHere's the core idea, and it's simpler than it looks. In logistic regression, we had one split — Y = 0 vs. Y = 1 — and we modeled it with one logit equation. **In ordinal regression, we have multiple cumulative splits.** With three categories, we get two splits: everything up to and including Low versus everything above it, and everything up to and including Medium versus everything above it.\n\n**Each split is literally a logistic regression.** We take the cumulative probability — P of Y less than or equal to k — and apply the logit link. The trick is that all these logistic regressions **share the same slope**. They differ only in their intercepts — which we call thresholds.\n\nRead the callout box with me. **If you only have two categories, this reduces to exactly the logistic regression you already know.** One threshold, one slope. So ordinal regression isn't something new — it's a generalization.\n\n*Let's connect this back to the latent variable we saw in our dice simulation.*\n:::\n\n## The latent variable interpretation\n\n::::: columns\n::: {.column width=\"50%\"}\n-   There is a continuous latent variable $\\tilde{Y}$ (the \"true score\") that gets categorized into bins by **thresholds**: $\\tau_1, \\tau_2, \\dots, \\tau_{K-1}$\n\n-   In our dice simulation:\n\n    -   $\\tilde{Y}$ = the latent score\n    -   $\\tau_1 = -0.5$, $\\tau_2 = 1.0$\n    -   Categories = Low, Medium, High\n:::\n\n::: {.column width=\"50%\"}\n![](images/ordimage.jpeg){fig-align=\"center\"}\n:::\n:::::\n\n::: notes\nRemember the hidden y-axis from the dice simulation? The continuous score underneath the categories? **The model assumes that's real.** Every ordinal response has a latent variable behind it — you just can't see it. In our dice simulation, we actually got to see it — the latent score on the y-axis. In real life, you never see it, but the model assumes it's there.\n\n**The thresholds are the cut points** that divide this continuous variable into your observed categories. In our simulation, tau 1 was −0.5 and tau 2 was 1.0. With K categories, you need K − 1 thresholds. **We always estimate J minus 1 thresholds**, because once we know all but the last cut point, the final one is determined automatically.\n\nImagine a Gaussian getting sliced by vertical lines into bins. Each bin is an observed category. The model's job is to estimate where those slices are and how the predictor shifts the curve.\n\n*Now let's formalize what \"cumulative\" means here.*\n:::\n\n## Ordered = Cumulative\n\n::::: columns\n::: {.column width=\"50%\"}\n-   We use the **cumulative distribution** to model ordered categories\n\n-   Cumulative probability: $P(Y \\leq k)$\n\n    -   Preserves the natural ordering\n    -   Always increasing: $P(Y \\leq 1) \\leq P(Y \\leq 2) \\leq \\dots$\n:::\n\n::: {.column width=\"50%\"}\n<br>\n\n![Richard McElreath](images/cum_ord.jpg){fig-alt=\"Statistical Rethinking\" fig-align=\"center\" width=\"1088\"}\n:::\n:::::\n\n::: notes\nWhy cumulative? Because **cumulative probabilities naturally respect the ordering.** The probability of being at or below category 2 is always at least as big as the probability of being at or below category 1. That monotonic structure is baked in, which is exactly what we want for ordered data.\n\nThe figure from McElreath illustrates this nicely. The bars on the left show the probability of each category. The bars on the right show the cumulative probabilities — each one stacks on top of the last, always growing, always reaching 1 at the top.\n\n*Let's see where this sits in the GLM framework.*\n:::\n\n## Generalized linear model {.smaller}\n\nYou saw this in the logistic regression lecture. Same skeleton — three components:\n\n$$\\begin{align*}\n  Y_i & \\sim \\mathrm{Dist}(\\mu_i, \\tau) & \\quad & \\text{← Random component} \\\\\n  g(\\mu_i) & = \\eta_i & \\quad & \\text{← Link function} \\\\\n  \\eta_i & = \\beta_0 + \\beta_1 X_{1i} + \\beta_2 X_{2i} + \\ldots & \\quad & \\text{← Linear predictor}\n\\end{align*}$$\n\n. . .\n\nLast time we filled in: **Bernoulli** distribution, **logit** link, linear predictor with one intercept and slopes.\n\n. . .\n\n**What changes for ordinal data?**\n\n::: notes\nThis is the same equation you saw two weeks ago. Nothing new yet — just the GLM skeleton. **Three components: a distribution, a link function, and a linear predictor.** Last time we plugged in Bernoulli for the distribution, logit for the link, and got logistic regression.\n\n**The question is: what do we plug in this time?**\n\n*Let me show you.*\n:::\n\n## Ordinal regression: Filling in the GLM {.smaller}\n\n$$\\begin{align*}\n  Y_i & \\sim \\color{#d63031}{\\mathrm{Cumulative}}(\\pi_1, \\ldots, \\pi_K) & \\quad & \\color{#d63031}{\\text{← Ordinal outcome (K ordered categories)}} \\\\[8pt]\n  \\color{#2d3436}{g(\\mu_i)} & = \\color{#0984e3}{\\mathrm{logit}} & \\quad & \\color{#0984e3}{\\text{← Same link as logistic regression}} \\\\[8pt]\n  \\eta_i & = \\color{#00b894}{\\alpha_k - (\\beta_1 X_{1i} + \\beta_2 X_{2i} + \\ldots)} & \\quad & \\color{#00b894}{\\text{← Thresholds + slopes}}\n\\end{align*}$$\n\n. . .\n\n:::::: columns\n::: {.column width=\"33%\"}\n[**Distribution**]{style=\"color: #d63031; font-size: 1.1em;\"}\n\nModels cumulative probability $P(Y \\leq k)$ — preserves the ordering\n:::\n\n::: {.column width=\"33%\"}\n[**Link**]{style=\"color: #0984e3; font-size: 1.1em;\"}\n\nLogit — identical to logistic regression. Nothing new here.\n:::\n\n::: {.column width=\"33%\"}\n[**Linear predictor**]{style=\"color: #00b894; font-size: 1.1em;\"}\n\n$K-1$ thresholds $\\alpha_k$ (one per split) + shared slopes $\\beta$ (proportional odds)\n:::\n::::::\n\n::: notes\nNow we fill in the blanks. Three changes from logistic regression — and **only one of them is actually new.**\n\n## Cumulative logit model (notation) {.smaller}.\n\n**The distribution** — in red. Instead of Bernoulli (binary), we have a cumulative distribution over K ordered categories. The model works with cumulative probabilities — P of Y less than or equal to k — which naturally preserves the ordering. This is the new part.\n\n**The link function** — in blue. It's the logit. **Exactly the same logit as logistic regression.** Nothing new to learn here. You already know this.\n\n**The linear predictor** — in green. This is where the thresholds live. Instead of one intercept, you have K minus 1 thresholds — one for each cumulative split. And the slopes are shared across all splits. That shared slope is the proportional odds assumption. Two things that are new: multiple intercepts, and the subtraction sign.\n\nSo of the three GLM components, **one is new, one is identical, and one is a natural extension.** That's why ordinal regression is easier than it looks.\n\n*Now let's define the cumulative odds and the cumulative logit formally.*\n:::\n\n\\|-------------\\|--------------------------------------------------------\\| \\| $P_k$ \\| Probability of being in category k \\| \\| $C_{pk}$ \\| Cumulative probability of being in category k or lower \\| \\| 1 − $C_{pk}$ \\| Probability of being above category k \\|\n\n$$\\textrm{Cumulative Odds} = \\frac{P(Y \\leq k)}{P(Y > k)} = \\frac{C_{pk}}{1-C_{pk}}$$\n\n. . .\n\nTake the log to get the **cumulative logit**:\n\n$$\\log\\left(\\frac{C_{pk}}{1-C_{pk}}\\right)$$\n\n. . .\n\n::: callout-note\n## 🏷️ Jargon Alert\n\nCumulative logit = cumulative log-odds = the same logit link you already know, just applied to *cumulative* probabilities.\n:::\n\n::: notes\nLet's build this up step by step, just like we did for logistic regression. **The cumulative probability is P of Y less than or equal to k** — the probability of being in category k or any lower category. The cumulative odds are the ratio of that probability to its complement — the probability of being above category k. And the cumulative logit is just the log of those odds.\n\n**This is exactly the same logit you already know.** The only difference is that instead of modeling P(Y = 1), we're modeling P(Y ≤ k). Same link function, same transformation, same interpretation of log-odds. Just applied cumulatively.\n\n*Let's look at McElreath's visualization of how this works.*\n:::\n\n## Cumulative logit model\n\n![Richard McElreath](images/cum_logodds.jpg){fig-align=\"center\"}\n\n::: notes\nThis figure from McElreath shows the cumulative probabilities being mapped to the log-odds scale. **On the left, you have the cumulative probabilities — they go from 0 to 1, always increasing.** On the right, those get transformed to log-odds, which live on the full real line.\n\n**Each cumulative split gets its own log-odds value** — and those are the thresholds in our model. The threshold between category 1 and everything above it, the threshold between categories 1-and-2 and everything above, and so on. Here the outcomes 1 through 7 are labeled on the right — each one maps to a point on the log-odds axis.\n\n*The next figure adds the visual connection between the two panels.*\n:::\n\n## Cumulative logit model\n\n![Richard McElreath](images/cut.jpg){fig-align=\"center\"}\n\n::: notes\nSame figure, but now with dashed horizontal lines connecting the cumulative proportions on the left to their corresponding points on the log-odds scale on the right. **This makes the mapping visible** — you can trace each cumulative bar across to its log-odds value.\n\n\\[Fix: The user's Obsidian says \"β captures how much the distribution shifts\" for this slide. But this figure does NOT show a predictor or β — it just adds the dashed reference lines connecting the two panels. The predictor-shift idea belongs in the \"What the slope does\" slide, which already covers it with the latent distribution visualization. Keep this narration focused on the visual mapping between cumulative probabilities and log-odds.\\]\n\n*The next figure labels these points as the model's cutpoints.*\n:::\n\n## Cumulative logit model\n\n![Richard McElreath](images/cut_outcomes.jpg)\n\n::: notes\nNow the payoff. **The points on the log-odds axis are labeled as cutpoints — α₁ through α₆.** These are exactly the threshold parameters that the model estimates. With 7 categories, you get 6 cutpoints. The last category always goes to positive infinity.\n\n\\[Fix: The previous narration described \"top = cumulative probabilities, bottom = category-specific probabilities.\" That's wrong — this figure does NOT have two panels or show category-specific probabilities. It's the same left-right layout as the previous two figures, now with the cutpoint labels (α₁–α₆) added. The three McElreath figures are a progressive reveal: outcomes labeled → dashed lines → cutpoint labels.\\]\n\n**This is what the model estimates.** Each cutpoint is a log-cumulative-odds value — the same thing you computed by hand for the 3-gram die. A predictor shifts all these cutpoints simultaneously — that's the proportional odds assumption.\n\n*Now let's write down the actual equation.*\n:::\n\n## The model equation {.smaller}\n\n$$\\log \\left(\\frac{P(Y \\leq k)}{P(Y > k)}\\right) = \\alpha_k - \\beta X$$\n\n$$\\begin{array}{rcl} L_1 &=& \\alpha_1 - \\beta_1 x_1 - \\cdots - \\beta_p X_p\\\\ L_2 &=& \\alpha_2 - \\beta_1 x_1 - \\cdots - \\beta_p X_p \\\\ L_{J-1} &=& \\alpha_{J-1} - \\beta_1 x_1 - \\cdots - \\beta_p X_p \\end{array}$$\n\n-   We estimate **J − 1 equations** simultaneously\n\n-   Each equation has a **different intercept** $\\alpha_k$ (the thresholds/cut points)\n\n-   But a **common slope** $\\beta$ ← this is the proportional odds assumption\n\n-   Intercepts are always ordered: $\\alpha_1 < \\alpha_2 < \\dots$\n\n::: notes\nHere's the full equation. On the left side: the cumulative logit — log-odds of being at or below category k. On the right side: a threshold alpha k, minus the linear predictor.\n\n**Three things to notice.** First: we're estimating J minus 1 equations simultaneously — one for each cumulative split. With 3 categories, that's 2 equations. Second: **each equation has its own intercept, the threshold alpha k, but they all share the same slope beta.** That shared slope is the proportional odds assumption — the effect of the predictor is the same no matter which cumulative split you're looking at. Third: the thresholds are always ordered — alpha 1 is always less than alpha 2.\n\nFor our dice: J = 3 categories, so we estimate 2 thresholds and 1 slope. **That's 3 parameters total to describe the entire ordinal relationship.** Very parsimonious.\n\n*Let me break down what each piece means in plain language.*\n:::\n\n## What do the pieces mean?\n\n-   $\\alpha_k$ (thresholds/intercepts/cut-offs):\n\n    -   Log-odds of falling **at or below** category $k$ when all predictors = 0\n    -   These are the ordinal equivalent of $\\beta_0$ in logistic regression\n\n-   $\\beta$ (slopes):\n\n    -   Effect of the predictor on the log-odds of being in a **higher** category\n    -   Shared across all cumulative splits\n\n-   The $-$ sign:\n\n    -   Convention so that a **positive** $\\beta$ means higher X → higher category\n\n::: notes\nLet me translate each piece. **The thresholds, alpha k, are like intercepts.** They tell you the log-odds of being at or below category k when your predictor is zero. Think of them as the \"baseline cut points\" of your ordinal scale. In logistic regression, you had one intercept; here you have K minus 1 of them.\n\n**The slope, beta, is the effect of the predictor.** Just like in logistic regression, a one-unit increase in X changes the log-odds by beta. The difference is that this change applies to every cumulative split equally. **That's the power and the constraint of the proportional odds model.**\n\n**The subtraction sign is a convention** — it's there so that a positive beta means higher X leads to higher categories. Some software uses addition, which flips the sign. Always check your software's convention.\n\nJ: If we used the standard additive parameterization, **a more positive log odds would actually correspond to a higher probability of being in a *lower* category, which is counterintuitive.** The subtraction is there to make interpretation go in the natural direction. The packages we're using today — `ordinal::clm()` and `MASS::polr()` — both use subtraction, so positive means higher.\n\n*Now let me show you visually what the thresholds and slopes are doing.*\n:::\n\nThresholds are where the latent variable gets **cut** into categories.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](05-ordinal-regression-narrated-J_files/figure-revealjs/unnamed-chunk-11-1.png){width=1152}\n:::\n:::\n\n\n. . .\n\nClose thresholds → few people land in the middle category. Far-apart thresholds → the middle category captures a wide range.\n\n::: notes\nThese two panels show the same latent distribution, but with different thresholds. **On the left, the thresholds are close together** — the middle category, Medium, covers only a narrow band of the latent variable. Most people end up in either Low or High. Think of a scale where \"neutral\" almost never gets picked.\n\n**On the right, the thresholds are far apart** — the middle category is wide and absorbs a lot of the distribution. Most people end up in Medium. Think of a scale where people cluster in the middle and extremes are rare.\n\n**The thresholds are properties of the measurement scale, not the predictor.** They tell you about how your response categories carve up the latent continuum. The model estimates them — you don't have to assume equal spacing.\n\n*Now what about the slope?*\n:::\n\n## What the slope does {.smaller}\n\nThe slope $\\beta$ shifts the **entire latent distribution** along the x-axis — the thresholds stay put.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](05-ordinal-regression-narrated-J_files/figure-revealjs/unnamed-chunk-12-1.png){width=1152}\n:::\n:::\n\n\n. . .\n\nA positive $\\beta$ shifts the distribution **right**, increasing P(higher categories). The thresholds $\\alpha_k$ don't move — they're properties of the response scale, not the predictor.\n\n::: notes\nThis is the visual that ties it all together. **The thresholds — the dashed vertical lines — stay fixed.** They're at −0.5 and 1.0 in both panels. What changes is the distribution's position.\n\n**On the left: low lead weight.** The distribution is shifted left, so most of the area falls below the first threshold — most rolls are \"Low.\" **On the right: high lead weight.** The distribution is shifted right, so most of the area is above the second threshold — most rolls are \"High.\"\n\n**The slope beta controls how much the distribution shifts per unit of the predictor.** A large positive beta means a big rightward shift — a strong effect. A small beta means barely any shift.\n\nThis is conceptually identical to what the intercept and slope did in logistic regression — they shifted the S-curve. Here, they shift the latent distribution relative to fixed thresholds.\n\n*There's a parametrization detail I need to mention briefly.*\n:::\n\n## Parametrization note {.smaller}\n\n::::: columns\n::: {.column width=\"50%\"}\n-   With **subtraction** convention ($\\alpha_k - \\beta X$):\n\n    -   Positive $\\beta$ → higher probability of being in **higher** categories\n\n![](images/neg_coef2.jpg){fig-align=\"center\"}\n:::\n\n::: {.column width=\"50%\"}\n-   With **addition** convention ($\\alpha_k + \\beta X$):\n\n    -   Positive $\\beta$ → higher probability of being in **lower** categories\n\n![](images/neg_coef.jpg){fig-align=\"center\"}\n:::\n:::::\n\n. . .\n\n::: callout-tip\n`ordinal::clm()` uses **subtraction** by default (positive = higher). `MASS::polr()` also uses subtraction. Just check the documentation for whatever package you use.\n:::\n\n::: notes\nQuick practical note. **Different software uses different sign conventions.** The `clm` function we're using today and `polr` both use the subtraction convention — meaning a positive coefficient pushes observations toward higher categories, which is the intuitive direction. Some software uses addition, which flips the interpretation.\n\n**Whenever you use a new package for ordinal regression, check this.** It's the most common source of sign confusion. If your coefficient is positive but the predicted probabilities seem to go the wrong way, the sign convention is probably the issue.\n\n*OK — let's go back to our dice data and actually fit the model.*\n:::\n\n## RM: The intercept-only model {.smaller}\n\nBefore adding predictors, fit a model with **no predictor at all** — just the thresholds.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Intercept-only model: just thresholds, no slope\ndice_null <- clm(category ~ 1, data = rolls, link = \"logit\")\n\nbroom::tidy(dice_null) %>%\n  kable(digits = 3)\n```\n\n::: {.cell-output-display}\n\n\n|term             | estimate| std.error| statistic| p.value|coef.type |\n|:----------------|--------:|---------:|---------:|-------:|:---------|\n|Low&#124;Medium  |   -0.847|     0.163|    -5.209|       0|intercept |\n|Medium&#124;High |    0.744|     0.159|     4.662|       0|intercept |\n\n\n:::\n:::\n\n\n. . .\n\n::: callout-note\n## 🔗 Recognize these?\n\nThese threshold estimates are the **log-cumulative-odds pooled across all six dice** — the same quantity you just computed by hand, but now averaged over the whole dataset. When we add `lead_weight` as a predictor next, watch how the thresholds and model fit change.\n:::\n\n::: notes\nRM: This is another McElreath move — fit the model with no predictors first, just the thresholds. **This is pedagogically crucial because it grounds you in what the threshold parameters mean before any predictor shifts them around.**\n\nLook at the output. You get two numbers — one for Low\\|Medium and one for Medium\\|High. **These are the log-cumulative-odds of being at or below each category, pooled across all dice.** They're the \"baseline\" cut points when we don't know anything about lead weight.\n\nCompare these to the by-hand calculations you just did for the 3-gram die. The intercept-only model is doing the same arithmetic, but pooling across all dice rather than looking at just one. The numbers won't match any single die exactly — they're an average.\n\n**Now here's the payoff.** When we add `lead_weight` as a predictor on the next slide, you'll see the thresholds shift and a slope appear. The thresholds in the predictor model will be the log-cumulative-odds when lead_weight = 0, and the slope will tell you how much the distribution shifts per gram of lead. The intercept-only model is your reference point for understanding what changed.\n\n*Now let's add the predictor and see what happens.*\n:::\n\n## Fitting our dice data {.smaller}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ordinal)\n\n# Fit the ordinal model\ndice_fit <- clm(category ~ lead_weight, data = rolls, link = \"logit\")\n\nsummary(dice_fit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nformula: category ~ lead_weight\ndata:    rolls\n\n link  threshold nobs logLik  AIC    niter max.grad cond.H \n logit flexible  180  -142.92 291.84 5(0)  1.02e-07 2.7e+02\n\nCoefficients:\n            Estimate Std. Error z value            Pr(>|z|)    \nlead_weight   1.0517     0.1215   8.653 <0.0000000000000002 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nThreshold coefficients:\n            Estimate Std. Error z value\nLow|Medium    2.2662     0.3863   5.866\nMedium|High   4.9409     0.5507   8.973\n```\n\n\n:::\n:::\n\n\n::: notes\nHere's the moment of truth. We're fitting a cumulative logit model with `clm` from the ordinal package. **The syntax is almost identical to `glm` — outcome on the left, predictors on the right.** We specify link = \"logit\" although that's the default.\n\nJ: When you look at the summary output, you'll see some metadata at the top — the formula, the data, the link function, and the threshold setting. **By default, the threshold is set to \"flexible,\"** meaning the model estimates where the cut points are from the data rather than imposing equal spacing. You can change this with `threshold = \"equidistant\"` if you have theoretical reasons to believe the intervals are equal, but in practice, always use the flexible default — that's one of the main advantages of ordinal regression over OLS.\n\nLook at the output. You get two thresholds — Low\\|Medium and Medium\\|High — and one slope for lead_weight. **Remember, we know the true values: tau 1 was −0.5, tau 2 was 1.0, and the slope of the latent mean was roughly 0.7 per gram.** Compare those to what the model estimated.\n\n*Let me pull out the estimates more cleanly.*\n:::\n\n## Interpreting the output {.smaller}\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|term             | estimate| std.error| statistic| p.value| conf.low| conf.high|coef.type |\n|:----------------|--------:|---------:|---------:|-------:|--------:|---------:|:---------|\n|Low&#124;Medium  |    2.266|     0.386|     5.866|       0|       NA|        NA|intercept |\n|Medium&#124;High |    4.941|     0.551|     8.973|       0|       NA|        NA|intercept |\n|lead_weight      |    1.052|     0.122|     8.653|       0|    0.824|     1.302|location  |\n\n\n:::\n:::\n\n\n. . .\n\n**Two parts:**\n\n-   **Thresholds** (intercepts for each cumulative split)\n\n    -   `Low|Medium`: log-odds of $Y \\leq$ Low when lead_weight = 0\n    -   `Medium|High`: log-odds of $Y \\leq$ Medium when lead_weight = 0\n\n-   **Slope** (shared across splits)\n\n    -   `lead_weight`: effect on log-odds of being in a higher category\n\n. . .\n\n::: callout-tip\n## Can we recover the truth?\n\nTrue thresholds: $\\tau_1$ = -0.5, $\\tau_2$ = 1. Compare to the estimated thresholds above. True slope of the latent mean was roughly 0.7 per gram. How close did we get?\n:::\n\n::: notes\nHere's the tidy output. **Two thresholds and one slope — that's the entire model for three ordered categories with one predictor.**\n\nThe threshold for Low\\|Medium is the log-odds of being in the Low category when lead weight is 0. The threshold for Medium\\|High is the log-odds of being in the Low or Medium categories when lead weight is 0. And the slope tells us: **for each additional gram of lead, the log-odds of being in a higher category increase by this amount.**\n\nJ: The threshold coefficients are things we usually don't report or interpret in a write-up, but you should understand what they represent. **Each threshold is the log-odds of being in a given category or below when the predictor equals zero.** They map onto the number line of the latent scale — they are the cut points that carve the latent continuum into your observed categories.\n\nNow look at the callout. We built this data, so we know the truth. **How close are the estimates to the true values of −0.5 and 1.0?** They won't be exact because of sampling variability, but they should be in the right neighborhood. This is the power of simulation — you can verify your model is doing what it claims.\n\n*Let's convert these to odds ratios for easier interpretation.*\n:::\n\n## From log-odds to odds ratios\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Exponentiate to get cumulative odds ratios\nbroom::tidy(dice_fit, exponentiate = TRUE, conf.int = TRUE) %>%\n  filter(coef.type == \"location\") %>%\n  kable(digits = 3)\n```\n\n::: {.cell-output-display}\n\n\n|term        | estimate| std.error| statistic| p.value| conf.low| conf.high|coef.type |\n|:-----------|--------:|---------:|---------:|-------:|--------:|---------:|:---------|\n|lead_weight |    2.863|     0.122|     8.653|       0|     2.28|     3.677|location  |\n\n\n:::\n:::\n\n\n. . .\n\n-   Interpretation: Each additional gram of lead **multiplies** the odds of being in a higher category by the OR\n\n::: notes\nJust like in logistic regression, **we exponentiate the log-odds coefficient to get an odds ratio.** The interpretation is the same flavor: each additional gram of lead multiplies the cumulative odds of being in a higher category by this factor.\n\nIf the OR is, say, 2.0, that means each gram of lead doubles the odds of being in a higher category. **Remember — that's odds, not probability.** We'll get to predicted probabilities in a moment, which are often more intuitive.\n\n*Let's look at the predicted probabilities now.*\n:::\n\n## From log-odds to probabilities\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Predicted probabilities for each die\npredictions(dice_fit, newdata = datagrid(lead_weight = 1:6)) %>%\n  kable(digits = 3)\n```\n\n::: {.cell-output-display}\n\n\n| rowid|group  | estimate| std.error| statistic| p.value| s.value| conf.low| conf.high| lead_weight|category |\n|-----:|:------|--------:|---------:|---------:|-------:|-------:|--------:|---------:|-----------:|:--------|\n|     1|Low    |    0.771|     0.051|    15.098|   0.000| 168.680|    0.671|     0.871|           1|Low      |\n|     2|Low    |    0.541|     0.054|     9.962|   0.000|  75.249|    0.434|     0.647|           2|Low      |\n|     3|Low    |    0.291|     0.042|     6.943|   0.000|  37.921|    0.209|     0.374|           3|Low      |\n|     4|Low    |    0.126|     0.028|     4.506|   0.000|  17.206|    0.071|     0.180|           4|Low      |\n|     5|Low    |    0.048|     0.016|     3.069|   0.002|   8.864|    0.017|     0.078|           5|Low      |\n|     6|Low    |    0.017|     0.008|     2.279|   0.023|   5.465|    0.002|     0.032|           6|Low      |\n|     1|Medium |    0.209|     0.045|     4.604|   0.000|  17.878|    0.120|     0.298|           1|Low      |\n|     2|Medium |    0.404|     0.049|     8.204|   0.000|  51.932|    0.308|     0.501|           2|Low      |\n|     3|Medium |    0.565|     0.050|    11.222|   0.000|  94.666|    0.466|     0.664|           3|Low      |\n|     4|Medium |    0.550|     0.050|    10.935|   0.000|  90.050|    0.452|     0.649|           4|Low      |\n|     5|Medium |    0.373|     0.049|     7.658|   0.000|  45.592|    0.278|     0.469|           5|Low      |\n|     6|Medium |    0.185|     0.042|     4.370|   0.000|  16.299|    0.102|     0.269|           6|Low      |\n|     1|High   |    0.020|     0.009|     2.321|   0.020|   5.624|    0.003|     0.037|           1|Low      |\n|     2|High   |    0.055|     0.018|     3.151|   0.002|   9.266|    0.021|     0.090|           2|Low      |\n|     3|High   |    0.144|     0.031|     4.692|   0.000|  18.493|    0.084|     0.204|           3|Low      |\n|     4|High   |    0.324|     0.044|     7.345|   0.000|  42.142|    0.238|     0.411|           4|Low      |\n|     5|High   |    0.579|     0.054|    10.746|   0.000|  87.063|    0.473|     0.684|           5|Low      |\n|     6|High   |    0.797|     0.048|    16.769|   0.000| 207.233|    0.704|     0.890|           6|Low      |\n\n\n:::\n:::\n\n\n::: notes\nNow we're in the probability world, which is where you actually want to be for interpretation. **For each die, we get the predicted probability of falling into Low, Medium, and High.**\n\nLook at the pattern: the 1-gram die has a high predicted probability of Low and a low probability of High. The 6-gram die has the reverse. The probabilities always sum to 1 within each die. **This is what you'd show in a paper when you want readers to understand the practical meaning of your effect.**\n\n*Let me visualize this as a nice plot.*\n:::\n\n## Visualizing the dice model {.smaller}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot_predictions(dice_fit, condition = \"lead_weight\", type = \"prob\") +\n  facet_wrap(~group) +\n  scale_fill_manual(values = c(color_low, color_med, color_high)) +\n  labs(x = \"Lead weight (grams)\", y = \"Predicted probability\") +\n  theme_lucid(base_size = 16)\n```\n\n::: {.cell-output-display}\n![](05-ordinal-regression-narrated-J_files/figure-revealjs/unnamed-chunk-18-1.png){width=1056}\n:::\n:::\n\n\n. . .\n\nAs weight increases: P(Low) decreases, P(High) increases. The S-curves are the same shape (proportional odds!) — just shifted.\n\n::: notes\nThree panels, one per category. **Look at the shape — these are S-curves, just like in logistic regression.** P(Low) decreases as a sigmoid, P(High) increases as a sigmoid, and P(Medium) rises then falls — it's the squeeze in between.\n\n**The key observation: the S-curves in the Low and High panels have the same shape.** They're parallel on the log-odds scale. That's the proportional odds assumption visible in the plot — the effect of lead weight is the same regardless of which cumulative split you're looking at.\n\n*This leads us to the proportional odds assumption, which is the defining feature of this model.*\n:::\n\n## Proportional odds assumption {.smaller}\n\n-   The key assumption: the **slope is equal** across all cumulative splits\n\n-   In our dice model: the effect of lead weight on the log-odds of $Y \\leq$ Low vs. $Y >$ Low is the **same** as the effect on $Y \\leq$ Medium vs. $Y >$ Medium\n\n![](images/oddsassump.jpg){fig-align=\"center\"}\n\n. . .\n\n::: callout-note\nIf this assumption holds, you only need **one slope** per predictor — massive parsimony. If it doesn't hold, consider partial proportional odds or multinomial models.\n:::\n\n::: notes\n**This is the single most important assumption of the model**, and it's the one that gives it its name. The proportional odds assumption says: the effect of a predictor is the same for every cumulative split. The slope doesn't change depending on where you draw the line.\n\nJ: **The constant slope across equations is what makes interpretation straightforward** — a higher beta means a higher chance of being in a higher category, period. If the slopes are not constant — if the lines are not parallel — this interpretation breaks down, which complicates things considerably.\n\nThink about what this means for our dice. The effect of lead weight on the odds of being in Low versus Medium-or-High is the same as the effect on Low-or-Medium versus High. **One slope captures the whole story.** That's incredibly parsimonious — but it's also a strong assumption.\n\nIf it's violated — if, say, lead weight has a huge effect on moving from Low to Medium but almost no effect on moving from Medium to High — then you need a model that allows different slopes for different splits. We'll talk about how to test this.\n\n*Let me mention briefly what happens when it breaks.*\n:::\n\n## FYI: Partial proportional odds model {.smaller}\n\n-   Is it fair to say the effect of your predictor stays the same across all category transitions?\n\n. . .\n\n-   Examples of when this breaks down:\n    -   Test prep might help more for moving from F → D than from A− → A\n    -   Age might strongly affect moving from \"poor\" → \"fair\" health but less so from \"good\" → \"excellent\"\n    -   Ceiling effects\n\n. . .\n\n-   How to know?\n    -   Likelihood ratio test comparing the two types of models\n    -   Big difference ⇒ the proportional assumption is probably wrong\n\n::: notes\nHere are some real examples where proportional odds breaks down. **Test prep might help a failing student a lot but have almost no effect at the top of the scale** — that's a ceiling effect. **Age might strongly predict moving from poor to fair health, but the jump from good to excellent might depend more on genetics than age.** In both cases, the slope is different for different cumulative splits.\n\n**You test this with a likelihood ratio test** — compare the proportional odds model (one slope) to a model that allows different slopes at each split. If the more flexible model fits significantly better, the proportional odds assumption is probably wrong.\n\nWhen it is wrong, you have options: partial proportional odds, multinomial regression, or adjacent category models. We'll see the Brant test for this in the applied example.\n\n*Let me recap what the simulation taught us before we move on to real data.*\n:::\n\n## Dice simulation: Recap {.smaller}\n\n| Step | What we did | What it teaches |\n|------------------------|------------------------|------------------------|\n| Generate latent scores | `rnorm()` per die | Latent variable concept |\n| Apply thresholds | `case_when()` with $\\tau_1$, $\\tau_2$ | How categories arise from a continuum |\n| Fit OLS | `lm(y_numeric ~ lead_weight)` | Why treating ordinal as numeric fails |\n| Fit ordinal model | `clm(category ~ lead_weight)` | How cumulative logit works |\n| Check estimates vs. truth | Compare $\\hat{\\alpha}$ to $\\tau$, $\\hat{\\beta}$ to true slope | Model recovers the generating process |\n\n. . .\n\n::: callout-note\nNow let's apply this to real data — where we don't know the truth.\n:::\n\n::: notes\nLet me take a breath and summarize. We generated data with a known latent variable, known thresholds, and a known effect. We showed that OLS gets it wrong. **We fit the ordinal model and it recovered the true parameters.** That's the simulation-to-model pipeline.\n\n**The conceptual takeaways are:** ordinal outcomes arise from thresholding a latent variable, the cumulative logit respects the ordering, and the proportional odds assumption gives you a parsimonious shared slope.\n\n*Now we switch gears to a real dataset. No more ground truth to check against — just the tools and the interpretation.*\n:::\n\n# Case Study: Applying to Graduate School\n\n::: notes\n*For Part 2 of today, we're going to apply everything we just learned to real data. Same sequence as the logistic regression case study: load data, explore, fit models, interpret, compare, visualize, report.*\n:::\n\n## Data: Postgraduate school applications {.smaller}\n\n-   Undergraduate students report how likely they were to apply to graduate school (`apply`): \"Unlikely\", \"Somewhat Likely\", \"Very Likely\"\n\n-   Additional information: GPA (`gpa`), parent education (`pared`) (college vs. no college), type of schooling (`public`) (public vs. private)\n\n\n::: {.cell}\n\n:::\n\n\n```{webr-r}\ndat <- read.csv(\"https://raw.githubusercontent.com/jgeller112/PSY504-Advanced-Stats-S24/main/slides/Ordinal_Regression/data/graduate_school.csv\")\n```\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|apply           |   n| proportion|\n|:---------------|---:|----------:|\n|somewhat likely | 140|       0.35|\n|unlikely        | 220|       0.55|\n|very likely     |  40|       0.10|\n\n\n:::\n:::\n\n\n::: notes\nHere's our dataset. Undergraduates reported **how likely they are to apply to graduate school** — unlikely, somewhat likely, or very likely. Three ordered categories, just like our dice simulation. Our predictors are GPA (continuous), whether a parent went to college (binary), and whether the student attended a public or private school (binary).\n\nLook at the proportions. **The majority — about 55% — said \"unlikely.\"** Somewhat likely and very likely split the rest. So we have a right-skewed ordinal distribution, which is exactly the kind of thing OLS handles poorly.\n\n*Let's prepare the data properly.*\n:::\n\n## Data preparation\n\n\n::: {.cell}\n\n:::\n\n\n```{webr-r}\ndat <- dat %>%\n  mutate(pared = as.factor(pared), public = as.factor(public))\n\n# make sure the outcome is ordered properly \ndat$apply <- ordered(dat$apply, levels = c(\"unlikely\", \"somewhat likely\", \"very likely\"))\n\nhead(dat$apply)  # check to see if ordered\n```\n\n. . .\n\n::: callout-tip\nAlways use `ordered()` to explicitly set the level ordering. R won't guess correctly — it defaults to alphabetical.\n:::\n\n::: notes\nTwo critical data prep steps. **First, convert pared and public to factors** — they're coded as 0/1 in the raw data but they're categorical. **Second, and this is crucial: use `ordered()` to set the level ordering explicitly.** If you don't, R will use alphabetical order, which would put \"somewhat likely\" before \"unlikely\" because S comes before U. That would completely mess up your model.\n\nAlways check with `head()` to confirm the ordering looks right. You should see the levels listed as unlikely \\< somewhat likely \\< very likely.\n\n*Let's look at the data before we model it.*\n:::\n\n## Exploratory data analysis\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](05-ordinal-regression-narrated-J_files/figure-revealjs/unnamed-chunk-22-1.png){fig-align='center' width=960}\n:::\n:::\n\n\n::: notes\nThis is the same stacked bar chart format we used for the dice, now with real data. **Students whose parents went to college — pared equals 1 on the right — have a notably smaller red bar and a larger green bar.** They're more likely to say \"very likely\" and less likely to say \"unlikely.\"\n\nThat's the signal we're going to model. **The shift in the distribution from left to right is exactly what the ordinal regression slope will capture.**\n\n*Let's fit our first model.*\n:::\n\n## Model 1: Parent education only\n\n$$\\text{logit}(P(Y_i \\leq j)) = \\alpha_j - \\beta_1 \\cdot \\text{pared}_i$$\n\n-   Fit the model with `ordinal::clm` (can also use `MASS::polr`)\n\n\n::: {.cell}\n\n:::\n\n\n```{webr-r}\n# link = probit would also be acceptable\nols1 <- clm(apply ~ pared, data = dat, link = \"logit\")\n\nsummary(ols1)\n```\n\n::: notes\nOur first model uses only parent education as a predictor. **The equation is the same structure as our dice model** — cumulative logit on the left, thresholds minus the linear predictor on the right. With 3 categories, we get 2 thresholds and 1 slope.\n\nWe use `clm` from the ordinal package. The syntax is just like `glm` — you could also use `MASS::polr`, which gives the same estimates but slightly different output formatting.\n\n*Let's interpret what comes out.*\n:::\n\n## Interpreting output {.smaller}\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|term                             | estimate| std.error| statistic| p.value| conf.low| conf.high|coef.type |\n|:--------------------------------|--------:|---------:|---------:|-------:|--------:|---------:|:---------|\n|unlikely&#124;somewhat likely    |    0.377|     0.110|     3.415|   0.001|       NA|        NA|intercept |\n|somewhat likely&#124;very likely |    2.452|     0.183|    13.430|   0.000|       NA|        NA|intercept |\n|pared1                           |    1.127|     0.263|     4.280|   0.000|    0.613|     1.648|location  |\n\n\n:::\n:::\n\n\n. . .\n\n-   **Thresholds** (2 thresholds for 3 categories)\n\n    -   `unlikely|somewhat likely`: log-odds of being Unlikely vs. higher, when pared = 0\n    -   `somewhat likely|very likely`: log-odds of being ≤ Somewhat Likely vs. Very Likely, when pared = 0\n\n-   **Slope**\n\n    -   `pared1`: Students with a college-educated parent have higher log-odds of being in a higher application category\n\n```{webr-r}\n# What is the intercept?\n# What is the slope? How do we interpret it?\n\n```\n\n::: notes\nSame structure as our dice output. **Two thresholds and one slope.** The first threshold is the log-odds of being \"unlikely\" versus anything higher, when the parent didn't go to college. The second threshold is the log-odds of being \"unlikely or somewhat likely\" versus \"very likely,\" same baseline.\n\n**The slope for pared1 is the key number.** It tells us that students with a college-educated parent have higher log-odds of being in a higher application category. But log-odds are hard to interpret directly.\n\nTry the webr block — what's the intercept? What's the slope? How would you explain the slope in words?\n\n*Let's convert to odds ratios to make this more interpretable.*\n:::\n\n## Cumulative odds ratios\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbroom::tidy(ols1, exponentiate = TRUE, conf.int = TRUE) %>%\n  filter(coef.type == \"location\") %>%\n  kable(digits = 3)\n```\n\n::: {.cell-output-display}\n\n\n|term   | estimate| std.error| statistic| p.value| conf.low| conf.high|coef.type |\n|:------|--------:|---------:|---------:|-------:|--------:|---------:|:---------|\n|pared1 |    3.088|     0.263|      4.28|       0|    1.846|     5.196|location  |\n\n\n:::\n:::\n\n\n-   Exponentiate the log cumulative odds to get odds ratios\n\n-   Students with college-educated parents have roughly 3× the odds of applying to graduate school\n\n::: notes\nHere we exponentiate to get the odds ratio. **Students whose parents went to college have about 3 times the odds of being in a higher application category** compared to students whose parents didn't attend college.\n\nRemember: this is a *cumulative* odds ratio. It applies to every cumulative split equally — the odds of \"somewhat likely or very likely\" versus \"unlikely\" are multiplied by the same factor as the odds of \"very likely\" versus \"unlikely or somewhat likely.\" **That's the proportional odds assumption at work.**\n\n*But odds ratios are still somewhat abstract. Let's get actual probabilities.*\n:::\n\n## Probabilities\n\n$$P(Y \\leq k) = \\frac{\\exp(\\alpha_k - \\beta X)}{1 + \\exp(\\alpha_k - \\beta X)}$$\n\n```{webr-r}\n# Try converting manually:\n# What is P(unlikely) for pared = 0?\n# What is P(unlikely) for pared = 1?\n\n```\n\n::: notes\nHere's the formula for converting from the model's log-odds back to cumulative probabilities. **It's the same inverse logit — plogis in R — that we used in logistic regression.** You plug in the threshold and the linear predictor, and out comes a cumulative probability.\n\nJ: Let me walk through the manual calculation so you really see how it works. **P(unlikely) for a student with pared = 0 is just `plogis(threshold_1)` — apply the inverse logit to the first threshold.** For pared = 1, it's `plogis(threshold_1 - slope)`. To get **P(somewhat likely)**, you take the cumulative probability at the second threshold minus the cumulative probability at the first threshold — it's the area *between* the two cuts. And **P(very likely) is just 1 minus the cumulative probability at the second threshold** — everything above the last cut. While this is useful to understand conceptually, in practice you'd use `marginaleffects::predictions()`, which computes all of this in one line.\n\nTry it in the webr block. Take the first threshold, subtract beta times pared, and apply the inverse logit. What probability of \"unlikely\" do you get for students whose parents didn't go to college? What about for students whose parents did?\n\n*If you don't want to do this by hand, marginaleffects will do it for you.*\n:::\n\n## Predicted probabilities\n\n\n::: {.cell}\n\n```{.r .cell-code}\npredictions(ols1, newdata = datagrid(pared = c(\"0\", \"1\"))) %>%\n  kable(digits = 3)\n```\n\n::: {.cell-output-display}\n\n\n| rowid|group           | estimate| std.error| statistic| p.value| s.value| conf.low| conf.high|pared |apply       |\n|-----:|:---------------|--------:|---------:|---------:|-------:|-------:|--------:|---------:|:-----|:-----------|\n|     1|unlikely        |    0.593|     0.027|    22.273|       0| 362.664|    0.541|     0.645|0     |very likely |\n|     2|unlikely        |    0.321|     0.053|     6.019|       0|  29.089|    0.216|     0.425|1     |very likely |\n|     1|somewhat likely |    0.328|     0.024|    13.688|       0| 139.259|    0.281|     0.374|0     |very likely |\n|     2|somewhat likely |    0.469|     0.033|    14.070|       0| 146.949|    0.404|     0.535|1     |very likely |\n|     1|very likely     |    0.079|     0.013|     5.949|       0|  28.469|    0.053|     0.105|0     |very likely |\n|     2|very likely     |    0.210|     0.042|     4.944|       0|  20.316|    0.127|     0.293|1     |very likely |\n\n\n:::\n:::\n\n\n::: notes\nHere are the predicted probabilities from the `predictions` function. For each level of parent education, you get the predicted probability of being in each application category. **Compare pared = 0 to pared = 1** — you can see the probability of \"unlikely\" drops and the probability of \"very likely\" increases when the parent went to college.\n\nThese numbers are what you'd want to report in a paper for practical interpretation. Log-odds and odds ratios are useful for statistical comparison, **but predicted probabilities are what people actually understand.**\n\n*Let me plot this.*\n:::\n\n## Model 1 visualization\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nplot_predictions(ols1, condition = \"pared\", type = \"prob\") +\n  facet_wrap(~group) +\n  labs(x = \"Parent Education\", y = \"Predicted probability\") +\n  scale_y_continuous(labels = scales::percent) +\n  theme_lucid(base_size = 20)\n```\n\n::: {.cell-output-display}\n![](05-ordinal-regression-narrated-J_files/figure-revealjs/unnamed-chunk-27-1.png){fig-align='center' width=1152}\n:::\n:::\n\n\n::: notes\nThree panels — one per response category. **The left panel shows that the probability of \"unlikely\" drops from about 55% to about 35% when the parent went to college.** The right panel shows \"very likely\" goes up. The middle panel shows \"somewhat likely\" also increases a bit.\n\nJ: As you critically assess the default output, **notice that the categories may not be in the correct order and the x-axis labels could be more informative.** These are easy things to fix using ggplot2 — always clean up your plots before presenting them.\n\n**This is the visualization you'd include in a paper or presentation.** It makes the practical meaning of the model immediately clear, without requiring anyone to think in log-odds or odds ratios.\n\n*Now let's look at marginal effects — the change in probability.*\n:::\n\n## Marginal effects\n\n\n::: {.cell}\n\n```{.r .cell-code}\navg_comparisons(ols1) %>%\n  kable(digits = 3)\n```\n\n::: {.cell-output-display}\n\n\n|term  |group           |contrast | estimate| std.error| statistic| p.value| s.value| conf.low| conf.high|\n|:-----|:---------------|:--------|--------:|---------:|---------:|-------:|-------:|--------:|---------:|\n|pared |unlikely        |1 - 0    |   -0.272|     0.058|    -4.664|   0.000|  18.301|   -0.387|    -0.158|\n|pared |somewhat likely |1 - 0    |    0.142|     0.027|     5.257|   0.000|  22.700|    0.089|     0.194|\n|pared |very likely     |1 - 0    |    0.131|     0.040|     3.243|   0.001|   9.726|    0.052|     0.210|\n\n\n:::\n:::\n\n\n. . .\n\n::: callout-tip\nMarginal effects tell you the change in **probability** for each category — much easier to interpret than odds ratios.\n:::\n\n::: notes\nMarginal effects give you the change in predicted probability for each category when you go from pared = 0 to pared = 1. **You can say something like: having a college-educated parent reduces the probability of being \"unlikely\" by X percentage points and increases the probability of being \"very likely\" by Y percentage points.**\n\nJ: These are also called **risk differences** — the difference in probability between the two conditions. For example, students with a college-educated parent might be about 14% more likely to respond \"somewhat likely,\" 27% less likely to respond \"unlikely,\" and 13% more likely to respond \"very likely.\" **These can all be obtained in one line of code using `avg_comparisons()`.**\n\nThat's a much more intuitive statement than \"the odds ratio is 3.\" **I recommend always computing marginal effects alongside odds ratios** — they complement each other.\n\n*Now we need to check our key assumption: proportional odds.*\n:::\n\n## Testing proportional odds assumption\n\n-   `brant` test: compares the full proportional odds model to one that relaxes the assumption\n\n    -   You want a **non-significant** $\\chi^2$ test\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(gofcat)\nbrant.test(ols1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nBrant Test:\n           chi-sq   df   pr(>chi)\nOmnibus     0.017    1        0.9\npared1      0.017    1        0.9\n\nH0: Proportional odds assumption holds\n```\n\n\n:::\n:::\n\n\n::: notes\nThe Brant test is the standard frequentist test for the proportional odds assumption. It compares our model — which constrains the slope to be equal across all cumulative splits — to a model that allows different slopes. **If the test is significant, the assumption is violated — the slopes are meaningfully different across splits.**\n\nJ: Specifically, the Brant test performs **a chi-square comparison between a model with one common slope and a model with separate slopes for each threshold.** We want the chi-square to be non-significant — that's evidence that the proportional odds assumption holds and our single-slope model is adequate.\n\n**You want a non-significant result here.** That means the proportional odds model is adequate — the simplification of having one shared slope is defensible.\n\nLook at the p-value. Is it significant?\n\n*If it were violated, here's what you'd do.*\n:::\n\n## If the proportional odds test is violated\n\nSeveral options:\n\n-   **Multinomial regression** — use lowest level as reference; no ordering assumed\n\n-   **Adjacent category model** — model transitions between neighboring categories\n\n-   **Non-proportional odds (NPO) model** — allow slopes to vary by split\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# In VGAM: NPO model\nlibrary(VGAM)\nols_npo <- vglm(apply ~ pared, family = cumulative(parallel = FALSE, reverse = TRUE), data = dat)\n```\n:::\n\n\n::: notes\nIf the Brant test is significant, you have three main options. **Multinomial regression** throws away the ordering information and treats the categories as unordered — it's the most flexible but also the least efficient. **Adjacent category models** model each transition between neighboring categories separately. **Non-proportional odds models** keep the ordinal structure but allow different slopes at each split — this is often the best compromise.\n\nThe code here shows how to fit a non-proportional odds model in VGAM — you set `parallel = FALSE` to let the slopes vary.\n\nJ: The non-proportional odds model is fit using `vgam()` from the `VGAM` package with `parallel = FALSE`. **The output will show J minus 1 slopes rather than one** — one for each cumulative split — and you can interpret each coefficient the same way as in the standard ordinal model, just now they're allowed to differ.\n\n**In practice, a mildly significant Brant test with similar-looking slopes across splits is often not worth abandoning proportional odds for.** Use your judgment — the proportional odds model is more interpretable.\n\n*Let's keep building. Time to add more predictors.*\n:::\n\n## Model 2: Add public school + GPA\n\n\n::: {.cell}\n\n:::\n\n\n```{webr-r}\nols2 <- clm(apply ~ pared + public + gpa, data = dat)\n\nbroom::tidy(ols2, conf.int = TRUE) %>%\n  filter(coef.type == \"location\") %>%\n  kable(digits = 3)\n```\n\n. . .\n\n```{webr-r}\n# What do the coefficients mean?\n# pared1: \n# public1: \n# gpa: \n\n```\n\n::: notes\nModel 2 adds public school and GPA as predictors. **Same model structure — cumulative logit with proportional odds — but now with three predictors instead of one.** We still get 2 thresholds and now 3 slopes.\n\nJ: For the public school variable: the estimate is negative and not statistically significant. Nevertheless, for demonstrative purposes: **for students who attended public school compared to private, there is a decrease in the log odds of being in a higher category.** Exponentiating gives an odds ratio of about 0.94, corresponding to a 6% decrease in odds — not a meaningful effect. For GPA, each one-unit increase is associated with about an 86% increase in the odds of applying to graduate school.\n\nTry interpreting each slope in the webr block. **Pared1 is the effect of parent education, public1 is the effect of attending public school, and gpa is the effect of GPA.** Which ones are significant? Which direction do they go? Does the parent education effect change when you control for GPA?\n\n*Let's test the proportional odds assumption for this fuller model.*\n:::\n\n## Test proportional odds: Model 2\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbrant.test(ols2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nBrant Test:\n           chi-sq   df   pr(>chi)  \nOmnibus     4.343    3      0.227  \npared1      0.132    1      0.716  \npublic1     3.443    1      0.064 .\ngpa         0.179    1      0.672  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nH0: Proportional odds assumption holds\n```\n\n\n:::\n:::\n\n\n::: notes\nSame test, now for the model with all three predictors. **Check both the omnibus test — the overall test for all predictors — and the individual tests for each predictor.** It's possible for the assumption to hold overall but be violated for one specific predictor, or vice versa.\n\nLook at the results. Is the assumption holding?\n\n*Let's visualize what this model is doing.*\n:::\n\n## Visualization: Stacked area plots\n\n::: panel-tabset\n## Continuous (GPA)\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(effects)\nplot(effect(\"gpa\", ols2), style = \"stacked\")\n```\n\n::: {.cell-output-display}\n![](05-ordinal-regression-narrated-J_files/figure-revealjs/unnamed-chunk-33-1.png){fig-align='center' width=1152}\n:::\n:::\n\n\n## Categorical (Public)\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nplot(effect(\"public\", ols2), style = \"stacked\")\n```\n\n::: {.cell-output-display}\n![](05-ordinal-regression-narrated-J_files/figure-revealjs/unnamed-chunk-34-1.png){fig-align='center' width=1152}\n:::\n:::\n\n:::\n\n::: notes\nStacked area plots are a great way to visualize ordinal regression with continuous predictors. **The GPA panel shows how the probability of each category changes across the GPA range.** As GPA increases, the \"unlikely\" band shrinks and the \"very likely\" band grows.\n\nJ: The `effects` package produces this stacked area plot in one line of code. **Lower GPA students are more likely to respond \"unlikely,\" while the area for \"somewhat likely\" and \"very likely\" widens as GPA increases.** This can be customized with ggplot2 for a publication-ready figure.\n\n**The public school panel shows the same thing for the categorical predictor.** You can see whether the distribution shifts meaningfully between public and private school students.\n\nToggle between the tabs to compare the two predictors. **GPA has a more visible effect — the bands shift more — while public school barely moves the distribution.**\n\n*Now let's ask: does the effect of parent education depend on GPA?*\n:::\n\n## RM: Seeing the full redistribution {.smaller}\n\nA predictor doesn't push someone into a specific category — it shifts their latent score, which **redistributes probability across all categories simultaneously**.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npredictions(ols2, \n            newdata = datagrid(gpa = c(2.5, 3.0, 3.5, 4.0), \n                               pared = \"0\", public = \"0\")) %>%\n  mutate(gpa_label = paste0(\"GPA = \", gpa)) %>%\n  ggplot(aes(x = group, y = estimate, fill = group)) +\n  geom_col(width = 0.7) +\n  geom_errorbar(aes(ymin = conf.low, ymax = conf.high), width = 0.2) +\n  facet_wrap(~gpa_label, nrow = 1) +\n  scale_fill_manual(values = c(\"unlikely\" = color_low, \n                                \"somewhat likely\" = color_med, \n                                \"very likely\" = color_high),\n                    guide = \"none\") +\n  scale_y_continuous(labels = scales::percent) +\n  labs(x = \"Response category\", y = \"Predicted probability\",\n       title = \"How probability mass redistributes as GPA increases\",\n       subtitle = \"Non-college-educated parent, private school\") +\n  theme_lucid(base_size = 14) +\n  theme(axis.text.x = element_text(angle = 20, hjust = 1))\n```\n\n::: {.cell-output-display}\n![](05-ordinal-regression-narrated-J_files/figure-revealjs/unnamed-chunk-35-1.png){width=1056}\n:::\n:::\n\n\n. . .\n\n::: callout-tip\nThis is what the model *predicts*, not the raw data. As GPA rises, probability drains from \"unlikely\" and flows into \"somewhat likely\" and \"very likely.\" **All three categories change simultaneously — that's the ordinal redistribution.**\n:::\n\n::: notes\nRM: This visualization comes from McElreath's strongest pedagogical conviction: **never just stare at coefficient tables — plot the predicted probabilities.** The stacked area plot on the previous slide was useful, but this version is more direct. You can see the full probability distribution across all three response categories, side by side, for four representative GPA values.\n\n**Watch what happens as you move left to right.** At GPA = 2.5, the \"unlikely\" bar dominates — most of the probability mass is there. At GPA = 3.0, it starts to shrink. By GPA = 4.0, \"unlikely\" has dropped substantially and \"somewhat likely\" and \"very likely\" have grown.\n\n**The key insight** — and this is straight from McElreath — is that a predictor doesn't push someone into a specific category. It shifts their underlying latent score, which probabilistically redistributes them across all categories simultaneously. The bars move as a system. Probability drains from one end and flows to the other. That's what ordinal regression is capturing.\n\nThe error bars are 95% confidence intervals — notice they're wider at the extremes of GPA where we have less data. This is the kind of figure that belongs in a paper or presentation, because it communicates the practical meaning of your model without requiring anyone to think about log-odds.\n\n*Now let's ask: does the effect of parent education depend on GPA?*\n:::\n\n## Model 3: Add interaction (pared × GPA)\n\n\n::: {.cell}\n\n:::\n\n\n```{webr-r}\nols3 <- clm(apply ~ public + pared * gpa, data = dat)\n\nbroom::tidy(ols3, conf.int = TRUE) %>%\n  filter(coef.type == \"location\") %>%\n  kable(digits = 3)\n```\n\n::: notes\nModel 3 adds an interaction between parent education and GPA. **The question is: does the effect of having a college-educated parent depend on how high your GPA is?** Maybe parent education matters more for low-GPA students, or maybe it only kicks in at the high end.\n\nLook at the interaction term. Is it significant? What direction does it go?\n\n*Let's formally compare this to the main-effects model.*\n:::\n\n## Model comparisons\n\n-   Likelihood ratio test (LRT)\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Main effects model vs. interaction\nols_test <- anova(ols2, ols3)\nkable(ols_test)\n```\n\n::: {.cell-output-display}\n\n\n|     | no.par|      AIC|    logLik|   LR.stat| df| Pr(>Chisq)|\n|:----|------:|--------:|---------:|---------:|--:|----------:|\n|ols2 |      5| 727.0249| -358.5124|        NA| NA|         NA|\n|ols3 |      6| 728.9774| -358.4887| 0.0474444|  1|  0.8275715|\n\n\n:::\n:::\n\n\n::: notes\nJust like in logistic regression, **we use a likelihood ratio test to compare nested models.** We're asking: does adding the pared-by-GPA interaction significantly improve model fit over the main-effects model?\n\nLook at the p-value. **If it's not significant, the interaction isn't adding enough to justify the extra complexity**, and we'd stick with the simpler main-effects model.\n\n*We can also test each predictor's contribution individually.*\n:::\n\n## Testing significance\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Use Type III if interactions are important\nols_test3 <- anova(ols3, type = \"III\")\nkable(ols_test3)\n```\n\n::: {.cell-output-display}\n\n\n|          | Df|     Chisq| Pr(>Chisq)|\n|:---------|--:|---------:|----------:|\n|public    |  1| 0.0433179|  0.8351278|\n|pared     |  1| 0.0760440|  0.7827319|\n|gpa       |  1| 4.3838466|  0.0362810|\n|pared:gpa |  1| 0.0473770|  0.8276920|\n\n\n:::\n:::\n\n\n::: notes\nType III tests give you the significance of each predictor **conditional on all other predictors in the model, including the interaction.** This is important when you have interactions — Type I tests are sequential and the order of entry matters, but Type III tests are order-independent.\n\nJ: **If testing interactions, use Type III sums of squares. For a main effects model, use Type II. Never use Type I** — Type I is sequential and the order you enter variables changes the results, which is almost never what you want.\n\n**Look for which predictors have significant chi-square values.** Those are the ones contributing meaningfully to the model.\n\n*Now let me show you all three models side by side.*\n:::\n\n## Model comparison table\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodelsummary(\n  list(\"Parent Ed\" = ols1,\n       \"Main Effects\" = ols2,\n       \"Interaction\" = ols3),\n  exponentiate = TRUE,\n  stars = TRUE,\n  title = \"Ordinal Regression: Model Comparison\"\n)\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<!-- preamble start -->\n\n    <script>\n\n      function styleCell_5fzb5mwhhyrkvzrwhwio(i, j, css_id) {\n          var table = document.getElementById(\"tinytable_5fzb5mwhhyrkvzrwhwio\");\n          var cell = table.rows[i]?.cells[j];  // Safe navigation to avoid errors\n          if (cell) {\n              console.log(`Styling cell at (${i}, ${j}) with class ${css_id}`);\n              cell.classList.add(css_id);\n          } else {\n              console.warn(`Cell at (${i}, ${j}) not found.`);\n          }\n      }\n      function insertSpanRow(i, colspan, content) {\n        var table = document.getElementById('tinytable_5fzb5mwhhyrkvzrwhwio');\n        var newRow = table.insertRow(i);\n        var newCell = newRow.insertCell(0);\n        newCell.setAttribute(\"colspan\", colspan);\n        // newCell.innerText = content;\n        // this may be unsafe, but innerText does not interpret <br>\n        newCell.innerHTML = content;\n      }\n      function spanCell_5fzb5mwhhyrkvzrwhwio(i, j, rowspan, colspan) {\n        var table = document.getElementById(\"tinytable_5fzb5mwhhyrkvzrwhwio\");\n        const targetRow = table.rows[i];\n        const targetCell = targetRow.cells[j];\n        for (let r = 0; r < rowspan; r++) {\n          // Only start deleting cells to the right for the first row (r == 0)\n          if (r === 0) {\n            // Delete cells to the right of the target cell in the first row\n            for (let c = colspan - 1; c > 0; c--) {\n              if (table.rows[i + r].cells[j + c]) {\n                table.rows[i + r].deleteCell(j + c);\n              }\n            }\n          }\n          // For rows below the first, delete starting from the target column\n          if (r > 0) {\n            for (let c = colspan - 1; c >= 0; c--) {\n              if (table.rows[i + r] && table.rows[i + r].cells[j]) {\n                table.rows[i + r].deleteCell(j);\n              }\n            }\n          }\n        }\n        // Set rowspan and colspan of the target cell\n        targetCell.rowSpan = rowspan;\n        targetCell.colSpan = colspan;\n      }\n      // tinytable span after\n      window.addEventListener('load', function () {\n          var cellsToStyle = [\n            // tinytable style arrays after\n          { positions: [ { i: 0, j: 0 },  ], css_id: 'tinytable_css_x7be7seu4kufjgqqs5oi',}, \n          { positions: [ { i: 16, j: 1 }, { i: 16, j: 2 }, { i: 16, j: 3 },  ], css_id: 'tinytable_css_miywjz0as7edknm9q7ft',}, \n          { positions: [ { i: 12, j: 0 },  ], css_id: 'tinytable_css_mblmwzftjbet7kyyeydu',}, \n          { positions: [ { i: 12, j: 1 }, { i: 12, j: 2 }, { i: 12, j: 3 },  ], css_id: 'tinytable_css_kiuqi084tcmof5ddnkph',}, \n          { positions: [ { i: 1, j: 1 }, { i: 2, j: 1 }, { i: 3, j: 1 }, { i: 5, j: 1 }, { i: 6, j: 1 }, { i: 7, j: 1 }, { i: 9, j: 1 }, { i: 10, j: 1 }, { i: 11, j: 1 }, { i: 8, j: 2 }, { i: 13, j: 1 }, { i: 14, j: 1 }, { i: 15, j: 1 }, { i: 8, j: 3 }, { i: 4, j: 1 }, { i: 1, j: 2 }, { i: 2, j: 2 }, { i: 3, j: 2 }, { i: 8, j: 1 }, { i: 5, j: 2 }, { i: 6, j: 2 }, { i: 7, j: 2 }, { i: 4, j: 3 }, { i: 9, j: 2 }, { i: 10, j: 2 }, { i: 11, j: 2 }, { i: 3, j: 3 }, { i: 13, j: 2 }, { i: 14, j: 2 }, { i: 15, j: 2 }, { i: 7, j: 3 }, { i: 4, j: 2 }, { i: 1, j: 3 }, { i: 2, j: 3 }, { i: 11, j: 3 }, { i: 5, j: 3 }, { i: 6, j: 3 }, { i: 15, j: 3 }, { i: 9, j: 3 }, { i: 10, j: 3 }, { i: 13, j: 3 }, { i: 14, j: 3 },  ], css_id: 'tinytable_css_kdocbhm11a1rdn3nm0cc',}, \n          { positions: [ { i: 1, j: 0 }, { i: 2, j: 0 }, { i: 3, j: 0 }, { i: 4, j: 0 }, { i: 5, j: 0 }, { i: 6, j: 0 }, { i: 7, j: 0 }, { i: 8, j: 0 }, { i: 9, j: 0 }, { i: 10, j: 0 }, { i: 11, j: 0 }, { i: 13, j: 0 }, { i: 14, j: 0 }, { i: 15, j: 0 },  ], css_id: 'tinytable_css_jg84fnwulelpks6k3i6o',}, \n          { positions: [ { i: 0, j: 1 }, { i: 0, j: 2 }, { i: 0, j: 3 },  ], css_id: 'tinytable_css_ha1ox34z60z862otnxje',}, \n          { positions: [ { i: 16, j: 0 },  ], css_id: 'tinytable_css_21fg6xs7pl690yv56ebc',}, \n          ];\n\n          // Loop over the arrays to style the cells\n          cellsToStyle.forEach(function (group) {\n              group.positions.forEach(function (cell) {\n                  styleCell_5fzb5mwhhyrkvzrwhwio(cell.i, cell.j, group.css_id);\n              });\n          });\n      });\n    </script>\n\n    <style>\n      /* tinytable css entries after */\n      .table td.tinytable_css_x7be7seu4kufjgqqs5oi, .table th.tinytable_css_x7be7seu4kufjgqqs5oi { text-align: left; border-top: solid #d3d8dc 0.1em; border-bottom: solid #d3d8dc 0.05em; }\n      .table td.tinytable_css_miywjz0as7edknm9q7ft, .table th.tinytable_css_miywjz0as7edknm9q7ft { text-align: center; border-bottom: solid #d3d8dc 0.1em; }\n      .table td.tinytable_css_mblmwzftjbet7kyyeydu, .table th.tinytable_css_mblmwzftjbet7kyyeydu { text-align: left; border-bottom: solid black 0.05em; }\n      .table td.tinytable_css_kiuqi084tcmof5ddnkph, .table th.tinytable_css_kiuqi084tcmof5ddnkph { text-align: center; border-bottom: solid black 0.05em; }\n      .table td.tinytable_css_kdocbhm11a1rdn3nm0cc, .table th.tinytable_css_kdocbhm11a1rdn3nm0cc { text-align: center; }\n      .table td.tinytable_css_jg84fnwulelpks6k3i6o, .table th.tinytable_css_jg84fnwulelpks6k3i6o { text-align: left; }\n      .table td.tinytable_css_ha1ox34z60z862otnxje, .table th.tinytable_css_ha1ox34z60z862otnxje { text-align: center; border-top: solid #d3d8dc 0.1em; border-bottom: solid #d3d8dc 0.05em; }\n      .table td.tinytable_css_21fg6xs7pl690yv56ebc, .table th.tinytable_css_21fg6xs7pl690yv56ebc { text-align: left; border-bottom: solid #d3d8dc 0.1em; }\n    </style>\n    <div class=\"container\">\n      <table class=\"table table-borderless\" id=\"tinytable_5fzb5mwhhyrkvzrwhwio\" style=\"width: auto; margin-left: auto; margin-right: auto;\" data-quarto-disable-processing='true'>\n        <thead>\n        <caption>Ordinal Regression: Model Comparison</caption>\n              <tr>\n                <th scope=\"col\"> </th>\n                <th scope=\"col\">Parent Ed</th>\n                <th scope=\"col\">Main Effects</th>\n                <th scope=\"col\">Interaction</th>\n              </tr>\n        </thead>\n        <tfoot><tr><td colspan='4'>+ p < 0.1, * p < 0.05, ** p < 0.01, *** p < 0.001</td></tr></tfoot>\n        <tbody>\n                <tr>\n                  <td>unlikely|somewhat likely</td>\n                  <td>1.458***</td>\n                  <td>9.055**</td>\n                  <td>8.424*</td>\n                </tr>\n                <tr>\n                  <td></td>\n                  <td>(0.161)</td>\n                  <td>(7.059)</td>\n                  <td>(7.130)</td>\n                </tr>\n                <tr>\n                  <td>somewhat likely|very likely</td>\n                  <td>11.610***</td>\n                  <td>73.609***</td>\n                  <td>68.570***</td>\n                </tr>\n                <tr>\n                  <td></td>\n                  <td>(2.120)</td>\n                  <td>(59.205)</td>\n                  <td>(59.450)</td>\n                </tr>\n                <tr>\n                  <td>pared1</td>\n                  <td>3.088***</td>\n                  <td>2.851***</td>\n                  <td>1.799</td>\n                </tr>\n                <tr>\n                  <td></td>\n                  <td>(0.813)</td>\n                  <td>(0.758)</td>\n                  <td>(3.834)</td>\n                </tr>\n                <tr>\n                  <td>public1</td>\n                  <td></td>\n                  <td>0.943</td>\n                  <td>0.940</td>\n                </tr>\n                <tr>\n                  <td></td>\n                  <td></td>\n                  <td>(0.281)</td>\n                  <td>(0.280)</td>\n                </tr>\n                <tr>\n                  <td>gpa</td>\n                  <td></td>\n                  <td>1.851*</td>\n                  <td>1.807*</td>\n                </tr>\n                <tr>\n                  <td></td>\n                  <td></td>\n                  <td>(0.482)</td>\n                  <td>(0.511)</td>\n                </tr>\n                <tr>\n                  <td>pared1 × gpa</td>\n                  <td></td>\n                  <td></td>\n                  <td>1.160</td>\n                </tr>\n                <tr>\n                  <td></td>\n                  <td></td>\n                  <td></td>\n                  <td>(0.791)</td>\n                </tr>\n                <tr>\n                  <td>Num.Obs.</td>\n                  <td>400</td>\n                  <td>400</td>\n                  <td>400</td>\n                </tr>\n                <tr>\n                  <td>AIC</td>\n                  <td>728.8</td>\n                  <td>727.0</td>\n                  <td>729.0</td>\n                </tr>\n                <tr>\n                  <td>BIC</td>\n                  <td>740.8</td>\n                  <td>747.0</td>\n                  <td>752.9</td>\n                </tr>\n                <tr>\n                  <td>RMSE</td>\n                  <td>1.37</td>\n                  <td>1.37</td>\n                  <td>1.37</td>\n                </tr>\n        </tbody>\n      </table>\n    </div>\n<!-- hack to avoid NA insertion in last line -->\n```\n\n:::\n:::\n\n\n::: notes\nThis is the `modelsummary` table — the same function we used in the logistic regression lecture. **All three models side by side, with exponentiated coefficients so you're reading odds ratios, plus significance stars and fit statistics at the bottom.**\n\n**This is the table you'd put in a paper.** It lets readers see how the estimates change as you add predictors, whether the interaction matters, and how model fit evolves. Compare the AIC values across models — lower is better.\n\n*Let's visualize the interaction specifically.*\n:::\n\n## Visualization: Interaction\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nplot_predictions(ols3, condition = c(\"gpa\", \"pared\"), type = \"prob\") +\n  facet_grid(~group) +\n  theme_lucid(base_size = 14)\n```\n\n::: {.cell-output-display}\n![](05-ordinal-regression-narrated-J_files/figure-revealjs/unnamed-chunk-40-1.png){fig-align='center' width=1152}\n:::\n:::\n\n\n::: notes\nNow you can see the interaction visually. **Each panel is one response category, and the two lines are for pared = 0 versus pared = 1.** If the lines are parallel, there's no interaction. If they diverge or converge, the interaction is doing something.\n\n**Look at the \"very likely\" panel especially.** Do the lines diverge at high GPA? Does parent education matter more at one end of the GPA scale than the other? This visual complements the formal test.\n\n*Now let's do some more focused follow-up tests.*\n:::\n\n## Pairwise comparisons\n\n-   Results are on the logit (latent scale) by default\n\n```{webr-r}\nemmeans(ols3, list(pairwise ~ pared, pairwise ~ public))\n```\n\n::: notes\n`emmeans` gives us estimated marginal means and pairwise comparisons. **By default, these are on the logit — latent — scale**, which means the comparisons are in log-odds units. You can add `type = \"response\"` to get them on the probability scale instead.\n\nJ: **The logit scale is the most natural scale for these comparisons since it's continuous** — it's the scale on which the model is linear. If you have theoretical reasons to work on the probability scale, `marginaleffects` provides comparisons there as well, but the logit scale is the default for a reason.\n\n**The pairwise contrast for pared tells you the log-odds difference** between students with and without college-educated parents, averaging over other predictors. For public, it's the difference between public and private school students.\n\n*For the interaction, we can also look at simple slopes.*\n:::\n\n## Simple slopes\n\n```{webr-r}\nemtrends(ols3, pairwise ~ pared, var = \"gpa\")\n```\n\n::: notes\n`emtrends` gives you the **slope of GPA separately for each level of parent education.** This is the simple slopes analysis for the interaction. If the slopes are meaningfully different, the interaction is real — the effect of GPA depends on parent education.\n\n**Look at the pairwise comparison of the two slopes.** If the difference is significant, you have evidence that GPA matters differently depending on whether the parent went to college.\n\n*We can also visualize this on the latent scale.*\n:::\n\n## Latent scale\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nplot(effect(\"pared:gpa\", ols3, latent = TRUE))\n```\n\n::: {.cell-output-display}\n![](05-ordinal-regression-narrated-J_files/figure-revealjs/unnamed-chunk-41-1.png){fig-align='center' width=1152}\n:::\n:::\n\n\n::: notes\nThis plot shows the interaction on the latent scale — **the hidden continuous variable that ordinal regression assumes underlies the categories.** The y-axis is the latent linear predictor, and the lines show how it changes with GPA for each level of parent education.\n\nJ: The `effects` package can map out an interaction on the latent scale and **actually shows the cut points on the figure itself** — those horizontal dashed lines are the thresholds. This gives you a direct visual of where the thresholds slice the latent variable relative to the predicted values for each group.\n\n**If the lines are parallel, the interaction is zero.** If they diverge or converge, the effect of GPA depends on parent education. This view strips away the nonlinearity of the cumulative logit and shows you the linear relationships underneath.\n\n*Let's compute marginal effects for the full model.*\n:::\n\n## Marginal effects\n\n\n::: {.cell}\n\n```{.r .cell-code}\navg_comparisons(ols3) %>%\n  kable(digits = 3)\n```\n\n::: {.cell-output-display}\n\n\n|term   |group           |contrast | estimate| std.error| statistic| p.value| s.value| conf.low| conf.high|\n|:------|:---------------|:--------|--------:|---------:|---------:|-------:|-------:|--------:|---------:|\n|gpa    |unlikely        |+1       |   -0.143|     0.059|    -2.430|   0.015|   6.049|   -0.258|    -0.028|\n|gpa    |somewhat likely |+1       |    0.074|     0.031|     2.350|   0.019|   5.735|    0.012|     0.135|\n|gpa    |very likely     |+1       |    0.069|     0.036|     1.906|   0.057|   4.143|   -0.002|     0.141|\n|pared  |unlikely        |1 - 0    |   -0.247|     0.063|    -3.928|   0.000|  13.510|   -0.370|    -0.124|\n|pared  |somewhat likely |1 - 0    |    0.130|     0.032|     4.071|   0.000|  14.383|    0.068|     0.193|\n|pared  |very likely     |1 - 0    |    0.117|     0.039|     3.034|   0.002|   8.697|    0.041|     0.193|\n|public |unlikely        |1 - 0    |    0.014|     0.069|     0.209|   0.835|   0.261|   -0.122|     0.151|\n|public |somewhat likely |1 - 0    |   -0.009|     0.044|    -0.207|   0.836|   0.259|   -0.096|     0.077|\n|public |very likely     |1 - 0    |   -0.005|     0.025|    -0.212|   0.832|   0.265|   -0.055|     0.044|\n\n\n:::\n:::\n\n\n::: notes\nAverage marginal effects for all predictors in the interaction model. **For each predictor, you get the average change in probability for each response category.** This is the most directly interpretable summary of your model — how much does each predictor move the predicted probabilities, on average?\n\n**These are the numbers I'd highlight in a talk.** An audience can understand \"parent education reduces the probability of 'unlikely' by X percentage points\" far more easily than \"the cumulative odds ratio is 2.85.\"\n\n*Now model fit.*\n:::\n\n## Model fit\n\n-   Pseudo-$R^2$\n\n\n::: {.cell}\n\n```{.r .cell-code}\nr2_mcfadden(ols2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# R2 for Generalized Linear Regression\n       R2: 0.033\n  adj. R2: 0.030\n```\n\n\n:::\n:::\n\n\n. . .\n\n-   Not \"explained variance\" — but a ratio indicating how much better the model fits than an intercept-only model\n\n::: notes\nMcFadden's pseudo-R-squared for ordinal regression. **This is not explained variance** — don't interpret it the way you would an R-squared from OLS. It's a ratio comparing the log-likelihood of your model to the log-likelihood of an intercept-only model. Values tend to be much lower than OLS R-squared — **a McFadden's R-squared of 0.2 to 0.4 is generally considered quite good.**\n\nOur value is quite small, which means these predictors explain only a modest amount of the variation in application intentions. That's not unusual in social science — there are many unmeasured factors that influence a decision like this.\n\n*Let's check our model diagnostics.*\n:::\n\n## Model diagnostics {.smaller}\n\n-   No `easystats` functions for ordinal models :(\n\n-   `sure` package: **surrogate residuals** — based on continuous residuals\n\n    -   Check normality, linearity, homoscedasticity\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(sure)\n\nset.seed(1225)\n\ngridExtra::grid.arrange(\n  autoplot.clm(ols2, nsim = 100, what = \"qq\"),\n  autoplot.clm(ols2, nsim = 100, what = \"fitted\", alpha = 0.5),\n  ncol = 2\n)\n```\n\n::: {.cell-output-display}\n![](05-ordinal-regression-narrated-J_files/figure-revealjs/unnamed-chunk-44-1.png){fig-align='center' width=1152}\n:::\n:::\n\n\n::: callout-note\nFor multicollinearity, check correlations between predictor variables directly.\n:::\n\n::: notes\nUnfortunately, the `easystats` diagnostic functions don't work for ordinal models. **The `sure` package fills the gap with surrogate residuals** — these are simulated continuous residuals that let you do the familiar QQ plots and residual-vs-fitted plots.\n\nJ: What are surrogate residuals? They're **continuous residuals derived by mapping the ordinal outcome onto a continuous space** — essentially reverse-engineering a continuous variable from your ordinal data so that standard diagnostic tools become applicable. For the Q-Q plot: **all points falling on the line indicates normality is not violated.** For the linearity plot: the **smoothed line should be roughly flat at zero.** For the box plots checking homoscedasticity: **the boxes should be approximately overlapping.**\n\n**The QQ plot on the left checks normality of the latent variable.** If the points follow the diagonal, you're fine. **The residual-vs-fitted plot on the right checks for patterns** — you want a random scatter, not a funnel or a curve.\n\nJ: For multicollinearity, you can't use `easystats` directly with `clm` models. Instead, **inspect correlations between predictors using Spearman rank correlations**, which are more appropriate for ordinal and non-normal data than Pearson correlations. You can also compute VIFs from a regular linear model with the same predictors as a rough check.\n\n*Now let's cover the formal assumptions.*\n:::\n\n# Assumptions\n\n::: notes\n*Quick summary of what you need to check and what you don't.*\n:::\n\n## Ordinal regression assumptions\n\n-   Outcome is **ordinal** (ordered categories)\n\n-   Observations are **independent**\n\n-   **Proportional odds** (parallel slopes across cumulative splits)\n\n-   **Linearity** in the log-odds (for continuous predictors)\n\n-   ~~No normality assumptions for residuals~~\n\n-   ~~Homogeneity of variance~~\n\n::: notes\nFour assumptions to check, two to celebrate. **First, the outcome must be ordinal** — obvious, but make sure your factor levels are correctly ordered. **Second, independence** — no repeated measures or clustering without accounting for it. **Third, proportional odds** — test with Brant or a likelihood ratio test. **Fourth, linearity in the log-odds** for continuous predictors — check with the surrogate residual plots.\n\n**The two crossed-out lines are things you don't need to worry about.** No normality assumption for observed residuals, and no homoscedasticity requirement. Those are OLS problems that the ordinal model avoids.\n\n*One more thing before we wrap up — what if your data has clustering?*\n:::\n\n## Multilevel ordinal regressions\n\n-   For repeated measures or clustered/nested designs:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Use clmm() from the ordinal package\nols_multilevel <- ordinal::clmm(\n  apply ~ pared + gpa + (1 | school_id),\n  data = dat\n)\n```\n:::\n\n\n::: notes\nIf you have repeated measures — say, the same person rates multiple items on a Likert scale — or nested data — students within schools — **you need `clmm` instead of `clm`.** The syntax is just like `lmer` — you add random effects in parentheses.\n\nThis is the same extension we made from `glm` to `glmer` for multilevel logistic regression. **The ordinal package makes this seamless.**\n\nJ: The `ordinal` package provides `clmm()`, which uses the same syntax as `lme4`. **It is straightforward to scale up from `clm` to `clmm` for these more complex designs** — you just add your random effects specification and everything else stays the same.\n\n*Now let's close with reporting — how do you write this up?*\n:::\n\n::: notes\n*Everything you've done is pointless if you can't communicate it. Let's talk about writing this up.*\n:::\n\n## Sample write-up\n\n::: callout-tip\nA proportional odds model with a logit link (estimated using ML) was used to investigate factors influencing undergraduates' likelihood of applying to graduate school (\"unlikely,\" \"somewhat likely,\" \"very likely\"). The overall model fit was modest, McFadden's pseudo-$R^2$ = .03. Parent education significantly predicted application likelihood, *b* = 1.05, *z* = 3.94, *p* \\< .001, OR = 2.85, 95% CI \\[1.55, 5.28\\]. Students with college-educated parents had roughly 185% higher odds of applying. Whether students attended public or private school did not significantly predict application likelihood, *b* = −0.06, *z* = −0.20, *p* = .844, OR = 0.94. GPA was also a significant predictor, *b* = 0.62, *z* = 2.36, *p* = .018, OR = 1.85. Each one-point increase in GPA was associated with 85% higher odds of applying.\n:::\n\n::: notes\nHere's a sample write-up. **Notice the structure: name the model, report fit, then go predictor by predictor with log-odds, z-values, p-values, odds ratios, and CIs.** Each predictor gets a plain-language interpretation after the numbers.\n\n**A few things to note:** We say \"proportional odds model with a logit link\" — that tells readers exactly what we did. We report both the log-odds coefficient and the odds ratio with CI — give readers both metrics. And we translate the odds ratio into a percentage — \"185% higher odds\" is more accessible than \"OR = 2.85.\"\n\n**What's missing from this write-up that you should add?** The proportional odds test results, the sample size, the distribution across categories, and ideally the marginal effects.\n\n*Here's the full checklist.*\n:::\n\n## Reporting checklist\n\n-   Report the model type (**proportional odds / cumulative logit**) and estimation method\n\n-   Report **log-odds coefficients and odds ratios** with 95% CIs\n\n-   Report thresholds (or note they are available)\n\n-   Report a measure of model fit (**McFadden pseudo-**$R^2$)\n\n-   **Test and report** the proportional odds assumption (Brant test or LRT)\n\n-   Consider reporting **marginal effects** / predicted probabilities for each category\n\n-   Include sample size and **distribution across response categories**\n\n-   Mention diagnostics (surrogate residuals, multicollinearity)\n\n::: notes\nYour reporting checklist — keep this handy for your assignments and papers. **The items in bold are the ones that get most often forgotten.** People report the coefficients but forget to test proportional odds. They report odds ratios but not marginal effects. They don't mention the category distribution.\n\n**Compare this to the logistic regression checklist from last time** — it's very similar, with two additions: the proportional odds test and the category distribution. The model type and fit measures are analogous.\n\n*And finally, the mistakes to avoid.*\n:::\n\n## Common Mistakes {.smaller}\n\n-   **Treating ordinal data as continuous** — running OLS or t-tests on Likert scales\n\n-   Forgetting that coefficients are in **cumulative log-odds**, not probabilities\n\n-   Confusing **thresholds with slopes** — thresholds are intercepts for each cumulative split, not effects of predictors\n\n-   **Ignoring the proportional odds assumption**\n\n    -   Always test it; if it fails, consider partial proportional odds or multinomial\n\n-   Interpreting **odds ratios as probability ratios**\n\n    -   OR = 3 means 3× the *odds*, not 3× the *probability*\n\n-   **Not visualizing** predicted probabilities per category\n\n    -   Log-odds and ORs are hard to interpret; always plot `plot_predictions()`\n\n::: notes\nLet me go through these one at a time. **Number one: treating ordinal data as continuous.** This is the most common mistake in psychology. We spent the first part of today showing you exactly why it fails — don't do it.\n\n**Number two: forgetting the metric.** Your coefficients are cumulative log-odds, not probabilities. Always convert when communicating results.\n\n**Number three: confusing thresholds and slopes.** Students often look at the threshold estimates and try to interpret them as effects. They're not — they're properties of the measurement scale. The slopes are the effects.\n\n**Number four: not testing proportional odds.** Always run the Brant test. It takes one line of code.\n\n**Number five: odds ratios are not probability ratios.** OR = 3 does not mean \"three times more likely.\" It means three times the odds. These are different, especially when probabilities are far from 0.5.\n\n**Number six: not plotting.** Ordinal regression outputs are hard to interpret from numbers alone. Always make the predicted probability plots — they're what your audience will actually understand.\n\nJ: If you are using ordinal variables in your research, **you really should be using ordinal regression.** Hopefully by the end of today you'll shift your focus from metric models toward ordinal models when working with this type of data.\n\nThat's everything. **The core message: ordinal regression is logistic regression extended to more than two ordered categories, with thresholds slicing a latent continuum. The proportional odds assumption gives you one slope per predictor. Test it, visualize it, report it properly.**\n:::\n",
    "supporting": [
      "05-ordinal-regression-narrated-J_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}