{
  "hash": "27ae84c7050f43629626258a74045602",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"From Coins to Regression\"\nsubtitle: \"Bayesian Posteriors in Regression\"\nauthor: \"Suyog Chandramouli\"\ncategories: [Bayes]\ndate: '2026-04-01'\ninstitute: 'PSY504, Advanced Statistics in Psychology<br>Princeton University'\nfooter: \"PSY 504: Advanced Statistics\"\nformat:\n  revealjs:\n    theme: solarized\n    css: slide-style.css\n    transition: fade\n    multiplex: false\n    slide-number: true\n    incremental: false\n    chalkboard: true\n    fontsize: \"25pt\"\nexecute:\n  freeze: auto\n  echo: true\n  message: false\n  warning: false\n  fig-align: center\n  fig-width: 12\n  fig-height: 8\n  code-overflow: wrap\neditor:\n  markdown:\n    wrap: sentence\n---\n\n## From coins to regression\n\nLast time we focused on coins — one parameter, $\\theta$. Each posterior draw was a single number.\n\nIn regression, each draw is a full set of parameters: $\\beta_0$, $\\beta_1$, and $\\sigma$. What changes?\n\n. . .\n\n|   | Coin | Regression |\n|---|------|-----------|\n| Model | $Y \\sim \\text{Binomial}(n, \\theta)$ | $Y \\sim \\text{Normal}(\\mu_i, \\sigma)$ |\n| Parameters | $\\theta$ | $\\beta_0, \\beta_1, \\sigma$ |\n| Draws | 4,000 values of $\\theta$ | 4,000 sets of $(\\beta_0, \\beta_1, \\sigma)$ |\n\n. . .\n\nMore parameters, but the recipe is the same — except that grid approximation no longer scales (1,000$^3$ = 1 billion cells), so we rely on MCMC.\n\n::: {.notes}\nWalk through the table row by row. \"In the coins lab, your model was Binomial. Your parameter was theta. Your draws were values of theta. Today, your model is Normal — standard linear regression. Your parameters are beta_0, beta_1, and sigma. Your draws will be 4,000 triplets.\" The number dropped from 12,000 to 4,000 because brms defaults to 4 chains x 1000 post-warmup = 4,000 draws. They computed the grid-scaling problem in coins lab Section 8.\n:::\n\n\n## Each draw is a full equation\n\nWith coins, each draw was one number ($\\theta$). With regression, each draw is a complete set of parameters:\n\n| Draw | $\\beta_0$ | $\\beta_1$ | $\\sigma$ |\n|------|-----------|-----------|----------|\n| 1    | 32.8      | 0.0041    | 2.85     |\n| 2    | 31.5      | 0.0044    | 2.97     |\n| 3    | 33.1      | 0.0039    | 2.88     |\n\n. . .\n\nEach row is a complete regression equation: $\\hat{y}_i = \\beta_0 + \\beta_1 x_i$\n\n. . .\n\n4,000 draws = 4,000 regression lines.\n\n::: {.notes}\nThis is the core conceptual shift. With coins, each draw was a single number you could histogram. With regression, each draw defines a line. Walk through: \"Draw 1 says intercept is 32.8, slope is 0.0041, sigma is 2.85. That's one regression line. Draw 2 says slightly different values — a different line.\"\n\nEach draw also includes sigma. A future lab will use sigma to simulate data from the posterior predictive distribution. For now, the focus is the lines defined by beta_0 and beta_1.\n\nIn the lab, students run as_draws_df(fit1.b), see columns b_Intercept, b_body_mass_g, and sigma, rename them, then compute y_hat = beta0 + beta1 * x. That produces a histogram of predictions at one x-value. The spaghetti plot extends this across the full range of x.\n:::\n\n\n## Spaghetti plots\n\n::::: columns\n::: {.column width=\"50%\"}\n\nOne draw from the posterior = one regression line.\n\nStack many of them = a fuzzy bundle, dense where the posterior is concentrated, sparse where uncertain.\n\nColor-code by intercept ($\\beta_0$): **lower intercepts pair with steeper slopes**.\n\nAll lines pass through the data cloud, so if a line starts lower it must rise more steeply.\n\n$\\beta_0$ and $\\beta_1$ are **negatively correlated** in the posterior.\n\n:::\n\n::: {.column width=\"50%\"}\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](Bayes_2_2026_Lecture_short_files/figure-revealjs/unnamed-chunk-1-1.png){width=480}\n:::\n:::\n\n\n:::\n:::::\n\n::: {.notes}\nDraw this on the chalkboard if you can. Sketch a scatter plot, draw one line, say \"that's draw 1.\" Draw another with a different intercept/slope — \"that's draw 2.\" Then: \"Now imagine 4,000 of these.\"\n\nStudents often think of \"the regression line\" as one fixed thing. The Bayesian perspective: there's a distribution over lines.\n\nFor the color-coded version: sketch two lines through the same data — one with low intercept and steep slope, one with high intercept and shallow slope. Both pass through the cloud, which is why the correlation exists. The lab uses scale_color_viridis_c to show this gradient. Lines fan out like a hand of cards, all anchored near the data centroid.\n\nOLS parameters have the same correlation (the lab shows vcov(fit1.ols) next to vcov(fit1.b) — nearly identical). In Bayes you can *see* it in the draws.\n:::\n\n\n# Joint vs. marginal distributions {.center}\n\n## Marginal distributions\n\nIn the coins lab, the posterior was one-dimensional: just $p(\\theta \\mid \\text{data})$.\n\n. . .\n\nIn regression, each parameter has its own **marginal** posterior:\n\n- $p(\\beta_0 \\mid \\text{data})$\n- $p(\\beta_1 \\mid \\text{data})$\n- $p(\\sigma \\mid \\text{data})$\n\n. . .\n\n\"Marginal\" = looking at one parameter at a time, collapsing over the others.\n\nThese are the histograms you'll make in the lab.\n\n::: {.notes}\nConnect \"marginal\" to something they know: \"If you have a joint distribution of X and Y, the marginal of X is what you get when you integrate over all values of Y.\" In practice, making a histogram of just the beta_0 column IS computing the marginal — you're ignoring beta_1 and sigma.\n\nWith coins, the posterior WAS marginal by default — only one parameter. Now with three, the full posterior lives in 3D. A histogram of beta_0 is a 1D slice.\n\nLab Question 2.1 asks: \"What is the term for the distributions on the diagonal of the pairs() plot? And the off-diagonal?\" Having heard \"marginal\" and \"joint\" here, they'll be ready.\n:::\n\n## Joint distributions\n\nThe parameters don't vary independently.\n\nThe **joint** posterior captures how they move *together*:\n\n$$p(\\beta_0, \\beta_1, \\sigma \\mid \\text{data})$$\n\n. . .\n\nVisualize the joint for two parameters as a scatter plot — each point is one draw.\n\n. . .\n\nCircle = independent. Tilted ellipse = correlated.\n\n::: {.notes}\n\"We can't visualize 3D easily, but we can look at 2D slices: beta_0 vs beta_1, beta_0 vs sigma, beta_1 vs sigma.\" Draw a 2D scatter on the board: x-axis is beta_0, y-axis is beta_1, each dot is one draw. \"If dots form a circle, parameters are independent. A tilted ellipse means correlated.\" That's exactly what the pairs() plot shows.\n:::\n\n## The `pairs()` plot\n\n```r\npairs(fit1.b)\n```\n\n**Diagonal:** marginal distributions (one parameter at a time)\n\n**Off-diagonal:** joint distributions (two parameters together)\n\n. . .\n\nYou'll see a tight ellipse between $\\beta_0$ and $\\beta_1$, tilted from upper-left to lower-right.\n\nThat tilt = the negative correlation from the spaghetti plot.\n\n::: {.notes}\nThe pairs() plot is a standard Bayesian diagnostic: (1) marginal posteriors on the diagonal, (2) parameter correlations off-diagonal. The off-diagonal scatter plots shade different chains differently (half above, half below diagonal) — students don't need to worry about that detail. The key is the cloud shape.\n\nFor beta_0 vs beta_1: tight tilted ellipse (strong negative correlation). For beta_0 vs sigma and beta_1 vs sigma: rounder clouds (weaker correlation).\n:::\n\n\n## Why marginals alone can mislead\n\n::::: columns\n::: {.column width=\"55%\"}\n\n$\\beta_0 = 35$ is plausible. $\\beta_1 = 0.005$ is plausible.\n\nBut $\\beta_0 = 35$ **and** $\\beta_1 = 0.005$ together? The joint posterior may assign that combination very low probability.\n\nYou never see a line that starts high **and** rises steeply.\n\n`vcov(fit1.b, correlation = TRUE)` quantifies the correlation.\n\n:::\n\n::: {.column width=\"45%\"}\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](Bayes_2_2026_Lecture_short_files/figure-revealjs/unnamed-chunk-2-1.png){width=480}\n:::\n:::\n\n\n:::\n:::::\n\n::: {.notes}\nAn analogy: \"Being 6 feet tall is common. Wearing size 12 shoes is common. Being 6 feet tall AND wearing size 5 shoes? Very rare — even though each is individually plausible.\" The logic is the same for beta_0 and beta_1: high intercept + steep slope would overshoot every data point.\n\nThe vcov() function returns the variance-covariance matrix. The lab shows both vcov(fit1.b) and vcov(fit1.ols) side by side — nearly identical. Parameter correlations are not Bayes-specific. The lab also converts covariances to correlations using the formula, and shows the shortcut vcov(fit1.b, correlation = TRUE).\n:::\n\n\n## Sigma skew and summarizing posteriors\n\n::::: columns\n::: {.column width=\"55%\"}\n\n$\\sigma$ must be positive, so its posterior is **right-skewed**.\n\n. . .\n\nWhen skewed, mean, median, and mode diverge:\n\n- **Mean** — pulled toward tail (brms default)\n- **Median** — more robust (Gelman)\n- **Mode** — the peak (Kruschke)\n\n. . .\n\n`robust = TRUE` switches brms to median + MAD SD.\n\n:::\n\n::: {.column width=\"45%\"}\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](Bayes_2_2026_Lecture_short_files/figure-revealjs/unnamed-chunk-3-1.png){width=480}\n:::\n:::\n\n\n:::\n:::::\n\n::: {.notes}\nThis prepares students for lab Questions 2.3 and 2.4. \"Sigma is the residual SD. It must be positive — can't be zero (perfect prediction), unlikely to be huge. The posterior is squeezed between a hard floor at zero and a soft ceiling set by the data. That compression creates right skew.\"\n\nConnect to their experience: the sampling distribution of s is also right-skewed for small samples, for the same reason.\n\nThe plot shows mean (red) pulled toward the tail and median (green) closer to the bulk. In the lab, they'll see mode too (at the peak, left of both), overlaid as vertical lines on the real posterior draws.\n\nAbout MAD SD: it's the spread analog of the median. The lab walks through the formula step by step: (1) find the median of draws, (2) compute absolute distance of each draw from median, (3) take the median of those distances, (4) multiply by 1.4826. The constant makes MAD SD = SD for a normal distribution. For most students, the takeaway is just: \"robust = TRUE gives median + MAD SD. Use it when the posterior is skewed.\"\n\nPractical point: for beta_0 and beta_1 (symmetric posteriors), mean vs median barely differs. For sigma, the choice can matter. In the lab plot, the three vertical lines sit on top of each other for the betas but visibly separate for sigma.\n:::\n\n## The lab\n\n**Part 1:** Fit `lm()` and `brm()` on Chinstrap penguins, compare output\n\n**Part 2:** Extract draws, `pairs()` plot, spaghetti plots, parameter summaries\n\n**Exercise:** Redo it all with Gentoo penguins\n\n::: {.notes}\nPractical notes before releasing them:\n\n1. brm() takes ~30-60 seconds to compile and sample. \"Compiling Stan model\" in the console is normal.\n\n2. The lab has conceptual questions (1.1-1.3, 2.1-2.5). They should pause and answer these — not just run code. Question 2.5 is particularly important: \"We have done all this without yet specifying a prior. What do you think is going on?\" This sets up the next lab on priors.\n\n3. The exercises ask them to redo with Gentoo penguins — that's where learning consolidates. Encourage trying before looking at chinstrap code.\n\n4. Required packages: palmerpenguins, tidyverse, brms, ggside, broom, broom.mixed, ggdist, tidybayes. brms needs a C++ compiler (rstan dependency) — pair anyone with install issues.\n\n5. If students finish early: try adding flipper_length_mm as a second predictor and see how pairs() changes.\n:::\n",
    "supporting": [
      "Bayes_2_2026_Lecture_short_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}