{
  "hash": "e600319d259e2f4ca874d3dddd5ab1c6",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"I Don't Likert You: Ordinal Regression\"\nsubtitle: \"Princeton University\"\nauthor: \"Suyog Chandramouli\"\ndate: '2026-02-21'\ncategories: [GLM]\nfooter: \"PSY 504: Advanced Statistics\"\nformat: \n  revealjs:\n    theme: solarized\n    css: slide-style.css \n    transition: fade\n    slide-number: true\n    incremental: false \n    chalkboard: true\n    fontsize: \"25pt\"\nwebr:\n  packages: [\"tidyverse\", \"easystats\", \"broom\", \"knitr\", \"emmeans\", \"ordinal\", \"ggeffects\", \"marginaleffects\"]\nfilters:\n  - webr\nexecute:\n  freeze: auto\n  echo: true\n  message: false\n  warning: false \n  fig-align: center\n  fig-width: 12\n  fig-height: 8\n  editor_options: \n  chunk_output_type: inline\n  code-overflow: wrap\n  html:\n    code-fold: true\n    code-tools: true\n---\n\n## Packages\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(easystats)\nlibrary(marginaleffects)\nlibrary(effects)\nlibrary(ordinal)\nlibrary(ggeffects)\nlibrary(emmeans)\nlibrary(car)\nlibrary(knitr)\nlibrary(patchwork)\nlibrary(MASS)\nlibrary(broom)\nlibrary(modelsummary)\n\noptions(scipen = 999)\n```\n:::\n\n\n-   Access the .qmd document here: <https://github.com/suyoghc/PSY504_Spring_2026/tree/main/posts>\n\n\n## Announcements\n\n## Today\n\n::::: columns\n::: {.column width=\"50%\"}\n-   From logistic to ordinal\n\n-   Motivating simulation: Loaded dice\n\n    -   Why not just use OLS?\n    -   The latent variable idea\n    -   Cumulative logit link\n    -   Thresholds and slopes\n:::\n\n::: {.column width=\"50%\"}\n-   Application: Graduate school\n\n    -   Model fitting\n    -   Parameter interpretation\n    -   Proportional odds assumption\n    -   Model comparisons\n    -   Visualizing\n    -   Reporting\n:::\n:::::\n\n\n## Last time: Logistic regression\n\n-   Binary outcomes: 0 or 1\n\n-   We modeled P(Y = 1) using the logit link\n\n$$\\text{logit}(p) = \\log\\frac{p}{1-p} = \\beta_0 + \\beta_1 X$$\n\n-   The logit mapped probabilities $(0, 1)$ → log-odds $(-\\infty, +\\infty)$, allowing a linear model\n\n. . .\n\n::: callout-note\nToday we extend this idea. What happens when your outcome has **more than two** ordered categories?\n:::\n\n\n## Ordinal Response Variables\n\n-   In psychology many variables have a natural ordering\n\n    -   Grades (e.g., A, B, C)\n    -   Education level (e.g., BA, MS, PhD)\n    -   Competitions (e.g., 1st, 2nd, 3rd)\n    -   Economic status (e.g., wealthy, middle class, poor)\n\n-   Most common are Likert scale (\"Lick-ert\") items\n\n\n## This is a cat, not a dog?\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](images/Idli.JPG){fig-align='center' width=50%}\n:::\n:::\n\n\n1.  Very likely to be a cat\n2.  Somewhat likely to be a cat\n3.  As likely to be cat or dog\n4.  Somewhat likely to be a dog\n5.  Very likely to be a dog\n\n\n## Methods for analysis\n\n-   **Metric models** (e.g., t-test, OLS)\n    -   Overestimate information in data; common & \"simple\"\n-   **Nonparametric** (e.g., signed ranks)\n    -   Underestimate information; don't scale well\n-   **Ordinal models** ← today\n    -   Treat outcomes appropriately as ordered categories\n\n\n## \"What could possibly go wrong?\" {.smaller}\n\nLiddell and Kruschke (2018) surveyed 68 Psychology articles and found that **every** article used metric models on ordinal data.\n\n. . .\n\nThree main problems:\n\n-   Response categories may not be (psychologically) **equidistant**\n\n-   Responses can be **non-normally distributed**\n\n-   Differences in **variances** of the underlying variable are treated inappropriately\n\n. . .\n\n::: callout-warning\nUsing metric models on ordinal data can lead to false alarms, failures to detect true effects, distorted effect sizes, and even inversions of effects.\n:::\n\n\n# Under the Hood: The Loaded Dice\n\n\n## The Loaded Dice {.center}\n\nEasier to understand ordinal regression if we **simulate it from scratch** and watch the steps unfold.\n\nJust like our weighted coins helped us understand logistic regression.\n\n\n## Simulation with a Data Generating Process {.smaller}\n\n6 dice. 30 rolls each.\n\nEach die has a lead weight. More lead → the die tends to produce higher scores on a continuous latent \"quality\" scale.\n\nWe then **bin** these latent scores into three ordered categories: **Low**, **Medium**, **High**.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(504)\n\n# --- DATA GENERATING PROCESS ---\n# Lead weight determines each die's latent mean\ndice <- tibble(\n  die         = 1:6,\n  lead_weight = 1:6,\n  latent_mean = c(-1.5, -0.5, 0, 0.5, 1.0, 2.0)\n)\n\n# TRUE thresholds (students will try to recover these)\ntau1 <- -0.5   # boundary between Low and Medium\ntau2 <-  1.0   # boundary between Medium and High\n\n# Roll each die 30 times → continuous latent score → categorize\nrolls <- dice %>%\n  rowwise() %>%\n  mutate(latent = list(rnorm(30, mean = latent_mean, sd = 1))) %>%\n  unnest(latent) %>%\n  ungroup() %>%\n  group_by(die) %>%\n  mutate(roll = row_number()) %>%\n  ungroup() %>%\n  mutate(\n    category = case_when(\n      latent <= tau1 ~ \"Low\",\n      latent <= tau2 ~ \"Medium\",\n      TRUE           ~ \"High\"\n    ),\n    category = ordered(category, levels = c(\"Low\", \"Medium\", \"High\"))\n  )\n```\n:::\n\n\n\n## The truth you normally never see {.smaller}\n\nEach point is a roll. The **dashed lines** are the true thresholds. Color = the category it falls into.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](ordinal-regression-lecture_files/figure-revealjs/unnamed-chunk-4-1.png){width=1056}\n:::\n:::\n\n\n. . .\n\n::: callout-important\nIn real life, you **never see this plot**. You only see the colors — the categories. The y-axis is hidden from you. Ordinal regression's job is to recover the thresholds and the effect of lead weight **using only the categories**.\n:::\n\n\n## What you actually observe\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](ordinal-regression-lecture_files/figure-revealjs/unnamed-chunk-5-1.png){width=1056}\n:::\n:::\n\n\n. . .\n\nMore weight → more \"High\" and fewer \"Low.\" The pattern is clear. How do we model it?\n\n\n## RM: From counts to cumulative log-odds {.smaller}\n\nBefore we model anything, let's do the arithmetic ourselves. Pick the **3-gram die** (30 rolls):\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndie3 <- rolls %>% filter(lead_weight == 3)\n\n# Step 1: Category counts and proportions\ndie3_counts <- die3 %>%\n  count(category) %>%\n  mutate(\n    prop         = n / sum(n),\n    cum_prop     = cumsum(prop),\n    cum_odds     = cum_prop / (1 - cum_prop),\n    log_cum_odds = log(cum_odds)\n  )\n\nkable(die3_counts, digits = 3)\n```\n\n::: {.cell-output-display}\n\n\n|category |  n| prop| cum_prop| cum_odds| log_cum_odds|\n|:--------|--:|----:|--------:|--------:|------------:|\n|Low      | 12|  0.4|      0.4|    0.667|       -0.405|\n|Medium   | 15|  0.5|      0.9|    9.000|        2.197|\n|High     |  3|  0.1|      1.0|      Inf|          Inf|\n\n\n:::\n:::\n\n\n. . .\n\n::: callout-tip\n## 🔗 Connection to the model\n\nThose log-cumulative-odds you just computed? **They're exactly what the model's thresholds estimate** when there's no predictor. You just did ordinal regression by hand.\n:::\n\n```{webr-r}\n# Try it yourself: pick a different die (change the number) and repeat\nmy_die <- rolls %>% filter(lead_weight == 5)\n\nmy_die %>%\n  count(category) %>%\n  mutate(\n    prop = n / sum(n),\n    cum_prop = cumsum(prop),\n    cum_odds = cum_prop / (1 - cum_prop),\n    log_cum_odds = log(cum_odds)\n  )\n```\n\n\n## What if we just use OLS? {.smaller}\n\nCode the categories as numbers (Low = 1, Medium = 2, High = 3) and fit a linear regression.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrolls_numeric <- rolls %>%\n  mutate(y_numeric = as.numeric(category))\n\nols_bad <- lm(y_numeric ~ lead_weight, data = rolls_numeric)\n\nggplot(rolls_numeric, aes(x = lead_weight, y = y_numeric)) +\n  geom_jitter(aes(color = category), width = 0.15, height = 0.1, alpha = 0.4, size = 2) +\n  geom_smooth(method = \"lm\", se = TRUE, color = \"red\", linewidth = 1.2, fullrange = TRUE) +\n  scale_color_manual(values = c(\"Low\" = color_low, \"Medium\" = color_med, \"High\" = color_high),\n                     guide = \"none\") +\n  scale_x_continuous(limits = c(-1, 9)) +\n  scale_y_continuous(breaks = 1:3, labels = c(\"Low\", \"Medium\", \"High\")) +\n  geom_hline(yintercept = c(0.5, 3.5), linetype = \"dashed\", color = \"grey50\") +\n  annotate(\"text\", x = 8, y = 3.4, label = \"Impossible!\", color = \"red\", size = 5) +\n  annotate(\"text\", x = -0.5, y = 0.6, label = \"Impossible!\", color = \"red\", size = 5) +\n  labs(x = \"Lead weight (grams)\", y = \"Response\",\n       title = \"OLS on ordinal data: looks fine, isn't\") +\n  theme_lucid(base_size = 16)\n```\n\n::: {.cell-output-display}\n![](ordinal-regression-lecture_files/figure-revealjs/unnamed-chunk-7-1.png){width=960}\n:::\n:::\n\n\n\n## Thresholds matter — OLS can't see them {.smaller}\n\nSame latent scores, **two different threshold placements**. OLS treats both identically.\n\n::: panel-tabset\n## Observed distributions\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](ordinal-regression-lecture_files/figure-revealjs/unnamed-chunk-8-1.png){width=1152}\n:::\n:::\n\n\n## OLS on both\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](ordinal-regression-lecture_files/figure-revealjs/unnamed-chunk-9-1.png){width=1152}\n:::\n:::\n\n\n## Ordinal model recovers both\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Ordinal model on original thresholds\nfit_orig <- clm(category ~ lead_weight, data = rolls, link = \"logit\")\n\n# Ordinal model on squeezed thresholds\nfit_alt <- clm(category_alt ~ lead_weight, data = rolls_alt, link = \"logit\")\n\nbind_rows(\n  tibble(thresholds = \"Original (−0.5, 1.0)\", term = names(coef(fit_orig)), estimate = coef(fit_orig)),\n  tibble(thresholds = \"Squeezed (0.0, 0.5)\",  term = names(coef(fit_alt)),  estimate = coef(fit_alt))\n) %>%\n  kable(digits = 3)\n```\n\n::: {.cell-output-display}\n\n\n|thresholds           |term             | estimate|\n|:--------------------|:----------------|--------:|\n|Original (−0.5, 1.0) |Low&#124;Medium  |    2.266|\n|Original (−0.5, 1.0) |Medium&#124;High |    4.941|\n|Original (−0.5, 1.0) |lead_weight      |    1.052|\n|Squeezed (0.0, 0.5)  |Low&#124;Medium  |    3.625|\n|Squeezed (0.0, 0.5)  |Medium&#124;High |    4.470|\n|Squeezed (0.0, 0.5)  |lead_weight      |    1.216|\n\n\n:::\n:::\n\n:::\n\n::: callout-important\n## The point\n\nThe distributions look completely different. OLS gives nearly the same answer for both. The ordinal model **recovers the different thresholds** — it knows the measurement scales differ.\n:::\n\n\n## Problems with the \"treat it as numeric\" approach\n\n::: callout-warning\n## Three things went wrong\n\n1.  **Assumes equal spacing** — is the jump from Low → Medium the same as Medium → High? We don't know, but OLS assumes it is.\n\n2.  **Predicts impossible values** — the line escapes the range of the data.\n\n3.  **Wrong distributional assumptions** — residuals are not normal, variance is not constant.\n:::\n\n. . .\n\nWe need a model that respects the **ordered** nature of the outcome without assuming it's metric.\n\n\n# Cumulative Logit Model\n\n\n## The key idea: Cumulative splits {.smaller}\n\nWith **binary** logistic regression, we modeled one split:\n\n$$\\text{logit}(P(Y = 1)) = \\beta_0 + \\beta_1 X$$\n\n. . .\n\nWith **ordinal** regression, we model **multiple cumulative splits**:\n\n-   Split 1: P(Low) vs. P(Medium or High)\n-   Split 2: P(Low or Medium) vs. P(High)\n\n. . .\n\nEach split is its own logistic regression — but they all share the **same slope**.\n\n::: callout-note\n## 🔗 The connection\n\nWith 2 categories, ordinal regression **is** logistic regression. There's 1 threshold, 1 slope.\n\nWith K categories, you get **K − 1 thresholds** but still just **1 slope** per predictor. Think of it as running K − 1 logistic regressions simultaneously, forced to have the same slope.\n:::\n\n\n## The latent variable interpretation\n\n::::: columns\n::: {.column width=\"50%\"}\n-   There is a continuous latent variable $\\tilde{Y}$ (the \"true score\") that gets categorized into bins by **thresholds**: $\\tau_1, \\tau_2, \\dots, \\tau_{K-1}$\n\n-   In our dice simulation:\n    -   $\\tilde{Y}$ = the latent score\n    -   $\\tau_1 = -0.5$, $\\tau_2 = 1.0$\n    -   Categories = Low, Medium, High\n:::\n\n::: {.column width=\"50%\"}\n![](images/ordimage.jpeg){fig-align=\"center\"}\n:::\n:::::\n\n\n## Ordered = Cumulative\n\n::::: columns\n::: {.column width=\"50%\"}\n-   We use the **cumulative distribution** to model ordered categories\n\n-   Cumulative probability: $P(Y \\leq k)$\n\n    -   Preserves the natural ordering\n    -   Always increasing: $P(Y \\leq 1) \\leq P(Y \\leq 2) \\leq \\dots$\n:::\n\n::: {.column width=\"50%\"}\n<br>\n\n![Richard McElreath](images/cum_ord.jpg){fig-alt=\"Statistical Rethinking\" fig-align=\"center\" width=\"1088\"}\n:::\n:::::\n\n\n## Generalized linear model {.smaller}\n\nYou saw this in the logistic regression lecture. Same skeleton — three components:\n\n$$\\begin{align*}\n  Y_i & \\sim \\mathrm{Dist}(\\mu_i, \\tau) & \\quad & \\text{← Random component} \\\\\n  g(\\mu_i) & = \\eta_i & \\quad & \\text{← Link function} \\\\\n  \\eta_i & = \\beta_0 + \\beta_1 X_{1i} + \\beta_2 X_{2i} + \\ldots & \\quad & \\text{← Linear predictor}\n\\end{align*}$$\n\n. . .\n\nLast time we filled in: **Bernoulli** distribution, **logit** link, linear predictor with one intercept and slopes.\n\n. . .\n\n**What changes for ordinal data?**\n\n\n## Ordinal regression: Filling in the GLM {.smaller}\n\n$$\\begin{align*}\n  Y_i & \\sim \\color{#d63031}{\\mathrm{Cumulative}}(\\pi_1, \\ldots, \\pi_K) & \\quad & \\color{#d63031}{\\text{← Ordinal outcome (K ordered categories)}} \\\\[8pt]\n  \\color{#2d3436}{g(\\mu_i)} & = \\color{#0984e3}{\\mathrm{logit}} & \\quad & \\color{#0984e3}{\\text{← Same link as logistic regression}} \\\\[8pt]\n  \\eta_i & = \\color{#00b894}{\\alpha_k - (\\beta_1 X_{1i} + \\beta_2 X_{2i} + \\ldots)} & \\quad & \\color{#00b894}{\\text{← Thresholds + slopes}}\n\\end{align*}$$\n\n. . .\n\n::::: columns\n::: {.column width=\"33%\"}\n[**Distribution**]{style=\"color: #d63031; font-size: 1.1em;\"}\n\nModels cumulative probability $P(Y \\leq k)$ — preserves the ordering\n:::\n::: {.column width=\"33%\"}\n[**Link**]{style=\"color: #0984e3; font-size: 1.1em;\"}\n\nLogit — identical to logistic regression. Nothing new here.\n:::\n::: {.column width=\"33%\"}\n[**Linear predictor**]{style=\"color: #00b894; font-size: 1.1em;\"}\n\n$K-1$ thresholds $\\alpha_k$ (one per split) + shared slopes $\\beta$ (proportional odds)\n:::\n:::::\n\n\n## Cumulative logit model (notation) {.smaller}\n\n| Symbol        | Meaning                                                |\n|---------------|--------------------------------------------------------|\n| $P_k$         | Probability of being in category k                     |\n| $C_{pk}$      | Cumulative probability of being in category k or lower |\n| 1 − $C_{pk}$  | Probability of being above category k                  |\n\n$$\\textrm{Cumulative Odds} = \\frac{P(Y \\leq k)}{P(Y > k)} = \\frac{C_{pk}}{1-C_{pk}}$$\n\n. . .\n\nTake the log to get the **cumulative logit**:\n\n$$\\log\\left(\\frac{C_{pk}}{1-C_{pk}}\\right)$$\n\n. . .\n\n::: callout-note\n## 🏷️ Jargon Alert\n\nCumulative logit = cumulative log-odds = the same logit link you already know, just applied to *cumulative* probabilities.\n:::\n\n\n## Cumulative logit model\n\n![Richard McElreath](images/cum_logodds.jpg){fig-align=\"center\"}\n\n\n## Cumulative logit model\n\n![Richard McElreath](images/cut.jpg){fig-align=\"center\"}\n\n\n## Cumulative logit model\n\n![Richard McElreath](images/cut_outcomes.jpg)\n\n\n## The model equation {.smaller}\n\n$$\\log \\left(\\frac{P(Y \\leq k)}{P(Y > k)}\\right) = \\alpha_k - \\beta X$$\n\n$$\\begin{array}{rcl} L_1 &=& \\alpha_1 - \\beta_1 x_1 - \\cdots - \\beta_p X_p\\\\ L_2 &=& \\alpha_2 - \\beta_1 x_1 - \\cdots - \\beta_p X_p \\\\ L_{J-1} &=& \\alpha_{J-1} - \\beta_1 x_1 - \\cdots - \\beta_p X_p \\end{array}$$\n\n-   We estimate **J − 1 equations** simultaneously\n\n-   Each equation has a **different intercept** $\\alpha_k$ (the thresholds/cut points)\n\n-   But a **common slope** $\\beta$ ← this is the proportional odds assumption\n\n-   Intercepts are always ordered: $\\alpha_1 < \\alpha_2 < \\dots$\n\n\n## What do the pieces mean?\n\n-   $\\alpha_k$ (thresholds/intercepts/cut-offs):\n\n    -   Log-odds of falling **at or below** category $k$ when all predictors = 0\n    -   These are the ordinal equivalent of $\\beta_0$ in logistic regression\n\n-   $\\beta$ (slopes):\n\n    -   Effect of the predictor on the log-odds of being in a **higher** category\n    -   Shared across all cumulative splits\n\n-   The $-$ sign:\n\n    -   Convention so that a **positive** $\\beta$ means higher X → higher category\n\n\nThresholds are where the latent variable gets **cut** into categories.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](ordinal-regression-lecture_files/figure-revealjs/unnamed-chunk-11-1.png){width=1152}\n:::\n:::\n\n\n. . .\n\nClose thresholds → few people land in the middle category. Far-apart thresholds → the middle category captures a wide range.\n\n\n## What the slope does {.smaller}\n\nThe slope $\\beta$ shifts the **entire latent distribution** along the x-axis — the thresholds stay put.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](ordinal-regression-lecture_files/figure-revealjs/unnamed-chunk-12-1.png){width=1152}\n:::\n:::\n\n\n. . .\n\nA positive $\\beta$ shifts the distribution **right**, increasing P(higher categories). The thresholds $\\alpha_k$ don't move — they're properties of the response scale, not the predictor.\n\n\n## Parametrization note {.smaller}\n\n::::: columns\n::: {.column width=\"50%\"}\n-   With **subtraction** convention ($\\alpha_k - \\beta X$):\n\n    -   Positive $\\beta$ → higher probability of being in **higher** categories\n\n![](images/neg_coef2.jpg){fig-align=\"center\"}\n:::\n\n::: {.column width=\"50%\"}\n-   With **addition** convention ($\\alpha_k + \\beta X$):\n\n    -   Positive $\\beta$ → higher probability of being in **lower** categories\n\n![](images/neg_coef.jpg){fig-align=\"center\"}\n:::\n:::::\n\n. . .\n\n::: callout-tip\n`ordinal::clm()` uses **subtraction** by default (positive = higher). `MASS::polr()` also uses subtraction. Just check the documentation for whatever package you use.\n:::\n\n\n## RM: The intercept-only model {.smaller}\n\nBefore adding predictors, fit a model with **no predictor at all** — just the thresholds.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Intercept-only model: just thresholds, no slope\ndice_null <- clm(category ~ 1, data = rolls, link = \"logit\")\n\nbroom::tidy(dice_null) %>%\n  kable(digits = 3)\n```\n\n::: {.cell-output-display}\n\n\n|term             | estimate| std.error| statistic| p.value|coef.type |\n|:----------------|--------:|---------:|---------:|-------:|:---------|\n|Low&#124;Medium  |   -0.847|     0.163|    -5.209|       0|intercept |\n|Medium&#124;High |    0.744|     0.159|     4.662|       0|intercept |\n\n\n:::\n:::\n\n\n. . .\n\n::: callout-note\n## 🔗 Recognize these?\n\nThese threshold estimates are the **log-cumulative-odds pooled across all six dice** — the same quantity you just computed by hand, but now averaged over the whole dataset. When we add `lead_weight` as a predictor next, watch how the thresholds and model fit change.\n:::\n\n\n## Fitting our dice data {.smaller}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ordinal)\n\n# Fit the ordinal model\ndice_fit <- clm(category ~ lead_weight, data = rolls, link = \"logit\")\n\nsummary(dice_fit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nformula: category ~ lead_weight\ndata:    rolls\n\n link  threshold nobs logLik  AIC    niter max.grad cond.H \n logit flexible  180  -142.92 291.84 5(0)  1.02e-07 2.7e+02\n\nCoefficients:\n            Estimate Std. Error z value            Pr(>|z|)    \nlead_weight   1.0517     0.1215   8.653 <0.0000000000000002 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nThreshold coefficients:\n            Estimate Std. Error z value\nLow|Medium    2.2662     0.3863   5.866\nMedium|High   4.9409     0.5507   8.973\n```\n\n\n:::\n:::\n\n\n\n## Interpreting the output {.smaller}\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|term             | estimate| std.error| statistic| p.value| conf.low| conf.high|coef.type |\n|:----------------|--------:|---------:|---------:|-------:|--------:|---------:|:---------|\n|Low&#124;Medium  |    2.266|     0.386|     5.866|       0|       NA|        NA|intercept |\n|Medium&#124;High |    4.941|     0.551|     8.973|       0|       NA|        NA|intercept |\n|lead_weight      |    1.052|     0.122|     8.653|       0|    0.824|     1.302|location  |\n\n\n:::\n:::\n\n\n. . .\n\n**Two parts:**\n\n-   **Thresholds** (intercepts for each cumulative split)\n\n    -   `Low|Medium`: log-odds of $Y \\leq$ Low when lead_weight = 0\n    -   `Medium|High`: log-odds of $Y \\leq$ Medium when lead_weight = 0\n\n-   **Slope** (shared across splits)\n\n    -   `lead_weight`: effect on log-odds of being in a higher category\n\n. . .\n\n::: callout-tip\n## Can we recover the truth?\n\nTrue thresholds: $\\tau_1$ = -0.5, $\\tau_2$ = 1. Compare to the estimated thresholds above. True slope of the latent mean was roughly 0.7 per gram. How close did we get?\n:::\n\n\n## From log-odds to odds ratios\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Exponentiate to get cumulative odds ratios\nbroom::tidy(dice_fit, exponentiate = TRUE, conf.int = TRUE) %>%\n  filter(coef.type == \"location\") %>%\n  kable(digits = 3)\n```\n\n::: {.cell-output-display}\n\n\n|term        | estimate| std.error| statistic| p.value| conf.low| conf.high|coef.type |\n|:-----------|--------:|---------:|---------:|-------:|--------:|---------:|:---------|\n|lead_weight |    2.863|     0.122|     8.653|       0|     2.28|     3.677|location  |\n\n\n:::\n:::\n\n\n. . .\n\n-   Interpretation: Each additional gram of lead **multiplies** the odds of being in a higher category by the OR\n\n\n## From log-odds to probabilities\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Predicted probabilities for each die\npredictions(dice_fit, newdata = datagrid(lead_weight = 1:6)) %>%\n  kable(digits = 3)\n```\n\n::: {.cell-output-display}\n\n\n| rowid|group  | estimate| std.error| statistic| p.value| s.value| conf.low| conf.high| lead_weight|category |\n|-----:|:------|--------:|---------:|---------:|-------:|-------:|--------:|---------:|-----------:|:--------|\n|     1|Low    |    0.771|     0.051|    15.098|   0.000| 168.680|    0.671|     0.871|           1|Low      |\n|     2|Low    |    0.541|     0.054|     9.962|   0.000|  75.249|    0.434|     0.647|           2|Low      |\n|     3|Low    |    0.291|     0.042|     6.943|   0.000|  37.921|    0.209|     0.374|           3|Low      |\n|     4|Low    |    0.126|     0.028|     4.506|   0.000|  17.206|    0.071|     0.180|           4|Low      |\n|     5|Low    |    0.048|     0.016|     3.069|   0.002|   8.864|    0.017|     0.078|           5|Low      |\n|     6|Low    |    0.017|     0.008|     2.279|   0.023|   5.465|    0.002|     0.032|           6|Low      |\n|     1|Medium |    0.209|     0.045|     4.604|   0.000|  17.878|    0.120|     0.298|           1|Low      |\n|     2|Medium |    0.404|     0.049|     8.204|   0.000|  51.932|    0.308|     0.501|           2|Low      |\n|     3|Medium |    0.565|     0.050|    11.222|   0.000|  94.666|    0.466|     0.664|           3|Low      |\n|     4|Medium |    0.550|     0.050|    10.935|   0.000|  90.050|    0.452|     0.649|           4|Low      |\n|     5|Medium |    0.373|     0.049|     7.658|   0.000|  45.592|    0.278|     0.469|           5|Low      |\n|     6|Medium |    0.185|     0.042|     4.370|   0.000|  16.299|    0.102|     0.269|           6|Low      |\n|     1|High   |    0.020|     0.009|     2.321|   0.020|   5.624|    0.003|     0.037|           1|Low      |\n|     2|High   |    0.055|     0.018|     3.151|   0.002|   9.266|    0.021|     0.090|           2|Low      |\n|     3|High   |    0.144|     0.031|     4.692|   0.000|  18.493|    0.084|     0.204|           3|Low      |\n|     4|High   |    0.324|     0.044|     7.345|   0.000|  42.142|    0.238|     0.411|           4|Low      |\n|     5|High   |    0.579|     0.054|    10.746|   0.000|  87.063|    0.473|     0.684|           5|Low      |\n|     6|High   |    0.797|     0.048|    16.769|   0.000| 207.233|    0.704|     0.890|           6|Low      |\n\n\n:::\n:::\n\n\n\n## Visualizing the dice model {.smaller}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot_predictions(dice_fit, condition = \"lead_weight\", type = \"prob\") +\n  facet_wrap(~group) +\n  scale_fill_manual(values = c(color_low, color_med, color_high)) +\n  labs(x = \"Lead weight (grams)\", y = \"Predicted probability\") +\n  theme_lucid(base_size = 16)\n```\n\n::: {.cell-output-display}\n![](ordinal-regression-lecture_files/figure-revealjs/unnamed-chunk-18-1.png){width=1056}\n:::\n:::\n\n\n. . .\n\nAs weight increases: P(Low) decreases, P(High) increases. The S-curves are the same shape (proportional odds!) — just shifted.\n\n\n## Proportional odds assumption {.smaller}\n\n-   The key assumption: the **slope is equal** across all cumulative splits\n\n-   In our dice model: the effect of lead weight on the log-odds of $Y \\leq$ Low vs. $Y >$ Low is the **same** as the effect on $Y \\leq$ Medium vs. $Y >$ Medium\n\n![](images/oddsassump.jpg){fig-align=\"center\"}\n\n. . .\n\n::: callout-note\nIf this assumption holds, you only need **one slope** per predictor — massive parsimony. If it doesn't hold, consider partial proportional odds or multinomial models.\n:::\n\n\n## FYI: Partial proportional odds model {.smaller}\n\n-   Is it fair to say the effect of your predictor stays the same across all category transitions?\n\n. . .\n\n-   Examples of when this breaks down:\n    -   Test prep might help more for moving from F → D than from A− → A\n    -   Age might strongly affect moving from \"poor\" → \"fair\" health but less so from \"good\" → \"excellent\"\n    -   Ceiling effects\n\n. . .\n\n-   How to know?\n    -   Likelihood ratio test comparing the two types of models\n    -   Big difference ⇒ the proportional assumption is probably wrong\n\n\n## Dice simulation: Recap {.smaller}\n\n| Step | What we did | What it teaches |\n|------|------------|-----------------|\n| Generate latent scores | `rnorm()` per die | Latent variable concept |\n| Apply thresholds | `case_when()` with $\\tau_1$, $\\tau_2$ | How categories arise from a continuum |\n| Fit OLS | `lm(y_numeric ~ lead_weight)` | Why treating ordinal as numeric fails |\n| Fit ordinal model | `clm(category ~ lead_weight)` | How cumulative logit works |\n| Check estimates vs. truth | Compare $\\hat{\\alpha}$ to $\\tau$, $\\hat{\\beta}$ to true slope | Model recovers the generating process |\n\n. . .\n\n::: callout-note\nNow let's apply this to real data — where we don't know the truth.\n:::\n\n\n# Case Study: Applying to Graduate School\n\n\n## Data: Postgraduate school applications {.smaller}\n\n-   Undergraduate students report how likely they were to apply to graduate school (`apply`): \"Unlikely\", \"Somewhat Likely\", \"Very Likely\"\n\n-   Additional information: GPA (`gpa`), parent education (`pared`) (college vs. no college), type of schooling (`public`) (public vs. private)\n\n\n::: {.cell}\n\n:::\n\n\n```{webr-r}\ndat <- read.csv(\"https://raw.githubusercontent.com/jgeller112/PSY504-Advanced-Stats-S24/main/slides/Ordinal_Regression/data/graduate_school.csv\")\n```\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|apply           |   n| proportion|\n|:---------------|---:|----------:|\n|somewhat likely | 140|       0.35|\n|unlikely        | 220|       0.55|\n|very likely     |  40|       0.10|\n\n\n:::\n:::\n\n\n\n## Data preparation\n\n\n::: {.cell}\n\n:::\n\n\n```{webr-r}\ndat <- dat %>%\n  mutate(pared = as.factor(pared), public = as.factor(public))\n\n# make sure the outcome is ordered properly \ndat$apply <- ordered(dat$apply, levels = c(\"unlikely\", \"somewhat likely\", \"very likely\"))\n\nhead(dat$apply)  # check to see if ordered\n```\n\n. . .\n\n::: callout-tip\nAlways use `ordered()` to explicitly set the level ordering. R won't guess correctly — it defaults to alphabetical.\n:::\n\n\n## Exploratory data analysis\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](ordinal-regression-lecture_files/figure-revealjs/unnamed-chunk-22-1.png){fig-align='center' width=960}\n:::\n:::\n\n\n\n## Model 1: Parent education only\n\n$$\\text{logit}(P(Y_i \\leq j)) = \\alpha_j - \\beta_1 \\cdot \\text{pared}_i$$\n\n-   Fit the model with `ordinal::clm` (can also use `MASS::polr`)\n\n\n::: {.cell}\n\n:::\n\n\n```{webr-r}\n# link = probit would also be acceptable\nols1 <- clm(apply ~ pared, data = dat, link = \"logit\")\n\nsummary(ols1)\n```\n\n\n## Interpreting output {.smaller}\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|term                             | estimate| std.error| statistic| p.value| conf.low| conf.high|coef.type |\n|:--------------------------------|--------:|---------:|---------:|-------:|--------:|---------:|:---------|\n|unlikely&#124;somewhat likely    |    0.377|     0.110|     3.415|   0.001|       NA|        NA|intercept |\n|somewhat likely&#124;very likely |    2.452|     0.183|    13.430|   0.000|       NA|        NA|intercept |\n|pared1                           |    1.127|     0.263|     4.280|   0.000|    0.613|     1.648|location  |\n\n\n:::\n:::\n\n\n. . .\n\n-   **Thresholds** (2 thresholds for 3 categories)\n\n    -   `unlikely|somewhat likely`: log-odds of being Unlikely vs. higher, when pared = 0\n    -   `somewhat likely|very likely`: log-odds of being ≤ Somewhat Likely vs. Very Likely, when pared = 0\n\n-   **Slope**\n\n    -   `pared1`: Students with a college-educated parent have higher log-odds of being in a higher application category\n\n```{webr-r}\n# What is the intercept?\n# What is the slope? How do we interpret it?\n\n```\n\n\n## Cumulative odds ratios\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbroom::tidy(ols1, exponentiate = TRUE, conf.int = TRUE) %>%\n  filter(coef.type == \"location\") %>%\n  kable(digits = 3)\n```\n\n::: {.cell-output-display}\n\n\n|term   | estimate| std.error| statistic| p.value| conf.low| conf.high|coef.type |\n|:------|--------:|---------:|---------:|-------:|--------:|---------:|:---------|\n|pared1 |    3.088|     0.263|      4.28|       0|    1.846|     5.196|location  |\n\n\n:::\n:::\n\n\n-   Exponentiate the log cumulative odds to get odds ratios\n\n-   Students with college-educated parents have roughly 3× the odds of applying to graduate school\n\n\n## Probabilities\n\n$$P(Y \\leq k) = \\frac{\\exp(\\alpha_k - \\beta X)}{1 + \\exp(\\alpha_k - \\beta X)}$$\n\n```{webr-r}\n# Try converting manually:\n# What is P(unlikely) for pared = 0?\n# What is P(unlikely) for pared = 1?\n\n```\n\n\n## Predicted probabilities\n\n\n::: {.cell}\n\n```{.r .cell-code}\npredictions(ols1, newdata = datagrid(pared = c(\"0\", \"1\"))) %>%\n  kable(digits = 3)\n```\n\n::: {.cell-output-display}\n\n\n| rowid|group           | estimate| std.error| statistic| p.value| s.value| conf.low| conf.high|pared |apply       |\n|-----:|:---------------|--------:|---------:|---------:|-------:|-------:|--------:|---------:|:-----|:-----------|\n|     1|unlikely        |    0.593|     0.027|    22.273|       0| 362.664|    0.541|     0.645|0     |very likely |\n|     2|unlikely        |    0.321|     0.053|     6.019|       0|  29.089|    0.216|     0.425|1     |very likely |\n|     1|somewhat likely |    0.328|     0.024|    13.688|       0| 139.259|    0.281|     0.374|0     |very likely |\n|     2|somewhat likely |    0.469|     0.033|    14.070|       0| 146.949|    0.404|     0.535|1     |very likely |\n|     1|very likely     |    0.079|     0.013|     5.949|       0|  28.469|    0.053|     0.105|0     |very likely |\n|     2|very likely     |    0.210|     0.042|     4.944|       0|  20.316|    0.127|     0.293|1     |very likely |\n\n\n:::\n:::\n\n\n\n## Model 1 visualization\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nplot_predictions(ols1, condition = \"pared\", type = \"prob\") +\n  facet_wrap(~group) +\n  labs(x = \"Parent Education\", y = \"Predicted probability\") +\n  scale_y_continuous(labels = scales::percent) +\n  theme_lucid(base_size = 20)\n```\n\n::: {.cell-output-display}\n![](ordinal-regression-lecture_files/figure-revealjs/unnamed-chunk-27-1.png){fig-align='center' width=1152}\n:::\n:::\n\n\n\n## Marginal effects\n\n\n::: {.cell}\n\n```{.r .cell-code}\navg_comparisons(ols1) %>%\n  kable(digits = 3)\n```\n\n::: {.cell-output-display}\n\n\n|term  |group           |contrast | estimate| std.error| statistic| p.value| s.value| conf.low| conf.high|\n|:-----|:---------------|:--------|--------:|---------:|---------:|-------:|-------:|--------:|---------:|\n|pared |unlikely        |1 - 0    |   -0.272|     0.058|    -4.664|   0.000|  18.301|   -0.387|    -0.158|\n|pared |somewhat likely |1 - 0    |    0.142|     0.027|     5.257|   0.000|  22.700|    0.089|     0.194|\n|pared |very likely     |1 - 0    |    0.131|     0.040|     3.243|   0.001|   9.726|    0.052|     0.210|\n\n\n:::\n:::\n\n\n. . .\n\n::: callout-tip\nMarginal effects tell you the change in **probability** for each category — much easier to interpret than odds ratios.\n:::\n\n\n## Testing proportional odds assumption\n\n-   `brant` test: compares the full proportional odds model to one that relaxes the assumption\n\n    -   You want a **non-significant** $\\chi^2$ test\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(gofcat)\nbrant.test(ols1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nBrant Test:\n           chi-sq   df   pr(>chi)\nOmnibus     0.017    1        0.9\npared1      0.017    1        0.9\n\nH0: Proportional odds assumption holds\n```\n\n\n:::\n:::\n\n\n\n## If the proportional odds test is violated\n\nSeveral options:\n\n-   **Multinomial regression** — use lowest level as reference; no ordering assumed\n\n-   **Adjacent category model** — model transitions between neighboring categories\n\n-   **Non-proportional odds (NPO) model** — allow slopes to vary by split\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# In VGAM: NPO model\nlibrary(VGAM)\nols_npo <- vglm(apply ~ pared, family = cumulative(parallel = FALSE, reverse = TRUE), data = dat)\n```\n:::\n\n\n\n## Model 2: Add public school + GPA\n\n\n::: {.cell}\n\n:::\n\n\n```{webr-r}\nols2 <- clm(apply ~ pared + public + gpa, data = dat)\n\nbroom::tidy(ols2, conf.int = TRUE) %>%\n  filter(coef.type == \"location\") %>%\n  kable(digits = 3)\n```\n\n. . .\n\n```{webr-r}\n# What do the coefficients mean?\n# pared1: \n# public1: \n# gpa: \n\n```\n\n\n## Test proportional odds: Model 2\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbrant.test(ols2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nBrant Test:\n           chi-sq   df   pr(>chi)  \nOmnibus     4.343    3      0.227  \npared1      0.132    1      0.716  \npublic1     3.443    1      0.064 .\ngpa         0.179    1      0.672  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nH0: Proportional odds assumption holds\n```\n\n\n:::\n:::\n\n\n\n## Visualization: Stacked area plots\n\n::: panel-tabset\n## Continuous (GPA)\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(effects)\nplot(effect(\"gpa\", ols2), style = \"stacked\")\n```\n\n::: {.cell-output-display}\n![](ordinal-regression-lecture_files/figure-revealjs/unnamed-chunk-33-1.png){fig-align='center' width=1152}\n:::\n:::\n\n\n## Categorical (Public)\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nplot(effect(\"public\", ols2), style = \"stacked\")\n```\n\n::: {.cell-output-display}\n![](ordinal-regression-lecture_files/figure-revealjs/unnamed-chunk-34-1.png){fig-align='center' width=1152}\n:::\n:::\n\n:::\n\n\n## RM: Seeing the full redistribution {.smaller}\n\nA predictor doesn't push someone into a specific category — it shifts their latent score, which **redistributes probability across all categories simultaneously**.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npredictions(ols2, \n            newdata = datagrid(gpa = c(2.5, 3.0, 3.5, 4.0), \n                               pared = \"0\", public = \"0\")) %>%\n  mutate(gpa_label = paste0(\"GPA = \", gpa)) %>%\n  ggplot(aes(x = group, y = estimate, fill = group)) +\n  geom_col(width = 0.7) +\n  geom_errorbar(aes(ymin = conf.low, ymax = conf.high), width = 0.2) +\n  facet_wrap(~gpa_label, nrow = 1) +\n  scale_fill_manual(values = c(\"unlikely\" = color_low, \n                                \"somewhat likely\" = color_med, \n                                \"very likely\" = color_high),\n                    guide = \"none\") +\n  scale_y_continuous(labels = scales::percent) +\n  labs(x = \"Response category\", y = \"Predicted probability\",\n       title = \"How probability mass redistributes as GPA increases\",\n       subtitle = \"Non-college-educated parent, private school\") +\n  theme_lucid(base_size = 14) +\n  theme(axis.text.x = element_text(angle = 20, hjust = 1))\n```\n\n::: {.cell-output-display}\n![](ordinal-regression-lecture_files/figure-revealjs/unnamed-chunk-35-1.png){width=1056}\n:::\n:::\n\n\n. . .\n\n::: callout-tip\nThis is what the model *predicts*, not the raw data. As GPA rises, probability drains from \"unlikely\" and flows into \"somewhat likely\" and \"very likely.\" **All three categories change simultaneously — that's the ordinal redistribution.**\n:::\n\n\n## Model 3: Add interaction (pared × GPA)\n\n\n::: {.cell}\n\n:::\n\n\n```{webr-r}\nols3 <- clm(apply ~ public + pared * gpa, data = dat)\n\nbroom::tidy(ols3, conf.int = TRUE) %>%\n  filter(coef.type == \"location\") %>%\n  kable(digits = 3)\n```\n\n\n## Model comparisons\n\n-   Likelihood ratio test (LRT)\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Main effects model vs. interaction\nols_test <- anova(ols2, ols3)\nkable(ols_test)\n```\n\n::: {.cell-output-display}\n\n\n|     | no.par|      AIC|    logLik|   LR.stat| df| Pr(>Chisq)|\n|:----|------:|--------:|---------:|---------:|--:|----------:|\n|ols2 |      5| 727.0249| -358.5124|        NA| NA|         NA|\n|ols3 |      6| 728.9774| -358.4887| 0.0474444|  1|  0.8275715|\n\n\n:::\n:::\n\n\n\n## Testing significance\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Use Type III if interactions are important\nols_test3 <- anova(ols3, type = \"III\")\nkable(ols_test3)\n```\n\n::: {.cell-output-display}\n\n\n|          | Df|     Chisq| Pr(>Chisq)|\n|:---------|--:|---------:|----------:|\n|public    |  1| 0.0433179|  0.8351278|\n|pared     |  1| 0.0760440|  0.7827319|\n|gpa       |  1| 4.3838466|  0.0362810|\n|pared:gpa |  1| 0.0473770|  0.8276920|\n\n\n:::\n:::\n\n\n\n## Model comparison table\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodelsummary(\n  list(\"Parent Ed\" = ols1,\n       \"Main Effects\" = ols2,\n       \"Interaction\" = ols3),\n  exponentiate = TRUE,\n  stars = TRUE,\n  title = \"Ordinal Regression: Model Comparison\"\n)\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<!-- preamble start -->\n\n    <script>\n\n      function styleCell_5fzb5mwhhyrkvzrwhwio(i, j, css_id) {\n          var table = document.getElementById(\"tinytable_5fzb5mwhhyrkvzrwhwio\");\n          var cell = table.rows[i]?.cells[j];  // Safe navigation to avoid errors\n          if (cell) {\n              console.log(`Styling cell at (${i}, ${j}) with class ${css_id}`);\n              cell.classList.add(css_id);\n          } else {\n              console.warn(`Cell at (${i}, ${j}) not found.`);\n          }\n      }\n      function insertSpanRow(i, colspan, content) {\n        var table = document.getElementById('tinytable_5fzb5mwhhyrkvzrwhwio');\n        var newRow = table.insertRow(i);\n        var newCell = newRow.insertCell(0);\n        newCell.setAttribute(\"colspan\", colspan);\n        // newCell.innerText = content;\n        // this may be unsafe, but innerText does not interpret <br>\n        newCell.innerHTML = content;\n      }\n      function spanCell_5fzb5mwhhyrkvzrwhwio(i, j, rowspan, colspan) {\n        var table = document.getElementById(\"tinytable_5fzb5mwhhyrkvzrwhwio\");\n        const targetRow = table.rows[i];\n        const targetCell = targetRow.cells[j];\n        for (let r = 0; r < rowspan; r++) {\n          // Only start deleting cells to the right for the first row (r == 0)\n          if (r === 0) {\n            // Delete cells to the right of the target cell in the first row\n            for (let c = colspan - 1; c > 0; c--) {\n              if (table.rows[i + r].cells[j + c]) {\n                table.rows[i + r].deleteCell(j + c);\n              }\n            }\n          }\n          // For rows below the first, delete starting from the target column\n          if (r > 0) {\n            for (let c = colspan - 1; c >= 0; c--) {\n              if (table.rows[i + r] && table.rows[i + r].cells[j]) {\n                table.rows[i + r].deleteCell(j);\n              }\n            }\n          }\n        }\n        // Set rowspan and colspan of the target cell\n        targetCell.rowSpan = rowspan;\n        targetCell.colSpan = colspan;\n      }\n      // tinytable span after\n      window.addEventListener('load', function () {\n          var cellsToStyle = [\n            // tinytable style arrays after\n          { positions: [ { i: 0, j: 0 },  ], css_id: 'tinytable_css_x7be7seu4kufjgqqs5oi',}, \n          { positions: [ { i: 16, j: 1 }, { i: 16, j: 2 }, { i: 16, j: 3 },  ], css_id: 'tinytable_css_miywjz0as7edknm9q7ft',}, \n          { positions: [ { i: 12, j: 0 },  ], css_id: 'tinytable_css_mblmwzftjbet7kyyeydu',}, \n          { positions: [ { i: 12, j: 1 }, { i: 12, j: 2 }, { i: 12, j: 3 },  ], css_id: 'tinytable_css_kiuqi084tcmof5ddnkph',}, \n          { positions: [ { i: 1, j: 1 }, { i: 2, j: 1 }, { i: 3, j: 1 }, { i: 5, j: 1 }, { i: 6, j: 1 }, { i: 7, j: 1 }, { i: 9, j: 1 }, { i: 10, j: 1 }, { i: 11, j: 1 }, { i: 8, j: 2 }, { i: 13, j: 1 }, { i: 14, j: 1 }, { i: 15, j: 1 }, { i: 8, j: 3 }, { i: 4, j: 1 }, { i: 1, j: 2 }, { i: 2, j: 2 }, { i: 3, j: 2 }, { i: 8, j: 1 }, { i: 5, j: 2 }, { i: 6, j: 2 }, { i: 7, j: 2 }, { i: 4, j: 3 }, { i: 9, j: 2 }, { i: 10, j: 2 }, { i: 11, j: 2 }, { i: 3, j: 3 }, { i: 13, j: 2 }, { i: 14, j: 2 }, { i: 15, j: 2 }, { i: 7, j: 3 }, { i: 4, j: 2 }, { i: 1, j: 3 }, { i: 2, j: 3 }, { i: 11, j: 3 }, { i: 5, j: 3 }, { i: 6, j: 3 }, { i: 15, j: 3 }, { i: 9, j: 3 }, { i: 10, j: 3 }, { i: 13, j: 3 }, { i: 14, j: 3 },  ], css_id: 'tinytable_css_kdocbhm11a1rdn3nm0cc',}, \n          { positions: [ { i: 1, j: 0 }, { i: 2, j: 0 }, { i: 3, j: 0 }, { i: 4, j: 0 }, { i: 5, j: 0 }, { i: 6, j: 0 }, { i: 7, j: 0 }, { i: 8, j: 0 }, { i: 9, j: 0 }, { i: 10, j: 0 }, { i: 11, j: 0 }, { i: 13, j: 0 }, { i: 14, j: 0 }, { i: 15, j: 0 },  ], css_id: 'tinytable_css_jg84fnwulelpks6k3i6o',}, \n          { positions: [ { i: 0, j: 1 }, { i: 0, j: 2 }, { i: 0, j: 3 },  ], css_id: 'tinytable_css_ha1ox34z60z862otnxje',}, \n          { positions: [ { i: 16, j: 0 },  ], css_id: 'tinytable_css_21fg6xs7pl690yv56ebc',}, \n          ];\n\n          // Loop over the arrays to style the cells\n          cellsToStyle.forEach(function (group) {\n              group.positions.forEach(function (cell) {\n                  styleCell_5fzb5mwhhyrkvzrwhwio(cell.i, cell.j, group.css_id);\n              });\n          });\n      });\n    </script>\n\n    <style>\n      /* tinytable css entries after */\n      .table td.tinytable_css_x7be7seu4kufjgqqs5oi, .table th.tinytable_css_x7be7seu4kufjgqqs5oi { text-align: left; border-top: solid #d3d8dc 0.1em; border-bottom: solid #d3d8dc 0.05em; }\n      .table td.tinytable_css_miywjz0as7edknm9q7ft, .table th.tinytable_css_miywjz0as7edknm9q7ft { text-align: center; border-bottom: solid #d3d8dc 0.1em; }\n      .table td.tinytable_css_mblmwzftjbet7kyyeydu, .table th.tinytable_css_mblmwzftjbet7kyyeydu { text-align: left; border-bottom: solid black 0.05em; }\n      .table td.tinytable_css_kiuqi084tcmof5ddnkph, .table th.tinytable_css_kiuqi084tcmof5ddnkph { text-align: center; border-bottom: solid black 0.05em; }\n      .table td.tinytable_css_kdocbhm11a1rdn3nm0cc, .table th.tinytable_css_kdocbhm11a1rdn3nm0cc { text-align: center; }\n      .table td.tinytable_css_jg84fnwulelpks6k3i6o, .table th.tinytable_css_jg84fnwulelpks6k3i6o { text-align: left; }\n      .table td.tinytable_css_ha1ox34z60z862otnxje, .table th.tinytable_css_ha1ox34z60z862otnxje { text-align: center; border-top: solid #d3d8dc 0.1em; border-bottom: solid #d3d8dc 0.05em; }\n      .table td.tinytable_css_21fg6xs7pl690yv56ebc, .table th.tinytable_css_21fg6xs7pl690yv56ebc { text-align: left; border-bottom: solid #d3d8dc 0.1em; }\n    </style>\n    <div class=\"container\">\n      <table class=\"table table-borderless\" id=\"tinytable_5fzb5mwhhyrkvzrwhwio\" style=\"width: auto; margin-left: auto; margin-right: auto;\" data-quarto-disable-processing='true'>\n        <thead>\n        <caption>Ordinal Regression: Model Comparison</caption>\n              <tr>\n                <th scope=\"col\"> </th>\n                <th scope=\"col\">Parent Ed</th>\n                <th scope=\"col\">Main Effects</th>\n                <th scope=\"col\">Interaction</th>\n              </tr>\n        </thead>\n        <tfoot><tr><td colspan='4'>+ p < 0.1, * p < 0.05, ** p < 0.01, *** p < 0.001</td></tr></tfoot>\n        <tbody>\n                <tr>\n                  <td>unlikely|somewhat likely</td>\n                  <td>1.458***</td>\n                  <td>9.055**</td>\n                  <td>8.424*</td>\n                </tr>\n                <tr>\n                  <td></td>\n                  <td>(0.161)</td>\n                  <td>(7.059)</td>\n                  <td>(7.130)</td>\n                </tr>\n                <tr>\n                  <td>somewhat likely|very likely</td>\n                  <td>11.610***</td>\n                  <td>73.609***</td>\n                  <td>68.570***</td>\n                </tr>\n                <tr>\n                  <td></td>\n                  <td>(2.120)</td>\n                  <td>(59.205)</td>\n                  <td>(59.450)</td>\n                </tr>\n                <tr>\n                  <td>pared1</td>\n                  <td>3.088***</td>\n                  <td>2.851***</td>\n                  <td>1.799</td>\n                </tr>\n                <tr>\n                  <td></td>\n                  <td>(0.813)</td>\n                  <td>(0.758)</td>\n                  <td>(3.834)</td>\n                </tr>\n                <tr>\n                  <td>public1</td>\n                  <td></td>\n                  <td>0.943</td>\n                  <td>0.940</td>\n                </tr>\n                <tr>\n                  <td></td>\n                  <td></td>\n                  <td>(0.281)</td>\n                  <td>(0.280)</td>\n                </tr>\n                <tr>\n                  <td>gpa</td>\n                  <td></td>\n                  <td>1.851*</td>\n                  <td>1.807*</td>\n                </tr>\n                <tr>\n                  <td></td>\n                  <td></td>\n                  <td>(0.482)</td>\n                  <td>(0.511)</td>\n                </tr>\n                <tr>\n                  <td>pared1 × gpa</td>\n                  <td></td>\n                  <td></td>\n                  <td>1.160</td>\n                </tr>\n                <tr>\n                  <td></td>\n                  <td></td>\n                  <td></td>\n                  <td>(0.791)</td>\n                </tr>\n                <tr>\n                  <td>Num.Obs.</td>\n                  <td>400</td>\n                  <td>400</td>\n                  <td>400</td>\n                </tr>\n                <tr>\n                  <td>AIC</td>\n                  <td>728.8</td>\n                  <td>727.0</td>\n                  <td>729.0</td>\n                </tr>\n                <tr>\n                  <td>BIC</td>\n                  <td>740.8</td>\n                  <td>747.0</td>\n                  <td>752.9</td>\n                </tr>\n                <tr>\n                  <td>RMSE</td>\n                  <td>1.37</td>\n                  <td>1.37</td>\n                  <td>1.37</td>\n                </tr>\n        </tbody>\n      </table>\n    </div>\n<!-- hack to avoid NA insertion in last line -->\n```\n\n:::\n:::\n\n\n\n## Visualization: Interaction\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nplot_predictions(ols3, condition = c(\"gpa\", \"pared\"), type = \"prob\") +\n  facet_grid(~group) +\n  theme_lucid(base_size = 14)\n```\n\n::: {.cell-output-display}\n![](ordinal-regression-lecture_files/figure-revealjs/unnamed-chunk-40-1.png){fig-align='center' width=1152}\n:::\n:::\n\n\n\n## Pairwise comparisons\n\n-   Results are on the logit (latent scale) by default\n\n```{webr-r}\nemmeans(ols3, list(pairwise ~ pared, pairwise ~ public))\n```\n\n\n## Simple slopes\n\n```{webr-r}\nemtrends(ols3, pairwise ~ pared, var = \"gpa\")\n```\n\n\n## Latent scale\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nplot(effect(\"pared:gpa\", ols3, latent = TRUE))\n```\n\n::: {.cell-output-display}\n![](ordinal-regression-lecture_files/figure-revealjs/unnamed-chunk-41-1.png){fig-align='center' width=1152}\n:::\n:::\n\n\n\n## Marginal effects\n\n\n::: {.cell}\n\n```{.r .cell-code}\navg_comparisons(ols3) %>%\n  kable(digits = 3)\n```\n\n::: {.cell-output-display}\n\n\n|term   |group           |contrast | estimate| std.error| statistic| p.value| s.value| conf.low| conf.high|\n|:------|:---------------|:--------|--------:|---------:|---------:|-------:|-------:|--------:|---------:|\n|gpa    |unlikely        |+1       |   -0.143|     0.059|    -2.430|   0.015|   6.049|   -0.258|    -0.028|\n|gpa    |somewhat likely |+1       |    0.074|     0.031|     2.350|   0.019|   5.735|    0.012|     0.135|\n|gpa    |very likely     |+1       |    0.069|     0.036|     1.906|   0.057|   4.143|   -0.002|     0.141|\n|pared  |unlikely        |1 - 0    |   -0.247|     0.063|    -3.928|   0.000|  13.510|   -0.370|    -0.124|\n|pared  |somewhat likely |1 - 0    |    0.130|     0.032|     4.071|   0.000|  14.383|    0.068|     0.193|\n|pared  |very likely     |1 - 0    |    0.117|     0.039|     3.034|   0.002|   8.697|    0.041|     0.193|\n|public |unlikely        |1 - 0    |    0.014|     0.069|     0.209|   0.835|   0.261|   -0.122|     0.151|\n|public |somewhat likely |1 - 0    |   -0.009|     0.044|    -0.207|   0.836|   0.259|   -0.096|     0.077|\n|public |very likely     |1 - 0    |   -0.005|     0.025|    -0.212|   0.832|   0.265|   -0.055|     0.044|\n\n\n:::\n:::\n\n\n\n## Model fit\n\n-   Pseudo-$R^2$\n\n\n::: {.cell}\n\n```{.r .cell-code}\nr2_mcfadden(ols2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# R2 for Generalized Linear Regression\n       R2: 0.033\n  adj. R2: 0.030\n```\n\n\n:::\n:::\n\n\n. . .\n\n-   Not \"explained variance\" — but a ratio indicating how much better the model fits than an intercept-only model\n\n\n## Model diagnostics {.smaller}\n\n-   No `easystats` functions for ordinal models :(\n\n-   `sure` package: **surrogate residuals** — based on continuous residuals\n\n    -   Check normality, linearity, homoscedasticity\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(sure)\n\nset.seed(1225)\n\ngridExtra::grid.arrange(\n  autoplot.clm(ols2, nsim = 100, what = \"qq\"),\n  autoplot.clm(ols2, nsim = 100, what = \"fitted\", alpha = 0.5),\n  ncol = 2\n)\n```\n\n::: {.cell-output-display}\n![](ordinal-regression-lecture_files/figure-revealjs/unnamed-chunk-44-1.png){fig-align='center' width=1152}\n:::\n:::\n\n\n::: callout-note\nFor multicollinearity, check correlations between predictor variables directly.\n:::\n\n\n# Assumptions\n\n\n## Ordinal regression assumptions\n\n-   Outcome is **ordinal** (ordered categories)\n\n-   Observations are **independent**\n\n-   **Proportional odds** (parallel slopes across cumulative splits)\n\n-   **Linearity** in the log-odds (for continuous predictors)\n\n-   ~~No normality assumptions for residuals~~\n\n-   ~~Homogeneity of variance~~\n\n\n## Multilevel ordinal regressions\n\n-   For repeated measures or clustered/nested designs:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Use clmm() from the ordinal package\nols_multilevel <- ordinal::clmm(\n  apply ~ pared + gpa + (1 | school_id),\n  data = dat\n)\n```\n:::\n\n\n\n\n## Sample write-up\n\n::: callout-tip\nA proportional odds model with a logit link (estimated using ML) was used to investigate factors influencing undergraduates' likelihood of applying to graduate school (\"unlikely,\" \"somewhat likely,\" \"very likely\"). The overall model fit was modest, McFadden's pseudo-$R^2$ = .03. Parent education significantly predicted application likelihood, *b* = 1.05, *z* = 3.94, *p* < .001, OR = 2.85, 95% CI [1.55, 5.28]. Students with college-educated parents had roughly 185% higher odds of applying. Whether students attended public or private school did not significantly predict application likelihood, *b* = −0.06, *z* = −0.20, *p* = .844, OR = 0.94. GPA was also a significant predictor, *b* = 0.62, *z* = 2.36, *p* = .018, OR = 1.85. Each one-point increase in GPA was associated with 85% higher odds of applying.\n:::\n\n\n## Reporting checklist\n\n-   Report the model type (**proportional odds / cumulative logit**) and estimation method\n\n-   Report **log-odds coefficients and odds ratios** with 95% CIs\n\n-   Report thresholds (or note they are available)\n\n-   Report a measure of model fit (**McFadden pseudo-$R^2$**)\n\n-   **Test and report** the proportional odds assumption (Brant test or LRT)\n\n-   Consider reporting **marginal effects** / predicted probabilities for each category\n\n-   Include sample size and **distribution across response categories**\n\n-   Mention diagnostics (surrogate residuals, multicollinearity)\n\n\n## Common Mistakes {.smaller}\n\n-   **Treating ordinal data as continuous** — running OLS or t-tests on Likert scales\n\n-   Forgetting that coefficients are in **cumulative log-odds**, not probabilities\n\n-   Confusing **thresholds with slopes** — thresholds are intercepts for each cumulative split, not effects of predictors\n\n-   **Ignoring the proportional odds assumption**\n    -   Always test it; if it fails, consider partial proportional odds or multinomial\n\n-   Interpreting **odds ratios as probability ratios**\n    -   OR = 3 means 3× the *odds*, not 3× the *probability*\n\n-   **Not visualizing** predicted probabilities per category\n    -   Log-odds and ORs are hard to interpret; always plot `plot_predictions()`\n\n",
    "supporting": [
      "ordinal-regression-lecture_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}